### ISSUE TITLE
[REVIEW]: rucrdtw: Fast time series subsequence search in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#100]
**Submitting author:** @pboesu (<a href="http://orcid.org/0000-0001-6723-6833">Philipp Boersch-Supan</a>)
**Repository:** <a href="https://github.com/pboesu/rucrdtw" target ="_blank">https://github.com/pboesu/rucrdtw</a>
**Version:** v0.1.0
**Editor:** @arfon
**Reviewer:** @masalmon
**Archive:** <a href="https://dx.doi.org/10.5281/zenodo.164995" target="_blank">https://dx.doi.org/10.5281/zenodo.164995</a>

## Status

[![status](http://joss.theoj.org/papers/17bb01f6599983da0597e1aeec4d3bfc/status.svg)](http://joss.theoj.org/papers/17bb01f6599983da0597e1aeec4d3bfc)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/17bb01f6599983da0597e1aeec4d3bfc"><img src="http://joss.theoj.org/papers/17bb01f6599983da0597e1aeec4d3bfc/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/17bb01f6599983da0597e1aeec4d3bfc/status.svg)](http://joss.theoj.org/papers/17bb01f6599983da0597e1aeec4d3bfc)
```

**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/pboesu/rucrdtw" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)
### Conflict of interest
- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).
### General checks
- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pboesu/rucrdtw">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@pboesu) made major contributions to the software?
### Functionality
- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?
### Documentation
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
### Software paper
- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@masalmon - please follow the review guidelines (http://joss.theoj.org/about#reviewer_guidelines) and complete the checklist above as you go. Any questions, please don't hesitate to ask!

**Comment by masalmon** [comment]
@arfon Ok! Will try to do it this or next week :-)

**Comment by masalmon** [comment]
Maybe I only accepted for getting issue number 100 ;-)

**Comment by arfon** [comment]
> Maybe I only accepted for getting issue number 100 ;-)

😆

**Comment by noamross** [comment]
## Reviewer questions

This is a second review.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pboesu/rucrdtw">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@pboesu) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

---

Comments:


Thank you for your submission and the opportunity to review this package as a
way of learning more about DTW. This is an excellent, compact package that
provides bindings to a very useful library. I can see its use as a building
block for many applications.

There is one major issue I wish to address here, which is licensing. While the
original UCR source code has re-usage comment, I could not locate a
*license* for the original UCR code which is included in this package.  This
isn't my area of expertise but I want to make sure that re-release under the
Apache license is permitted.

As noted above, there is currently no GitHub release of this package.

I have opened issues on the main repository on [documentation](https://github.com/pboesu/rucrdtw/issues/3)
[testing](https://github.com/pboesu/rucrdtw/issues/2) and [API](https://github.com/pboesu/rucrdtw/issues/4).

**Comment by pboesu** [comment]
Thanks @noamross for the review and the constructive feedback! I will try to address the specific issues/pull requests in the coming days.

I did want to respond to the issue of licensing, immediately, though, as this is something I was not 100% certain how to handle at the initial submission. As you note, the original source of the wrapped C++ library is copyrighted, but not licensed. I did contact Eamonn Keogh, the senior author of the original code/paper, prior to making my R wrapper repository public on github and he consented to a public release under the Apache license on github and ultimately CRAN.

**Comment by masalmon** [comment]
## Reviewer questions

This is actually the second review, in theory the first one. ;-)

### Conflict of interest
- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).
### General checks
- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/pboesu/rucrdtw">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@pboesu) made major contributions to the software?
### Functionality
- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?
### Documentation
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
### Software paper
- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

# Comments:

Thank you for this package! 

* I haven't checked the "statement of need" box because I feel there should/could be more details about practical applications.

* There are two examples in the vignette, but they are no "real world" examples, which would really be nice. 

* I commented in https://github.com/pboesu/rucrdtw/issues/3 about those two latter points.

**Comment by pboesu** [comment]
Thank you @masalmon for the review and the PR!

I will try to address all of your comments this week.

**Comment by pboesu** [comment]
Hi @masalmon  and @noamross ,
Thank you again for your constructive reviews! I have now completed my revision of the paper and code. 

I believe I have addressed all suggestions, except for adding "real world" examples.  A detailed response about the examples, and the other changes to the documentation is [here](https://github.com/pboesu/rucrdtw/issues/3#issuecomment-258646019).

I have also responded to the other two issues about a [C++ level interface](https://github.com/pboesu/rucrdtw/issues/4#issuecomment-258286311) and additional [unit tests](https://github.com/pboesu/rucrdtw/issues/2#issuecomment-258307597).

If you are happy with those changes please let me know. I will then tag the release on github to create an archived version on zenodo, and also submit to CRAN.

**Comment by masalmon** [comment]
Hi @pboesu as discussed in the issue in your repo I'm happy with the changes, nice work!

**Comment by noamross** [comment]
I've examined all of the changes since I first reviewed this package and @pboesu has satisfied all my concerns.  I approve!

**Comment by pboesu** [comment]
Brilliant! Thanks again, @noamross and @masalmon for the constructive review!

I have tagged the release and archived it on zenodo. The archive doi is [10.5281/zenodo.164995](https://doi.org/10.5281/zenodo.164995).

I also have submitted the package to CRAN.

**Comment by arfon** [comment]
@noamross and @masalmon many thanks for the reviews here ✨ 

@pboesu - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00100 🎉 🚀 💥
