### ISSUE TITLE
[REVIEW]: Visualizing alpha-helical peptides in R with helixvis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1008]
**Submitting author:** @rrrlw (<a href="http://orcid.org/0000-0003-0503-9580">Raoul R. Wadhwa</a>)
**Repository:** <a href="https://github.com/rrrlw/helixvis" target ="_blank">https://github.com/rrrlw/helixvis</a>
**Version:** v1.0.0
**Editor:** @yochannah
**Reviewer:** @nagoue, @tomsing1
**Archive:** <a href="https://doi.org/10.5281/zenodo.1470939" target="_blank">10.5281/zenodo.1470939</a>

## Status

[![status](http://joss.theoj.org/papers/f28ccdaa9e62646cf673f36dac630eab/status.svg)](http://joss.theoj.org/papers/f28ccdaa9e62646cf673f36dac630eab)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/f28ccdaa9e62646cf673f36dac630eab"><img src="http://joss.theoj.org/papers/f28ccdaa9e62646cf673f36dac630eab/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/f28ccdaa9e62646cf673f36dac630eab/status.svg)](http://joss.theoj.org/papers/f28ccdaa9e62646cf673f36dac630eab)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/rrrlw/helixvis" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@nagoue & @tomsing1, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @yochannah know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rrrlw/helixvis">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@rrrlw) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rrrlw/helixvis">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@rrrlw) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @nagoue, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01008/joss.01008/10.21105.joss.01008.pdf)

**Comment by rrrlw** [comment]
First off, thank you @yochannah for editing and @tomsing1, @nagoue for reviewing! Very grateful for the time and effort you all are contributing.

A couple of quick notes for the reviewers:

- The CRAN version of helixvis is very much out-of-date (will update on CRAN when the review on this thread is complete, even if helixvis is not accepted to JOSS), so please use `devtools::install_github("rrrlw/helixvis")` to install the package
- I have added a document reflecting the reviewer checklist for this JOSS submission [here](https://github.com/rrrlw/helixvis/blob/master/JOSS-paper/reviewer-checklist.md), which could save the reviewers some time on the checklists above. Hope it helps.

Looking forward to everyone's feedback!

**Comment by nagoue** [comment]
Hi,
I have a minor comments:

1. Consider adding **units (>= 0.6-1)** in the Imports part of the DESCRIPTION file as the installation wasn't going smoothly with the devtools option.

2. There is a typo error l40 in paper.md (graphical).

3. Redirection is not working for reference Sandve et al.

as well as improvement suggestions:

4. Include a legend to graphic plots.

5. There is no reason to limit peptide length to 18 aa in wenxiang diagram unless to make it comparable to the helical diagram. I would rather suggest not limiting this length to wenxiang diagram style and "only" give a warning to the user to inform him that the comparison between the 2 diagram styles will not be possible.

**Comment by tomsing1** [comment]
Dear authors and editors, 

I have completed my review. Please find a few minor suggestions below (also filed as issues in the `helixvis` repository). Great work!

## Installation: Does installation proceed as outlined in the documentation?

[Issue #9](https://github.com/rrrlw/helixvis/issues/9)
Yes. The authors included a great vignette with the package - but it is not built automatically when the package is pulled from github. I recommend including 

```r
devtools::install_github("rrrlw/helixvis", build_vignettes=TRUE)
````

in the `README.md` file to make sure all users get to see the compiled vignette.

## Does the release version given match the GitHub release (v1.0.0)?

[Issue #8](https://github.com/rrrlw/helixvis/issues/8)
No, the current github release is v0.9, but the DESCRIPTION file shows v1.0.0.
There have been > 90 commits to the master branch since v0.9 has been released.
(I have reviewed the master branch by cloning the master branch.)

## Authorship: Does the full list of paper authors seem appropriate and complete?

rrrlw has currently made all 106 commits to the github repository, so I cannot verify the contributions of the other authors outlined in [additional information provided by the authors](https://github.com/rrrlw/helixvis/blob/master/JOSS-paper/reviewer-checklist.md). I will therefore trust that

> The authors themselves assume responsibility for deciding who should be credited with co-authorship.

as outlined in the [reviewer guidelines](https://joss.readthedocs.io/en/latest/submitting.html#authorship).

## Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

[Issue #7](https://github.com/rrrlw/helixvis/issues/7)
The authors include a small set of example peptides sequences, which is great. The source code includes the data in two forms: the binary `data/sequence.rda` and the plain `data-raw/sequence.R` file with the code that generates the former.

The `sequence.R` file can be included in the `data` directory directly and will be sourced automatically when then `data("sequence")` call is executed. There is no need for the binary file (or the `data-raw` directory). See the `?data` help page for details.

## Code style

The code is very clear, but the authors might want to consider automatic checking of the
code style, e.g.

```r
library(lintr)
lintr::lint_package()
```
and automatic styling e.g. using

```r
library(styler)
styler::style_pkg()
```

**Comment by rrrlw** [comment]
Thank you to the reviewers for their clear feedback.

In response to the points brought up by @nagoue:
1. The units (>= 0.6) dependency has been added to the Imports field in the DESCRIPTION file.
2. The typo in line 40 of paper.md has been fixed.
3. The redirection to Sandve et al. is not working for me either. However, the DOI in paper.md matches the DOI on the PLoS CB website (https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285), which also does not redirect properly. Since the DOIs match, I have left it in paper.md unchanged; however, since redirection is not working, I would be willing to remove the DOI from the Sandve et al. reference in the JOSS paper.
4. Legends can be added to helical wheels (with `draw_wheel`) and wenxiang diagrams (with `draw_wenxiang`) using the `legend=TRUE` parameter. A corresponding section will be added in the helixvis introduction vignette.
5. You make a good point about limiting the wenxiang diagram to 18 residues. Because the code is currently based on explicit coordinates (that are based on a max of 18 residues), adding this feature would require major code changes. However, this is would be a very useful enhancement for users as wenxiang diagrams are not inherently limited in sequence length as helical wheels are, so I have added this as an [Issue](https://github.com/rrrlw/helixvis/issues/10) to the helixvis GitHub repo, and will work on it in the future to improve helixvis.

In response to the points brought up by @tomsing1:
1. [Issue 9](https://github.com/rrrlw/helixvis/issues/9) has been fixed by adding `build_vignettes = TRUE` to the GitHub README.md file.
2. The version mismatch has been corrected with the [latest helixvis release](https://github.com/rrrlw/helixvis/releases/tag/v1.0.0).
3. Thank you for the trust on authorship.
4. [Issue 7](https://github.com/rrrlw/helixvis/issues/7) has been fixed by removing the redundant files and only retaining the R script in the data directory.
5. lintr has been added to Travis CI for checking code style; notifications are all about snake case for variables (my personal style is to separate words in variables with a period and words in functions with an underscore) and not having greater than 80 characters of code in a single line (only error and warning messages seem to violate this). I do not think either of these types of errors are major code style violations.

Please let me know if there are any other changes I should make.

**Comment by tomsing1** [comment]
Looks good to me - accept!

**Comment by yochannah** [comment]
@nagoue and @tomsing1 - thanks for your great work reviewing! 👍 There's still once checkbox each that needs to be checked. Are we happy to check these and move ahead?

**Comment by tomsing1** [comment]
Thanks for reminder - we are good to go!

**Comment by rrrlw** [comment]
Thank you, @tomsing1! I have made a couple of changes to the JOSS paper text so will recompile here to get an updated PDF, my apologies for any resulting notification spam.

**Comment by rrrlw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01008/joss.01008/10.21105.joss.01008.pdf)

**Comment by rrrlw** [comment]
Hi @nagoue, thank you for reviewing helixvis! Is there anything else you would like me to modify to satisfy the last checkbox?

**Comment by rrrlw** [comment]
Great, thank you! @yochannah, is the primary review process complete?

**Comment by yochannah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01008/joss.01008/10.21105.joss.01008.pdf)

**Comment by yochannah** [comment]
I think we're good to go - @rrrlw, I'm assuming http://doi.org/10.5281/zenodo.1470939 the correct DOI to associate with this paper?

**Comment by rrrlw** [comment]
Great, thank you @yochannah! Yes, that is the correct DOI.

**Comment by yochannah** [comment]
@whedon set http://doi.org/10.5281/zenodo.1470939 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1470939" target="_blank">10.5281/zenodo.1470939</a> is the archive.

**Comment by yochannah** [comment]
@arfon We're ready to accept this! 🎉

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/46

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/46, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/47
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01008](https://doi.org/10.21105/joss.01008)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by rrrlw** [comment]
Thank you so much @nagoue and @tomsing1 for reviewing, @yochannah for editing, and @arfon for setting up a great experience with JOSS!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01008/status.svg)](https://doi.org/10.21105/joss.01008)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01008">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01008/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01008/status.svg
   :target: https://doi.org/10.21105/joss.01008
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01008/status.svg)](https://doi.org/10.21105/joss.01008)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by arfon** [comment]
@nagoue, @tomsing1 - many thanks for your reviews here and to @yochannah  for editing this submission ✨

@rrrlw - your paper is now accepted into JOSS ⚡️🚀💥
