### ISSUE TITLE
[REVIEW]: Pingouin: statistics in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1026]
**Submitting author:** @raphaelvallat (<a href="http://orcid.org/0000-0003-1779-7653">Raphael Vallat</a>)
**Repository:** <a href="https://github.com/raphaelvallat/pingouin" target ="_blank">https://github.com/raphaelvallat/pingouin</a>
**Version:** v0.1.10
**Editor:** @cMadan
**Reviewer:** @snastase
**Archive:** <a href="https://doi.org/10.5281/zenodo.1491783" target="_blank">10.5281/zenodo.1491783</a>

## Status

[![status](http://joss.theoj.org/papers/d2254e6d8e8478da192148e4cfbe4244/status.svg)](http://joss.theoj.org/papers/d2254e6d8e8478da192148e4cfbe4244)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d2254e6d8e8478da192148e4cfbe4244"><img src="http://joss.theoj.org/papers/d2254e6d8e8478da192148e4cfbe4244/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d2254e6d8e8478da192148e4cfbe4244/status.svg)](http://joss.theoj.org/papers/d2254e6d8e8478da192148e4cfbe4244)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/raphaelvallat/pingouin" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@snastase, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @cMadan know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/raphaelvallat/pingouin">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.9)?
- [x] **Authorship:** Has the submitting author (@raphaelvallat) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @snastase it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01026/joss.01026/10.21105.joss.01026.pdf)

**Comment by raphaelvallat** [comment]
Hi @cMadan and @snastase! 

I was hoping to release the version 0.2.0 of Pingouin by early next week and ideally I would really love to include the JOSS paper in it. Do you think that it would be possible to do the review by then? If not, no worries, I'll just include it in a future release.

Thank you and have a great day!
Raphael

**Comment by cMadan** [comment]
@snastase, how is the review coming? Do you have any questions about the review procedures?

**Comment by snastase** [comment]
@cMadan @raphaelvallat Sorry for holding this up!

I’m not a very experienced developer (also my first JOSS review), so take this as the perspective of intermediate-skill-level user. Overall, I think this is a great contribution. Documentation and examples are stellar. I work through the checklist and point out some minor issues below (most of which are installation issues that may be peculiar to my environment).

General checklist: general checks are all good (version has progressed to 0.1.10).

Functional checklist: Installation with pip (on Mac) was smooth, although it might be worth including a note for folks like me who still have a python 2.7 installation floating around; e.g., `pip3 install pingouin`. I get some incompatibility warnings for requirements (`mock`, `future`, `jsonschema`, `decorator`), but these do not derail installation. Install via pip was smooth enough on a Linux machine. Module imports fine in IPython. Developer install via git clone was smooth. 

I followed the “10 Minutes to Pingouin” walkthrough in IPython on both Mac and Linux machines, and most of it ran smoothly. I ran into the following handful of errors.

- When I run post-hoc tests using `pairwise_ttests` on my Linux machine, I get a `TypeError: drop() got an unexpected keyword argument 'columns'` at line 243 in `pairwise.py`... not sure why. The `stats` object is a pandas DataFrame and I’m evidently on pandas version 0.20.3 , so that’s probably the issue. However this error did not occur with the Mac installation.

- On my Mac machine, I was unable to `from pingouin import linear_regression` probably due to a pandas incompatibility (v.0.23.1). Upgrade to pandas v.0.23.4 didn’t seem to fix this issue. On my Linux installation I had a similar issue when importing `linear_regression` which returned `ModuleNotFoundError: No module named 'pandas.compat'`. Same issue when importing `mediation_analysis`. I just noticed in the Quick Start notebook that maybe these features are provisional and planned for release in v.0.2.0…?

I also walked through all of the tutorial notebooks on Binder. This is an excellent approach to interactive examples. I ran into the following issues:

- In the 00_QuickStart notebook running on Binder, the `‘mixed_anova’` dataset does not seem to exist in `pingouin.datasets`.

- In the 04_Correlations notebook, in the second code cell of the “Advanced column selection” where you do `pairwise_corr(df, columns='Age')`, I get a pandas error: `KeyError: 'A'`. The following cells in that section do not run correctly either.

Documentation checklist: Regarding the statement of need, it might be helpful to include in the introductory documentation how this relates to adjacent packages such as `statsmodels`, whether it provides complementary functionality, etc. I spot-checked the tests, and they seem comprehensive enough. Community guidelines are fine, e.g,. code of conduct, gitter, etc. Documentation (tutorials, docstrings) and examples are _excellent_. The flowchart guidelines are really nice too.

Paper checklist: Everything in order. You might do a final pass over the references to make sure formatting is correct; e.g., most of the journal names in your list are abbreviated, but the Berens reference is not—should be “J. Stat. Softw.”; also capitalize the proceedings name for the McKinney reference.

Random highly-specific feature request: In the `corr` function, it would be nice to have separate implementations of Kendall’s tau-a, tau-b, and tau-c. This occurs to me because in representational similarity analysis in neuroimaging, the recommended metric for comparing representational similarity matrices is Kendall’s tau-a (Nili et al., PLOS Comp Biol, 2014). As far as I know, there’s no python implementation of tau-a.

Again, sorry for the delay! Let me know if I can be of help.

Sam

**Comment by raphaelvallat** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01026/joss.01026/10.21105.joss.01026.pdf)

**Comment by raphaelvallat** [comment]
Hi @snastase! 

Thank you so much for your review and your positive feedback, I really appreciate it!

Please find below the answers to the main points that you mentioned in your review:

1) I never tried to run Pingouin on Python 2.7. My idea when I started working on the project was that it would be a Python 3 only package. I uploaded the installation instructions to emphasize that it works better with Python 3 and that users should be careful when using Python 2.7

2) Thank you for noticing the `pandas.drop()` error in the `pairwise_ttests()` function. I realized that the `columns` argument has only been added since Pandas 0.21. I have therefore updated the requirements.txt file to make sure that the pip installation also updates the pandas version.

3) I have just uploaded the version 0.2.0 of Pingouin to PyPi, which should solve all the bugs that you have encountered in the Binder notebooks (i.e. no linear regression, missing example datasets...).
Just make sure to upgrade your version: `pip install --upgrade pingouin`

4) I liked the idea of adding a section explaining how Pingouin relates to similar packages. Therefore, I have just added a [FAQ](https://raphaelvallat.github.io/pingouin/build/html/faq.html) section in the documentation to explain the differences between Statsmodels, Scipy and Pingouin, as well as to answer some of the most basic functions that users may ask when they first start to use Python and/or Pingouin.

5) I have updated the Berens reference  in the paper, however, I am not able to capitalize the proceedings name for the McKinney reference (the automatic PDF generation somehow does not take it into account).

6) I was not aware of these alternatives metrics of the Kendall tau. The Pingouin implementation relies on the `scipy.stats.kendalltau()` function, which, according to the documentation, uses the tau-b when ties are present and tau-a in absence of ties. Therefore, it seems that only the tau-c implementation is missing. I will definitely keep that in mind and maybe try to add it in a future release.

Thank you again, Samuel, for your review! Please let me know if there is anything else that I can do.
Have a great day,
Raphael

**Comment by raphaelvallat** [comment]
Hi @snastase and @cMadan !

I am just wondering what should be the next step(s) for this review. Is there anything else that I can do?
This is my very first JOSS paper so I am new to this process,

Thank you and have an excellent day!
Raphael

**Comment by cMadan** [comment]
@raphaelvallat, I think you're all set for now.

@snastase, can you look over the reviewer checklist in the first post in this issue and check off what's all sorted, and see what still needs to be addressed? Apart from that, please look over @raphaelvallat's response and revisions and let us know what you think of the current state of the submission.

**Comment by snastase** [comment]
Okay, I think the author has adequately addressed my comments! New v0.2.0 fixes my import problems for `linear_regression` and `mediation_analysis`. The `pairwise_ttests` functionality now works normally for me. I like the mention of statsmodels in the FAQ. I've completed the review checklist above and am satisfied with the current state of the package—I endorse it for acceptance/publication.

**Comment by cMadan** [comment]
@snastase, perfect, thank you for your thorough review!

@raphaelvallat, you're almost done! I just need the DOI for an archived version of the current code (i.e., deposit it on Zenodo or FigShare).

**Comment by raphaelvallat** [comment]
@snastase Great! thank you so much, Samuel, for your review!

@cMadan The DOI number of the current release is: https://zenodo.org/badge/latestdoi/127584791

[![DOI](https://zenodo.org/badge/127584791.svg)](https://zenodo.org/badge/latestdoi/127584791)

Have a great day!
Raphael

**Comment by cMadan** [comment]
@whedon set archive as 10.5281/zenodo.1491783

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/71
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01026](https://doi.org/10.21105/joss.01026)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@snastase - many thanks for your review and to @cMadan for editing this submission ✨ 

@raphaelvallat - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01026/status.svg)](https://doi.org/10.21105/joss.01026)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01026">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01026/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01026/status.svg
   :target: https://doi.org/10.21105/joss.01026
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01026/status.svg)](https://doi.org/10.21105/joss.01026)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
