### ISSUE TITLE
[PRE REVIEW]: OApackage: A Python package for generation and analysis of orthogonal arrays and conference designs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1079]
**Submitting author:** @eendebakpt (<a href="http://orcid.org/0000-0001-7018-1124">Pieter Eendebak</a>)
**Repository:** <a href="https://github.com/eendebakpt/oapackage" target ="_blank">https://github.com/eendebakpt/oapackage</a>
**Version:** 2.5.1
**Editor:** @danielskatz
**Reviewers:** @djmitche, @tanaken-basis

**Author instructions**

Thanks for submitting your paper to JOSS @eendebakpt. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@eendebakpt if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by danielskatz** [comment]
👋 @eendebakpt

1) there seem to be a bunch of reference problems in the compiled PDF.  If you fix the .md, you should be able recompile here by adding a new comment that starts with:
```@whedon generate pdf```

2) Can you suggest reviewers, perhaps from [this list of people](https://bit.ly/joss-reviewers) who have already agreed to review for JOSS, or from outside the list as well.  I think it would be good to get one reviewer who can check the Python API as well as the C++ source.

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by eendebakpt** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Compile the paper
@whedon generate pdf

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper from a custom git branch
@whedon generate pdf from branch custom-branch-name

```

**Comment by eendebakpt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01079/joss.01079/10.21105.joss.01079.pdf)

**Comment by eendebakpt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01079/joss.01079/10.21105.joss.01079.pdf)

**Comment by eendebakpt** [comment]
@danielskatz Thanks for picking this up. I updated the references in the paper. As for reviewers: 

Based on Python/C++ experience: pragyansmita, katyhuff or djmitche
Based on Python and content experience: tupi

**Comment by djmitche** [comment]
I can definitely take a look!

**Comment by katyhuff** [comment]
This is somewhat outside my wheelhouse conceptually and I'm a bit overcommitted at the moment, so I should be a reviewer of last resort for this one. Hopefully @pragyansmita or @tupi are available. If not, let me know.

**Comment by djmitche** [comment]
For my reference, since I haven't reviewed anything here since volunteering, [these](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) are the reviewer guidelines.

**Comment by djmitche** [comment]
Aside from the community guidelines noted above, everything looks on the up-and-up.  I would like a general pointer in the docs or README to what the heck a Conference Design is -- it's a particularly difficult thing to search for, since there are a lot of Design Conferences out there.   A quick sentence about how this might be used would be helpful, too.  The paragraph beginning "As an example" in [EN95] was tantalizing, but of course I can't see the second page!

I took some extra time to stare at the `LICENSE` file, as it identifies some separately-licensed bits (the MPL2 bits, in particular, concern me).  However, I think this is fine: anyone using this software in an open-source context will automatically be compliant with the MPL2 license, and anyone using it in a proprietary context has the information they need available to them in `LICENSE`.  Whether that means that the package is essentially MPL2-licensed is neither something I can figure out, nor particularly important to the review.  Which is a long way of saying that it's nice to see proper attention paid to licensing, and I see nothing to be concerned about here.

I perused the C++ and Python source.  I didn't look at everything, and certainly didn't understand the meaning of much of what I saw.  But the code looks well-structured and well-documented.  Nothing seems alarming or suggestive of any systemic issues.  This looks like solid, efficient numerical software.

**Comment by danielskatz** [comment]
Thanks @djmitche  - let me try to find another reviewer, then I'll open a review issue, where you can check off stuff like you've started to do above...
Sorry for the delay.

**Comment by danielskatz** [comment]
👋 @pragyansmita & @tupi - I'm checking again to see if one of you might be willing to be the second reviewer for this submission...

**Comment by danielskatz** [comment]
Update: I've found another reviewer via email, and once I get his github username, I will add him and start the review.

**Comment by danielskatz** [comment]
@whedon assign @djmitche as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @djmitche

**Comment by danielskatz** [comment]
@whedon add @tanaken-basis as reviewer

**Comment by whedon** [comment]
OK, @tanaken-basis is now a reviewer

**Comment by danielskatz** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1097. Feel free to close this issue now!
