### ISSUE TITLE
[REVIEW]: Pyessence - Generalised Coupled Quintessence Linear Perturbation Python Code

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#108]
**Submitting author:** @leithes (<a href="http://orcid.org/0000-0001-9593-6757">Alexander Leithes</a>)
**Repository:** <a href="https://bitbucket.org/pyessence/pyessence" target ="_blank">https://bitbucket.org/pyessence/pyessence</a>
**Version:** v2.0.1
**Editor:** @jakevdp
**Reviewer:** @joergdietrich

## Status

[![status](http://joss.theoj.org/papers/4bc95a31164930b8441ad43a5812eae1/status.svg)](http://joss.theoj.org/papers/4bc95a31164930b8441ad43a5812eae1)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/4bc95a31164930b8441ad43a5812eae1"><img src="http://joss.theoj.org/papers/4bc95a31164930b8441ad43a5812eae1/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/4bc95a31164930b8441ad43a5812eae1/status.svg)](http://joss.theoj.org/papers/4bc95a31164930b8441ad43a5812eae1)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://bitbucket.org/pyessence/pyessence" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/pyessence/pyessence">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v2.0.1)?
- [x] **Authorship:** Has the submitting author (@leithes) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by joergdietrich** [comment]
It would be good if the author could enable the issue tracker over at bitbucket. Otherwise I will not be able to open issues discovered during my review.

**Comment by leithes** [comment]
Tied up at the moment - will hopefully have this done by midday.

Thank you.

Alex Leithes

On 10 November 2016 09:56:03 GMT+00:00, "Jörg Dietrich" <notifications@github.com> wrote:
>It would be good if the author could enable the issue tracker over at
>bitbucket. Otherwise I will not be able to open issues discovered
>during my review.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/openjournals/joss-reviews/issues/108#issuecomment-259647976

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by joergdietrich** [comment]
My preliminary review of Pyessence indicates that **major** modifications are required before the software can be accepted for publication in JOSS. I have started to open issues at the software issue tracker and will keep editing this comment as I add issues at the software repository and in this comment.

- **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?

Strictly speaking, no. The software uses a BSD 3-clause license with slightly
modified non-endorsement clause that protects not only the names of the
contributors but also the software name. This is not the form approved by
OSI. I'll leave it to the editors to decide whether this is a significant
departure or not.

- **Version:** Does the release version given match the GitHub release (v2.0.1)?

No release version is given in the source code repository. The user guide (arXiv:1608.00910)
refers to the "latest version".

### Functionality

- **Installation:** Does installation proceed as outlined in the documentation?

Yes, although there is unfortunately no automated installion, e.g., via
pip. The user has to download the Python code and add it to their
PYTHONPATH. The installation instructions are specific to systems with a bash
shell present.

- **Functionality:** Have the functional claims of the software been confirmed?

Unfortunately, already the example scripts mostly crash. Bitbucket issues:
* https://bitbucket.org/pyessence/pyessence/issues/4/lcdm-crashes
* https://bitbucket.org/pyessence/pyessence/issues/3/examplepad-crashes

**Performance:** Have any performance claims of the software been confirmed?

No performance claims have been made except that the code is "fast". It is
unclear what this means. Running EXAMPLE1.py takes 5m33s on my laptop without
plotting. I don't know whether this is fast and whether there are other codes
with similar functionality to compare this to.

- **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?

The user guide on arXiv contains enough information.

- **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

Python dependencies are clearly listed in the documentation. However, the user
guide states "Pyessence was written and tested using Python 2.7.3 and should
therefore work on higher versions." while Pyessence does not work with Python
3.x.

- **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

Three examples, however, two of them crash. 

-  **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?

No. The user guide gives a description of the physical problem this software
is designed to solve but any code documentation like API method documentation
is absent.

- **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?

Unfortunately, no automated tests are present. This is exacerbated by the failure of 2/3 examples distributed with the code.

- **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

No. The issue tracker on bitbucket was activated in response to this review but the documentation does not point to it yet. Neither is any preference given how to report problems or contribute to the software.

### Software paper

- **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?

Yes, the brief explanation in the README and paper.md are sufficient to outline what problems the software is designed to solve. More details are given in the user guide on arXiv.

-  **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

No, \fn4 in paper.md has a DOI that is not listed.

**Comment by jakevdp** [comment]
Thank you for the thorough review, @joergdietrich. @leithes, I hope you will take a look at the issues raise here – I think addressing them will make your software much more impactful within your community!

**Comment by arfon** [comment]
@leithes - please make sure that you move all footnotes into references in the `paper.bib` file and reference them as citations [like this](https://github.com/jgm/pandoc/wiki/Pandoc-vs-Multimarkdown#citations-and-bibliography).

**Comment by arfon** [comment]
Friendly new year reminder on this @leithes

**Comment by arfon** [comment]
> Friendly new year reminder on this @leithes

**Bump** @leithes 😁

**Comment by arfon** [comment]
:wave: @leithes - are you still working on the feedback on your submission?

**Comment by arfon** [comment]
Followed up with @leithes over email.

**Comment by arfon** [comment]
This paper has been withdrawn from JOSS on behalf of @leithes as they don't seem to be interested in pursuing this publication.

Thanks for all of your help on this @joergdietrich & @jakevdp
