### ISSUE TITLE
[PRE REVIEW]: Py-school-match: Matching algorithms to assign students to schools

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1106]
**Submitting author:** @igarizio (<a href="http://orcid.org/0000-0002-8431-516X">Iacopo Garizio</a>)
**Repository:** <a href="https://github.com/igarizio/py-school-match" target ="_blank">https://github.com/igarizio/py-school-match</a>
**Version:** 0.2.0
**Editor:** @arokem
**Reviewers:** jmhernan

**Author instructions**

Thanks for submitting your paper to JOSS @igarizio. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@igarizio if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arokem it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arokem) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01106/joss.01106/10.21105.joss.01106.pdf)

**Comment by arfon** [comment]
:wave: @igarizio, many thanks for your submission to JOSS. 

This looks like a nice piece of software, but from first inspection it doesn't appear to be _research software_. In particular, quoting from our [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements):

> - The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)

Could you please explain what the research challenge being addressed by this software is? Links to academic research on these topics would be helpful.

**Comment by igarizio** [comment]
Hi @arfon, thank you for your quick response!
I will try to explain the main problem that this software addresses:

In many countries or states where schools cannot discriminate among students (this means, no tests, no interviews, no previous grades examination, etc.), there is a problem that always appears: How to assign students fairly and efficiently.
There are many proposed solutions. One could think that a simple "lottery" (random assignation) could solve the problem, but this overlooks the fact that there may be better alternatives where EVERY student is better off.
For example, imagine 2 students (S1 and S2) and 2 schools (A and B), with this preferences: 
S1: A > B (S1 wants to go to A)
S2: B > A (S2 wants to go to B)

A simple "lottery" could result in S1 going to B, and S2 going to A (both students are assigned to their worst option).
Here is where the algorithms come into play: If we apply, for example, Stable Improvement Cycles (SIC) we would get, S1 going to A and S2 going to B. In this assignation both students are better off. 
In the real world, the problems are not as straightforward as the one above, because of many restrictions, different preferences, among others. This means that there is no one-size-fits-all algorithm. The only way to select the best algorithm is to simulate the country's conditions and possible student's preferences and evaluate the resulting assignation.

The software helps researchers focus on the "simulation" and the "selection of the best algorithm" parts, as they do not have to develop from zero all the available algorithms in order to recommend an assignation mechanism.

While there are other libraries that implement matching algorithms, none of those (as far as I know) have the capability to implement quotas, restrictions, etc. (which is the most common case for the majority of countries/states [I actually do not know any country that does not have any sort of special restriction]).

Here are some publications that research that exact problem (and that could have been benefited with the package):
- Evaluation for Boston: https://economics.mit.edu/files/3021
- Evaluation for New York: https://seii.mit.edu/wp-content/uploads/2011/12/Paper-New-York-City-High-School-Math.pdf
 A more in-depth comparison/description: https://economics.mit.edu/files/3962
- I also made a comparison for the Chilean school system (where I recommend changing the current mechanism), if you want to see that one too, I will happily upload a copy.
- Also, If needed I can provide more technical information explaining the algorithms.

I am sorry for writing such a long text!
Thank you!

**Comment by arokem** [comment]
@whedon assign arokem as editor

**Comment by whedon** [comment]
OK, the editor is arokem

**Comment by igarizio** [comment]
Thank you @arokem!
I will add those explanations as soon as possible.

**Comment by jmhernan** [comment]
@arokem I'd love to review this article.

**Comment by arokem** [comment]
@whedon assign jmhernan as reviewer

**Comment by whedon** [comment]
OK, the reviewer is jmhernan

**Comment by arokem** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1111. Feel free to close this issue now!

**Comment by arokem** [comment]
@jmhernan : thanks for taking this on! Head over to the auspiciously numbered #1111 for the check-list for your review. I'll close this.
