### ISSUE TITLE
[REVIEW]: SurvivalVolume: interactive volume threshold survival graphs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#111]
**Submitting author:** @genomematt (<a href="http://orcid.org/0000-0001-6624-4698">Matthew J Wakefield</a>)
**Repository:** <a href="https://github.com/genomematt/survivalvolume" target ="_blank">https://github.com/genomematt/survivalvolume</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewer:** @janschulz
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.200268" target="_blank">10.5281/zenodo.200268</a>

## Status

[![status](http://joss.theoj.org/papers/2876777be3db1050198a70bb6a8306a9/status.svg)](http://joss.theoj.org/papers/2876777be3db1050198a70bb6a8306a9)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/2876777be3db1050198a70bb6a8306a9"><img src="http://joss.theoj.org/papers/2876777be3db1050198a70bb6a8306a9/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/2876777be3db1050198a70bb6a8306a9/status.svg)](http://joss.theoj.org/papers/2876777be3db1050198a70bb6a8306a9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/genomematt/survivalvolume" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/genomematt/survivalvolume">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@genomematt) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00111.pdf](https://github.com/openjournals/joss-reviews/files/594733/10.21105.joss.00111.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@janschulz - I've just added the compiled paper PDF for your review.

**Comment by genomematt** [comment]
hi @janschulz do you need anything else from me to progress this?

**Comment by janschulz** [comment]
@genomematt Will take the time tomorrow evening. Sorry for the long wait :-/

**Comment by genomematt** [comment]
’Tis the season to be overworked.  Thanks.

On 8 Dec. 2016, at 8:07 am, Jan Schulz <notifications@github.com<mailto:notifications@github.com>> wrote:


@genomematt<https://github.com/genomematt> Will take the time tomorrow evening. Sorry for the long wait :-/

**Comment by janschulz** [comment]
Create a new conda env with `conda create -n "survivalvolume" python=3.5 matplotlib mpld3 lifelines scipy pandas numpy xlrd ipykernel` -> worked like a charm :-) 

* License is GPL V3 -> :heavy_check_mark: 
* Version in github and pip is v1.0.0b1 :question: 
* most commits come from @genomematt :heavy_check_mark: 
* installation works as outlines (ok, had to use `pip` instead of `pip3`, but both pypi and git works)
* Functionality: I went through the ipynb and the plots showed up as described. :heavy_check_mark: 
* Performance: no performance claims were maid but with the ipynb with example data, there was no performance problem. :heavy_check_mark: 

* Statement of need: "A set of tools for parsing measurement with threshold over time data (eg tyre wear, tumour treatment studies) and generating interactive and static plots". as a not-from-that-field guy, I have actually no idea what I can do with that, but I guess if you working in that field you do -> a sentence of who the target audience is would have helped me. The description in the paper is actually longer and and I actually understood it a bit :-) -> I give the paper version a "passed" because my feeling is that it contains all the buzzwords needed to get the attention of people in the field and I got the impression that I can't use it to do a customers survival analysis (If I could, please talk to me :-)) but please copy that to the real docs as well :question: 
* Api Docs: https://genomematt.github.io/survivalvolume/docs/parse.m.html has garbled parameter docs (=they do not show up in bold like in https://genomematt.github.io/survivalvolume/docs/plot.m.html) -> https://github.com/genomematt/survivalvolume/issues/2, otherwise :heavy_check_mark: 
* travis shows 18 tests. Test coverage seems ok, some tests even check matplotlib internal stuff (you might like [pytest-mpl](https://pypi.python.org/pypi/pytest-mpl) to test plots directly) :heavy_check_mark: 
* guidelines: short and to the point :heavy_check_mark: 

# Paper
* authors have OrcIDs :+1: and affiliations :heavy_check_mark: 
* statement of need: see above: :heavy_check_mark: 
* DOIs are shown where I think they are available

# open
- verison: 1.0.0 vs beta?
- It would be nice if the readme doc gets the "statement of need" from the paper

**Comment by genomematt** [comment]
Thanks @janschulz I will fix those documentation issues, and mint a final 1.0.0 version (that was the purpose of being still a beta release).

**Comment by genomematt** [comment]
Ok @janschulz genomematt@c1cba47e490f766affffc2f108915a57bd5b0b87 should fix all the outstanding issues.
Uploaded to PyPI and new Zenodo DOI is 10.5281/zenodo.200268

**Comment by genomematt** [comment]
As far as retention rate analysis / customer survival analysis there is only one potential way of parameterising that would make sense for survivalvolume.  If you had an activity measure you could use this in place of volume.  The obvious one would be days (or minutes) of inactivity, and then at a threshold you would declare them inactive.  Probably better with cumulative days of inactivity so it increases monotonically.  You could then look at patterns of inactivity in the activity graph, mouse over a specific customer etc.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.200268 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.200268" target="_blank">10.5281/zenodo.200268</a> is the archive.

**Comment by arfon** [comment]
@janschulz can you confirm we're good to accept here?

**Comment by janschulz** [comment]
@arfon: yes, i looked at the new readme and the version and bot LGTM :-)

@genomematt Thanks for the timely response, especially after I let this slide!  :-/

**Comment by janschulz** [comment]
@genomematt Ah, and also thank you for your explanation on using it for customer retention analysis!

**Comment by arfon** [comment]
Thanks for the review @janschulz ✨ 

@genomematt - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00111 ⚡️ 🚀 💥
