### ISSUE TITLE
[PRE REVIEW]: Assembling a Historical National Drug Code Directory from the Internet Archive

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1128]
**Submitting author:** @mhowison (<a href="http://orcid.org/0000-0002-0764-4090">Mark Howison</a>)
**Repository:** <a href="https://github.com/ripl-org/historical-ndc" target ="_blank">https://github.com/ripl-org/historical-ndc</a>
**Version:** 20181212
**Editor:** @trallard
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @mhowison. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mhowison if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1128 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    239      0 --:--:-- --:--:-- --:--:--   242
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.01128.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01128/joss.01128/10.21105.joss.01128.pdf)

**Comment by arfon** [comment]
:wave: @trallard - would you be willing to edit this submission for JOSS?

**Comment by danielskatz** [comment]
👋 @trallard - ping...

**Comment by trallard** [comment]
sorry @arfon @danielskatz I have been off the radar over the holidays but now I can take up on this submission

**Comment by danielskatz** [comment]
@whedon assign @trallard as editor

**Comment by whedon** [comment]
OK, the editor is @trallard

**Comment by labarba** [comment]
👋  @trallard — We haven't seen movement on this thread for a while. Are you working offline to find reviewers? Give us a quick update here, or request help, if you need it. Thanks!

**Comment by trallard** [comment]
Thanks for your submission to JOSS  @mhowison and apologies for the delay in moving this. 
 
Unfortunately, this submission is not acceptable to JOSS as it falls into the 'minor utility' category:

> The software should be feature complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications). Minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable.

**Comment by mhowison** [comment]
Hi @trallard, thank you for your response and for taking the time to consider our submission. I realize this is a volunteer effort on your part!

The criteria used to reject our submission were that it is not feature complete and designed for maintainable extension. We would very much appreciate if you could elaborate on this based on our questions below, so that we can understand the basis of the decision. We did review both of those criteria before we submitted and felt that our package met them.

We designed the package to extract all necessary information to solve the stated problem of identifying and classifying drugs based on ingredient. This is a problem facing all scientists who work with medical claims data on prescription drugs. There are no open-source resources we could identify that currently exist to solve this problem - there are only commercially-licensed options. We further demonstrated that out package works on a real problem related to opioid prescriptions. **Which specific feature do you believe we failed to include in the package to solve the problem of identifying and classifying prescription drugs?**

We also designed the package to be maintainable and extendable. To maintain a current snapshot of Internet Archive data, we included a set of scripts that update the list of Internet Archive timestamps (https://github.com/ripl-org/historical-ndc/tree/master/InternetArchive). This allows the package to remain current and provide researchers with up-to-date prescription drug information as the FDA releases new versions of the NDC.

Our included classification of opioid drugs (https://github.com/ripl-org/historical-ndc/blob/master/lib/opioids.py) is extendable both to alternative threshold amounts for opioids, as well as to other classes of drugs.

**Which specific part of the package were you concerned about not being maintainable or extendable?**

Thank you for considering our questions above - your responses will help us to improve the package!

cc @labarba @whedon @danielskatz @arfon

**Comment by arfon** [comment]
Hi @mhowison, thanks for the followup question. Just to clarify, there are actually a few criteria wrapped up in this statement and it's the latter-half of the statement that we feel applies to your submission:

> Minor ‘utility’ packages, including ‘thin’ API clients, are not acceptable.

Packages like yours present an editorial challenge for us at JOSS: There's clearly value to wrapping APIs/data services like this tool does however we feel it necessary to put some kind of lower limit on the threshold of complexity/effort required to build a particular tool. In your case, we feel like this submission didn't quite reach that standard.

**Comment by mhowison** [comment]
Ok, thank you for clarifying @arfon. I would suggest adding more clarification to the information for authors page, since it wasn't very clear to us when we submitted what a minor utility or thin API client is (especially since those terms are in quotes). My understanding now is that JOSS does not accept papers that are primarily about new data resources (which is understandable since there are other journals specifically geared toward describing new data resources). It would help prevent future confusion if you made that more explicit in the instructions though!
