### ISSUE TITLE
[REVIEW]: BoltzMM: an R package for maximum pseudolikelihood estimation of fully-visible   Boltzmann machines

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1193]
**Submitting author:** @andrewthomasjones (<a href="http://orcid.org/0000-0003-1324-703X">Andrew Jones</a>)
**Repository:** <a href="https://github.com/andrewthomasjones/BoltzMM" target ="_blank">https://github.com/andrewthomasjones/BoltzMM</a>
**Version:** 0.1.3
**Editor:** @yochannah
**Reviewer:** @ja-thomas, @schalkdaniel
**Archive:** <a href="https://doi.org/10.5281/zenodo.2563411" target="_blank">10.5281/zenodo.2563411</a>

## Status

[![status](http://joss.theoj.org/papers/23eb189a5e0bdd2b51f668621abcc75a/status.svg)](http://joss.theoj.org/papers/23eb189a5e0bdd2b51f668621abcc75a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/23eb189a5e0bdd2b51f668621abcc75a"><img src="http://joss.theoj.org/papers/23eb189a5e0bdd2b51f668621abcc75a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/23eb189a5e0bdd2b51f668621abcc75a/status.svg)](http://joss.theoj.org/papers/23eb189a5e0bdd2b51f668621abcc75a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/andrewthomasjones/BoltzMM" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ja-thomas & @schalkdaniel, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @yochannah know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/andrewthomasjones/BoltzMM">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.3)?
- [x] **Authorship:** Has the submitting author (@andrewthomasjones) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/andrewthomasjones/BoltzMM">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.3)?
- [x] **Authorship:** Has the submitting author (@andrewthomasjones) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ja-thomas, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01193/joss.01193/10.21105.joss.01193.pdf)

**Comment by ja-thomas** [comment]
Major comments:

- The second author of the paper "Jessica J. Bagnall" does not seem to have commits to the repository. It might be a good idea to specify the contributions of every author in the README. 

- The tests cannot be reproduced with the instructions in the README

- 5 out of 11 tests fail when running locally, after calling `devtools::document()` and `devtools::test()`, all with `XXX has changed from known value recorded in XXX`. (See https://github.com/andrewthomasjones/BoltzMM/issues/3)



Minor comments:

- Using the shortcut `T` for `TRUE` is rather bad practice in R since it can be easily overwritten as a variable. (As done in the installation instructions)  
- `knn.impute` produces warnings in the example
- Installation works (with Ubuntu 18.04). Since the version is on CRAN, installation on windows should have been checked by the WINbuilder. It still might be a good idea to add continuous integration for Linux (with Travis) and Windows (with Appveyor). Especially considering the above problems with reproducing the tests  
- A reference to the paper given the theoretical framework for this method would be nice. (Or the JOSS paper, since it contains/references the required backround).

**Comment by hiendn** [comment]
Hi @ja-thomas, thank you for taking the time to review our paper! We very much appreciate your time and effort! 😊

I will reply to some of your comments now, and @andrewthomasjones will reply to the others at a later stage. 

> The second author of the paper "Jessica J. Bagnall" does not seem to have commits to the repository. It might be a good idea to specify the contributions of every author in the README.

Unfortunately, Jessica is not actively on GitHub (we will persuade her, yet!) and has therefore made most of her contributions via commits by @andrewthomasjones and I. She has made numerous contributions to the paper via the documentation of the package, the `senate` data set that she had supplied and analysed from her paper https://hal.archives-ouvertes.fr/hal-01927188v1. As well as with identifying and helping to fix various bugs that were in previous versions of the code.

We have now included an **Authorship statement** section in the README in order to highlight the contributions of each of the three co-authors of the package.

> knn.impute produces warnings in the example

Unfortunately, this cannot be help. No matter how the data is processed or preprocessed before conducting imputation, `NA`s will be created since there is presence of missingness. Thus, a warning **MUST** be signalled at some part in time in the workflow. Since it is a little bit unsightly to have *warning* messages in the README, we have opted to use a `suppressWarnings()` command in order to make the output more pleasing to the eye.

> A reference to the paper given the theoretical framework for this method would be nice. (Or the JOSS paper, since it contains/references the required backround).

This was a great idea! We have now included a **Technical references** section in the README to address this comment.

> There is no citation information in the README. At least the same information as `citation("BoltzMM")` should be given in the README

Again, great idea! We have now included a **Reference to package** section in the README that contains exactly the output of the command `citation("BoltzMM")` as you have suggested.

Thanks again for your time, @ja-thomas. It is very much appreciated.

**Comment by ja-thomas** [comment]
great, thanks for the quick reply and fix. 

I guess the only point open from my side are the issues with the tests discussed here https://github.com/andrewthomasjones/BoltzMM/issues/3. When this is resolved everything is fine from my side.

**Comment by ja-thomas** [comment]
all done from my side :+1:

**Comment by yochannah** [comment]
Okay, looking good! @ja-thomas and @schalkdaniel thanks for reviewing. 😄 

@schalkdaniel - You still have a couple of checkboxes unchecked. When you get a moment could you let us know if your concerns are resolved, or if not what needs to be done? 👍

**Comment by schalkdaniel** [comment]
All done from my side too. Everything looks great. 👍

**Comment by yochannah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01193/joss.01193/10.21105.joss.01193.pdf)

**Comment by yochannah** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1002/widm.1198 may be missing for title: An introduction to MM algorithms for machine learning and statistical estimation
- https://doi.org/10.1198/0003130042836 may be missing for title: A tutorial on MM algorithms
- https://doi.org/10.1109/tnnls.2015.2425898 may be missing for title: Asymptotic normality of the maximum pseudolikelihood estimator for fully visible Boltzmann machines
- https://doi.org/10.1162/neco_a_00813 may be missing for title: A block successive lower-bound maximization algorithm for the maximum pseudolikelihood estimation of fully visible Boltzmann machines
- https://doi.org/10.1090/conm/080/999014 may be missing for title: Composite likelihood methods
- https://doi.org/10.1055/a-0732-9020 may be missing for title: Pseudolikelihood estimation: some examples
- https://doi.org/10.2307/2346482 may be missing for title: The analysis of multivariate binary data
- https://doi.org/10.1162/neco.2006.18.10.2283 may be missing for title: Consistency of pseudolikelihood estimation of fully visible Boltzmann machines
- https://doi.org/10.1162/neco.2008.04-07-510 may be missing for title: Representation power of restricted Boltzmann machines and deep belief networks
- https://doi.org/10.1016/s0364-0213(85)80012-4 may be missing for title: A learning algorithm for Boltzmann machines

INVALID DOIs

- None
```

**Comment by yochannah** [comment]
hmm, this is strange - these DOIs all seem to resolve correctly when I click on them. 

I note there is a space as the last character for some of the DOIs which maybe we should fix, but that's only present on three so presumably can't be affecting them all! 

- https://doi.org/10.1162/NECO_a_00813
- https://doi.org/10.1162/neco.2006.18.10.2283
- https://doi.org/10.1002/widm.1198 

@andrewthomasjones - it might be a good idea to remove those spaces from https://github.com/andrewthomasjones/BoltzMM/blob/master/paper.bib just in case? 

@arfon  / @openjournals/joss-eics - any idea what has whedon grumpy - something I missed or misunderstood maybe?

**Comment by hiendn** [comment]
Hi @yochannah, spaces have now been removed. I also clicked on all of the links and they all seem to correctly direct to the papers. So 🤷‍♂️? Thank you for you editorial work! 🙇

**Comment by arfon** [comment]
@yochannah - I've tried fixing the whitespace issue in https://github.com/openjournals/whedon-api/commit/c1d4e5e5c0bdb343207bf19e2dee2e2e8bd7304b.

**Comment by arfon** [comment]
More generally though, I think the issue is these should be `doi` fields, not `urls`, i.e. https://github.com/andrewthomasjones/BoltzMM/blob/master/paper.bib#L28 should be:

```
doi = {https://doi.org/10.1007/978-1-4614-6868-4}
```

**Comment by hiendn** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01193/joss.01193/10.21105.joss.01193.pdf)

**Comment by hiendn** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01193/joss.01193/10.21105.joss.01193.pdf)

**Comment by hiendn** [comment]
Hi @arfon and @yochannah, I've changed everything that should be a DOI from URL to DOI. There are a couple of items left that do not have DOIs, so I left them as URL. I hope that this resolves the issue! 😄

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/https://doi.org/10.1002/widm.1198 is OK
- http://doi.org/https://doi.org/10.1198/0003130042836 is OK
- http://doi.org/https://doi.org/10.1109/TNNLS.2015.2425898 is OK
- http://doi.org/https://doi.org/10.1162/NECO_a_00813 is OK
- http://doi.org/http://dx.doi.org/10.1090/conm/080/999014 is OK
- http://doi.org/https://doi.org/10.1162/neco.2006.18.10.2283 is OK
- http://doi.org/https://doi.org/10.1162/neco.2008.04-07-510 is OK
- http://doi.org/https://doi.org/10.1016/S0364-0213(85)80012-4 is OK

MISSING DOIs

- https://doi.org/10.1055/a-0732-9020 may be missing for title: Pseudolikelihood estimation: some examples
- https://doi.org/10.2307/2346482 may be missing for title: The analysis of multivariate binary data

INVALID DOIs

- None
```

**Comment by hiendn** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/https://doi.org/10.1002/widm.1198 is OK
- http://doi.org/https://doi.org/10.1198/0003130042836 is OK
- http://doi.org/https://doi.org/10.1109/TNNLS.2015.2425898 is OK
- http://doi.org/https://doi.org/10.1162/NECO_a_00813 is OK
- http://doi.org/http://dx.doi.org/10.1090/conm/080/999014 is OK
- http://doi.org/https://doi.org/10.2307/2346482 is OK
- http://doi.org/https://doi.org/10.1162/neco.2006.18.10.2283 is OK
- http://doi.org/https://doi.org/10.1162/neco.2008.04-07-510 is OK
- http://doi.org/https://doi.org/10.1016/S0364-0213(85)80012-4 is OK

MISSING DOIs

- https://doi.org/10.1055/a-0732-9020 may be missing for title: Pseudolikelihood estimation: some examples

INVALID DOIs

- None
```

**Comment by hiendn** [comment]
@arfon , it doesn't look like a DOI exists anywhere on the internet for that last paper, unfortunately. 😞

**Comment by arfon** [comment]
> @arfon , it doesn't look like a DOI exists anywhere on the internet for that last paper, unfortunately. 

That's OK. These are only meant to be suggestions - it's fine to have references without DOIs if there isn't one.

**Comment by hiendn** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01193/joss.01193/10.21105.joss.01193.pdf)

**Comment by yochannah** [comment]
@arfon thanks for clarifying what the issue was and @hiendn thank you for resolving the issues! :+1:

**Comment by yochannah** [comment]
@hiendn @andrewthomasjones - at this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive?  It's probably worth giving the manuscript a final proofread if you feel you need to, as well. 👍

**Comment by hiendn** [comment]
Hi @yochannah! Thank you for handling the editorial process. the Zenodo DOI/link is http://doi.org/10.5281/zenodo.2538256. And I have given the paper a final proof read and it is all good to go! 😄

**Comment by labarba** [comment]
👋  @hiendn — Could you edit the title in Zenodo so it matches the title of the JOSS paper? Thanks!

**Comment by labarba** [comment]
@whedon set10.5281/zenodo.2563411 as archive

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.2563411 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2563411" target="_blank">10.5281/zenodo.2563411</a> is the archive.

**Comment by hiendn** [comment]
Hi @labarba, the Zenodo archive name has been changed to match the paper title 😄.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/https://doi.org/10.1002/widm.1198 is OK
- http://doi.org/https://doi.org/10.1198/0003130042836 is OK
- http://doi.org/https://doi.org/10.1109/TNNLS.2015.2425898 is OK
- http://doi.org/https://doi.org/10.1162/NECO_a_00813 is OK
- http://doi.org/http://dx.doi.org/10.1090/conm/080/999014 is OK
- http://doi.org/https://doi.org/10.2307/2346482 is OK
- http://doi.org/https://doi.org/10.1162/neco.2006.18.10.2283 is OK
- http://doi.org/https://doi.org/10.1162/neco.2008.04-07-510 is OK
- http://doi.org/https://doi.org/10.1016/S0364-0213(85)80012-4 is OK

MISSING DOIs

- https://doi.org/10.1055/a-0732-9020 may be missing for title: Pseudolikelihood estimation: some examples

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/491

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/491, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@hiendn — I'm going to have a few more editorial fixes to request.

¶1
that is able densely represent >> is able _to_ 
when d is large and sample size n >> what about the sample size? (missing a verb and parallel construction)

In general, I find the whole first page really jargon-heavy and I wonder if you would consider editing this to be more readable. E.g., what is "latent variable construction"? Do you mean the same by "complex form" and "elaborate form" And what _do_ you mean by that? Jus that it's hard to implement? Or is it really "intractable"? Because then you talk about a "tractable simplification" ... so many big words. Are they all necessary for the JOSS audience to plough through, to finally learn what the software does on page 2?

Many of your DOIs are not resolving because you have a full URL instead of the DOI in the BibTeX field, so the link appears broken. Please check.

**Comment by labarba** [comment]
Page 2:
All of the functions that have been comprehensively documented >> delete "that"
Furthermore, the analysis of data arising from… >> Unclear how this sentence is connected with the previous and the need for "Furthermore" 
complimentary >> complementary (meaning: flattering versus supportive)

It's not necessary to include the GitHub repo address or the archive address in the text, because they will appear linked in the page-1 margin of the formatted paper, and will also be linked on the paper web page. Please remove.

Overall:
I suggest a pass of ruthless editing for clarity and conciseness. For example, how does one know the difference between "comprehensively documented" and "documented," between a report that "describes" versus "clearly describes"? What is "particularly computationally intensive" versus just "computationally intensive"? When is a package "sufficiently suitable" versus "suitable"?

What I'm trying to say, as an editor, is that the paper is too long and a slog to read, and I hope you can give it a bit of a clean.

Also, note the [Author Guideline](https://joss.readthedocs.io/en/latest/submitting.html) that says to "include in the paper some sentences that would explain the software functionality and domain of use to a non-specialist reader."

**Comment by hiendn** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1002/widm.1198 is OK
- http://doi.org/10.1198/0003130042836 is OK
- http://doi.org/10.1109/TNNLS.2015.2425898 is OK
- http://doi.org/10.1162/NECO_a_00813 is OK
- http://doi.org/10.1090/conm/080/999014 is OK
- http://doi.org/10.2307/2346482 is OK
- http://doi.org/10.1162/neco.2006.18.10.2283 is OK
- http://doi.org/10.1162/neco.2008.04-07-510 is OK
- http://doi.org/10.1016/S0364-0213(85)80012-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by hiendn** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01193/joss.01193/10.21105.joss.01193.pdf)

**Comment by hiendn** [comment]
Hi @labarba, thank you for the very comprehensive technical editing of the paper! 🙇 Your careful reading and many suggestions have been incredibly helpful in my reorganisation of the paper to be more suitable for the lay audience of the journal. Please find my responses to your comments, below. I hope that I have addressed all of your concerns . 😄

**@hiendn — I'm going to have a few more editorial fixes to request.

¶1
that is able densely represent >> is able _to_**

---In light of your comments below, regarding jargon, I have chosen to replace the word densely represent, with 'closely approximate', which I feel can be interpreted at face value by a lay reader, without the need for a dive into approximation theoretic nomenclature. The grammar of the sentence has also been fixed in order to comply with the new phraseology.

**when d is large and sample size n >> what about the sample size? (missing a verb and parallel construction)**

---Thanks for pointing out the typo, I have now change it to 'when both dimension $d$ and sample size $n$ are large.'

**In general, I find the whole first page really jargon-heavy and I wonder if you would consider editing this to be more readable.** 

---Thank you for this comment. I suppose that I am new to writing more lay focused papers and so a lot of my technical writing habits come through. In what follows, I endeavour to choose better words that are meaningful to a lay audience, but do not detract from the technical meaning, either.

**E.g., what is "latent variable construction"?**

---'Latent variable construction' is now replaced by 'requirement for hidden (or unobserved) variables'.

**Do you mean the same by "complex form" and "elaborate form" And what _do_ you mean by that? Jus that it's hard to implement? Or is it really "intractable"? Because then you talk about a "tractable simplification" ... so many big words.** 

---You are correct in inferring that all of these phrases are just my attempt to not be repetitively writing 'intractable' over and over again. Although, with your comments in mind, I have now combed the document for unnecessary instances of words that could be replaced by things with more meaning to the reader.

**Are they all necessary for the JOSS audience to plough through, to finally learn what the software does on page 2?**

---I have rearranged the paragraphs of the article to be more direct in presenting the core value of the software to the reader, before going on a tangent with what the model that underlies the software is, and its history.

**Many of your DOIs are not resolving because you have a full URL instead of the DOI in the BibTeX field, so the link appears broken. Please check.
[EDIT] To clarify, the links come out as `https://doi.org/https://doi.org/10.1016/S0364-0213(85)80012-4` which don't resolve.**

---The http... bits of the string, up to the DOIs have now been removed from each of the references. Thank you for this correction. I didn't know how the system was handling the DOIs and thought that all of the OKs from the reference checks meant that I must have been doing the right thing.

**Page 2:
All of the functions that have been comprehensively documented >> delete "that"**

---'that' has been deleted.

**Furthermore, the analysis of data arising from… >> Unclear how this sentence is connected with the previous and the need for "Furthermore"**

---'Furthermore' has been removed.

**complimentary >> complementary (meaning: flattering versus supportive)**

---I get these two wrong all of the time. Thank you for the correction!

**It's not necessary to include the GitHub repo address or the archive address in the text, because they will appear linked in the page-1 margin of the formatted paper, and will also be linked on the paper web page. Please remove.**

---Github repo and archive addresses have been removed.

**Overall:
I suggest a pass of ruthless editing for clarity and conciseness. For example, how does one know the difference between "comprehensively documented" and "documented," between a report that "describes" versus "clearly describes"? What is "particularly computationally intensive" versus just "computationally intensive"? When is a package "sufficiently suitable" versus "suitable"?**

---You've caught me out on one of my quirks of being overly generous with adjectives and adverbs usage. The document has been combed for the over abundance of such phraseology.

**What I'm trying to say, as an editor, is that the paper is too long and a slog to read, and I hope you can give it a bit of a clean.**

---Point taken. I have rearranged the document so that the interesting software stuff is at the start and the more technical stuff, which I would still like to include for completeness, appears afterwards. 

**Also, note the [Author Guideline](https://joss.readthedocs.io/en/latest/submitting.html) that says to "include in the paper some sentences that would explain the software functionality and domain of use to a non-specialist reader."**

---I have included the following sentence for non-specialist readers: "Simply put, the FVBM is a model that allows for the characterization of interactions between multiple binary random variables, simultaneously."

**Comment by labarba** [comment]
Thanks, @hiendn.

¶1
The FVBM was  first in Hyvarinen (2006) >> missing verb?

**Comment by hiendn** [comment]
@labarba haha thanks for spotting the typo; 'considered' was the missing verb. Now included. Its amazing what you end up mentally filling in when you proof read your own writing.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- http://doi.org/10.1002/widm.1198 is OK
- http://doi.org/10.1198/0003130042836 is OK
- http://doi.org/10.1109/TNNLS.2015.2425898 is OK
- http://doi.org/10.1162/NECO_a_00813 is OK
- http://doi.org/10.1090/conm/080/999014 is OK
- http://doi.org/10.2307/2346482 is OK
- http://doi.org/10.1162/neco.2006.18.10.2283 is OK
- http://doi.org/10.1162/neco.2008.04-07-510 is OK
- http://doi.org/10.1016/S0364-0213(85)80012-4 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/494

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/494, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/495
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01193](https://doi.org/10.21105/joss.01193)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @hiendn, your paper is now published!

And sincere thanks to the handling editor, @yochannah, and the reviewers, @ja-thomas, and @schalkdaniel 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01193/status.svg)](https://doi.org/10.21105/joss.01193)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01193">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01193/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01193/status.svg
   :target: https://doi.org/10.21105/joss.01193
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01193/status.svg)](https://doi.org/10.21105/joss.01193)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
