### ISSUE TITLE
Submission: mst_clustering: Clustering via Minimum Spanning Trees

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#12]
**Submitting author:** @jakevdp (<a href="http://orcid.org/0000-0002-9623-3401">Jacob VanderPlas</a>)
**Repository:** <a href="http://github.com/jakevdp/mst_clustering" target="_blank">http://github.com/jakevdp/mst_clustering</a>
**Version:** v1.0.0
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.50995" target ="_blank">http://dx.doi.org/10.5281/zenodo.50995</a>

## Status

[![status](http://joss.theoj.org/papers/0b73d249cd34985b6fa1a5ad4f4f8014/status.svg)](http://joss.theoj.org/papers/0b73d249cd34985b6fa1a5ad4f4f8014)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0b73d249cd34985b6fa1a5ad4f4f8014"><img src="http://joss.theoj.org/papers/0b73d249cd34985b6fa1a5ad4f4f8014/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0b73d249cd34985b6fa1a5ad4f4f8014/status.svg)]http://joss.theoj.org/papers/0b73d249cd34985b6fa1a5ad4f4f8014
```

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="http://github.com/jakevdp/mst_clustering">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Archive:** Does the <a target="_blank" href="http://dx.doi.org/10.5281/zenodo.50995">software archive</a> resolve?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have the performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Compiled paper PDF: [paper.pdf](https://github.com/openjournals/joss-reviews/files/249940/paper.pdf)

**Comment by whedon** [comment]
Hi @jakevdp. Many thanks for submitting to JOSS!

The next step is to look for a couple of reviewers - if you have any suggestions please add them here. :rocket:

**Comment by jakevdp** [comment]
I notice that the generated PDF doesn't have any link or reference to github or the software DOI – are authors meant to put that in explicitly? I would have expected it to be included automatically somehow.

**Comment by arfon** [comment]
> I notice that the generated PDF doesn't have any link or reference to github or the software DOI – are authors meant to put that in explicitly? I would have expected it to be included automatically somehow.

Good catch. I've been meaning to add that but completely forgot. Thanks for the reminder!

**Comment by whedon** [comment]
Compiled paper PDF: [paper.pdf](https://github.com/openjournals/joss-reviews/files/253261/paper.pdf) (now including software repository address and archive)

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers anyone interested in reviewing this?

**Comment by nicoguaro** [comment]
I am writing this _review_ following the points stated above. The software provides the implementation of a particular algorithm for clustering.

# General checks

- License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?

    Yes, the license is [2-clause BSD license](https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_.28.22Simplified_BSD_License.22_or_.22FreeBSD_License.22.29). I think it can be helpful to provide this information explicitly.

- Version: Does the release version given match the GitHub release (v1.0.0)?

    No. The version that is installed when I run `pip install mst_clustering` is 0.1.

- Archive: Does the software archive resolve?

    Yes.

# Functionality

- Installation: Does installation proceed as outlined in the documentation?

    Yes.

- Have the functional claims of the software been confirmed?

    Yes.

- Performance: Have the performance claims of the software been confirmed?

    I could not find a claim about performance.

# Documentation

- A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

    Partially. It does state what the algorithm does, but it does not say what the target audience is.

- Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

    Yes.

- Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

    Yes. The repository includes an IPython notebook with this purpose.

- Functionality documentation: Is the functionality of the software documented to a satisfactory level (e.g. API method documentation)?

    Partially. Besides the examples provided in the IPython notebook there are not more documentation and functions do not have `docstrings`.

- Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?

    The tests run ok using `nosetests test_mst_clustering.py`. But they make a relative reference instead of instead of importing the package. I suggest to change line 11 of this [script](https://github.com/jakevdp/mst_clustering/blob/master/mst_clustering/tests/test_mst_clustering.py).

- Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

    No. Recommend editing README.md to make clear. It does include a description about [How to make new releases](https://github.com/jakevdp/mst_clustering/blob/master/HOWTO_RELEASE.md).

# Software Paper

- Authors: Does the paper.md file include a list of authors with their affiliations?

    Yes.

    
- A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

    Partially. It does state what the algorithm does, but it does not say what the target audience is.


-References: Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

    I am not sure to understand this point, but none of the references have a DOI.

Since I am not sure about the procedures I do not know if it should be recommended to continue the process.

**Comment by arfon** [comment]
@nicoguaro - many thanks for this review :zap: I'll let @jakevdp reply to some of your questions here.

> References: Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

This questions is about items in the references. Published papers and datasets will usually have a DOI and so either are cited then we would like the author to include the DOI in the reference too.

> Since I am not sure about the procedures I do not know if it should be recommended to continue the process.

@nicoguaro - is it safe to assume that if your comments are addressed then you recommend this for publication?

@jakevdp - it looks like there are a couple of quick things to address here.

**Comment by nicoguaro** [comment]
@arfon - yes, I think that.

**Comment by jakevdp** [comment]
@nicoguaro – thanks for the review! I'll try to address everything you brought up.

One question regarding documentation: you mentioned that functions do not have docstrings, but the class and both its methods defined by the module [*do* have doc-strings](https://github.com/jakevdp/mst_clustering/blob/master/mst_clustering/_mst_clustering.py). Can you point me to what was specifically concerning you?

Also, since this is basically a module with a single method, I felt that an example notebook would be much more useful than a typical sphinx/readthedocs-style website. Do you feel the current setup is sufficient for a potential user, or should I do the extra work to create a separate docs website?

Thanks

**Comment by nicoguaro** [comment]
@jakevdp – thanks for taking the comments into consideration.

Regarding the documentation, I apologize, I see the docstrings now. I use Spyder regularly, and the `Ctrl + i` hotkey to render docstrings through `sphinx`... but it did not work before. But the docstrings are there and they can be pulled.

I also agree that the example notebook is good enough, maybe you would like to compare the results with some other method, but that is just a suggestion.

**Comment by arfon** [comment]
@jakevdp @nicoguaro - just checking in on this.

**Comment by jakevdp** [comment]
I need to address comments. I've been wrapped up with finishing and astropy PR by tomorrow to get it into v1.2 :smile:

**Comment by jakevdp** [comment]
OK – I've pushed updates to the mst_clustering repository addressing all of @nicoguaro's concerns. What's the next step @arfon?

**Comment by arfon** [comment]
> OK – I've pushed updates to the mst_clustering repository addressing all of @nicoguaro's concerns. What's the next step @arfon?

@nicoguaro - are we good to accept?

**Comment by nicoguaro** [comment]
@arfon - We are good to accept. I just installed it in a different computer to check, and everything seems alright.

**Comment by arfon** [comment]
> @arfon - We are good to accept. I just installed it in a different computer to check, and everything seems alright.

👍

**Comment by arfon** [comment]
Thanks all! http://dx.doi.org/10.21105/joss.00012
