### ISSUE TITLE
[PRE REVIEW]: Chem-name-gen: A Markov name generator for chemoinformatical projects

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1282]
**Submitting author:** @Schallaven (<a href="http://orcid.org/0000-0001-7423-4609">Sven Kochmann</a>)
**Repository:** <a href="https://github.com/Schallaven/chem-name-gen" target ="_blank">https://github.com/Schallaven/chem-name-gen</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @Schallaven. **Currently, there isn't an JOSS editor assigned** to your paper.

@Schallaven if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01282/joss.01282/10.21105.joss.01282.pdf)

**Comment by Schallaven** [comment]
From the JOSS list of reviewers, I think the following people (chemists + python experience) would be a good choice for review:

khinsen, bjmorgan, richardjgowers, mkhorton, diegoenry, vahtras, bovee, JCH936, matthiaslein, fdroessler, semacu, malramsay64, robertodr, KEIPERTK, peterjwatkins, arosen93, Rgcjk, usethedata, maxscheurer, foeroyingur, goerz, utf, untzag, mdmurbach, RMeli, symmy596

Additionally, the following persons not from the list might be potential reviewers as well:
mSorok (Maria Sorokina), egonw (Egon Willghagen), sandygiuliani (Sandra Giuliani), steinbeck (Christoph Steinbeck), A-Thakkar (Amol Thakkar), johnmay (John Mayfield)

**Comment by danielskatz** [comment]
Thanks @Schallaven - the editor will work on getting some of these reviews lined up, once we get one :)

**Comment by danielskatz** [comment]
I also want to make sure this submission meets the JOSS requirements.  Can you explain how it is research software, and how it will be cited by researchers?

**Comment by Schallaven** [comment]
Sorry for the late reply!

I was looking for a good common definition of _research software_, but despite the frequent usage of the term it is rarely defined (well). Definitions are usually based on _software used in research_.

My naive approach to this issue is: I am a researcher. I use this software in research. Therefore, it is _research software_. And I will be citing it in one of the papers I am currently at (and in future). Others are highly encouraged to do this, too!

I mainly use chem-name-gen (as implied in the paper) to overcome the _blank page problem_: If you need to start a project, paper, etc you start with a _blank page_. There are a lot of things (title/program name, first sentences/implementations, etc) to do in the beginning which might be (psychologically) overwhelming (huge activation energy) creating a huge urge to simply NOT to do it and procrastinate instead. This is a common problem! Everything that annihilates these initial tasks by even simple stupidity (run and just take one of the suggestions) will reduce this overwhelming feeling and help to focus on the (main) task at hand.

I know that at the current stage _helper software_ in research is rarely cited - a culture that has to change IMHO. And it can only change, if we create the option to cite it academically, i.e. in peer reviewed form! In this context, JOSS already considers (simple) converters such as [Scyland3D](https://github.com/openjournals/joss-reviews/issues/1153#issuecomment-462152222) for review and possible publication.

I kindly ask to consider chem-name-gen for review and possible publication as well! Thank you for your time!

**Comment by kyleniemeyer** [comment]
Hi @Schallaven,

Apologies for the delay—the JOSS editorial board was having a discussion about whether we thought your submission should be considered substantial research software and thus eligible for publication, or instead a minor (though still useful) utility software.

After some discussion from most of the editors, we reached a consensus that your submission is more along the lines of what we consider utility or helper software, and thus not quite right for JOSS's definition of research software. (This is still something we have to consider on a case-by-case basis when it isn't obvious.) That said, many of us do think your software is cool and could be helpful, so please don't view this as a judgment of quality—just fit for JOSS in this particular case.
