### ISSUE TITLE
[REVIEW]: UTDEventData: An R package to access political event data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1322]
**Submitting author:** @KateHyoung (<a href="http://orcid.org/0000-0002-0744-5884">Hyoungah Kim</a>)
**Repository:** <a href="https://github.com/KateHyoung/UTDEventData" target ="_blank">https://github.com/KateHyoung/UTDEventData</a>
**Version:** v1.0.0
**Editor:** @alexhanna
**Reviewer:** @briatte, @andrewheiss
**Archive:** <a href="https://doi.org/10.5281/zenodo.2648643" target="_blank">10.5281/zenodo.2648643</a>

## Status

[![status](http://joss.theoj.org/papers/fd6fd7f126c57c8aed32d2920f66c608/status.svg)](http://joss.theoj.org/papers/fd6fd7f126c57c8aed32d2920f66c608)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/fd6fd7f126c57c8aed32d2920f66c608"><img src="http://joss.theoj.org/papers/fd6fd7f126c57c8aed32d2920f66c608/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/fd6fd7f126c57c8aed32d2920f66c608/status.svg)](http://joss.theoj.org/papers/fd6fd7f126c57c8aed32d2920f66c608)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/KateHyoung/UTDEventData" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@briatte & @andrewheiss, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @alexhanna know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/KateHyoung/UTDEventData">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@KateHyoung) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/KateHyoung/UTDEventData">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@KateHyoung) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @briatte, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01322/joss.01322/10.21105.joss.01322.pdf)

**Comment by briatte** [comment]
Quick note re: API registration, the UTD server does not check for email address validity and will return an error (500) if provided an invalid email address. That's not something that can be blamed on the package, of course, but the UTD server admins might benefit from improving their API registration form.

**Comment by briatte** [comment]
The error message shown when the API key is wrong could be improved:

```
DataTables(api_key="foobar")
[1] "{\"STATUS\": \"ERROR\", \"DATA\":\"(<TYPE 'EXCEPTIONS.VALUEERROR'>, VALUEERROR('INVALID API KEY',), <TRACEBACK OBJECT AT 0X7F5ACD310488>)\"}"
```

**Comment by briatte** [comment]
Typo in vignette:

> but `"cline_phenix"` will return __noting__.

**Comment by briatte** [comment]
Comment # 5 [replicating vignette `UTDEventData.html`]

Thinking about the API key, it is customary to allow its storage as an environment variable (see [`?options`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/options.html)). Is that possible with this package? The vignette does not mention it.

**Comment by briatte** [comment]
Comment # 6 [replicating vignette `UTDEventData.html`]

The vignette is very helpful (and the authors do a great job at documenting possible errors/traps, e.g. Windows memory issues), yet I believe it would benefit from being broken down in more digestible chunks, such as:

- an 'intro' vignette explaining the gist of the package, how to cite it, and further useful links
- one or two 'example' vignettes (the first one could combine Examples 1 and 2)
- a 'designing complex queries' vignette covering things like regex-ed queries

**Comment by briatte** [comment]
Comment # 7 [replicating vignette `UTDEventData.html`]

I'm done replicating the vignette.

Thinking about the package and data more globally, I think I'd appreciate a mention, somewhere in the docs, of how the data relate to (and whether it can be articulated with) similar event data and related event nomenclatures, e.g. those that Phil Schrodt has worked (or is working) on.

Apologies for not being more specific here, as I have limited experience with event data -- if this comment is too vague to be addressed, I'll inquire a bit and reformulate.

**Comment by briatte** [comment]
Comment # 8 [reviewing `paper.bib`]

Re: this review point,

> __References:__ Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

It seems to me that IEEE papers always come with a DOI. Those are not in the bibliography. Same goes for the Schrodt paper.

As for the Althaus _et al._ dataset (BibTeX reference `cline`), is that kind of data that could get distributed via e.g. Zenodo (and get a DOI from there)?

**Comment by briatte** [comment]
Comment # 9 [checking my unchecked review points]

> __Functionality:__ Have the functional claims of the software been confirmed?

Yup. Checking off.

> __Performance:__ If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

I do not think this really applies here. Performance in this package boils down (mostly) to API query speed. While replicating the vignette, I found some queries to be slow-ish, but given the size of the data returned by some examples (250,000+ obs.), I'm fine with it.

Checking off.

> __Automated tests:__ Are there automated tests or manual steps described so that the function of the software can be verified?

Also checking off this one, given that the package cannot really be tested against the API without providing an API key.

Some very basic unit tests could be imagined for small parts of the code: perhaps the authors will want to introduce a few control flow checks (e.g. making sure the argument to `andList` is a list).

> __Community guidelines:__ Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Also checking off this one, as I'm not sure the authors really expect community contributions.

That's pretty much it for me: over to @andrewheiss.

Last,

@whedon check references

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1109/isi.2016.7745457 may be missing for title: Near real-time atrocity event coding
- https://doi.org/10.1109/iri.2018.00065 may be missing for title: TwoRavens for Event Data
- https://doi.org/10.1080/03050629.2012.697430 may be missing for title: Precedents, progress, and prospects in political event data
- https://doi.org/10.1109/bigdata.2017.8258256 may be missing for title: Adaptive scalable pipelines for political event data generation

INVALID DOIs

- None
```

**Comment by briatte** [comment]
Dear @KateHyoung (I hope it's fine to address submitting authors in JOSS review threads?)

I posted a bunch of numbered comments in the thread above. I hope that you will find them useful in improving your package, which I found helpful and carefully coded. Thanks for your work, looking forward to discussing things further.

All the best~

**Comment by KateHyoung** [comment]
Thank you @briatte for taking your time to review our R package and documents. Your comments are very helpful to improve our package. Regarding comment #1, I will contact the server manager at UTD to improve security. For others, I will try my best to reflect your comments on codes and vignette and will discuss if I have questions on your comments. Thank you again!

**Comment by KateHyoung** [comment]
Dear @briatte and other reviewers

I have made some changes corresponding to the comments from @briatte.
1.	Response for the comment #2
I have fixed the code of DataTables(). With an invalid API key, the function returns a message. 
> DataTables("fooboo")
[1] "This API key is invalid. Please check that you have entered your key correctly."

Ref. https://github.com/KateHyoung/UTDEventData/commit/a469ff91d028897a2e7dd6804e434fb64ab90cc5

 
2.	Response for the comment #3
I have fixed the function of tableVar() that now prints a variable list without a space. Along with the change of this function, returnRexExp() was also fixed to provide appropriate query elements for API syntax. 
https://github.com/KateHyoung/UTDEventData/commit/7f76c78f9c618a225acc5e8dbc12117732dd5a1d#diff-6134badaa82d09a6bcf0dffd6b2f97b4
> tableVar(k, "Phoenix_rt")
 [1] "code"            "src_actor"       "month"           "tgt_actor"       

3.	Response for the comment #4 
I am thinking which way is better for users. If I make it to accept country objects directly, users should provide it as c(“ctr”, “time”) in order to generate a proper query syntax. I feel that listing query elements with list() is no big difference with accepting the query element with c().  But if I have a better idea for it. I will update it.  
4.	Response for the comment #8
I have updated the DOIs of the reference in a paper. 
Ref.
https://github.com/KateHyoung/UTDEventData/commit/a64c03691cc8dd50e5b36cd420e85c161cba4328#diff-68dc399b92868c40cec2beeb0a59b48e
https://github.com/KateHyoung/UTDEventData/commit/9f0eea2b4fd6f6a6717670349e010fadfa1274d3#diff-68dc399b92868c40cec2beeb0a59b48e

I am working on editing the vignette according to the comments on it. Once I have done for this work I will post it soon. 
Thank you again,
Kate

**Comment by alexhanna** [comment]
Thanks so much for the comprehensive comments, @briatte, and your responses @KateHyoung. 

@andrewheiss have you had a chance to look through the submission?

**Comment by andrewheiss** [comment]
Hi! Yep, I've been traveling way too much and have had unreliable internet access, but I should be able to do the formal review tomorrow. Sorry for the delay!

**Comment by andrewheiss** [comment]
**UTDEventData** is a fantastic new package that provides easy access to [UT Dallas's event data server](http://eventdata.utdallas.edu/). This is an important package, given the complexities involved in pulling event data from half a dozen different sources, and I've already started to use it in my own research. The package is easy to install and use, and I only came across a few issues, noted below. I've opened issues for a few of these at the package repository.

## Documentation

The README is fairly sparse and doesn't include any details on how to use the package (beyond providing a list of possible functions). The vignette currently contains complete examples of how to use the package, but reading those examples outside of R (i.e. through GitHub) is trickier since GitHub doesn't display HTML.

The README should include instructions about how to set up and use the API key, either as a local variable (e.g. `k <- "blah"`) or as a system variable (e.g. adding `Sys.setenv(APIKEY = "blah")` to `.Rprofile`). 

I have not really ever come across instructions to build vignettes when building packages with **devtools**, even when a package has vignettes ([see **gganimate**, for example](https://github.com/thomasp85/gganimate)), and most packages I've seen on GitHub don't include two different options for package installation (except when one version is on CRAN and one is on GitHub). Additionally, nothing in the vignette is actually run when the package is built, since `eval=FALSE` is enabled on all the vignette chunks. This makes sense to prevent overloading the event data server, and it makes it so users don't need an API key to install the package, but if nothing in the vignette actually runs, it might be easier to include lots of the documentation and examples in the README so users (1) don't have to explicitly build vignettes to see how the package works, and (2) users can follow rendered HTML online through GitHub.

But there's also utility in actually using vignettes so that users can run `vignette("UTDEventData")` within R to see documentation.

There's no right answer here. I don't have any official suggestion for README vs. vignettes, other than the fact that the README should at least include some quick "getting started right away" examples.

In a similar vein, the practical examples at the end of the vignette are extremely helpful, but they're buried at the bottom of the long vignette. Perhaps consider splitting the vignette into two parts—one highlighting the different ways of using the different functions, and one with the examples so that users can jump to actual usage faster.


## API access

Allowing users to store the API key in an environment variable is convenient. It might be worth changing the name of the system variable. Right now it is `APIKEY`, but it's hard to distinguish that from other system-level variables users might be using. Adding a prefix like `UTD_APIKEY` or `UTD_API` would help with recognizability. 

Additionally, it might be useful (someday later, perhaps—not necessarily for this release) to have the system-level API key a default option in functions like `DataTables()` or `tableVar()` so that users can run `tableVar("Phoenix_rt")` without needing to pass the `api_key` argument every time. Other functions like `devtools::install_github()` do something similar—if there's a `GITHUB_PAT` system variable, it uses it, otherwise it doesn't. 

## Functionality issues

The biggest issue is that the S4 class doesn't seem to be working correctly right now. When I run `obj <- Table$new()`, I get the following error:

```r
# > obj <- Table$new()
# Error: object 'Table' not found
```

As such, I'm unable to test the rest of the `obj$*` commands. (see https://github.com/KateHyoung/UTDEventData/issues/10)

I see the utility of building the API key into the `Table` objects, but the documentation doesn't explain why this method is preferable to the other more documented approaches to extracting data. The vignette mentions that using `Table` objects simplifies API calls, but that it is limited to just `DataTables()`, `tableVar()`, and `pullData()`. What should users do if they want to use other functions like `sendQuery()`? Is there value in maintaining two different ways of accessing data (especially when one method is incomplete)? (I'm assuming there is value—it might be helpful to explain the difference in approaches).

The "Data request function" section doesn't reproduce and there's minimal explanation of what `query_block` should look like. It says to pass "a list of queries created by `andList()`, `orList()`, or a single query block in the function as shown in the following example code," but the documentation hasn't covered `andList()` and `orList()` yet, and there's no working single query block in the example code. For now, running the example `sendQuery()` as it stands in the vignette produces an error:

```r
myData <- sendQuery(k,"icews", query_block, citation = TRUE)

# Error in sendQuery(k, "icews", query_block, citation = TRUE) : 
#   object 'query_block' not found
```

It might be helpful to include code for creating an example `query_block` object that users can use before delving into all the query examples that follow. 

There's a comment in the first example that "`# the data set d1 and d2 are identical`", but there is no `d1` or `d2`. I'm guessing that these are now `dt1` and `dt`, but maybe they should be renamed?

The call to `xtable()` in example 2 assumes that the user has loaded the xtable library already, but that never happens explicitly in the vignette. It might be helpful to prefix the function with `xtable::xtable()`. Alternatively, since you're using rmarkdown to generate the vignette, consider using `pander::pandoc.table()` or `knitr::kable()` to generate a Markdown table instead of raw TeX.

## Clarity and quality of writing

The vignette is generally easy to follow and is a helpful guide to using the package.

There are several typos and grammatical errors in the vignette. I've corrected some of the typos in https://github.com/KateHyoung/UTDEventData/pull/9 - a quick round of editing should clean up the rest.

## Testing

There are no formal tests, likely because the package is heavily reliant on remote access to an API and it would be computationally costly to hit the server for each test. Creating a cache of data locally might be helpful for testing, or perhaps adding tests for non-server-based functions like `returnLatLon()` or `returnDyad()` could be helpful (this isn't necessary, though)

## Contributions

It might be helpful to have some community guidelines in the package too, such as a CONTRIBUTING.md file (perhaps modeled after something like [this](https://github.com/ropensci/nomisr/blob/master/CONTRIBUTING.md) or [this](https://github.com/tidyverse/ggplot2/blob/master/CONTRIBUTING.md)) and a CONDUCT.md file (like [this](https://github.com/ropensci/qualtRics/blob/master/CONDUCT.md) or [this](https://github.com/tidyverse/readr/blob/master/CONDUCT.md))

---- 

Phew. That's all I've got. I'm excited for this package!

**Comment by KateHyoung** [comment]
Dear reviewers,

Thank you for your helpful comments for our package. I thoughtfully went over every comment and tried to reflect all of them because those make sense and enhance the package’s operations. 

For the @briatte ‘s comment #4, we have changed the function code as you suggested. Users now can throw objects directly rather than list up with `list()`. 
Ref. https://github.com/KateHyoung/UTDEventData/commit/87f42817ba1e17734cffea4559130c734738ec5f#diff-079497ecdda4a05bbcdba43d0d5cacac

For the @briatte ‘s comment #7, I have added paragraphs to describe how this package is linked to the other previous political event studies in the introduction part of the vignette. 
https://github.com/KateHyoung/UTDEventData/commit/e41ee52f4d24d79435d57091ea64d34495135a17#diff-a28523db019dca3cb3eaab6cda57fe4d

@andrewheiss, thank you for the idea of handling API access in the package. I have learned lots of things from the information you provided me. I have incorporated the way to set an API key in some functions as an environment variable. See the updates in `DataTables()`, `tableVar()`, and `prevewData()` (Please see README and vignette files). I have tried to apply the method to apply to other functions that require an API key and noticed that some functions created minor issues because of the argument setting as breaking a function. I need more time to make them stable working without errors, so I leave it for later works and will complete it during a summer break. I hope this work is good enough for this version. 
Also, I have added a prefix to `api_key` variable as to be `utd_api_key`. 
Ref. https://github.com/KateHyoung/UTDEventData/commit/4db04487d88a66e43fabe2ec67c478413bc5f04f

For the comments in Functionality issues, I have fixed the code so that `Table` is working well. Ref. https://github.com/KateHyoung/UTDEventData/commit/159b807815bc36bf34a74baeeef4b39e189c6c5a#diff-ada2ba640dbb79b8d3a115369830f718
```
> obj<-Table$new()
> obj$setAPIKey("utd_api_key")
> obj$DataTables()
[1] "'CLINE_PHOENIX_SWB', 'CLINE_PHOENIX_NYT', 'ICEWS', 'PHOENIX_RT', 'CLINE_PHOENIX_FBIS', 'TERRIER'"
```
I have changed/deleted some codes not completely works in R code chunks in the vignette.  And the `xtable()` code is also changed to the `knitr::kable()` function. 
You can find a comment about community guidelines in README.md and CONDUCT.md in the file list. 
Ref: https://github.com/KateHyoung/UTDEventData/commit/432c713fdd13a6938c978496de54b157f245f5f0#diff-46b8dc461fb4104140b72e4043aaeefe

README was restructured and now includes more information for users. Please see [here]( https://github.com/KateHyoung/UTDEventData). If you think it needs more information, please let me know. 

Package’s vignette is edited and restructured according to the comments of @briatte and @andrewheiss. 
Ref. https://github.com/KateHyoung/UTDEventData/blob/master/vignettes/UTDEventData.Rmd

I am trying to list up all my changes from the reviewer’s comments and hope not to miss any important feedback. If I have, please feel free let me know. 

This entire review process was very useful to make the package stable and functional. I sincerely appreciate your time and comments for this review. 

Best regards,
Kate

**Comment by alexhanna** [comment]
@KateHyoung: thanks so much for incorporating these edits. @andrewheiss and @briatte, thanks for the comprehensive comments. Can you two review the changes on the updated package and let me know if you're willing to sign off on the package for meeting the JOSS criteria for acceptance?

**Comment by andrewheiss** [comment]
These changes look great! I approve and sign off. ✅

**Comment by briatte** [comment]
The changes look very thorough indeed, and the updated package loads fine, as does the vignette: I'm signing off too.

**Comment by alexhanna** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by alexhanna** [comment]
You'll need to get a DOI for your repository, @KateHyoung. You'll need to create an archive (on Zenodo, figshare, or somewhere else, if you haven't already) and post the archive DOI here.

**Comment by KateHyoung** [comment]
Hello @alexhanna, 

Here is the archive DOI. 
https://zenodo.org/badge/latestdoi/113074713

Thank you for kindly letting me know the information.

**Comment by alexhanna** [comment]
@whedon set 10.5281/zenodo.2648643 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2648643" target="_blank">10.5281/zenodo.2648643</a> is the archive.

**Comment by alexhanna** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/635

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/635, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/isi.2016.7745457 is OK
- 10.7910/DVN/28075 is OK
- 10.1109/iri.2018.00065 is OK
- 10.1080/03050629.2012.697430 is OK
- 10.1109/bigdata.2017.8258256 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by alexhanna** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
I'm sorry @alexhanna, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by alexhanna** [comment]
@kyleniemeyer and @arfon, this is ready for deposit.

**Comment by danielskatz** [comment]
Hi - in the future, please notify @openjournals/joss-eics to get the AEiC on duty (me this week)

**Comment by danielskatz** [comment]
@KateHyoung - before we accept this, please fix the references in the paper.  

1. Items that should be in upper case may need additional {}s around them to preserve the case. 
1. For the Salam reference, some additional detail about the paper is needed.  "In. EECS." is not sufficient for someone else to find this.

Once you've done this, please check the resulting pdf by entering ```@whedon generate pdf``` in a new comment here.

Then we'll be ready to accept.

**Comment by danielskatz** [comment]
👋 @briatte & @andrewheiss - thanks for your reviews!
And @alexhanna, thanks for your editing!

**Comment by KateHyoung** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01322/joss.01322/10.21105.joss.01322.pdf)

**Comment by KateHyoung** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01322/joss.01322/10.21105.joss.01322.pdf)

**Comment by KateHyoung** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1322 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0     81      0 --:--:-- --:--:-- --:--:--    81
Error reading bibliography ./paper.bib (line 18, column 3):
unexpected "u"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by KateHyoung** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01322/joss.01322/10.21105.joss.01322.pdf)

**Comment by KateHyoung** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01322/joss.01322/10.21105.joss.01322.pdf)

**Comment by KateHyoung** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01322/joss.01322/10.21105.joss.01322.pdf)

**Comment by KateHyoung** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01322/joss.01322/10.21105.joss.01322.pdf)

**Comment by KateHyoung** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01322/joss.01322/10.21105.joss.01322.pdf)

**Comment by KateHyoung** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01322/joss.01322/10.21105.joss.01322.pdf)

**Comment by KateHyoung** [comment]
Dear @danielskatz, 
I have corrected and added information for the references and checked other parts of the paper as well. My apology for several attempts for compiling. A style `whedon`  generated differs from my internal compiling system.   I think the draft looks good. 

I would like to express my gratitude to the editor, @alexhanna, and the reviewers; @briatte and @andrewheiss, again for their times and comments for this R library and its paper. 

Kate

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/isi.2016.7745457 is OK
- 10.7910/DVN/28075 is OK
- 10.1109/iri.2018.00065 is OK
- 10.1080/03050629.2012.697430 is OK
- 10.1109/bigdata.2017.8258256 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/636

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/636, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
Can you also merge https://github.com/KateHyoung/UTDEventData/pull/12 or make similar changes?

**Comment by KateHyoung** [comment]
@danielskatz, I have merged the changes in the bib file. Thank you.

**Comment by danielskatz** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/isi.2016.7745457 is OK
- 10.7910/DVN/28075 is OK
- 10.1109/iri.2018.00065 is OK
- 10.1080/03050629.2012.697430 is OK
- 10.1109/bigdata.2017.8258256 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/637

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/637, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/638
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01322](https://doi.org/10.21105/joss.01322)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01322/status.svg)](https://doi.org/10.21105/joss.01322)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01322">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01322/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01322/status.svg
   :target: https://doi.org/10.21105/joss.01322
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01322/status.svg)](https://doi.org/10.21105/joss.01322)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
