### ISSUE TITLE
[REVIEW]: corporaexplorer: an R package for dynamic exploration of text collections

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1342]
**Submitting author:** @kgjerde (<a href="http://orcid.org/0000-0001-8291-6837">Kristian Lundby Gjerde</a>)
**Repository:** <a href="https://github.com/kgjerde/corporaexplorer" target ="_blank">https://github.com/kgjerde/corporaexplorer</a>
**Version:** 0.5.1
**Editor:** @leouieda
**Reviewer:** @kbenoit, @trinker
**Archive:** <a href="https://doi.org/10.5281/zenodo.3239136" target="_blank">10.5281/zenodo.3239136</a>

## Status

[![status](http://joss.theoj.org/papers/63b0c40585cd7bdf601f9ac9138642ae/status.svg)](http://joss.theoj.org/papers/63b0c40585cd7bdf601f9ac9138642ae)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/63b0c40585cd7bdf601f9ac9138642ae"><img src="http://joss.theoj.org/papers/63b0c40585cd7bdf601f9ac9138642ae/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/63b0c40585cd7bdf601f9ac9138642ae/status.svg)](http://joss.theoj.org/papers/63b0c40585cd7bdf601f9ac9138642ae)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/kgjerde/corporaexplorer" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@kbenoit & @trinker, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leouieda know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kgjerde/corporaexplorer">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.5.1
- [x] **Authorship:** Has the submitting author (@kgjerde) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kgjerde/corporaexplorer">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.5.1
- [x] **Authorship:** Has the submitting author (@kgjerde) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @kbenoit, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01342/joss.01342/10.21105.joss.01342.pdf)

**Comment by leouieda** [comment]
:wave: Hi @kbenoit @trinker, just checking in on the progress of this review.

@trinker thank you for posting the issues on the repo :1st_place_medal:  I see that you edited the initial review comment to link to the issues. Please post these as a comment on this issue instead. Otherwise I don't get notifications and it's difficult to keep track of the review progress.

**Comment by trinker** [comment]
> 👋 Hi @kbenoit @trinker, just checking in on the progress of this review.
> 
> @trinker thank you for posting the issues on the repo 🥇 I see that you edited the initial review comment to link to the issues. Please post these as a comment on this issue instead. Otherwise I don't get notifications and it's difficult to keep track of the review progress.

Will do.  Makes sense on the notifications.  This might be better clarified in the review process as it says:

> Reviewers and authors:
> Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the target repository and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

Maybe jsut add the phrase "as a reply" in the thread below.

**Comment by leouieda** [comment]
@trinker thanks for bringing that to our attention. I'll suggest the change to the editorial team.

**Comment by trinker** [comment]
All Elements of the Review Checklist I had raised have been addressed.  

## Review checklist for @trinker
### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/kgjerde/corporaexplorer">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.4.0)?
- [x] **Authorship:** Has the submitting author (@kgjerde) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
  - [x] https://github.com/kgjerde/corporaexplorer/issues/1
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
  - [x] https://github.com/kgjerde/corporaexplorer/issues/2
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
  - [x] https://github.com/kgjerde/corporaexplorer/issues/5
  - [x] https://github.com/kgjerde/corporaexplorer/issues/8
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
  - [x] https://github.com/kgjerde/corporaexplorer/issues/6

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Other

  - [ ] App Encoding issue: https://github.com/kgjerde/corporaexplorer/issues/3
  - [ ] `prepare_date()` object case inconsistencies: https://github.com/kgjerde/corporaexplorer/issues/4

**Comment by leouieda** [comment]
@trinker thank you! (Also, I followed up with your suggestion and it has already been included for future JOSS submissions :100:)

@kgjerde please try to address or respond to the last two remaining issues.

**Comment by kgjerde** [comment]
@trinker I think I have addressed all the points you raised – thanks a lot for the very useful input, much appreciated!

In addition, your point on Windows encoding issues (kgjerde/corporaexplorer#3) forced me to set up a Windows environment, which turned out to be very useful. (I had relied on AppVeyor CI to verify the basic functionality on Windows, having only access to Mac OS and Linux myself.) Playing around a bit on Windows, I realized that unicode datasets that work fine on Mac and Linux may play less nicely with Windows, due to encoding issues. I therefore decided to add a note about this in the README (in https://github.com/kgjerde/corporaexplorer/commit/748f961). Any feedback appreciated.

**Comment by trinker** [comment]
@kgjerde I tested and they address the issues I raised.

**Comment by kgjerde** [comment]
@trinker Yes, the UI issues you thankfully pointed out was quite easy to fix as soon as I got aware of the problem! Which led me to understand that similar issues may arise for the corpus texts as well, if one is unlucky/not careful with encoding – hence the README note.

**Comment by leouieda** [comment]
:wave: Hi @kbenoit please let us know when you have some time to review this submission.

**Comment by kbenoit** [comment]
Sorry for the delay. I've now had time to examine the package and the paper in detail, and here are my comments.

### Overall

I really like the application and its simplicity. It looks great and is very functional. I had almost no problem installing it and testing it. I think this makes a nice addition to text analysis tools. However given the JOSS criteria I think it could be improved a in few ways that will likely not require too much work.

### General checks

- [ ] **Version:** Does the release version given match the GitHub release (v0.4.0)?

The last GitHub release (0.4.0) is behind the current version (0.4.0.9000) but this can be corrected upon acceptance.

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?

Yes although in its current form, it's very oriented toward documents that span dates, yet the statement of need in the paper speaks to digital humanities and other fields where this may not be the case. See my comments on this below. 

- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

Yes, but I had to install **PhantomJS** before I could get the tests to work. I suggest adding a note about this in the `README.md` on GitHub.

- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

The Russia example is shown nicely in the GitHub README. But I think that another example that could excite digital humanities scholars would be to apply it to any corpus of documents chapters of a novel, such as _Moby Dick_ as it is analyzed in Jockers, M. L. (2014). _Text analysis with R for students of literature_. New York: Springer. (We replicate this for **quanteda** [here](http://quanteda.io/articles/pkgdown/replication/digital-humanities.html). I think that there are far more corpora that lack dates than that have them, so generalizing this and demonstrating it as an example would greatly broaden the user base of the package. Demonstrating the package on _Moby Dick_ would be a great application and it's easy to access that dataset online or bundle it with the package. (You would need to segment it by chapter first but this is not difficult.)

- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

    I'd like to see a bit more in the documentation for the `prepare_data()` function, especially as relates to the structure of its variables such as Date and other document metadata fields.

### Software paper

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?

    Yes but see my comments above relating to the requirement that documents have a date attached.

### Other

-  "paramater" and "treshold" are misspellings and should be corrected.
-  I think a better name would be **corpusexplorer**, since it only works with one corpus at a time (and this is easier to pronounce 😁)
-  I would really like to see `prepare_data()` defined as a generic with one method for an input `data.frame` to make it easy to extend this in the future. For example, this would then make it easy to add a method for a **quanteda** corpus in that package to make it easy to hand off a **quanteda** corpus to **corporaexplorer**.
-  Rather than require a date to be attached to each document, I think it would be better to replace this with an _optional_ sequence variable, and to assign one in the document order if none is given. If this is a date, great, and the package can use dates as is. Otherwise the sequence items would simply be serial numbers.

**Comment by kgjerde** [comment]
@kbenoit Thank you very much indeed for the review and proposals! I will start pondering them this weekend.

**Comment by leouieda** [comment]
Thanks for the comments @kbenoit :+1: 

@kgjerde please make sure to link back to the review issue in any issues or PRs opened in the software repo. Let us know when you have addressed the comments or if you want any clarification or further input.

**Comment by kgjerde** [comment]
@kbenoit 

I have now addressed or commented your points summarised in: 
* kgjerde/corporaexplorer#12  (prepare_data() as generic)
* kgjerde/corporaexplorer#13  (misspellings)
* kgjerde/corporaexplorer#14  (PhantomJS)
* kgjerde/corporaexplorer#15  (several points regarding corpora without dates)
* kgjerde/corporaexplorer#16  (name)
* kgjerde/corporaexplorer#17  (versioning)
*  kgjerde/corporaexplorer#18  (documentation)

Thank you again for very useful input. In particular, allowing for corpora without dates demanded some work on the app internals, but you are clearly correct that this significantly broadens the potensial use cases. I look forward to hearing what you think about the changes made.

**Comment by leouieda** [comment]
@kgjerde thank you for reporting back to us :+1: 

:wave: @trinker @kbenoit please take another look at the project and paper when you have time. Here are a few things to keep in mind:

* Have all your comments/concerns been addressed? 
* Are there still any items from the checklist at the top of this issue left un-checked?

If you're satisfied with the revisions, please let me know and check any remaining items from the checklist.

**Comment by trinker** [comment]
The items brought up were addressed and have been checked off

> @kgjerde thank you for reporting back to us 👍
> 
> 👋 @trinker @kbenoit please take another look at the project and paper when you have time. Here are a few things to keep in mind:
> 
> * Have all your comments/concerns been addressed?
> * Are there still any items from the checklist at the top of this issue left un-checked?
> 
> If you're satisfied with the revisions, please let me know and check any remaining items from the checklist.

**Comment by kbenoit** [comment]
This all looks great to me, and 👏 for the clear and elegant use of issues in your repo with linked commit references. The generalization away from just dates is great, and the two examples are perfect here. Nice!  And the name is your decision of course.
 
One thing only I would suggest, a 20-second change:
* I don't think it would clutter the README at all to add a note about PhantomJS to the section on Installation. (It's more appropriate there than in DESCRIPTION, but you can leave it in DESCRIPTION too.)

**Comment by kgjerde** [comment]
Excellent, thank you! @kbenoit, I have no addressed your last point (see kgjerde/corporaexplorer#14).

@leouieda I will now also take a new look at the paper itself, bearing in mind the changes I have made to the package in response to the reviews. Will post here when done.

**Comment by leouieda** [comment]
:confetti_ball: @kbenoit @trinker thank you for your input! @kbenoit I see some items left unchecked in your section at the very top. Is this intentional?

@kgjerde OK, let us know when you're done and we'll compile a new version of the pdf so we can have a final round of reviews of the paper.

**Comment by kbenoit** [comment]
Sorry, I should have checked those. I have now done so for everything except the DOI, since I have not seen the update paper yet.

**Comment by leouieda** [comment]
:+1: Thanks @kbenoit, I just wanted to make sure that was the case.

**Comment by kgjerde** [comment]
@leouieda I have now updated the paper (mainly in kgjerde/corporaexplorer@b0a495c, then just a few corrections). The paper is slightly revised (most of the diffs are language edits) and I have also added a figure to illustrate the apps.

**Comment by kgjerde** [comment]
@whedon compile

**Comment by kgjerde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01342/joss.01342/10.21105.joss.01342.pdf)

**Comment by kgjerde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01342/joss.01342/10.21105.joss.01342.pdf)

**Comment by kgjerde** [comment]
@leouieda Sorry about the repeated article rendering. There is just a small problem with unicode characters in the caption to figure 1, which is probably linked with whedon's pandoc pdf rendering, but I do not know how to fix it.

**Comment by leouieda** [comment]
Hi @kgjerde, no worries. Compiling the PDF can be troublesome. I don't know why it's not rendering the unicode in the caption when it has no problem with other characters in the text. I'll have to check with some higher-ups.

@trinker and @kbenoit in the mean time, could you please go over the paper one final time? Please let me know if you're ready to sign off on this submission. Thank you for all your input!

**Comment by kgjerde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1342 with the following error: 

 Error producing PDF.
! LaTeX Error: File `polyglossia.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.216   \setmainlanguage

Looks like we failed to compile the PDF

**Comment by kgjerde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01342/joss.01342/10.21105.joss.01342.pdf)

**Comment by kgjerde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01342/joss.01342/10.21105.joss.01342.pdf)

**Comment by kgjerde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01342/joss.01342/10.21105.joss.01342.pdf)

**Comment by kgjerde** [comment]
@leouieda As noted in https://github.com/openjournals/joss/issues/534, I have now fixed the layout issues I wanted to fix in the pdf.

**Comment by kgjerde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01342/joss.01342/10.21105.joss.01342.pdf)

**Comment by trinker** [comment]
@leouieda I'm ready to sign off on the submission.

**Comment by kgjerde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01342/joss.01342/10.21105.joss.01342.pdf)

**Comment by kgjerde** [comment]
Last change in pdf:
* Manually added one case of hyphenation of package name
* replaced 'highlighted text' with 'pattern matches highlighted'.

**Comment by kgjerde** [comment]
@leouieda Is there any action required on my part at the moment?

**Comment by leouieda** [comment]
@kgjerde I apologize for letting this hang for so long. Both reviewers have ticked all review boxes. I'll have a final look at the paper first and then we can move on to acceptance.

**Comment by leouieda** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1080/19312458.2017.1387238 is OK
- 10.1126/science.1167742 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by leouieda** [comment]
@kgjerde the paper looks good to me so we're ready to move this forward. Before accepting, you'll need to:

1. Release a new version with the changes made after the review (please post the version number here)
2. Archive a copy of source code for this new version on [Zenodo](https://zenodo.org/) and post the DOI for the archive here. 

Please don't hesitate to contact me if you have questions or need any help with this.

**Comment by kgjerde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01342/joss.01342/10.21105.joss.01342.pdf)

**Comment by kgjerde** [comment]
@leouieda Great!

1. Please note that I now corrected some very few title capitalisation/formatting issues in https://github.com/kgjerde/corporaexplorer/commit/78d40ef and https://github.com/kgjerde/corporaexplorer/commit/284d6d1.

2. I have updated the version number. The version is now 0.5.0.

3. The Zenodo DOI is http://doi.org/10.5281/zenodo.3239097 (see https://zenodo.org/record/3239097).

**Comment by leouieda** [comment]
@whedon set 0.5.1 as version

**Comment by whedon** [comment]
OK. 0.5.1 is the version.

**Comment by leouieda** [comment]
@whedon set 10.5281/zenodo.3239136 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3239136" target="_blank">10.5281/zenodo.3239136</a> is the archive.

**Comment by leouieda** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01342/joss.01342/10.21105.joss.01342.pdf)

**Comment by leouieda** [comment]
@kgjerde thanks for the updates. I've done a last pass of the paper and we're ready to accept :fireworks:

**Comment by leouieda** [comment]
:wave: @openjournals/joss-eics this submission is ready for acceptance

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1080/19312458.2017.1387238 is OK
- 10.1126/science.1167742 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/752

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/752, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1139161952259891200) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/753
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01342](https://doi.org/10.21105/joss.01342)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@kbenoit, @trinker - many thanks for your reviews here and to @leouieda for editing this submission ✨ 

@kgjerde - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.01342/status.svg)](https://doi.org/10.21105/joss.01342)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01342">
  <img src="http://joss.theoj.org/papers/10.21105/joss.01342/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.01342/status.svg
   :target: https://doi.org/10.21105/joss.01342
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01342/status.svg)](https://doi.org/10.21105/joss.01342)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1080/19312458.2017.1387238 is OK
- 10.1126/science.1167742 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1342 with the following error: 

 Error producing PDF.
! Unable to load picture or PDF file 'man/figures/paper_illustration.png'.
<to be read again> 
                   }
l.380 ...phics{man/figures/paper_illustration.png}

Looks like we failed to compile the PDF

**Comment by leouieda** [comment]
@kgjerde congratulations on the publication! Many thanks to @kbenoit and @trinker for the reviews and @arfon for handling the PDF troubles.
