### ISSUE TITLE
[REVIEW]: coronagraph: Telescope Noise Modeling for Exoplanets in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1387]
**Submitting author:** @jlustigy (<a href="http://orcid.org/0000-0002-0746-1980">Jacob Lustig-Yaeger</a>)
**Repository:** <a href="https://github.com/jlustigy/coronagraph" target ="_blank">https://github.com/jlustigy/coronagraph</a>
**Version:** v0.1
**Editor:** @arfon
**Reviewer:** @lpueyo
**Archive:** <a href="https://doi.org/10.5281/zenodo.3375103" target="_blank">10.5281/zenodo.3375103</a>

## Status

[![status](http://joss.theoj.org/papers/29a123d0178ea95da358dafc0282e8f7/status.svg)](http://joss.theoj.org/papers/29a123d0178ea95da358dafc0282e8f7)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/29a123d0178ea95da358dafc0282e8f7"><img src="http://joss.theoj.org/papers/29a123d0178ea95da358dafc0282e8f7/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/29a123d0178ea95da358dafc0282e8f7/status.svg)](http://joss.theoj.org/papers/29a123d0178ea95da358dafc0282e8f7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/jlustigy/coronagraph" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@lpueyo, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/jlustigy/coronagraph">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1)?
- [x] **Authorship:** Has the submitting author (@jlustigy) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lpueyo it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01387/joss.01387/10.21105.joss.01387.pdf)

**Comment by arfon** [comment]
:wave: @lpueyo - how are you getting along here?

**Comment by danielskatz** [comment]
👋 @arfon, this review seems to have stalled...

**Comment by arfon** [comment]
I've just followed up with @lpueyo over email. I think he might have just gone out on paternity leave...

**Comment by danielskatz** [comment]
Maybe we need to find an alternate reviewer?

**Comment by jlustigy** [comment]
👋 @arfon and @danielskatz, for what it's worth, I think @lpueyo would make a great reviewer for this paper/code and I'm willing to wait until he has the time to complete it. But I also understand if JOSS policy favors an alternate reviewer.

**Comment by labarba** [comment]
@arfon, @danielskatz — Any of you tried to contact @lpueyo by email to find out if they can come back here to do this review?

**Comment by lpueyo** [comment]
This is very useful software software that greatly needed to me made public. I am glad that the authors took this initiative. I have ran all example notebooks and changed parameters. The results make sense. I did not find any major software issues. I did notice that the reference file “earth_avg_hitran2012_300_100000cm.trns” is missing and preventing one of the notebooks to completely run.  I would suggest the authors to double check for the presence of all the reference files. 

While the software in itself will be useful to our community, I do have a few  outstanding  issues with the documentation:

-	I was not able to find a detailed API description. This is needed to make the software more broadly accessible. 

-	The statement of purpose in vague in the actual paper. Why do we need this code? Who should use this? Are there caveats for which the results ought to be taken with a grain of salt? 

- Also, there are already a few public coronagraph simulation codes, say for instance https://github.com/wfirst-cgi or https://github.com/dsavransky/EXOSIMS or the python version of the code in http://spie.org/Publications/Proceedings/Paper/10.1117/12.2274396. Since I have been involved (sometime remotely) with most of these projects, it is very clear to me when to you use which package. However, it is not clear to any random user. The paper ought to explain this. It does not have to be very detailed, but the code associated with this submission is the only one that features the “reverse” calculation (SNR to exposure time) so this needs to be highlighted. A

-	An example notebook comparing the submitted code with one of these already existing in the context of the “forward” calculation would be nice, but it might be too much work for little benefit to the users.

**Comment by arfon** [comment]
✨ many thanks for the review @lpueyo! 

@jlustigy - please take a look at the review feedback and update your submission accordingly.

**Comment by arfon** [comment]
I've just emailed @jlustigy and asked him to revisit this submission soon.

**Comment by arfon** [comment]
The author has responded to say that he's made a number of improvements to his submission but still needs a little more time to finish them up. He suggested he would be able to complete these in the next two weeks.

**Comment by arfon** [comment]
@whedon remind @jlustigy in two weeks

**Comment by whedon** [comment]
Reminder set for @jlustigy in two weeks

**Comment by whedon** [comment]
:wave: @jlustigy, please update us on how things are progressing here.

**Comment by jlustigy** [comment]
Thank you @lpueyo for the review (especially during your paternity leave!). My apologies for the delay, it has been a busy summer for me so far. 

>  I did notice that the reference file “earth_avg_hitran2012_300_100000cm.trns” is missing and preventing one of the notebooks to completely run. I would suggest the authors to double check for the presence of all the reference files.

I have updated the `setup.py` file to include `data_files` including the file that you noted was missing. However, I have not yet updated the package version number or version on PyPI, because I wanted to double check with @arfon the correct procedure for doing so since this review is tied to a specific version number of my code. I would appreciate guidance on this if possible! In the meantime, @lpueyo, if you clone the github repository you should find that the code now detects the file: “earth_avg_hitran2012_300_100000cm.trnst”. 

> I was not able to find a detailed API description. This is needed to make the software more broadly accessible.

Regarding the API, I have added significantly more detail to the existing API, which can be found within the code documentation here: https://jlustigy.github.io/coronagraph/api.html. 

> The statement of purpose in vague in the actual paper. Why do we need this code? Who should use this? Are there caveats for which the results ought to be taken with a grain of salt?

The paper (paper.md) was modified in the following ways: 
* added a statement about the code allowing for "reverse" S/N calculations (requisite exposure time to get a given S/N); 
* added a paragraph describing the general purpose of the code, including when it may be useful and under what circumstances it may not be the code of choice; 
* updated the Acknowledgements to reflect newer funding sources
* clock-induced photon charge is now included as a noise source;

Regrading the other similar codes and suggested example, I verified (offline) that this code (`coronagraph`) agrees with the model originally written in IDL by Tyler Robinson, which was published in https://iopscience.iop.org/article/10.1088/1538-3873/128/960/025003. Note that the WFIRST CGI coronagraph model (https://github.com/wfirst-cgi) is essentially the same (original IDL) code, albeit with parameters hard coded for the WFIRST mission. I very little experience using the EXOSIMS code, and although I really like the idea of adding an example notebook to my docs comparing it to my code, this may take a significant amount of time for me to create an apples-to-apples benchmarking test. Unless acceptance of this model in JOSS hinges on this, it may be appropriate for me to add this as an “enhancement" issue to my github repo, so I can complete it at a later time. 

Thank you all for your patience awaiting my updates on this!

**Comment by arfon** [comment]
:wave: @lpueyo - please come and take a look at these changes when you get a chance and let us know if these meet your concerns/feedback on this submission.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01387/joss.01387/10.21105.joss.01387.pdf)

**Comment by lpueyo** [comment]
Excellent job @jlustigy the new API helps a lot. Thank you for doing it. I am happy about this submission and looking forward to using it for my research! This is closed as far as I am concerned.

**Comment by arfon** [comment]
Thanks @lpueyo! Before closing the issue there are a few more things I need to do here...

@jlustigy - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01387/joss.01387/10.21105.joss.01387.pdf)

**Comment by arfon** [comment]
Also, please merge this PR @jlustigy - it should fix a few formatting issues with your paper: https://github.com/jlustigy/coronagraph/pull/3

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01387/joss.01387/10.21105.joss.01387.pdf)

**Comment by jlustigy** [comment]
Thanks again @lpueyo for the helpful review! 

@arfon - I released the updated code as v1.0 and archived it on Zenodo [here](https://zenodo.org/record/3375103). The DOI for the archive is: 10.5281/zenodo.3375103. Thank you for all the help during the review process!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.3375103 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3375103" target="_blank">10.5281/zenodo.3375103</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/921

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/921, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1164849769392607232) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/922
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01387](https://doi.org/10.21105/joss.01387)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@lpueyo - many thanks again for your review here ✨ 

@jlustigy - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01387/status.svg)](https://doi.org/10.21105/joss.01387)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01387">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01387/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01387/status.svg
   :target: https://doi.org/10.21105/joss.01387
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01387/status.svg)](https://doi.org/10.21105/joss.01387)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss

**Comment by jlustigy** [comment]
@arfon - I was just notified of two minor typos associated with one of the coauthor's name and affiliation. I just pushed the corrections to [coronagraph master](https://github.com/jlustigy/coronagraph/tree/master). Is it possible to recompile the paper at this point?

**Comment by arfon** [comment]
> @arfon - I was just notified of two minor typos associated with one of the coauthor's name and affiliation. I just pushed the corrections to coronagraph master. Is it possible to recompile the paper at this point?

Sure thing. I've updated the paper now. Note, it can take a while to show updated on the JOSS site as there's caching in place for the PDFs.

**Comment by jlustigy** [comment]
Excellent! I also updated the Zenodo archive to match the name change. Thanks for this! JOSS for the win 🎉
