### ISSUE TITLE
[REVIEW]: SlicerITKUltrasound: A 3D Slicer extension for ultrasound image formation, processing, and analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#153]
**Submitting author:** @thewtex (<a href="http://orcid.org/0000-0001-9475-3756">Matthew McCormick</a>)
**Repository:** <a href="https://github.com/KitwareMedical/SlicerITKUltrasound" target ="_blank">https://github.com/KitwareMedical/SlicerITKUltrasound</a>
**Version:** v0.2.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @lassoan
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.290628" target="_blank">10.5281/zenodo.290628</a>

## Status

[![status](http://joss.theoj.org/papers/746880f9243feff57502fae59abce923/status.svg)](http://joss.theoj.org/papers/746880f9243feff57502fae59abce923)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/746880f9243feff57502fae59abce923"><img src="http://joss.theoj.org/papers/746880f9243feff57502fae59abce923/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/746880f9243feff57502fae59abce923/status.svg)](http://joss.theoj.org/papers/746880f9243feff57502fae59abce923)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/KitwareMedical/SlicerITKUltrasound" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/KitwareMedical/SlicerITKUltrasound">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.2.0)?
- [x] **Authorship:** Has the submitting author (@thewtex) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @lassoan it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@lassoan @fedorov @thewtex apologies for the confusion. This is where the review process will happen. Reviewers, see reviewer instructions here http://joss.theoj.org/about#reviewer_guidelines and follow the above checklist. Let me know if you have any questions.

**Comment by thewtex** [comment]
```
The submission fulfills the JOSS requirements.

My only concern is that the software's scope (as described in the title) is "ultrasound image formation, processing, and analysis", but now it only addresses a small task in ultrasound image formation (scan conversion). Many more modules will be needed to make the software fulfill its promise.
```

@lassoan Thank you for the review.  Yes, this could be clarified.  Please review this patch:

  https://github.com/KitwareMedical/SlicerITKUltrasound/pull/49

that changes the title and description to clarify that the extension performs scan conversion on image formation that is currently executed elsewhere.

**Comment by thewtex** [comment]
@Kevin-Mattheus-Moerman @arfon Thanks for moving this forward!

Examining the preview here:

  http://joss.theoj.org/papers/746880f9243feff57502fae59abce923

The references in the *paper.bib* file are not rendered. Is this intended? Is there a problem with the *paper.md* file?

**Comment by arfon** [comment]
> The references in the paper.bib file are not rendered. Is this intended? Is there a problem with the paper.md file?

@thewtex here's the compiled paper PDF [10.21105.joss.00153.pdf](https://github.com/openjournals/joss-reviews/files/709556/10.21105.joss.00153.pdf)

**Comment by thewtex** [comment]
@arfon Nice! Looks great.

**Comment by lassoan** [comment]
@thewtex Thanks for updating the text to make things a bit more clear.

**Comment by lassoan** [comment]
I think I kind of understand the goal of this journal and using github for storing data could work. However, you should really improve the experience for reviewers. The process and usage of tools should be much simpler, more convenient and similar to existing review systems. It's also unclear for me how useful an initial, one-time review of a software repository can be, because a software library is continuously changing in time.

**Comment by Kevin-Mattheus-Moerman** [comment]
@lassoan 
> However, you should really improve the experience for reviewers. 
> The process and usage of tools should be much simpler, more convenient and similar to existing review systems. 

Thanks for your feedback. We are continuously trying to improve our system and also our review process.  Feel free to suggest improvements to our system. You can add comments to our open issues or create new ones. 
>  The process and usage of tools should be much simpler, more convenient and similar to existing review systems. 

What existing systems are you referring to? Current software journals? Traditional journals? We deviate from other journals since we uniquely focus on the software. Let us know if you have suggestions for improvement. 
> It's also unclear for me how useful an initial, one-time review of a software repository can be, because a software library is continuously changing in time.

I understand your point. JOSS came about to help provide academic credit for software, i.e. to create journal publication style credit, which involves having formal peer review, and upon acceptance assigning CrossRef DOI's enabling citations which "count". See also a blogpost from the JOSS lauch http://www.arfon.org/announcing-the-journal-of-open-source-software
In relation to future versions we feel that major releases can be resubmitted for review and can be a candidate for a new paper. This enables continuous review and accurate citing of the correct releases.

**Comment by fedorov** [comment]
> JOSS came about to help provide academic credit for software

FYI, at least in my field, a publication in a journal that is not indexed by Medline is not recognized, so publication itself gives no credit. It is more conventional to publish a software article in a Medline-indexed journal so that both academic credit for the publication and citations can come from the same location. I am sorry to say this, but as is, I see no benefit in submitting to JOSS. For academics, the criteria for choosing a journal is typically Medline-indexed (hard requirement) and journal impact factor. Do you do any work to advance JOSS in these two areas?

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @fedorov @lassoan. These are good comments. To avoid clogging this review issue I invite you to look at / open issues on these questions here: https://github.com/openjournals/joss

Also some of the issues with MEDLINE/Pubmed indexing are addressed here: 
https://github.com/openjournals/joss/issues/153

**Comment by fedorov** [comment]
@Kevin-Mattheus-Moerman I agree, this kind of discussion does not belong to this specific issue. Sorry for hi-jacking the topic.

**Comment by Kevin-Mattheus-Moerman** [comment]
@fedorov that is fine. We are a novel journal and there are definitely several creases we need to iron out and some of those are highlighted first by the reviewers at this stage so it is fine. 

Now on to the review process here. 
@lassoan have you finalised your end of the review process or or will you provide more detailed feedback?
@fedorov @thewtex can you confirm you are also reviewing this submission? 

Let me know if you have any questions.

**Comment by lassoan** [comment]
I'm done with my review at this stage of the project.

**Comment by thewtex** [comment]
@Kevin-Mattheus-Moerman as the submitting author, I am not reviewing.

**Comment by fedorov** [comment]
I guess I am still confused by the review process. There is a bunch of checkboxes on top of this issue. Who is supposed to check all of those? Is that part of the review process or not?

**Comment by Kevin-Mattheus-Moerman** [comment]
@fedorov One of the current flaws in our system is that only 1 reviewer (currently @lassoan) can be assigned to this issue through our system to check those boxes. Handling multiple reviewers in that sense is a work in progress. Of course multiple reviewers are desired so in order to handle multiple we need to be a bit creative at the moment. Currently only @lassoan is able to tick those boxes. However we will not converge on a decision to publish until we have reasonable agreement between all reviewers that all boxes can be ticked and that this submission is deemed acceptable. For the moment the other reviewers can post any review comments they have here. Also feel free to quote portions of the check-box text to comment specifically on the points highlighted there. 

Here is an example of a completed review process: 
https://github.com/openjournals/joss-reviews/issues/64

and here is an example of a lengthy review process with multiple reviewers working their comments in: 
https://github.com/openjournals/joss-reviews/issues/47

Hope that helps.

**Comment by Kevin-Mattheus-Moerman** [comment]
@thewtex sorry copied your name over by accident.

**Comment by fedorov** [comment]
I went over the items on the check list, and I am fine with all of them except:

- [ ] Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support - **contributing guidelines are missing**
- [ ] References: Do all archival references that should have a DOI list one (e.g. papers, datasets, software)? - **references are missing in [paper.md](https://github.com/KitwareMedical/SlicerITKUltrasound/blob/master/paper.md) (unless they are somehow smartly generated in some other view from .bib file!) and no DOIs are listed in the .bib file**

Over to @thewtex.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @fedorov, In relation to the second point, we do generate a PDF with references, here is the compiled paper PDF with some references and DOI's in place: [10.21105.joss.00153.pdf](https://github.com/openjournals/joss-reviews/files/709556/10.21105.joss.00153.pdf), so please review that document. 

@thewtex let me know when you've addressed these comments.

**Comment by fedorov** [comment]
@Kevin-Mattheus-Moerman indeed this resolves my second concern. Thanks!

**Comment by fedorov** [comment]
@thewtex it may be my personal preference, and of course independent of this paper review, but I would recommend using a different color scheme for the documentation: light blue and grey do not work well together, in my opinion.

![image](https://cloud.githubusercontent.com/assets/313942/22841006/c811de90-ef9d-11e6-9f16-a4bdbfa25551.png)

**Comment by thewtex** [comment]
@fedorov Thanks for the review.

I've added a basic *CONTRIBUTING.md* here: https://github.com/KitwareMedical/SlicerITKUltrasound/pull/52

Agreed on the colorscheme, too. I've removed the bright blue and used black for the normal text.

**Comment by fedorov** [comment]
I don't have any further concerns about the check list at the top of this review. Looks good to me to be accepted!

**Comment by Kevin-Mattheus-Moerman** [comment]
🎉 Great. Thank you @fedorov and @lassoan for reviewing this submission!

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon We are all good to accept here

**Comment by Kevin-Mattheus-Moerman** [comment]
@thewtex perhaps you have done this already, but can you create an updated archive of the reviewed software in Zenodo (or figshare/other service) and update this thread with the DOI of that archive?

**Comment by thewtex** [comment]
@Kevin-Mattheus-Moerman yes, here it is: https://zenodo.org/record/290628

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.290628 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.290628" target="_blank">10.5281/zenodo.290628</a> is the archive.

**Comment by arfon** [comment]
@lassoan @fedorov many thanks for your review here and to @Kevin-Mattheus-Moerman for editing this one ✨ 

@thewtex your paper is now accepted into JOSS and your paper DOI is http://dx.doi.org/10.21105/joss.00153 ⚡️ 🚀 💥

**Comment by thewtex** [comment]
Excellent! Thanks to all!
