### ISSUE TITLE
[REVIEW]: ccostr: An R package for estimating mean costs with censored data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1593]
**Submitting author:** @LarsHernandez (<a href="http://orcid.org/0000-0002-3715-8528">Lars Nielsen</a>)
**Repository:** <a href="https://github.com/HaemAalborg/ccostr" target ="_blank">https://github.com/HaemAalborg/ccostr</a>
**Version:** v0.1.0
**Editor:** @csoneson
**Reviewers:** @joethorley, @tgerke
**Archive:** <a href="https://doi.org/10.5281/zenodo.3386740" target="_blank">10.5281/zenodo.3386740</a>

## Status

[![status](http://joss.theoj.org/papers/0b9e631729dd9fadff3d6875e84ed954/status.svg)](http://joss.theoj.org/papers/0b9e631729dd9fadff3d6875e84ed954)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0b9e631729dd9fadff3d6875e84ed954"><img src="http://joss.theoj.org/papers/0b9e631729dd9fadff3d6875e84ed954/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0b9e631729dd9fadff3d6875e84ed954/status.svg)](http://joss.theoj.org/papers/0b9e631729dd9fadff3d6875e84ed954)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/HaemAalborg/ccostr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@BarryDeCicco & @joethorley, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/HaemAalborg/ccostr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.1.0
- [x] **Authorship:** Has the submitting author (@LarsHernandez) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/HaemAalborg/ccostr">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** v0.1.0
- [x] **Authorship:** Has the submitting author (@LarsHernandez) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @BarryDeCicco, @joethorley it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01593/joss.01593/10.21105.joss.01593.pdf)

**Comment by csoneson** [comment]
@BarryDeCicco, @joethorley - please perform your reviews here (see instructions in the issue above). Don't hesitate to ping me if you have any questions!

**Comment by csoneson** [comment]
@LarsHernandez - please take a look at the reviewer checklists above and make sure that all the required parts are available in your submission - if not, you can fix that already now, to simplify the review process!

**Comment by joethorley** [comment]
@csoneson and @LarsHernandez 

I've made a start on reviewing and filed some issues that require addressing.

I would strongly recommend that the authors study the freely available R packages by Hadley Wickham <http://r-pkgs.had.co.nz> and implement the best practices to R package development detailed in this book.

Although the methods are worthy of publication in JOSS the packaging of the code needs improvement.

**Comment by BarryDeCicco** [comment]
Please note that this is my first JOSS review, so don't expect perfection.Also, I got hit by a barrage of e-mails, in a very transactional, step-by-step format.

   
   - Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.  I was not able to find the list of dependencies; the software installed correctly.   

   -    

   -  Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?  I was not able to find/understand that.   

   -  Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?   I was not able to find them.  Furthermore, in one section there was a reference to a data set 'df_1', which I didn't find out how to create.   

Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support   No
 References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

I didn't find any references to external test data sets.

    On Wednesday, July 24, 2019, 4:13:16 PM EDT, whedon <notifications@github.com> wrote:  
 
 
Submitting author: @LarsHernandez (Lars Nielsen)
Repository: https://github.com/HaemAalborg/ccostr
Version: 0.1.0
Editor: @csoneson
Reviewer: @BarryDeCicco, @joethorley
Archive: Pending

Status



Status badge code:
HTML: <a href="http://joss.theoj.org/papers/0b9e631729dd9fadff3d6875e84ed954"><img src="http://joss.theoj.org/papers/0b9e631729dd9fadff3d6875e84ed954/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0b9e631729dd9fadff3d6875e84ed954/status.svg)](http://joss.theoj.org/papers/0b9e631729dd9fadff3d6875e84ed954)

Reviewers and authors:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the target repository and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

Reviewer instructions & questions

@BarryDeCicco & @joethorley, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
   
   - Make sure you're logged in to your GitHub account
   - Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

 ✨ Please try and complete your review in the next two weeks ✨
 
Review checklist for @BarryDeCicco

Conflict of interest
   
   -  As the reviewer I confirm that I have read the JOSS conflict of interest policy and that there are no conflicts of interest for me to review this work.

Code of Conduct
   
   -  I confirm that I read and will adhere to the JOSS code of conduct.

General checks
   
   -  Repository: Is the source code for this software available at the repository url?
   -  License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?
   -  Version: Does the release version given match the GitHub release (0.1.0)?
   -  Authorship: Has the submitting author (@LarsHernandez) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

Functionality
   
   -  Installation: Does installation proceed as outlined in the documentation?
   -  Functionality: Have the functional claims of the software been confirmed?
   -  Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

Documentation
   
   -  A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
   -  Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
   -  Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
   -  Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
   -  Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?
   -  Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Software paper
   
   -  Authors: Does the paper.md file include a list of authors with their affiliations?
   -  A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
   -  References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

Review checklist for @joethorley

Conflict of interest
   
   -  As the reviewer I confirm that I have read the JOSS conflict of interest policy and that there are no conflicts of interest for me to review this work.

Code of Conduct
   
   -  I confirm that I read and will adhere to the JOSS code of conduct.

General checks
   
   -  Repository: Is the source code for this software available at the repository url?
   -  License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?
   -  Version: Does the release version given match the GitHub release (0.1.0)?
   -  Authorship: Has the submitting author (@LarsHernandez) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

Functionality
   
   -  Installation: Does installation proceed as outlined in the documentation?
   -  Functionality: Have the functional claims of the software been confirmed?
   -  Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

Documentation
   
   -  A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
   -  Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
   -  Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
   -  Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
   -  Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?
   -  Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Software paper
   
   -  Authors: Does the paper.md file include a list of authors with their affiliations?
   -  A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
   -  References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by BarryDeCicco** [comment]
I have sent some comments; if you didn't get them, please let me know (there are several aliased addresses, so I don't know who is what).
Barry

    On Wednesday, July 24, 2019, 7:23:28 PM EDT, Joe Thorley <notifications@github.com> wrote:  
 
 
@csoneson and @LarsHernandez

I've made a start on reviewing and filed some issues that require addressing.

I would strongly recommend that the authors study the freely available R packages by Hadley Wickham http://r-pkgs.had.co.nz and implement the best practices to R package development detailed in this book.

Although the methods are worthy of publication in JOSS the packaging of the code needs improvement.

**Comment by csoneson** [comment]
@BarryDeCicco Thanks, your comments showed up here. Probably the easiest is to comment directly in this GitHub issue (click on "view it on GitHub" in the bottom of your email), that avoids having to worry about email addresses etc. Also note that there is a checklist in the beginning of this issue, where you should check off the aspects that you find satisfactory in the submission (and either provide comments in this issue or open issues in the submitted repository for the points that you do not find satisfactorily addressed). As the authors update the submission, please keep ticking the boxes as you consider them fulfilled. All boxes need to be ticked by all reviewers in order to eventually accept the paper.

**Comment by BarryDeCicco** [comment]
Charlotte, 
Please remove me from your list of reviewers.
Sincerely,
Barry
    On Thursday, July 25, 2019, 7:32:44 AM EDT, Charlotte Soneson <notifications@github.com> wrote:  
 
 
@BarryDeCicco Thanks, your comments showed up here. Probably the easiest is to comment directly in this GitHub issue (click on "view it on GitHub" in the bottom of your email), that avoids having to worry about email addresses etc. Also note that there is a checklist in the beginning of this issue, where you should check off the aspects that you find satisfactory in the submission (and either provide comments in this issue or open issues in the submitted repository for the points that you do not find satisfactorily addressed). As the authors update the submission, please keep ticking the boxes as you consider them fulfilled. All boxes need to be ticked by all reviewers in order to eventually accept the paper.

**Comment by csoneson** [comment]
@BarryDeCicco - could you please clarify? Do you no longer wish to be a reviewer for this submission? And/or do you want to be removed from the list of JOSS reviewers for future submissions?

**Comment by csoneson** [comment]
ping @BarryDeCicco 
> @BarryDeCicco - could you please clarify? Do you no longer wish to be a reviewer for this submission? And/or do you want to be removed from the list of JOSS reviewers for future submissions?

**Comment by csoneson** [comment]
@zedtaha - would you be interested in reviewing this submission for JOSS?

**Comment by csoneson** [comment]
@tgerke - would you be interested in reviewing this submission for JOSS?

**Comment by LarsHernandez** [comment]
Hey Charlotte, thank you for your effort so far. I just returned from vacation and I've just been fixing some of the Github issues raised by @joethorley, and looked into the comments from @BarryDeCicco, thanks a lot for the issues/comments. This is my first submission/article, so i'm very new in this, but i guess the submission needs two reviewers right? If @tgerke doesn't answer i can try to suggest one, i think the primary focus is R and survival analysis, i can see two with both in the list.

**Comment by csoneson** [comment]
Hi @LarsHernandez - welcome back :) Yes, I would like to have two reviewers - I'm hoping either @zedtaha or @tgerke will be available, otherwise we'll keep looking!

**Comment by LarsHernandez** [comment]
Thanks, and that sounds good, also I've just added a standard code of conduct to the repository which should check the **community guidelines** box

**Comment by tgerke** [comment]
This looks really interesting! Happy to help. Will aim to tackle the review late this week, if that timeline works for you all.

**Comment by csoneson** [comment]
Thanks @tgerke - that sounds great!

**Comment by csoneson** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by csoneson** [comment]
@whedon remove @BarryDeCicco as reviewer

**Comment by whedon** [comment]
OK, @BarryDeCicco is no longer a reviewer

**Comment by csoneson** [comment]
@whedon add @tgerke as reviewer

**Comment by whedon** [comment]
OK, @tgerke is now a reviewer

**Comment by LarsHernandez** [comment]
Thanks @joethorley and @tgerke for all the comments/issues, I've tried to implement all of the things you have raised. I can see both of you have not checked the Functionality/Example usage boxes, is there anything i/we can do to get that checked? Is the package lacking anything aside from the examples included in the two vignettes?

**Comment by tgerke** [comment]
Looking great @LarsHernandez! I just opened two issues regarding the examples in the vignettes, and once those minor points are resolved, it looks all set to me.

**Comment by joethorley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01593/joss.01593/10.21105.joss.01593.pdf)

**Comment by LarsHernandez** [comment]
@whedon generate pdf

**Comment by LarsHernandez** [comment]
update: I've tested the SAS/IML macro that also implements the BT and ZT estimator. The macro was very slow so i created new small datasets to test it, and i get all the same results down to two decimal points, except for the variance of the ZT estimator. It must be implemented a bit different in SAS, but it is very close.

**Comment by csoneson** [comment]
@joethorley, @tgerke - thanks a lot for your reviews! I can see that you have both checked all the items in your checklists. @joethorley, based on your comment above I take it that you are happy with the current state of the submission. @tgerke - could you confirm that your final issues have been resolved as well?

**Comment by tgerke** [comment]
Yes all looks in order to me -- great work @LarsHernandez!

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01593/joss.01593/10.21105.joss.01593.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/biomet/87.2.329 is OK
- 10.1177/1536867X1501500305 is OK
- 10.1002/hec.1648 is OK
- 10.2307/2533947 is OK
- 10.1002/dir.20049 is OK
- 10.1002/sim.2882 is OK
- 10.1111/j.0006-341X.2001.01002.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@LarsHernandez - I have sent a PR with some small modifications to the manuscript - please check and merge (and generate a new proof with `@whedon generate pdf`). Specifically, note that the link to the GitHub repository will be given on the first page of the article, and does not need to be repeated in the text. 

Next, please:
- [ ] check that the version information is consistently reported
- [ ] create a tagged release of the software
- [ ] make a Zenodo archive. Note that the archive should have the same title and authors as the article (you can also add authors' ORCID)
- [ ] report back here with the version number and the DOI of the Zenodo archive

**Comment by LarsHernandez** [comment]
- [x] check that the version information is consistently reported:
I've removed some experimentation with a new estimator, BTp, and released it with version 0.1.0.. it passes all tests and the CMD check.. I've created a branch Version-0.1.1 and added the BTp function, so that might be added to the MASTER sometime in the future.

- [x] create a tagged release of the software:
I did the Github release, hope that is what you meant.

**Comment by LarsHernandez** [comment]
- [x]  make a Zenodo archive. Note that the archive should have the same title and authors as the article (you can also add authors' ORCID):
[link](https://zenodo.org/record/3386740#.XXC21Cj7RPY) 

- [x]  report back here with the version number and the DOI of the Zenodo archive
version: 0.1.0
doi: 10.5281/zenodo.3386740

**Comment by LarsHernandez** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01593/joss.01593/10.21105.joss.01593.pdf)

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.3386740 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3386740" target="_blank">10.5281/zenodo.3386740</a> is the archive.

**Comment by csoneson** [comment]
@whedon set v0.1.0 as version

**Comment by whedon** [comment]
OK. v0.1.0 is the version.

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/948

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/948, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by csoneson** [comment]
Thanks @LarsHernandez - this looks all good. I'll hand over to the AEiC on duty, who will do the final steps. 
@openjournals/joss-eics - this paper is ready to be accepted!

**Comment by LarsHernandez** [comment]
Thanks everyone on making my first paper submission so pleasant 😀

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1169556073331732480) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/949
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01593](https://doi.org/10.21105/joss.01593)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@joethorley, @tgerke - many thanks for your reviews here and to @csoneson for editing this submission ✨ 

@LarsHernandez - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01593/status.svg)](https://doi.org/10.21105/joss.01593)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01593">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01593/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01593/status.svg
   :target: https://doi.org/10.21105/joss.01593
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01593/status.svg)](https://doi.org/10.21105/joss.01593)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-joss
