### ISSUE TITLE
[PRE REVIEW]: AutoGAMESS: A Python package for automation of GAMESS(us) Raman calculations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1602]
**Submitting author:** @Cavenfish (<a href="http://orcid.org/0000-0002-7416-8629">Brian Ferrari</a>)
**Repository:** <a href="https://github.com/Cavenfish/autogamess" target ="_blank">https://github.com/Cavenfish/autogamess</a>
**Version:** 1.0.31
**Editor:** @jedbrown
**Reviewers:** @arosen93, @shivupa, @colleeneb

**Author instructions**

Thanks for submitting your paper to JOSS @Cavenfish. **Currently, there isn't an JOSS editor assigned** to your paper.

@Cavenfish if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1602 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: authors, affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment]
Hi @Cavenfish, thanks for your interest in JOSS. Before we move forward with your submission, I have a few concerns based on our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements) and [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html):

The biggest issue is that, while useful, the software appears (to me) to be more of a utility for interacting with another software package, AutoGAMESS, rather than fully fledged research software in its own right.  One common test for this is: if used towards a research paper, would it be cited? (Due to contributing meaningfully to the results.)

In addition, your submission is missing some of the major things we look for:
- I don't see any test suite, making it impossible for reviewers to assess whether the software works correctly.
- I don't see any documentation, or examples.
- I don't see any sort of community guidelines.

**Comment by Cavenfish** [comment]
Hello Dr. Niemeyer,

This is my first submission to JOSS, so I am not sure how to continue from here. I understand rebuttals are typical in other journals, I’m not sure if this is the same in JOSS.

To address your concerns:

-AutoGAMESS is in fact a utility for interacting with another software package, however since it expedites the process of completing computational chemistry research it would certainly be cited, most likely within the acknowledgements section. It has already been acknowledged at conferences for aiding in the research progress. I’m also in contact with other researchers that plan on citing AutoGAMESS, once able to, In their future work.

-I will make and commit the test suit as soon as possible.

-The current level of documentation and guidelines is the doc strings for each function. If this is not sufficient I can write up documentation and community guidelines in the GitHub markdown as soon as possible.

Thank you for you time.

Thanks,
Brian Ferrari

________________________________

**Comment by kyleniemeyer** [comment]
@Cavenfish with JOSS all interactions with editors and reviewers are more like conversations rather than the more formal step-by-step process of older journals. In this case, the Associate Editor-in-Chief on duty (me) does a quick filter of new submissions before assigning to an editor. We look to ensure submissions are in scope, and aren't missing any major items.

For documentation, software packages should come with enough information such that a new user could come across the package and begin using it. At minimum, this could be in a README, but frequently more detailed documentation (like that generated via Sphinx) also accompanies software. This also generally includes installation info and examples.

**Comment by labarba** [comment]
👋 @Cavenfish — I am the Associate Editor-in-Chief on rotation this week. Given the major issues identified by the previous AEiC, this submission is not ready to be assigned an editor and proceed to review. I will thus add the "paused" label now, and wait for your updates. If you decide to withdraw your submission and re-submit at a later date, do let me know by a reply here.

**Comment by Cavenfish** [comment]
@labarba I believe I have fully satisfied all the previously addressed concerns. I have added documentation and examples to the README.md and added community guidelines to a CONTRIBUTE.md.  A test suite was also added for the package. 

Is this ready to proceed to the review stage, or should i make more updates first?

Thanks!

**Comment by Cavenfish** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #1602 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: authors, affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01602/joss.01602/10.21105.joss.01602.pdf)

**Comment by labarba** [comment]
👋 @jedbrown — Could you handle this new JOSS submission as editor? Thanks!

**Comment by jedbrown** [comment]
@whedon assign @jedbrown as editor

**Comment by whedon** [comment]
OK, the editor is @jedbrown

**Comment by jedbrown** [comment]
@arosen93 @goerz @shivupa @robertodr @KEIPERTK :wave: Would you be willing to review this submission for JOSS?

**Comment by arosen93** [comment]
@jedbrown. This is in my area. I would be happy to review.

**Comment by shivupa** [comment]
I’d feel comfortable and would enjoy reviewing this as well!

**Comment by jedbrown** [comment]
@whedon add @arosen93 as reviewer

**Comment by whedon** [comment]
OK, @arosen93 is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @shivupa as reviewer

**Comment by whedon** [comment]
OK, @shivupa is now a reviewer

**Comment by jedbrown** [comment]
@whedon add @colleeneb as reviewer

**Comment by whedon** [comment]
OK, @colleeneb is now a reviewer

**Comment by jedbrown** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1612. Feel free to close this issue now!
