### ISSUE TITLE
[REVIEW]: Effective-Quadratures: Polynomials for Computational Engineering Studies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#166]
**Submitting author:** @psesh (<a href="http://orcid.org/0000-0002-7351-012X">Pranay Seshadri</a>)
**Repository:** <a href="https://github.com/Effective-Quadratures/Effective-Quadratures" target ="_blank">https://github.com/Effective-Quadratures/Effective-Quadratures</a>
**Version:** v5.2
**Editor:** @katyhuff
**Reviewer:** @nicoguaro
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.438320" target="_blank">10.5281/zenodo.438320</a>

## Status

[![status](http://joss.theoj.org/papers/ba651f2b3608a5d2b085af06b1108747/status.svg)](http://joss.theoj.org/papers/ba651f2b3608a5d2b085af06b1108747)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ba651f2b3608a5d2b085af06b1108747"><img src="http://joss.theoj.org/papers/ba651f2b3608a5d2b085af06b1108747/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ba651f2b3608a5d2b085af06b1108747/status.svg)](http://joss.theoj.org/papers/ba651f2b3608a5d2b085af06b1108747)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Effective-Quadratures/Effective-Quadratures/blob/master/joss/paper.md" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Effective-Quadratures/Effective-Quadratures/blob/master/joss/paper.md">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v3.0)?
- [x] **Authorship:** Has the submitting author (@psesh) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @nicoguaro it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @nicoguaro - how are you getting on with this review?

**Comment by nicoguaro** [comment]
@arfon, the beginning of semester took my time. But I already tested the software.

>Effective-Quadratures (EQ) is a suite of tools for generating polynomials for parametric computational studies.

The inclusion of a statement of need is important, since it shows to a broader audience the usefulness of the software. Regarding the installation, it has dependencies on ``numpy`` and ``scipy``, although this is not stated in the README. It mentions that it should use Python 2.7, but there is not apparent reason for not supporting Python 3.

Some particular comments below.

## General checks
- [ ] The version in the download section of the repository is 4 and not 3 as stated in submission.

## Functionality
- [ ] Functionality: Have the functional claims of the software been confirmed? Although there is a general description of what the software does, it would be more clear with the **statement of need**.
- [x] Performance: Have any performance claims of the software been confirmed? There are no claims about the performance.

## Documentation
- [ ] A statement of need. There is not a statement of need.
- [x] Example of use. This is done as a set of Jupyter Notebooks. I would suggest to include a simple example in the README.
- [ ] Functionality documentation. Not completely, see comment below.
- [ ] Community guidelines. There are not community guidelines stated, just contact information.

Regarding the documentation, I think that it should include more than just the docstrings from the code. Some points that I consider pertinent are below. Some examples (http://barbagroup.github.io/pygbe/docs/, http://cvxopt.org/documentation/index.html)
- Description of the software.
- Installation.
- How to use the software, examples. There is no need to repeat the notebooks, but maybe one or two examples. Maybe a toy example:  [Polynomial regression in 1D](http://nbviewer.jupyter.org/github/Effective-Quadratures/Effective-Quadratures/blob/master/ipython-notebooks/Regression1D.ipynb)..
- Link to the repository.
- FAQ.

## Software paper
- [ ] A statement of need. This part is missing.
- [ ] References. The paper does not have references.

**Comment by katyhuff** [comment]
@nicoguaro thank you for your review!
 @psesh Please let us know in this thread how you will address these comments from the review and proceed with addressing them. Don't hesitate to let us know if you have any questions.

**Comment by psesh** [comment]
@nicoguaro thank you for the review :)
@katyhuff I will address these comments and get back to you shortly.

**Comment by katyhuff** [comment]
@psesh, how are the edits going?

**Comment by psesh** [comment]
Hi @katyhuff almost done, will be done by Sunday hopefully :)

**Comment by psesh** [comment]
Hi @katyhuff, apologizes for the delay in getting back. I have addressed the reviewer's comments. Here is a summary of what I've done:

1. Added references & a statement of need to the software paper;
2. Added community guidelines, a simple example, & a statement of need to the README.md file;
3. Added plenty of examples (which can be found at: www.effective-quadratures.org). The README.md file has a link to the website. I found it easier to put all the examples in the website instead of the sphinx generated html files. 
4. Updated (and cleaned up) the code to make it easier to use. The current version is 5.2 (which is what I am submitting)

Do let me know if this is alright! Thanks again :)

**Comment by nicoguaro** [comment]
@katyhuff, it seems like it is good to go. I would say that the "Community guidelines" might be a little bit more explicit. But, you let me know.

**Comment by katyhuff** [comment]
@psesh thank you for your updated paper. I believe this is ready to accept. 

@nicoguaro Thanks for the speedy responses! It looks good to me, too! I agree, we certainly would encourage more detailed community guidelines, but I think the statement in the readme, combined with some additional encouragement for contribution on the website fits the bill. 

@arfon, can you take it from here? This paper is ready to accept. Please note the version is now 5.2 and not 3 as stated in submission.

**Comment by psesh** [comment]
Sweet! Thank you @kathuff & @nicoguaro :)

**Comment by arfon** [comment]
@psesh - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by psesh** [comment]
@afron All done. Here is the link: https://zenodo.org/record/438320#.WNkf4aOZOiM

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.438320 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.438320" target="_blank">10.5281/zenodo.438320</a> is the archive.

**Comment by arfon** [comment]
@nicoguaro many thanks for reviewing this and @katyhuff for editing ✨ 

@psesh - your paper is now accepted into JOSS and your paper DOI is http://dx.doi.org/10.21105/joss.00166 ⚡️ 🚀 💥
