### ISSUE TITLE
[REVIEW]: GPU-Accelerated LArge-scale MOlecular Simulation Toolkit

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1682]
**Submitting author:** @zhuyouliang (<a href="http://orcid.org/0000-0002-9561-0770">You-Liang Zhu</a>)
**Repository:** <a href="https://bitbucket.org/galamostdevelopergroup/source-code" target ="_blank">https://bitbucket.org/galamostdevelopergroup/source-code</a>
**Version:** v4.0.1
**Editor:** @kyleniemeyer
**Reviewer:** @mabraham, @jiajiexiao, @ChayaSt
**Archive:** Pending

## Status

[![status](https://joss.theoj.org/papers/11de4b73164165c4b0d0093e04c32485/status.svg)](https://joss.theoj.org/papers/11de4b73164165c4b0d0093e04c32485)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/11de4b73164165c4b0d0093e04c32485"><img src="https://joss.theoj.org/papers/11de4b73164165c4b0d0093e04c32485/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/11de4b73164165c4b0d0093e04c32485/status.svg)](https://joss.theoj.org/papers/11de4b73164165c4b0d0093e04c32485)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://bitbucket.org/galamostdevelopergroup/source-code" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mabraham & @jiajiexiao & @ChayaSt, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kyleniemeyer know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/galamostdevelopergroup/source-code">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v4.0.1)?
- [ ] **Authorship:** Has the submitting author (@zhuyouliang) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/galamostdevelopergroup/source-code">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v4.0.1)?
- [x] **Authorship:** Has the submitting author (@zhuyouliang) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/galamostdevelopergroup/source-code">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v4.0.1)?
- [ ] **Authorship:** Has the submitting author (@zhuyouliang) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by ChayaSt** [comment]
I tried running the config script on a cluster and it tells me that it cant find boost_thread. Below is the full error it generated:
```
gcc: error: /lib64/libboost_thread-mt.so: No such file or directory
gcc: error: /lib64/libboost_filesystem-mt.so: No such file or directory
gcc: error: /lib64/libboost_python-mt.so: No such file or directory
gcc: error: /lib64/libboost_program_options-mt.so: No such file or directory
gcc: error: /lib64/libboost_signals-mt.so: No such file or directory
gcc: error: /lib64/libboost_iostreams-mt.so: No such file or directory
gcc: error: /lib64/libboost_system-mt.so: No such file or directory
gcc: error: /lib64/libboost_serialization-mt.so: No such file or directory
make: *** [galamost.so] Error 1
make: *** Waiting for unfinished jobs....
```
On this specific cluster the dependencies are provided as modules and the configuration script seems to be looking only in a few system paths. 

The instructions in the example directories should be in markdown. Currently they are in .docx which does not render. Some examples do not even have the .docx file. In addition, some examples only have the xml file without documentation how those xml files were generated.

The examples also mention that systems can be viewed using the command `vmd ...`. I am assuming this refers to [VMD](https://www.ks.uiuc.edu/Research/vmd/), but it should be clear in the documentation that this is the visualization software the author is referring to. 

It also seems like forcefield parameters need to be hand coded for every simulation. This can become very cumbersome. Is there a way to export and import existing forcefields without hand coding every parameter? 

I did not test the functionality of the code because the installation is currently not smooth and needs to be fixed first.

**Comment by zhuyouliang** [comment]
Dear Chaya Stem,

Please try again by setting the path of boost library at configuration step, such as ./configure --boost=/usr.
Before doing that, please check the existence of the boost library files.
I will improve the example and documentation according to your suggestion.
Thank you for your kind help!

Best Regards,
Youliang



zhuyouliang12345@163.com
 
From: Chaya Stern
Date: 2019-09-11 06:50
To: openjournals/joss-reviews
CC: zhuyouliang; Mention
Subject: Re: [openjournals/joss-reviews] [REVIEW]: GPU-Accelerated LArge-scale MOlecular Simulation Toolkit (#1682)
I tried running the config script on a cluster and it tells me that it cant find boost_thread. Below is the full error it generated:
gcc: error: /lib64/libboost_thread-mt.so: No such file or directory
gcc: error: /lib64/libboost_filesystem-mt.so: No such file or directory
gcc: error: /lib64/libboost_python-mt.so: No such file or directory
gcc: error: /lib64/libboost_program_options-mt.so: No such file or directory
gcc: error: /lib64/libboost_signals-mt.so: No such file or directory
gcc: error: /lib64/libboost_iostreams-mt.so: No such file or directory
gcc: error: /lib64/libboost_system-mt.so: No such file or directory
gcc: error: /lib64/libboost_serialization-mt.so: No such file or directory
make: *** [galamost.so] Error 1
make: *** Waiting for unfinished jobs....

On this specific cluster the dependencies are provided as modules and the configuration script seems to be looking only in a few system paths.
The instructions in the example directories should be in markdown. Currently they are in .docx which does not render. Some examples do not even have the .docx file. In addition, some examples only have the xml file without documentation how those xml files were generated.
The examples also mention that systems can be viewed using the command vmd .... I am assuming this refers to VMD, but it should be clear in the documentation that this is the visualization software the author is referring to.
It also seems like forcefield parameters need to be hand coded for every simulation. This can become very cumbersome. Is there a way to export and import existing forcefields without hand coding every parameter?
I did not test the functionality of the code because the installation is currently not smooth and needs to be fixed first.

**Comment by kyleniemeyer** [comment]
Hi @mabraham @jiajiexiao, just wanted to check on the status of your reviews.

@zhuyouliang please let us know when you've been able to resolve the issue @ChayaSt brought up. 

Thanks!

**Comment by zhuyouliang** [comment]
Sorry for my delayed response.
Answer to @jiajiexiao:
Thanks for your comments.
1. The "reaction" means polymerization. I will revised the readme and instruction files. 
2. I will add more examples including TIP3P and DNA, etc.
3. I am writing a Python module to help our package read force fields of all-atom and coarse-grained MATINI models from files in a format that is similar to the ITP files of GROMACS.
This will be achieved in about 2 months.
4. Thanks for your suggestion about the benchmark comparision.




zhuyouliang12345@163.com
 
From: Kyle Niemeyer
Date: 2019-08-27 00:00
To: openjournals/joss-reviews
CC: zhuyouliang; Mention
Subject: Re: [openjournals/joss-reviews] [REVIEW]: GPU-Accelerated LArge-scale MOlecular Simulation Toolkit (#1682)
From @jiajiexiao:
As I don't have a suitable personal device to test the toolkit, I just went through the repository, documentation and some of the references. Here are some of my comments based on what I have read.
The simulation toolkit doesn't seem to support any QM/MM methods that simulate the enzymatic reactions. Therefore, I suggest the author be more specific when he mentions the word "reaction" in the description.
Although the author showed an example of how to prepare the configuration XML file for a simple system via molgen plugin, it is still not clear how to set up a more complex system (e.g. monomers in TIP3P water or DNA and polymerase). Tutorials for these complex examples can be helpful for users.
It will be more accessible if the cases in the repository are presented via markdown rather than .docx files. Bitbucket or GitHub don't directly display the docx file on the website.
Additionally, the documentation website would be better to have a tutorial section to illustrate how to set up, run, and analysis a system that requires the unique and common functionality of the simulation toolkit.
It looks that the parameters of the force field have to be hard-coded every time before running the simulation. Is there a way to import and export the force-field settings? Is there a way to call any customed biomolecular force fields such as CHARMM, Amber in the toolkit?
This might be optional but it would be good if there could be some benchmark comparisons between the GPU/non-GPU version of the package.
From @mabraham:
Per the guidelines, we should assess "Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution."
There is a hand-written configure script, which I tried. It told me it didn't find boost_thread. I looked at the configure script, and it seems to be hard wired to search in a few system paths. This is unsuitable for HPC software, e.g. on clusters where software is provided by modules. There needs to be a way to provide dependencies from locations that are not system paths - particularly because users may need to install software themselves without support from their administrators. I strongly suggest the use of a automated solution for generated such build files, such as CMake (which has first-class support for CUDA for several years now).
I guess by the contents of the README.md file that there are dependencies/requirements on any or all of CUDA SDK, CUDA device architecture, some C++ compiler, boost, python. The supported and/or minimum required versions of all of these need to be documented.
There is a list of GPUs and their architecture, but there is no text to describe the content. Those are all fairly recent GPUs, but the example for the configure --cuda option refers to sm version 20, which is nearly a decade old. I presume the authors don't want me to infer that they are supporting Kepler hardware! :-) The mentions of sm_20 in the configure script code are very surprising.
configure assumes that devices are available on the machine upon which configure is run. The check that is run should be made optional, because users will often need to build on e.g. the head node of a cluster, which does not have any GPUs, or at least not the ones that might be run on the compute nodes.
There should be guidance on how to interface with python - are header files needed? The configure script looks like it supports python2, and seems to be hard-coded in some way to python 2.4. As python 2.4 is long out of support, and python 2.7 is going out of support at the end of this year, this software will not be usable unless it supports python 3 - I suggest 3.5 or 3.6 as an earliest supported version.
There should be guidance on the use of double or lower precision. Which calculations are shown to require double? Which are suitable with less? Is it full single precision? (No other major MD code has found a way to implement correct code, so the reason this is workable should be documented, and would perhaps be worth a publication in its own right.)

**Comment by zhuyouliang** [comment]
I have updated the "configure" file. @ChayaSt please try again.



zhuyouliang12345@163.com
 
From: Kyle Niemeyer
Date: 2019-09-25 02:12
To: openjournals/joss-reviews
CC: zhuyouliang; Mention
Subject: Re: [openjournals/joss-reviews] [REVIEW]: GPU-Accelerated LArge-scale MOlecular Simulation Toolkit (#1682)
Hi @mabraham @jiajiexiao, just wanted to check on the status of your reviews.
@zhuyouliang please let us know when you've been able to resolve the issue @ChayaSt brought up.
Thanks!

**Comment by jiajiexiao** [comment]
> Sorry for my delayed response. Answer to @jiajiexiao: Thanks for your comments. 1. The "reaction" means polymerization. I will revised the readme and instruction files. 2. I will add more examples including TIP3P and DNA, etc. 3. I am writing a Python module to help our package read force fields of all-atom and coarse-grained MATINI models from files in a format that is similar to the ITP files of GROMACS. This will be achieved in about 2 months. 4. Thanks for your suggestion about the benchmark comparision. zhuyouliang12345@163.com From: Kyle Niemeyer Date: 2019-08-27 00:00 To: openjournals/joss-reviews CC: zhuyouliang; Mention Subject: Re: [openjournals/joss-reviews] [REVIEW]: GPU-Accelerated LArge-scale MOlecular Simulation Toolkit (#1682) From @jiajiexiao: As I don't have a suitable personal device to test the toolkit, I just went through the repository, documentation and some of the references. Here are some of my comments based on what I have read. The simulation toolkit doesn't seem to support any QM/MM methods that simulate the enzymatic reactions. Therefore, I suggest the author be more specific when he mentions the word "reaction" in the description. Although the author showed an example of how to prepare the configuration XML file for a simple system via molgen plugin, it is still not clear how to set up a more complex system (e.g. monomers in TIP3P water or DNA and polymerase). Tutorials for these complex examples can be helpful for users. It will be more accessible if the cases in the repository are presented via markdown rather than .docx files. Bitbucket or GitHub don't directly display the docx file on the website. Additionally, the documentation website would be better to have a tutorial section to illustrate how to set up, run, and analysis a system that requires the unique and common functionality of the simulation toolkit. It looks that the parameters of the force field have to be hard-coded every time before running the simulation. Is there a way to import and export the force-field settings? Is there a way to call any customed biomolecular force fields such as CHARMM, Amber in the toolkit? This might be optional but it would be good if there could be some benchmark comparisons between the GPU/non-GPU version of the package. From @mabraham: Per the guidelines, we should assess "Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution." There is a hand-written configure script, which I tried. It told me it didn't find boost_thread. I looked at the configure script, and it seems to be hard wired to search in a few system paths. This is unsuitable for HPC software, e.g. on clusters where software is provided by modules. There needs to be a way to provide dependencies from locations that are not system paths - particularly because users may need to install software themselves without support from their administrators. I strongly suggest the use of a automated solution for generated such build files, such as CMake (which has first-class support for CUDA for several years now). I guess by the contents of the README.md file that there are dependencies/requirements on any or all of CUDA SDK, CUDA device architecture, some C++ compiler, boost, python. The supported and/or minimum required versions of all of these need to be documented. There is a list of GPUs and their architecture, but there is no text to describe the content. Those are all fairly recent GPUs, but the example for the configure --cuda option refers to sm version 20, which is nearly a decade old. I presume the authors don't want me to infer that they are supporting Kepler hardware! :-) The mentions of sm_20 in the configure script code are very surprising. configure assumes that devices are available on the machine upon which configure is run. The check that is run should be made optional, because users will often need to build on e.g. the head node of a cluster, which does not have any GPUs, or at least not the ones that might be run on the compute nodes. There should be guidance on how to interface with python - are header files needed? The configure script looks like it supports python2, and seems to be hard-coded in some way to python 2.4. As python 2.4 is long out of support, and python 2.7 is going out of support at the end of this year, this software will not be usable unless it supports python 3 - I suggest 3.5 or 3.6 as an earliest supported version. There should be guidance on the use of double or lower precision. Which calculations are shown to require double? Which are suitable with less? Is it full single precision? (No other major MD code has found a way to implement correct code, so the reason this is workable should be documented, and would perhaps be worth a publication in its own right.) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Thanks for taking time to address my questions, @zhuyouliang. Please ping me once you have finished so. I will update my review status then. Please let me know if there anything I need to do at this moment @kyleniemeyer.

**Comment by labarba** [comment]
@zhuyouliang — Could we have a status update of your work on responding to reviewer comments? Let me know if you want us to set a reminder for you.

**Comment by danielskatz** [comment]
👋 @zhuyouliang — Could we have a status update of your work on responding to reviewer comments?

**Comment by kyleniemeyer** [comment]
Hi @zhuyouliang, I've set this submission as paused until we hear back from you.

**Comment by danielskatz** [comment]
👋 @zhuyouliang — We now haven't heard anything from you in about 4 months.  Please let us know what's happening.

**Comment by danielskatz** [comment]
@kyleniemeyer - I don't have access to the repo being reviewed - it looks like it may be marked at private.  And having not heard from the author in a very long time, I think this submission should now be rejected, or if not now, after some additional short period as a last change (1 week?)

**Comment by kyleniemeyer** [comment]
@danielskatz I can't access the repo either. I will send an email, but then I agree.

**Comment by kyleniemeyer** [comment]
I contacted the author over email, who let me know that they wish to withdraw the submission at this time. Thanks @mabraham, @jiajiexiao, @ChayaSt for your efforts.

**Comment by kyleniemeyer** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
