### ISSUE TITLE
Submission: Xenomapper - short read mapping in a mixed species context

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#18]
**Submitting author:** @genomematt (<a href="http://orcid.org/0000-0001-6624-4698">Matthew J Wakefield</a>)
**Repository:** <a href="http://github.com/genomematt/xenomapper/" target ="_blank">http://github.com/genomematt/xenomapper/</a>
**Version:** v1.0.1
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.51798" target ="_blank">10.5281/zenodo.51798 </a>

## Status

[![status](http://joss.theoj.org/papers/7065e20e97ff4e44695b5e9fef7cdcd8/status.svg)](http://joss.theoj.org/papers/7065e20e97ff4e44695b5e9fef7cdcd8)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/7065e20e97ff4e44695b5e9fef7cdcd8"><img src="http://joss.theoj.org/papers/7065e20e97ff4e44695b5e9fef7cdcd8/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/7065e20e97ff4e44695b5e9fef7cdcd8/status.svg)](http://joss.theoj.org/papers/7065e20e97ff4e44695b5e9fef7cdcd8)
```

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="http://github.com/genomematt/xenomapper/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.1)?
- [x] **Archive:** Does the <a target="_blank" href="http://dx.doi.org/10.5281/zenodo.51337">software archive</a> resolve?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have the performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Compiled paper PDF: [10.21105.joss.00018.pdf](https://github.com/openjournals/joss-reviews/files/261671/10.21105.joss.00018.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by xuanxu** [comment]
:hand: I am reviewing this

**Comment by xuanxu** [comment]
## General checks
all checked

## Functionality
all checked
- I confirmed the functionality using code from the test suite

## Documentation
some checked

### Missing:
- Example Usage: There is no example usage or command to run the software using some of the sample data included. **Recommendation**: Add a 'Example usage' section with step-by-step commands to run Xenomapper with files from `xenomapper/tests/data` as input and explanation of each problem solved. More than a single example would be great to have examples of some of the multiple features.

- Community guidelines: There is no mention on how to contribute, report bugs or get support. **Recommendation**: Add a 'How to contribute' section with at least a brief statement encouraging posible contributors to help pointing them to open a new github issue. Even better would be to link to a CONTRIBUTING.md file with extended instructions. Add also comments on how to report a problem (opening an issue should be OK) and seek support (ideas: mailing list, contact email, github issue with a specific tag). 

## Software paper:
all checked
- Authors and statement of needs OK
- All DOIs verified 

## Nice-to-have improvements:
- License file is included in the repository, but users need to open it to know what is the actual license used. I'd recommend adding a mention in the readme file. Just something like "Licensed under GPL v3" would be useful.

- Tests are included, so that point is checked. But It would be good if instructions on how to run the tests are clearly stated in the README. Actually the command to do it (`python3 -m xenomapper.tests.test_all`) is there, but under the `Alternate Installation` section.

## Recommendation:
I recommend publication after some usage examples and contributing instructions are added to the documentation.

**Comment by arfon** [comment]
> I recommend publication after some minor revisions: usage examples and contributing instructions should be added to the documentation.

Many thanks for the review @xuanxu. @genomematt - please let us know when you've addressed @xuanxu's comments and we can move forward.

**Comment by genomematt** [comment]
@xuanxu @afron - updated version addressing review comments pushed.  Examples are still a bit sparse but I will continue to add to them.  Data access issues with most of the worked examples I already have so I will need to hunt up some more datasets.  I really want these to be runnable notebooks. I also added an extra affiliation line to reflect my dual appointment to the paper.md

**Comment by xuanxu** [comment]
:+1: thanks @genomematt!
I've checked both missing points and I consider this publication-ready now. 
A small doubt, @arfon & @genomematt: the [archive link](https://zenodo.org/record/51337) in this issue and the "DOI for current release" link in the "How to cite Xenomapper" section both still point to version 1.0.0. Probably a new DOI should be created for the current 1.0.1 version and have both links updated before paper is published.

**Comment by genomematt** [comment]
Ok @arfon and @xuanxu I have made an updated release with a new zenodo id 10.5281/zenodo.51798 but this is in the whedon part of the submission not the paper.md so I can't see a way for me to edit it.

Updated the how to cite to reflect JOSS, and the Zenodo badge updates automatically (links to current version not a fixed DOI).

**Comment by xuanxu** [comment]
All checked!

**Comment by genomematt** [comment]
Thanks @xuanxu 
@arfon PDF will need regenerating.  Look forward to being official!  Where do I sign up as a reviewer and evangelist?

**Comment by arfon** [comment]
Thanks @xuanxu for the review.

> @arfon PDF will need regenerating. 

👍 - yes, it's regenerated and should be correct at https://github.com/openjournals/joss-papers/blob/master/joss.00018/10.21105.joss.00018.pdf

@genomematt - your DOI _will_ be http://dx.doi.org/10.21105/joss.00018 but the Crossref system seems to be a little backed up right now (this paper is pretty far back in the queue).

> Where do I sign up as a reviewer and evangelist?

I'd be happy to add you to the `@openjournals/joss-reviewers` team if that sounds good?

:party:

**Comment by genomematt** [comment]
@arfon Only the second affiliation comes up on the PDF.  I will raise a bug.

Yes, add me to @openjournals/joss-reviewers

**Comment by arfon** [comment]
> Yes, add me to `@openjournals/joss-reviewers`

Excellent, thanks! You should have received an invite to join the team.

**Comment by arfon** [comment]
@genomematt - the DOI is now live: http://dx.doi.org/10.21105/joss.00018

**Comment by xuanxu** [comment]
:tada:
