### ISSUE TITLE
[PRE REVIEW]: hdbscan: A high performance implementation of HDBSCAN* clustering. 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#191]
**Submitting author:** @lmcinnes (<a href="http://orcid.org/0000-0003-2143-6834">Leland McInnes</a>)
**Repository:** <a href="https://github.com/scikit-learn-contrib/hdbscan" target ="_blank">https://github.com/scikit-learn-contrib/hdbscan</a>
**Version:** v0.8.8
**Editor:** @danielskatz
**Reviewer:** @zhaozhang

**What this issue is for**

Thanks for submitting your paper to JOSS @lmcinnes. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @jakevdp - would you be able to edit this one?

**Comment by arfon** [comment]
:wave: @danielskatz - any interest in editing this submission?

**Comment by danielskatz** [comment]
Ok.

**Comment by arfon** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
Hi @lmcinnes
While I look for a reviewer, you might want to fix the formatting of the paper part of your submission.  See https://github.com/mpastell/Weave.jl/blob/master/paper/paper.md for an example of another current submission that has a properly formatted paper.  By this, I refer to two things:
1. the metadata, which looks ok to me, but doesn't seem to generate a proper table like I expected, though perhaps this is a parsing issue, since I don't see anything wrong with your metadata itself.  Ah, I see it now - your line 12 needs one more space at the start.
2. references to items in the bibliography.  Only items that are referenced in the text will be shown in the bibliography when the paper is compiled, and you currently don't refer to any of them.

Thanks.

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by danielskatz** [comment]
@whedon assign @zhaozhang as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @zhaozhang

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by danielskatz** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/205. Feel free to close this issue now!

**Comment by danielskatz** [comment]
@zhaozhang - the review is is https://github.com/openjournals/joss-reviews/issues/205.  Thanks for agreeing to do this.  Let me know if you have any questions.
