### ISSUE TITLE
[PRE REVIEW]: WEPPCLIFF: A command-line tool to process climate inputs for soil loss models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1930]
**Submitting author:** @ryanpmcg (<a href="http://orcid.org/0000-0003-0464-9774">Ryan McGehee</a>)
**Repository:** <a href="https://github.com/ryanpmcg/WEPPCLIFF" target ="_blank">https://github.com/ryanpmcg/WEPPCLIFF</a>
**Version:** 1.4
**Editor:** @kbarnhart
**Reviewers:** @frengers, @stoor001, @khaors

**Author instructions**

Thanks for submitting your paper to JOSS @ryanpmcg. The JOSS editor @lheagy, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ryanpmcg if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lheagy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@lheagy) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.2489/jswc.74.4.334 may be missing for title: Updated climate database and impacts on WEPP model predictions
- https://doi.org/10.13031/2013.27921 may be missing for title: Erosivity index values for northern Mississippi
- https://doi.org/10.2489/jswc.73.4.363 may be missing for title: Benchmarking reliable erosion indices from quarter-hour station data for climate studies in the Southeastern United States

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01930/joss.01930/10.21105.joss.01930.pdf)

**Comment by danielskatz** [comment]
👋 @lheagy - sorry, I didn't mean to assign this to you as editor - Since I don't think @whedon will let me unassign it, I'm going to assign it to me for the minute while I find an appropriate editor

**Comment by danielskatz** [comment]
@whedon assign @danielskatz as editor

**Comment by whedon** [comment]
OK, the editor is @danielskatz

**Comment by danielskatz** [comment]
👋 @kbarnhart - would you be willing to edit this submission?

**Comment by danielskatz** [comment]
@whedon remind @danielskatz in 2 days

**Comment by whedon** [comment]
Sorry, I can't set reminders on PRE-REVIEW issues.

**Comment by danielskatz** [comment]
@whedon - what are you good for?

**Comment by danielskatz** [comment]
👋 @kbarnhart - would you be willing to edit this submission?

**Comment by kbarnhart** [comment]
Yes. I can do it

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart  as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kbarnhart** [comment]
@ryanpmcg if you have recommendations for reviewers please tag them on this thread. 

This here is a pre-review issue. Once I've attracted sufficient reviewers I'll open a dedicated review issue where check-boxes guide you through the review process.

Let me know if you have questions.

**Comment by ryanpmcg** [comment]
Thank you @kbarnhart, I am working on that, but I am new to the community and have not yet built up a network of potential reviewers on GitHub. Am I correct that they should have a GitHub account to be considered as a potential reviewer?

**Comment by ryanpmcg** [comment]
There are two post-docs who have now used WEPPCLIFF, and I can ask them to join and review. Otherwise, I saw two persons in the list of people who agreed to be reviewers for the journal (one with climate background and one with soil background).

**Comment by kbarnhart** [comment]
@ryanpmcg I think that its most important that the reviewers are well suited to reviewing the software. 

If there are people who you think would be good, but who are not yet on GitHub, I can reach out to them via email, see if they are interested in reviewing, and if they are willing, they would make a GitHub account in order to submit the review.

**Comment by kbarnhart** [comment]
@ryanpmcg while we are working to find suitable reviewers, I wanted to follow up with an additional comment. Based on looking over the contents of the submission, I would consider adding instructions describing how a user might test that the software has been installed correctly and is working as expected. 

Some more information about testing can be found in [this part of the JOSS docs](https://joss.readthedocs.io/en/latest/review_criteria.html#tests).

Given the tutorials you have provided, one possible approach might be a script that when run, executes the tutorial steps, asserts that known outputs are produced, and prints a success message when testing completes successfully.

**Comment by ryanpmcg** [comment]
@kbarnhart I have uploaded automated testing scripts for OSX and Windows. All changes have been added to an AUTOTEST folder in the repository. I tested both on my two machines, and verified the outputs. I will update the Readme.md with instructions soon; it will be exactly the same as the AutoTutorial shell and batch scripts for consistency.

**Comment by ryanpmcg** [comment]
@kbarnhart how should R packages used in WEPPCLIFF be given credit? Right now they are listed in the WEPPCLIFF documentation (acknowledgements). Should they also be listed in the paper somewhere?

**Comment by kbarnhart** [comment]
@ryanpmcg 

1. I think your approach to adding a testing component to this repository is a good one. Thanks for adding that. Now the repository will be prepared for the reviewers to test the ability to test WEPPCLIFF. 

2. If it is possible to cite those packages, I would recommend citing them in the paper. If not, I suspect that your approach thus far is good. 

3. I've found one reviewer for this package but want one or two more. If you have recommendations, please let me know.

**Comment by kbarnhart** [comment]
@whedon assign @frengers as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @frengers

**Comment by kbarnhart** [comment]
@frengers. Thanks for agreeing to review this. The review process is a bit different than other academic journals. The streamlined [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and focuses on the software and a [very short paper](https://github.com/openjournals/joss-papers/blob/joss.01887/joss.01887/10.21105.joss.01887.pdf). 

This here is a pre-review issue. Once I've attracted sufficient reviewers I'll open a dedicated review issue where check-boxes guide you through the review process. 

Once that has occurred, we generally request that reviewers try and complete their review in 2-3 weeks. Obviously many of us are at AGU right now, so I expect that the timeline for getting reviewers and getting reviews may be slightly stretched. 
 
Let me know if you have questions.

**Comment by ryanpmcg** [comment]
@kbarnhart in response to your three points:

1. Thank you. The tests are different for each system, and I do not know enough to make them identical for each. The OSX test is the better one (and the system I use most often). The Windows check does not use checksums because there are slight differences in the binary files produced in windows versus OSX from the same R code. So I just check the main output (.cli file) for any text differences with FC. If you or reviewers have suggestions to improve this, I would be glad to hear them.

2. I did not see examples in the 8-10 JOSS papers I read of dependencies being cited in the paper. That is what I based my decision on. I can always add a dependency section to the paper and discuss briefly how each package supports the tool.

3. WEPPCLIFF is the project that linked me to the two potential reviewers, so they may not be impartial in their reviews. Unfortunately, the few people I know that could be suitable reviewers all work with me on various projects. I am sorry that I am not able to help much on this.

**Comment by kbarnhart** [comment]
@ryanpmcg Thanks for the update. I've asked around for some review recommendations and have gotten some good ones. I'll be sending out review requests today and hope to get a total of three reviewers (two additional reviewers).

**Comment by kbarnhart** [comment]
:wave: @dvalters @tcoulthard would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue that I use to coordinate reviewers. Once there are sufficient reviewers (usually 2-3), I will open a new issue where the review will take place. 

If you are not able, please let me know if you have recommendations for other reviewers. Please recommend without mentioning a handle (e.g., you would refer to me as @ kbarnhart instead of @kbarnhart). This way we attempt to reduce the number of people who are subscribed to this thread.

**Comment by kbarnhart** [comment]
@ryanpmcg I wanted to touch base. I'm having a hard time finding additional reviewers who are able to review this. I suspect that this is in part because AGU was last week, most universities are ending their semester this week or last week, and the end of the year holidays are approaching. I've found one person who is appropriate and willing to review, and at minimum I'll need one more (ideally I try and get 3 reviewers, though sometimes this is not possible). 

I want to propose that I take a break from looking for reviewers and restart in early January after people return from vacation/not-working time. 

Is this OK with you? 

In the meantime, can you look through  [this list of people](https://bit.ly/joss-reviewers) to see if there are any people who look appropriate? Mention them here and put a space between the @ and their GitHub handle (e.g., you'd refer to me as @ kbarnhart).

**Comment by ryanpmcg** [comment]
@kbarnhart of course that is no problem, I expected things to be put on hold during the holidays. I am sorry for not replying sooner myself.

As for a second reviewer, you may try contacting Andrew.Fullhart@ars.usda.gov (he told me that he would be willing to review the software).

**Comment by kbarnhart** [comment]
@ryanpmcg thanks for the recommendation.

**Comment by kbarnhart** [comment]
@ryanpmcg I just wanted to touch base again and let you know that I am still actively seeking out reviewers for this submission. Unfortunately Andrew Fullhart has a conflict of interest for this submission, so I still need additional reviewers.

**Comment by ryanpmcg** [comment]
@kbarnhart thanks for the update. From the list of people, I have identified a few potentials with justification next to their names below:

@ KristinaRiemer -- lists R as preferred and interest in agriculture
@ dlebauer -- same as above
@ wjakethompson -- R preferred and interest in data management/workflow tools
@ khaors -- R preferred and interest in environmental modeling/hydrogeology
@ ha0ye -- R preferred and interest in time series analysis

WEPPCLIFF is a tool to process general time series climate inputs for agricultural/soil loss models like WEPP. Do you think any of these matches may work?

**Comment by kbarnhart** [comment]
@whedon add @stoor001 as reviewer

**Comment by whedon** [comment]
OK, @stoor001 is now a reviewer

**Comment by kbarnhart** [comment]
:wave: @KristinaRiemer @dlebauer @khaors would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue that I use to coordinate reviewers. I'm looking for one more reviewer for this submission.

**Comment by kbarnhart** [comment]
:wave: @KristinaRiemer @dlebauer @khaors would you be willing to review this submission for JOSS?

**Comment by khaors** [comment]
Dear Katy:

Yes, I am available to review the paper. Please let me know how can I start
the review process.

Thank & Regards,

Oscar

**Comment by kbarnhart** [comment]
@khaors thanks for your willingness to review! @ryanpmcg thank you for your patience as I found suitable reviewers. 

I will now start the official review issue which will provide additional instructions to @frengers, @stoor001 and @khaors for undertaking the review.

**Comment by kbarnhart** [comment]
@whedon add @khaors as reviewer

**Comment by whedon** [comment]
OK, @khaors is now a reviewer

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2029. Feel free to close this issue now!
