### ISSUE TITLE
[REVIEW]: partition: A fast and flexible framework for data reduction in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1991]
**Submitting author:** @malcolmbarrett (<a href="http://orcid.org/0000-0003-0299-5825">Malcolm Barrett</a>)
**Repository:** <a href="https://github.com/USCbiostats/partition" target ="_blank">https://github.com/USCbiostats/partition</a>
**Version:** v0.1.1.9000
**Editor:** @csoneson
**Reviewer:** @lmweber, @clauswilke
**Archive:** <a href="https://doi.org/10.5281/zenodo.3713898" target="_blank">10.5281/zenodo.3713898</a>

## Status

[![status](https://joss.theoj.org/papers/6d4569d6cea0a16c87703134fc78fe59/status.svg)](https://joss.theoj.org/papers/6d4569d6cea0a16c87703134fc78fe59)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6d4569d6cea0a16c87703134fc78fe59"><img src="https://joss.theoj.org/papers/6d4569d6cea0a16c87703134fc78fe59/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6d4569d6cea0a16c87703134fc78fe59/status.svg)](https://joss.theoj.org/papers/6d4569d6cea0a16c87703134fc78fe59)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/USCbiostats/partition" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@lmweber & @clauswilke, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @csoneson know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/USCbiostats/partition">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@malcolmbarrett) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/USCbiostats/partition">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@malcolmbarrett) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @lmweber, @clauswilke it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btz661 is OK
- 10.1038/nrg.2018.4 is OK
- https://doi.org/10.1016/j.coisb.2017.10.003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01991/joss.01991/10.21105.joss.01991.pdf)

**Comment by csoneson** [comment]
@lmweber, @clauswilke, thanks for agreeing to review this submission. This is where the review takes place. Please see the instructions in the post above, and don't hesitate to ping me if you have any questions!

**Comment by clauswilke** [comment]
Comments on the paper:

1. I don't understand the first sentence, "Data are increasingly wider". What does that mean? People are increasingly reluctant to store their data in long format? I don't think that's what you're trying to say, but that's what this sentence means to me. I suggest you write a first sentence that is less confusing, e.g., "Data are increasingly feature rich, ..." and then explain what "feature rich" means, i.e., many dimensions of observations per observational unit.

2. I don't know what the "Partition framework" is. I suggest you add 1-2 sentences at the end of the 1st paragraph or the beginning of the 2nd, giving a high-level description of this framework and describing how it differs, e.g., from PCA or t-SNE.

3. "While many tools exist in R for data reduction": Here it would be good to cite some packages that implement such tools.

4. I find that the first sentence of the second paragraph is difficult to read, due to the reference to R in the middle of the phrase "R package". I suggest you rephrase, e.g., "The package `partition` provides an implementation of the Partition framework for the statistical programming language R (R Core Team, 2019)."

5. You're not consistent in whether or not you place a space before references. I think there should be a space in front of every reference.

**Comment by lmweber** [comment]
Thank you for your submission.

My main comment relates to possible prior publication. The authors previously published a methods paper in August 2019 (Millstein et al., 2019, [Bioinformatics](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btz661/5554652)), describing the computational methodology and introducing the `partition` R package, which was made available via [CRAN](https://cran.r-project.org/web/packages/partition/index.html) at that time.

Could the authors please provide further details about why a new submission to JOSS is now needed? E.g. have any major updates been made to the methodology? Otherwise, I believe this would constitute dual publication, and the submission should be withdrawn.

Could the editors please also provide further guidance about what constitutes dual publication in the context of a JOSS submission? (e.g. first publishing a software package in JOSS, and then using it in a biological applications paper would presumably be fine). Apologies if I am misinterpreting this issue. @csoneson

I also have a few other more specific comments:

- The package successfully installs from the provided GitHub link, and the examples in the vignette run without error. The package appears to be well structured, documented, and tested.

- Is there a reason why the JOSS submission refers only to the GitHub version of the package, and not the CRAN version? For most users, it will be easier to install from CRAN.

- As suggested by @clauswilke above (and in issue USCbiostats/partition#7), it would be useful to expand the introductory text at the start of the vignette, to more clearly spell out the need for the package, and e.g. to explain what "agglomerative partitioning" means for readers who are not familiar with this.

- Also as suggested by @clauswilke, the wording "Data are increasingly wider" is confusing. It would be clearer to refer to this as "high-dimensional" instead of "wide" data.

- The title refers to the `partition` package as "fast". However, this is not demonstrated in the text. Some additional details should be included to justify this claim.

- Is there a reason why the license details were split up into two files (`LICENSE` and `LICENSE.md`)? Usually it would be simpler to put this all within `LICENSE`.

- Regarding authorship, the previous publication (Millstein et al., 2019, [Bioinformatics](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btz661/5554652)) included a number of additional authors. Could the authors provide additional details about why these authors were not included here? (e.g. if they were not involved with the development of the software).

- As mentioned by @clauswilke (and in issue USCbiostats/partition#6), it would be useful to provide some details for users on how to submit issues.

- There is a missing quotation mark in `# install.packages("remotes)` at the start of the vignette and the GitHub readme.

I have left several tick-boxes in the reviewer checklist empty for now, for the issues described above.

**Comment by malcolmbarrett** [comment]
Thank you for the helpful comments, @lmweber and @clauswilke. I will address them at the beginning of February. However, the question of dual publication seems urgent enough to reply immediately. So let me address that.

The Bioinformatics paper is about the framework and includes simulations and examples pertaining to it. We do mention that there *is* an R package, but that paper does *not* introduce the R package. In the JOSS paper, what we are describing is the software that was developed. Likewise, authorship pertains to the developers of the *software*, not the framework or its analysis. I think this is quite in line with the spirit of JOSS, but if this is truly an editorial concern, we are happy to discuss it further.

**Comment by clauswilke** [comment]
My opinion is that having a publication specifically about the R package is appropriate. Different authorship is also appropriate.

**Comment by csoneson** [comment]
> My main comment relates to possible prior publication. The authors previously published a methods paper in August 2019 (Millstein et al., 2019, Bioinformatics), describing the computational methodology and introducing the partition R package, which was made available via CRAN at that time.

Thanks for bringing this up @lmweber. I have looked at the _Bioinformatics_ paper, and I think this is acceptable for _JOSS_, given that the previous paper rather describes the algorithm/framework, while the _JOSS_ submission focuses on the software (which is also explicitly being reviewed here).

**Comment by lmweber** [comment]
Ok, thank you for the clarification @csoneson . Seems like this is my misunderstanding then.

In this case we can ignore this part of my review, and focus on the specific comments at the end.

Apologies for the confusion @malcolmbarrett .

**Comment by malcolmbarrett** [comment]
Thanks, everyone! No trouble. We'll begin responding to the other comments as soon as we are able.

**Comment by clauswilke** [comment]
@malcolmbarrett Please ping me when you've completed your revisions as I'd rather process everything at once.

**Comment by malcolmbarrett** [comment]
Sounds good. I will let you both know.

**Comment by csoneson** [comment]
👋 @malcolmbarrett - do you have an estimate of when you might be able to get back to the comments from the reviewers?

**Comment by malcolmbarrett** [comment]
Yes, as mentioned, we are working on them and will get respond to comments all at once soon 😄

**Comment by csoneson** [comment]
👋@malcolmbarrett - just wanted to check in on the revisions (I can see that there has been updates to the source repository relatively recently). Do you have an estimate of when the reviewers could expect a new version?

**Comment by malcolmbarrett** [comment]
Yes, early next week. We are almost done! Thanks for your patience.

**Comment by malcolmbarrett** [comment]
Thanks again for your patience and to the reviewers for their very helpful feedback. We have worked a substantial amount of this feedback into our paper and introductory vignette in particular, as well as other areas of the repository, which are now all available in the master branch of the repository. 

## Paper updates

### Clarity

Per the suggestions from both reviewers, we have reworked the introduction to be clearer and followed their other style suggestions. We have also added a comparison to other DR methods and mentioned several R implementations thereof. You can find the PR for the paper, including the diffs, at https://github.com/USCbiostats/partition/pull/15.

### Performance 

We have made two changes to clarify the performance of partition and our efforts to measure and improve it, in response to @lmweber's comment about speed. We added a short description of our efforts (e.g. re-writing key components in C++) to the paper. Additionally, we have added several benchmarks to the `README` to help the user understand performance of the package under a few different scenarios. Please see the PR at https://github.com/USCbiostats/partition/pull/14

### Other paper updates

Per the suggestion from @lmweber, we have mentioned that the package is available on CRAN. 

## Vignette updates

### Clarity

We have reworked the introduction to be a clearer and to include examples from PCA and a comparison of the output. Please see the PR at https://github.com/USCbiostats/partition/pull/17.

### Data and examples

One of our biggest changes was the addition of real-world data sets to the package, which we are excited to expand on in future releases. We included and exported several related data sets from a study on the microbiome, all starting with `baxter_*`. The most notable is `baxter_otu`, which we use in the intro vignette. Please see the PR at https://github.com/USCbiostats/partition/pull/16.

We demonstrated functionality in partition by using this data instead of simulated data, and we demonstrated how the simulated block data mimics real world data. We also included correlation heatmaps of both the microbiome data and simulated data to help the user understand how the features relate. 

Our thanks to @clauswilke for making these suggestions, which we feel greatly help the vignette. 

### Citation of Bioinformatics paper

We have added a citation of our Bioinformatics paper to the vignette. Additionally, we have added a citation to the `DESCRIPTION` file and to `inst/CITATION` (to render in `citation("partition")`), which we promised CRAN we would do when the paper was out, anyway. Please see the PR at https://github.com/USCbiostats/partition/pull/12

## Other changes

We have added an issue template and mentioned the contributor guidelines and CoC in the `README` (PR: https://github.com/USCbiostats/partition/pull/8)

We have corrected the `install.packages` typo pointed out by @lmweber (https://github.com/USCbiostats/partition/commit/60d2eb0862cbd5e0cf6473a35b5797e5dc15ed8b)

We have also made a few changes unrelated to the suggestions here. But FYI, since the review: 1) We now depend on the most current version of ggplot2 (we had previously depended on the GitHub version due to a bug fix required for one of our plot methods). 2) Our pkgdown site is now deployed automatically via GitHub Actions. 3) We fixed a minor partial name match for an argument in one function.

## Other comments

From @lmweber: "Is there a reason why the license details were split up into two files (`LICENSE` and `LICENSE.md`)? Usually it would be simpler to put this all within `LICENSE`."

Thank you for the attention to detail! Yes, this is because of a CRAN limitations with regards to `LICENSE`. Full license details are often put in build-ignored `LICENSE.md` files, as included in our repo, to supplement this file. From [R Packages, 2nd ed.](https://r-pkgs.org/whole-game.html):

> [The usethis package] puts a copy of the full license in LICENSE.md and adds this file to .Rbuildignore. It’s considered a best practice to include a full license in your package’s source, such as on GitHub, but CRAN disallows the inclusion of this file in a package tarball

Our thanks again to both reviewers. As expected, the feedback was extremely helpful.

**Comment by clauswilke** [comment]
Has the new paper pdf been generated?

**Comment by malcolmbarrett** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01991/joss.01991/10.21105.joss.01991.pdf)

**Comment by clauswilke** [comment]
I'm fine with the revisions. No further comments.

**Comment by arfon** [comment]
Dear authors and reviewers

We wanted to notify you that in light of the current COVID-19 pandemic, JOSS has decided to suspend submission of new manuscripts and to handle existing manuscripts (such as this one) on a "best efforts basis". We understand that you may need to attend to more pressing issues than completing a review or updating a repository in response to a review. If this is the case, a quick note indicating that you need to put a "pause" on your involvement with a review would be appreciated but is not required.

Thanks in advance for your understanding.

_Arfon Smith, Editor in Chief, on behalf of the JOSS editorial team._

**Comment by lmweber** [comment]
The authors have comprehensively addressed all of the previous comments raised. I have updated the tick boxes in the reviewer checklist above.

A couple of additional minor comments that I noticed in the update (but which should not stop acceptance):

- PCA should be "principal component analysis" not "principal components analysis"

- the reference to the `cluster` R package (page 2 of paper) could perhaps mention that this is a "recommended" R package, instead of just a regular R package

Thanks @arfon @csoneson for the message regarding COVID-19. I hope everyone stays safe.

**Comment by csoneson** [comment]
@clauswilke, @lmweber - thanks a lot for your thorough reviews and for checking the revised submission!

@malcolmbarrett - I will take a look at the submission and get back to you shortly with the next steps.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01991/joss.01991/10.21105.joss.01991.pdf)

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btz661 is OK
- 10.1038/nrg.2018.4 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.coisb.2017.10.003 is INVALID because of 'https://doi.org/' prefix
```

**Comment by arfon** [comment]
@csoneson & @malcolmbarrett - [this PR](https://github.com/USCbiostats/partition/pull/18) fixes that DOI issue that Whedon is complaining about.

**Comment by malcolmbarrett** [comment]
Thanks, it's been merged!

**Comment by csoneson** [comment]
Thanks @arfon. 

@malcolmbarrett - in addition to this PR, could you please take a look at the other references:
* there are a few places where you need case protection (using {}); such as R, Barnes-Hut and journal titles
* please provide a link to the Cluster package for consistency
* the Partition publication details should be updated

Next, could you please:
- [ ] create a tagged release of the software
- [ ] make a Zenodo archive. Please make sure that the title and authors of the archive are identical to those of the paper (you can also add ORCIDs in Zenodo)
- [ ] Report the archived version number and the DOI of the Zenodo archive back here

**Comment by malcolmbarrett** [comment]
Ok, the first part is done, as are the fixes recommended by @lmweber. 

I also created a release and the Zenodo archive, for which the doi is 10.5281/zenodo.3713898. I'm not sure what you mean by archived version number. Do you mean the software version? We archived a development version, `0.1.1.9000`, but the current CRAN release is `0.1.1`.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01991/joss.01991/10.21105.joss.01991.pdf)

**Comment by csoneson** [comment]
@malcolmbarrett - apologies for the unclarity on my side. The archived version number I meant is the release tag. In your case it's `joss` - we typically prefer semantic versioning (so the tag would be e.g. `v0.1.1.9000`), but if you have a reason for preferring `joss`, that would be ok too. 

For the Zenodo record, please fix the title and author list so that they are identical to those of the paper.

**Comment by malcolmbarrett** [comment]
Oh, sorry, it looks like my changes weren't published. The title and authors should match now. I'm ok with using `v0.1.1.9000`; I only meant to distinguish the release from a proper CRAN release. I changed it to the development version number for both the GitHub release and the Zenodo release. Thanks for clarifying; that was helpful!

**Comment by csoneson** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btz661 is OK
- 10.1038/nrg.2018.4 is OK
- 10.1016/j.coisb.2017.10.003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by csoneson** [comment]
@malcolmbarrett perfect, thanks, this looks all good. One final detail: could you add the volume/page information for the Millstein et al (2020) reference? Then we are ready for the final acceptance.

**Comment by malcolmbarrett** [comment]
Fixed! I also made the page numbers consistent in general.

**Comment by csoneson** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01991/joss.01991/10.21105.joss.01991.pdf)

**Comment by csoneson** [comment]
@whedon set 10.5281/zenodo.3713898 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3713898" target="_blank">10.5281/zenodo.3713898</a> is the archive.

**Comment by csoneson** [comment]
@whedon set v0.1.1.9000 as version

**Comment by whedon** [comment]
OK. v0.1.1.9000 is the version.

**Comment by csoneson** [comment]
Looks all good! I'm handing over to the editor in chief on rotation for the final publication step.

**Comment by csoneson** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1093/bioinformatics/btz661 is OK
- 10.1038/nrg.2018.4 is OK
- 10.1016/j.coisb.2017.10.003 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1375

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1375, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1240325508560232450) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1376
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01991](https://doi.org/10.21105/joss.01991)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
@lmweber, @clauswilke - many thanks for your reviews here and to @csoneson for editing this submission ✨ 

@malcolmbarrett - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01991/status.svg)](https://doi.org/10.21105/joss.01991)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01991">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01991/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01991/status.svg
   :target: https://doi.org/10.21105/joss.01991
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01991/status.svg)](https://doi.org/10.21105/joss.01991)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by malcolmbarrett** [comment]
Woohoo! Thanks so much, @csoneson and @arfon for the great editorial and submission process, and thanks again to @clauswilke and @lmweber for the very helpful reviews! We're grateful for the improvements to our software and paper that resulted from the process. 

May you all stay healthy during this challenging time!
