### ISSUE TITLE
[PRE REVIEW]: fastpos: A fast R implementation to find the critical point of stability for a correlation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2010]
**Submitting author:** @johannes-titz (<a href="http://orcid.org/0000-0002-1102-5719">Johannes Titz</a>)
**Repository:** <a href="https://github.com/johannes-titz/fastpos" target ="_blank">https://github.com/johannes-titz/fastpos</a>
**Version:** v0.2.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @johannes-titz. **Currently, there isn't an JOSS editor assigned** to your paper.

@johannes-titz if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02010/joss.02010/10.21105.joss.02010.pdf)

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (311.2 files/s, 127632.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              1            366              0           4053
Markdown                         5            192              0            851
XML                              1              0             14            761
HTML                             1             33              2            390
C++                              2             22             57            120
R                                4             18            116             97
Rmd                              2             75            125             72
YAML                             2              2              1             15
-------------------------------------------------------------------------------
SUM:                            18            708            315           6359
-------------------------------------------------------------------------------


Statistical information for the repository '2010' was gathered on 2020/01/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Johannes Titz                    8           233             34          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Johannes Titz               199           85.4          0.1               28.64
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@johannes-titz the editorial board has decided this submission (which is clearly useful, and well developed and documented) is unfortunately not suitable for consideration in JOSS at present. In particular it is classified as a "minor utility package" (see our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements)). 
We hope you consider JOSS for future more extensive work. You may also resubmit this work if the functionality is significantly expanded.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by johannes-titz** [comment]
@Kevin-Mattheus-Moerman I do respect your decision but I am a bit surprised. Could you list the criteria to categorize *fastpos* as a “minor utility package”? The documentation is not very clear on that and indeed puts “utility” in quotes.

I think the following criteria would make sense:

(1) wrapper package around existing implementation
(2) convenience package that makes existing things easier but offers no new core functionality
(3) software that has no clear research purpose

Considering these criteria *fastpos* is not a “minor utility package”. It is not a wrapper but was written from scratch. Parts of it in C++ for speed, parts of it in R. It offers a new core functionality: estimating the critical point of stability for correlations. This is not a minor utility, but offers a novel way of sample size planning for empirical studies (think power analysis and AIPE), which was not available until now. It can also be used for Monte Carlo simulations. As such it has a clear research purpose. 

I agree that *fastpos* is compact but why is this considered a bad thing? The original implementation of the stability approach (corEvol) has more lines of code but is around 500 times slower for a typical scenario and is not as flexible as *fastpos*. Furthermore, the lines of code are not an indicator of the quality of code and the ideas behind it. If *fastpos* is trivial (“minor utility”), why is it the first fast implementation for the stability approach seven years after the introduction of the concept? I believe the users of *fastpos* are very happy to have a relatively compact package that is fast and effective at solving a novel problem.

Are the git statistics correct? You seem to ignore R files (it should be 15 commits) although this is an R package. Besides, I think by only looking at the lines of code you disvalue the hard work on writing good documentation (a criterion for JOSS) and choosing good examples. (Note that the number of overall commits is 73 as can be seen on the github repository.)

There also arise fairness issues as JOSS has previously considered/published packages that (1) have similar amount of code as *fastpos* and (2) are clearly minor utility packages (for instance, bbsAssistant, univariateML, OpenTripPlanner—I can elaborate on this). But my main point is that *fastpos* should not be considered a “utility package” as it has a research-related novel core functionality.

As said before, I do respect your decision, but would like to have a more concrete reason. I put a lot of work into *fastpos* to comply with JOSS guidelines. If I had known before that *fastpos* does not meet JOSS submission requirements because of lines of code, this would have saved me precious time. Furthermore, I would like to hear what kind of functionality you would like to see in *fastpos* so that the stability approach can be used more effectively. You state that I can resubmit, but you do not point out any problems with the package nor how it should be extended.

Thanks for your time!

**Comment by arfon** [comment]
Dear @johannes-titz, it's Arfon Smith here, the JOSS Editor-in-Chief. 

Thank you for providing the additional comments and insights on your package. This is useful context but doesn't change our decision here. I recognise that this submission is similar to packages that have already been published in JOSS. The scope of JOSS has changed over time and many of the smaller packages that we've published in the past would be rejected as out of scope today.

I realize that your submission implements a very useful algorithm however one of the changes we're making at JOSS right now is to designate single function packages like this as minor and therefore out of scope. This change is relatively recent and we will be updating our documentation soon to reflect this change.

To address your question directly about what could be done to make this submission allowable in JOSS. There are a number of possible answers but something more comprehensive designed to address the research challenges common to authors in this field would be an obvious extension.
