### ISSUE TITLE
[REVIEW]: `learningCurve`: An implementation of Crawford's and Wright's learning curve production functions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#202]
**Submitting author:** @bradleyboehmke (<a href="http://orcid.org/0000-0002-3611-8516">Bradley Boehmke</a>)
**Repository:** <a href="https://github.com/Auburngrads/learningCurve" target ="_blank">https://github.com/Auburngrads/learningCurve</a>
**Version:** v1.1.1
**Editor:** @arfon
**Reviewer:** @TJBihl
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.570062" target="_blank">10.5281/zenodo.570062</a>

## Status

[![status](http://joss.theoj.org/papers/bccae7dcfe16909e54108800029614e3/status.svg)](http://joss.theoj.org/papers/bccae7dcfe16909e54108800029614e3)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/bccae7dcfe16909e54108800029614e3"><img src="http://joss.theoj.org/papers/bccae7dcfe16909e54108800029614e3/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/bccae7dcfe16909e54108800029614e3/status.svg)](http://joss.theoj.org/papers/bccae7dcfe16909e54108800029614e3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Auburngrads/learningCurve" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Auburngrads/learningCurve">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.1.1)?
- [x] **Authorship:** Has the submitting author (@bradleyboehmke) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @TJBihl it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @TJBihl - please carry out your review here.

**Comment by arfon** [comment]
:wave: @TJBihl - friendly reminder here.

**Comment by TJBihl** [comment]
The authors have provided a well composed package for learning rates.  I was able to use all of the files/functions with no issues and reproduce all examples.  Beyond this, I was able to explore additional operating points in the functions and saw no issues to correct.  

A few minor issues does exist though:
1.  Equations do not appear in the vignettes.  After much searching, this is probably due to the computer I'm using not having a LaTex program installed.  It would help if a comment/disclaimer was included in the install stating that one was needed.  I am using RStudio 1.0.136.  I could possibly need rmarkdown, but this wasn't in the specified library list.  
2. paper.md might need the authors names/affiliations
3.  When I first tried running setup.R, it was after I loaded the learning rate package.  But I didn't have the knitr package, so this might be a library the authors should have load by default.  
4. paper.bib has some primary references, but the vignette appears to have more.

**Comment by bradleyboehmke** [comment]
@arfon  How would you like me to proceed?  As for the reviewers comments # 1 & 3, we have included rmarkdown and knitr as suggested dependencies rather than absolute required dependencies.  This is because the package will operate without these packages; however, having them is suggested as it allows for enhancements such as seeing the formulas in the vignette.

Comment #2 - I updated the paper.md yaml so that the authors names/affiliations populate.

Comment #3 - Not sure how you want me to address this.  The vignette has a lot more references because it's written in a full paper format versus JOSS's requirements of keeping it to 1 page.  If I incorporate all the references then I would likely convert the JOSS paper into a much longer full-length paper.

Let me know how to proceed.  Thanks!  And thanks @TJBihl for the solid review!

Brad

**Comment by arfon** [comment]
> Comment #2 - I updated the paper.md yaml so that the authors names/affiliations populate.

👍 great.

> Comment #3 - Not sure how you want me to address this. The vignette has a lot more references because it's written in a full paper format versus JOSS's requirements of keeping it to 1 page. If I incorporate all the references then I would likely convert the JOSS paper into a much longer full-length paper.

I think it's OK if the JOSS `paper.md` only has a subset of these references (i.e. the ones necessary for the short paper).

@TJBihl - could you verify the changes and check off of the remaining review checkboxes if everything looks good?

**Comment by TJBihl** [comment]
Everything looks good to me now

**Comment by arfon** [comment]
Great. Thanks @TJBihl.

@bradleyboehmke - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by bradleyboehmke** [comment]
@arfon as requested:

<a href="https://zenodo.org/badge/latestdoi/60852792"><img src="https://zenodo.org/badge/60852792.svg" alt="DOI"></a>

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.570062 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.570062" target="_blank">10.5281/zenodo.570062</a> is the archive.

**Comment by arfon** [comment]
@TJBihl - many thanks for the review here ✨ 

@bradleyboehmke - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00202 ⚡️ 🚀 💥

**Comment by bradleyboehmke** [comment]
Great!  Thanks @arfon!
