### ISSUE TITLE
[PRE REVIEW]: SeisModels.jl: A Julia package for models of the Earth's interior

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2020]
**Submitting author:** @anowacki (<a href="http://orcid.org/0000-0001-7669-7383">Andy Nowacki</a>)
**Repository:** <a href="https://github.com/anowacki/SeisModels.jl" target ="_blank">https://github.com/anowacki/SeisModels.jl</a>
**Version:** v1.0.0
**Editor:** @kbarnhart
**Reviewers:** @daniellivingston, @fhorrobin

**Author instructions**

Thanks for submitting your paper to JOSS @anowacki. **Currently, there isn't an JOSS editor assigned** to your paper.

@anowacki if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (863.5 files/s, 60761.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           22            216            107           1509
Markdown                        10            127              0            510
YAML                             3             14              7             79
TeX                              1              7              0             71
TOML                             2              5              0             22
-------------------------------------------------------------------------------
SUM:                            38            369            114           2191
-------------------------------------------------------------------------------


Statistical information for the repository '2020' was gathered on 2020/01/17.
No commited files with the specified extensions were found.
```

**Comment by kyleniemeyer** [comment]
Hey @kbarnhart, could you edit this for us?

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1111/j.1365-246X.1995.tb03540.x is OK
- 10.1111/j.1365-246X.1991.tb06724.x is OK
- 10.1016/0031-9201(81)90046-7 is OK
- 10.1126/science.1199375 is OK
- 10.1785/gssrl.70.2.154 is OK
- 10.1785/gssrl.81.3.530 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02020/joss.02020/10.21105.joss.02020.pdf)

**Comment by anowacki** [comment]
> @anowacki if you have any suggestions for potential reviewers then please mention them here in this thread

Choosing from the list, I would suggest the following would be able to provide a review:
- daniellivingston
- lheagy
- fhorrobin

**Comment by kbarnhart** [comment]
@kyleniemeyer I can edit

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kbarnhart** [comment]
@anowacki I have a couple of clarification questions:

* Could you give me an example of using SeisModels.jl in a research application? I know the paper indicates that this package is used in research projects, but a specific example would be helpful. 

* The paper makes a performance claim but I don't see any demonstration of this claim (in the paper or the docs). Could you elaborate on this claim. 

>  The software has been benchmarked against independent implementations and has a significant speed advantage over similar Python software.

**Comment by anowacki** [comment]
Thank you for the questions, @kbarnhart.

> * Could you give me an example of using SeisModels.jl in a research application? I know the paper indicates that this package is used in research projects, but a specific example would be helpful.

The software has been used by a research group here at the University of Leeds to investigate 1D models of the Earth in our group meetings.  Some of these studies are available at https://github.com/anowacki/DERG_PREM.  There is also an article in review for inclusion in an AGU monograph (Nowacki & Cottaar, 2020) which has used SeisModels.

If you feel the manuscript itself should contain examples of usage or text similar to that above, I would be happy to include that.

> * The paper makes a performance claim but I don't see any demonstration of this claim (in the paper or the docs). Could you elaborate on this claim.
>> The software has been benchmarked against independent implementations and has a significant speed advantage over similar Python software.

The benchmarking was done against a simple equivalent, and unpublished, Python code, which is available here: https://github.com/andreww/prem4derg.  I am not aware of any other open-source and freely-available software apart from that which works similarly to SeisModels in calculating bulk Earth properties, which is why concrete performance benchmarks against other implementations aren't included.

Would it be better to remove the 'comparison' and simply state some times, such as: "For a PREM-like model, computation of the surface gravity takes 5 µs, whilst calculating pressure at the centre of the body takes 12 ms."

Note that the equivalent calculations for the Python code take respectively 560 µs and 720 ms.

### References
- Nowacki, A and Cottaar, S, 2020.  Towards imaging flow at the base of the mantle with seismic, mineral physics and geodynamic constraints.  In Marquardt, H, Ballmer, M, Cottaar, S and Konter, J.  Mantle Convection and Surface Expressions.  Geophysical Monograph, American Geophysical Union, Washington, D.C., USA (in revision).

**Comment by kbarnhart** [comment]
@anowacki thanks for the responses, they are very helpful. 

A couple of comments from me in advance of review. My comments are mostly things that I anticipate would come up in review based on looking at the package and knowing the review process and criteria. 

* I would consider revising the language about performance. Specifically, I would recommend describing performance in a way a reviewer can verify because one of the checklist items that reviewers will work through states:

> Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.) 

* I would add instructions regarding how to test SeisModels.jl. I see that you have automatic tests set up on TravisCI and AppVeyor, but it is not clear how a reviewer might run the tests themselves.

**Comment by kbarnhart** [comment]
:wave: @daniellivingston @lheagy @fhorrobin would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue that I use to coordinate reviewers. Once there are sufficient reviewers (usually 2-3), I will open a new issue where the review will take place.

If you are not able, please let me know if you have recommendations for other reviewers. Please recommend without mentioning a handle (e.g., you would refer to me as @ kbarnhart instead of @kbarnhart). This way we attempt to reduce the number of people who are subscribed to this thread.

**Comment by anowacki** [comment]
Thanks for those suggestions, @kbarnhart, and for moving things forward.

I have pushed an updated version of the manuscript to the repo's master branch with concrete example timings and instructions on how to test the package (https://github.com/anowacki/SeisModels.jl/commit/9e755d1225983960d47d10699fef76a73012a85a).

**Comment by daniellivingston** [comment]
Hi @kbarnhart , this is right up my alley. I'd be happy to review.

**Comment by kbarnhart** [comment]
Thanks for being willing to review @daniellivingston . I'll add you as a reviewer. Once I have a sufficient number of reviewers (typically a few days), I'll open a new issue where the review will take place.

**Comment by kbarnhart** [comment]
@whedon assign @daniellivingston as reviewer

**Comment by whedon** [comment]
OK, @daniellivingston is now a reviewer

**Comment by kbarnhart** [comment]
:wave: @lheagy @fhorrobin a friendly reminder to consider reviewing this submission to JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue that I use to coordinate reviewers. Once there are sufficient reviewers (usually 2-3), I will open a new issue where the review will take place.

If you are not able, please let me know if you have recommendations for other reviewers. Please recommend without mentioning a handle (e.g., you would refer to me as @ kbarnhart instead of @kbarnhart). This way we attempt to reduce the number of people who are subscribed to this thread.

**Comment by fhorrobin** [comment]
This is right up my ally as well, happy to assist.

**Comment by kbarnhart** [comment]
@whedon add @fhorrobin as reviewer

**Comment by whedon** [comment]
OK, @fhorrobin is now a reviewer

**Comment by kbarnhart** [comment]
Thanks for being willing to review this package @fhorrobin 👍 .

I'd like to find one more reviewer for this before I move it from the pre-review to the review stage. 

:wave: @rowanc1 @leouieda would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue that I use to coordinate reviewers. Once there are sufficient reviewers (usually 2-3), I will open a new issue where the review will take place.

If you are not able, please let me know if you have recommendations for other reviewers. Please recommend without mentioning a handle (e.g., you would refer to me as @ kbarnhart instead of @kbarnhart). This way we attempt to reduce the number of people who are subscribed to this thread.

**Comment by kbarnhart** [comment]
I'm going to move this forward from pre-review to review stage. 

If possible, I'd like to add one more reviewer. @lheagy, @rowanc1, @leouieda if you are interested, able, or have another reviewer to recommend, please let me know.

**Comment by kbarnhart** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2043.

**Comment by leouieda** [comment]
Hi @kbarnhart sorry, I don't have the bandwidth for this right now. But I would recommend seisman or joa-quim.

**Comment by kbarnhart** [comment]
@leouieda thanks for the recommendations. 

:wave: @seisman @joa-quim would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

This is a pre-review issue that I use to coordinate reviewers. If you are able, I will add you to the review issue at openjournals/joss-reviews/issues/2043.

**Comment by seisman** [comment]
Sorry, I'm not a Julia user.

**Comment by joa-quim** [comment]
Ok, I can do a review.

Joaquim

**Comment by kbarnhart** [comment]
thanks @seisman and @joa-quim for the speedy responses. I'll add @joa-quim over on the review issue (#2043).
