### ISSUE TITLE
[REVIEW]: skedm: Empirical Dynamic Modeling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#207]
**Submitting author:** @nickc1 (<a href="http://orcid.org/0000-0003-2262-663X">Nicholas Cortale</a>)
**Repository:** <a href="https://github.com/NickC1/skedm" target ="_blank">https://github.com/NickC1/skedm</a>
**Version:** v0.0.1
**Editor:** @jakevdp
**Reviewer:** @johnh2o2
**Archive:** <a href="http://dx.doi.org/10.6084/m9.figshare.4887398.v1" target="_blank">10.6084/m9.figshare.4887398.v1</a>

## Status

[![status](http://joss.theoj.org/papers/ab459afb8c8f600fef6873697aa1afba/status.svg)](http://joss.theoj.org/papers/ab459afb8c8f600fef6873697aa1afba)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ab459afb8c8f600fef6873697aa1afba"><img src="http://joss.theoj.org/papers/ab459afb8c8f600fef6873697aa1afba/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ab459afb8c8f600fef6873697aa1afba/status.svg)](http://joss.theoj.org/papers/ab459afb8c8f600fef6873697aa1afba)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/NickC1/skedm" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/NickC1/skedm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.0.1)?
- [x] **Authorship:** Has the submitting author (@nickc1) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @johnh2o2 it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by johnh2o2** [comment]
Hi @nickc1,

I've raised two issues (about the [version](https://github.com/nickc1/skedm/issues/2) and two [bugs in the ipynb](https://github.com/nickc1/skedm/issues/1)) in your GitHub repository. The rest of my review is below. Let me know if you have any questions or comments regarding anything!

## Overall
I'm not sure if I need to officially assign some status for this review, but currently I would say this is extremely close to submission with very minor issues. The vast majority of issues are with documentation, which is already quite thorough.

## Functionality
* The example `.ipynb` provides a large variety of both 1D and 2D examples with visualizations, all of which successfully execute (after fixing two typos).
* Unit tests of core functionality provide additional assurances of functionality.

## Performance
* There are only a few cursory and casual benchmarks, all of which were consistent with timing when run on my laptop. It (optionally) may be useful to present some basic timing analysis, but unless there is a discrepancy between stated and actual performance, I don't see this as a problem.

## API documentation
* Generally very good. Plots, in particular, were particularly helpful in illustrating some otherwise difficult to visualize points.
* Some detail is missing or glossed over that if provided should help clarify things for the reader that stumbles across your code. (I've detailed these below)
* In your docstrings for the `Classification` and `Regression` classes, I would try to add some more detail in the header
    * For instance Classification just says "Nonlinear classification", but nonlinear classification of what?
    * It would help to give some examples in the docstring (which you have for several functions):
    ```python
    """
    ...
    Examples
    --------
    >>> classifier = skedm.skedm.Classification(weights='distance')
    >>> classifier.fit(Xtrain, ytrain)
    ...
    """
    ```
### Install
* Looks good

### Quick example
* Great introduction!
* Great explanation of how to pick the time lag (mutual information minimum)
* This code I have trouble understanding
    ```python
    M.fit(Xtrain, ytrain) #fit the data (rebuilding the attractor)

    nn_list = np.arange(1,200,dtype='int') #first 200 NN
    ypred = M.predict(Xtest, nn_list)

    score = M.score(ytest) #score
    ```

    * What exactly is `score`? (I wasn't able to find the answer in the Score section)
    * What does `nn_list` represent? If I run `M.predict(Xtest, [ 1 ])` does this try to predict `y_test` by using only the closest neighbor for each of the points in `Xtest`? If I run `M.predict(Xtest, [1, 3])` does this use only the closest and third closest neighbor?
* The plot underneath makes sense, but I would explicitly show either some code that produces it or mention that this is generated by performing the same embed/regress/score procedure above, but for various `predict` and `nn_list` values (which correspond to the Forecast Distance and Near Neighbors).
* When talking about the forecast skill of each near neighbor, are you talking about how well you do by using a single neighbor trajectory? And you can choose to use the Nth nearest neighbor? If so, I think the X label on the plot underneath should be "Nth nearest neighbor" or something to denote that you aren't aggregating N near neighbors.

### Generate Data
* Some parameters are missing or inconsistent with the equation given in the docstring
    * Example: logistic map: `X(t+1) = rX(t)(1-X(t)) + random`
        * However, parameters are `A`, and `noise` should probably be used
    * `noisy_periodic`: use noise, freq in equation, etc.


### Embed
* You have `X, y = E.embed_vectors_1d(lag, emb, predict)`, but I think it might help to explicitly explain what `X` and `y` are via explaination in the text or via denoting them on your plots. I assume the green values are `y[n]` (vector of length `predict`) and the red values are `X[n]` (vector of length `embed`)?
 
### Predict
* Good overview.

### Score
* This is where I'm most confused -- I didn't see any explicit definition for what exactly
    `score` was; is this the $$R^2$$ correlation coefficient? Or something else?
* "After calculating near neighbors, calculating the forecast and forecast skill, the following plot is produced."
    * Too vague -- the plot was confusing to me. Are you plotting the "score" for predictions done using single neighbors? Meaning, do you say "ok lets use the 1st-closest neighbor", then compute R^2 and the average distance away that the 1st nearest neighbor is? Then moving on to the 2nd-closest, etc.? 
    * The sentence below the plot adds some clarification, but it would be helpful to have some verbose code snippets that explain exactly what is being done to produce the plot

## Paper
* Great! (The references section should be blank, right?)

**Comment by arfon** [comment]
> Great! (The references section should be blank, right?)

Yep, these will be added at paper compilation time (by Pandoc)

**Comment by jakevdp** [comment]
@johnh2o2 — thanks for the thorough review. I think that some of the confusion you noted could be remedied by somewhere pointing to the scikit-learn API, which this seems to be modeled after.

@nickc1 — I think these are a nice set of comments and suggestions, and will improve the usability of your code. I hope you're able to address them!

**Comment by nickc1** [comment]
@jakevdp -- I definitely agree. Working down the list as I type this.

@johnh2o2 -- Appreciate the thorough comments. It's great getting an outside perspective on something that has been only used in our lab.  Hoping to have it wrapped up by the end of today! Thanks again.

**Comment by nickc1** [comment]
Hey John @johnh2o2 ,

Thanks for the helpful comments. They made the documentation a lot clearer. Also, sorry for the lag in response time. I'm changing jobs at the end of next week, so I am getting pulled in a lot of different directions. Thanks for taking the time to review this! Let me know if you have any questions or want me to point you to specific commits or need me to clarify some of the new material.

Thanks again,
Nick


## Performance

> It (optionally) may be useful to present some basic timing analysis, but unless there is a discrepancy between stated and actual performance, I don't see this as a problem.

Added a section on performance in the documentation to make this more clear/helpful.

## API documentation

> In your docstrings for the Classification and Regression classes, I would try to add some more detail in the header. For instance Classification just says "Nonlinear classification", but nonlinear classification of what?

Updated docstrings with examples and fixed some of the formatting issues in the docstrings of the Embed class.

## Quick example

> What exactly is score? (I wasn't able to find the answer in the Score section) What does nn_list represent? If I run M.predict(Xtest, [ 1 ]) does this try to predict y_test by using only the closest neighbor for each of the points in Xtest? If I run M.predict(Xtest, [1, 3]) does this use only the closest and third closest neighbor?

I've added some new plots that (I think) do a better job of what the score represents. I also overhauled the score section to make it more clear to the reader what is actually going on. This comment was invaluable as I never really explained what score actually was. Appreciate this.

> When talking about the forecast skill of each near neighbor, are you talking about how well you do by using a single neighbor trajectory? And you can choose to use the Nth nearest neighbor? If so, I think the X label on the plot underneath should be "Nth nearest neighbor" or something to denote that you aren't aggregating N near neighbors.

Added an example of each in the quick example section to make this more clear.

## Generate Data

> Some parameters are missing or inconsistent with the equation given in the docstring Example: logistic map: X(t+1) = rX(t)(1-X(t)) + random

Updated the docstrings to represent the correct parameters.

## Embed

> You have X, y = E.embed_vectors_1d(lag, emb, predict), but I think it might help to explicitly explain what X and y are via explanation in the text or via denoting them on your plots. I assume the green values are y[n] (vector of length predict) and the red values are X[n] (vector of length embed)?

Explicitly stated now.

## Score

> This is where I'm most confused -- I didn't see any explicit definition for what exactly
score was; is this the $$R^2$$ correlation coefficient? Or something else?

I've completely overhauled this section as it was quite confusing. Let me know what you think.

## Paper

> Great! (The references section should be blank, right?)

I added a reference. An R package was actually released between the submission and now with similar functionality, so I decided to cite it in the paper.md.

## Statement of Need

Added a statement of need at the bottom of the documentation index.

## Versioning

If everything looks good, I'll change the version to 1.0 and push that to pypi.

**Comment by jakevdp** [comment]
@nickc1 – thanks for the quick response here. @johnh2o2 – let us know if you have any further suggestions for the submission. Thanks all!

**Comment by johnh2o2** [comment]
Hi @nickc1,

Things look much better! I have a few additional suggestions for you; once these are resolved I think everything should be ready to go.

## Version

> Version: Does the release version given match the GitHub release (v0.0.1)?

It's still `0.2.0` in the repo -- I would consider changing either the repo version, the Github release version (I'm not sure where that comes from) or both.

## Documentation

### Embed 

> Here `X` is the red matrix (features) and `y` is the red matrix above (targets)

I think you mean `y`is the **green** matrix above (right?).

### Generate data
Better, however there is still some confusing/incomplete documentation:

* For the Lorenz attractor, if you have time/it's easy, it might make sense to let the user change the default `sigma`, `beta`, and `rho` values.
* For the `chaos_2d` and `chaos_3d` -- could you provide a link with more information about the logistic map diffused in space? Or if it's simple to give an explicit definition that would be helpful too
* Same with `periodic_2d` (i.e. what is the explicit form of the equation?)
* In `periodic_brown`, the equaiton given is `X = sin(y + noise*2pi)`, however there's a `freq` param; I'm assuming it's `X = sin(2 * pi * (freq * y + noise))`?
* For `skedm.data.noise_2d(sz=128, seed=36)`; I imagine some people will want to know what library/algorithm you're using as the random number generation; I would just mention what library/function you're using (e.g. numpy, etc.).
* `random_circles` -- what is a "random gaussian circle?"
* `circle_in_circle`, `circles_with_stuff`,`random_sized_circles`, I'm not sure what the form of the output is. What does the `blobber`/`blobber2` function do? If you're returning A 2-D array of size `(sz, sz)`, what does that array represent? Is it a bit-map image? The explanation for these should be a bit more specific
* In the `voronoi_diagram`, you say `sz -- row and column size of the space in which the circle is placed.`, but I think that's a typo since these are polygons. The return value is also unclear to me (see previous note)

Other than these suggestions, everything else looks good from here. The `ipynb` notebook runs all cells without raising any exceptions, so that looks good now.

Let me know if you have any objections or if anything isn't clear!

John

**Comment by nickc1** [comment]
Hey John,

I think I have it all sorted out. Again, thanks for taking the time to come through my documentation.

> Version: Does the release version given match the GitHub release (v0.0.1)?

This should be all set now. Both are version v0.0.3. I did a fresh pip install in a conda environment and everything seems to run properly.

> I think you mean y is the green matrix above (right?).

Fixed!


> Documentation: Better, however there is still some confusing/incomplete documentation:

Fixed! Thanks for calling me out on blobber/blobber2. Those were ridiculous names. I also added a notebook (skedm_example_data.ipynb) giving examples of all of the test data.

> For the Lorenz attractor, if you have time/it's easy, it might make sense to let the user change the default sigma, beta, and rho values.

Check.

> For the chaos_2d and chaos_3d -- could you provide a link with more information about the logistic map diffused in space? Or if it's simple to give an explicit definition that would be helpful too.

Explicit definition given.

> Same with periodic_2d (i.e. what is the explicit form of the equation?)

Explicit form given.

> In periodic_brown, the equaiton given is X = sin(y + noise*2pi), however there's a freq param; I'm assuming it's X = sin(2 * pi * (freq * y + noise))?

Added to docstring.

> For skedm.data.noise_2d(sz=128, seed=36); I imagine some people will want to know what library/algorithm you're using as the random number generation; I would just mention what library/function you're using (e.g. numpy, etc.).

Added this to all functions utilizing numpy's random number generation.

> random_circles -- what is a "random gaussian circle?"

Updated docstring with links explaining what is going on.

> circle_in_circle, circles_with_stuff,random_sized_circles, I'm not sure what the form of the output is. What does the blobber/blobber2 function do? If you're returning A 2-D array of size (sz, sz), what does that array represent? Is it a bit-map image? The explanation for these should be a bit more specific

Updated docstring and added this to the notebook.

> In the voronoi_diagram, you say sz -- row and column size of the space in which the circle is placed., but I think that's a typo since these are polygons. The return value is also unclear to me (see previous note)

Fixed

Let me know if you need me to make any changes!

Thanks again,
Nick

**Comment by jakevdp** [comment]
Thanks for the response, Nick. @johnh2o2 – please let us know if the responses address all your concerns. Thanks!

**Comment by johnh2o2** [comment]
Hi @nickc1,

Sorry about the delay! This looks great. I feel comfortable recommending this for acceptance in JOSS as is.

John

**Comment by jakevdp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by jakevdp** [comment]
Thanks @nickc1 and @johnh2o2! Looks good – we'll conclude the review process shortly (cc @arfon).

**Comment by arfon** [comment]
@nickc1 - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by nickc1** [comment]
First time creating a doi, but here is the figshare link:

https://doi.org/10.6084/m9.figshare.4887398.v1

Let me know if you need anything else!

**Comment by arfon** [comment]
@whedon set 10.6084/m9.figshare.4887398.v1 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.6084/m9.figshare.4887398.v1" target="_blank">10.6084/m9.figshare.4887398.v1</a> is the archive.

**Comment by arfon** [comment]
@johnh2o2 - many thanks for your review here and @jakevdp for editing this submission ✨ 

@nickc1 - your paper is now accepted into JOSS and your paper DOI is http://dx.doi.org/10.21105/joss.00207 ⚡️ 🚀 💥

**Comment by nickc1** [comment]
Thanks again @johnh2o2 for all the thoughtful comments. The package and documentation are way more user friendly. Thanks @jakevdp for editing. This was a cool submission process and definitely learned quite a bit along the way. Thanks for taking the time to make skedm better!

**Comment by nickc1** [comment]
@johnh2o2 @jakevdp Realized I inadvertently left off the citation that actually coined the term empirical dynamic modeling. Any way to add it in in the first sentence after the first mention of the term? or is it all locked in?

Thanks! 

Ye, Hao, et al. "Equation-free mechanistic ecosystem forecasting using empirical dynamic modeling." Proceedings of the National Academy of Sciences 112.13 (2015): E1569-E1576.
