### ISSUE TITLE
[PRE REVIEW]: Ripeline and Rmanual speed up biological research and reporting

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2070]
**Submitting author:** @ashipunov (<a href="http://orcid.org/0000-0002-1387-8280">Alexey Shipunov</a>)
**Repository:** <a href="https://github.com/ashipunov/RR" target ="_blank">https://github.com/ashipunov/RR</a>
**Version:** 1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @ashipunov. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @karthik.

@ashipunov if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.02 s (60.7 files/s, 7158.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         1             15              0            103
-------------------------------------------------------------------------------


Statistical information for the repository '2070' was gathered on 2020/02/04.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02070/joss.02070/10.21105.joss.02070.pdf)

**Comment by ashipunov** [comment]
Please insert CC0 license.

AS

вт, 4 февр. 2020 г. в 22:26, whedon <notifications@github.com>:

**Comment by kthyng** [comment]
Hi @ashipunov! The repo linked to in this issue only contains a paper.md file. Is there a different repo where you package is located?

**Comment by ashipunov** [comment]
Yes, they located at https://github.com/ashipunov/Ripeline and
https://github.com/ashipunov/Rmanual, plus there are two more repositories
with examples, all on https://github.com/ashipunov

AS

вт, 4 февр. 2020 г. в 22:40, Kristen Thyng <notifications@github.com>:

**Comment by danielskatz** [comment]
CC0 is not a valid license for JOSS - it is not OSI-approved

**Comment by ashipunov** [comment]
Then please change it to the most free variant which is approved like GPL 3.0.

AS

вт, 4 февр. 2020 г. в 23:01, Daniel S. Katz <notifications@github.com>:

**Comment by kthyng** [comment]
@ashipunov Please look in detail through submission guidelines to see how to set up your repository so it could be reviewed: https://joss.readthedocs.io/en/latest/submitting.html
Right now it won't work to have pieces spread out over several places unless it is really necessary such as when the submission is a significant contribution to a larger package.

It may help to also look through previous JOSS submissions that have successfully come through review to see how those packages look.

We do not control your submission repository, so if you want to change your license file, you should do that yourself.

**Comment by ashipunov** [comment]
Dear colleagues,

I think that my submission complies with the requirements. The only
issue is the license. I will update it.

As for multiple repositories, the guidelines do not contain any
restrictions. In my case, it is necessary to have multiple
repositories since all of my packages are part of the bigger system
which I develop to help field biologists in their work.

With best wishes,

Alexey Shipunov


ср, 5 февр. 2020 г. в 00:49, Kristen Thyng <notifications@github.com>:

**Comment by kthyng** [comment]
@ashipunov How would a user know where all of these repositories are? Is it in your manual? Perhaps it would be useful to add to your paper. Please be more specific than listing the address for your github page.

**Comment by ashipunov** [comment]
OK, I will add all four repositories names into the paper. Thanks!

AS

ср, 5 февр. 2020 г. в 01:11, Kristen Thyng <notifications@github.com>:

**Comment by ashipunov** [comment]
Dear colleagues,

I entered links to repositories and license into the paper text. Thanks again!

With best wishes,

Alexey Shipunov

ср, 5 февр. 2020 г. в 01:13, Alexey Shipunov <dactylorhiza@gmail.com>:

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02070/joss.02070/10.21105.joss.02070.pdf)

**Comment by ashipunov** [comment]
Thanks, I have checked it.

AS

пт, 7 февр. 2020 г. в 01:02, whedon <notifications@github.com>:

**Comment by kthyng** [comment]
@ashipunov Thank you for your submission to JOSS. Unfortunately, we cannot accept your submission into review as it currently stands. Some of the problems include:

* Your repository contains a series of scripts instead of a software package (here is a suggested resource to learn more about good packaging practices in R: http://r-pkgs.had.co.nz/)
* The code is spread across several repositories, making it difficult to review or for a user to actually use
* The documentation needs to be compiled which makes it harder to quickly understand how your package works
* Are there tests? A way for a user to verify that the code works correctly is required.

All of these issues add up to too much time that would be required by an editor and reviewers at JOSS as your submission currently stands.  If you would like to work more on your package and then resubmit, I suggest that you start with a pre-review issue to discuss the package once it has been improved.

**Comment by kthyng** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by ashipunov** [comment]
Thank you for the review.

AS

вс, 9 февр. 2020 г. в 05:43, Kristen Thyng <notifications@github.com>:

**Comment by kthyng** [comment]
@ashipunov Just want to correct my final note from before. Rather than saying to start with a pre-review issue for discussion, I should have said that you can start with a pre-submission inquiry, as mentioned on https://joss.theoj.org/about#submitting. You can start one with this link when you're ready: https://github.com/openjournals/joss/issues/new?title=Pre-submission%20enquiry

**Comment by ashipunov** [comment]
OK, thank you.

AS

пн, 10 февр. 2020 г. в 01:15, Kristen Thyng <notifications@github.com>:
