### ISSUE TITLE
[PRE REVIEW]: wflo: A New Standard for Wind Farm Layout Optimization in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2190]
**Submitting author:** @CarstenCroonenbroeck (<a href="http://orcid.org/0000-0001-7848-0970">Carsten Croonenbroeck</a>)
**Repository:** <a href="https://github.com/CarstenCroonenbroeck/WFLO" target ="_blank">https://github.com/CarstenCroonenbroeck/WFLO</a>
**Version:** v1.5
**Editor:** @kyleniemeyer
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @CarstenCroonenbroeck. **Currently, there isn't an JOSS editor assigned** to your paper.

@CarstenCroonenbroeck if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2190 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2190 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-45a043c4bfc2/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1016/0304-4076(86)90002-3 is OK
- 10.1007/978-1-4899-3242-6 is OK
- 10.18637/jss.v023.i07 is OK
- 10.1007/978-0-387-21706-2 is OK
- 10.18637/jss.v032.i10 is OK
- 10.18637/jss.v027.i08 is OK

MISSING DOIs

- https://doi.org/10.3390/en11123268 may be missing for title: Realistic Wind Farm Layout Optimization through Genetic Algorithms Using a Gaussian Wake Model
- https://doi.org/10.2514/6.2019-0540 may be missing for title: Best Practices for Wake Model and Optimization Algorithm Selection in Wind Farm Layout Optimization
- https://doi.org/10.1016/j.enconman.2013.02.007 may be missing for title: Wind farm layout optimization using genetic algorithm with different hub height wind turbines
- https://doi.org/10.1088/1742-6596/1037/4/042012 may be missing for title: A method for reducing multi-modality in the wind farm layout optimization problem
- https://doi.org/10.1007/s42791-019-00026-z may be missing for title: Wind farm layout optimization using genetic algorithm and its application to Daegwallyeong wind farm
- https://doi.org/10.1016/j.renene.2019.07.002 may be missing for title: A design methodology for wind farm layout considering cable routing and economic benefit based on genetic algorithm and GeoSteiner
- https://doi.org/10.1016/j.apenergy.2019.114426 may be missing for title: Optimal design of wind farms in complex terrains using computational fluid dynamics and adjoint methods
- https://doi.org/10.1016/j.enconman.2019.04.059 may be missing for title: A novel method for wind farm layout optimization based on wind turbine selection

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02190/joss.02190/10.21105.joss.02190.pdf)

**Comment by arfon** [comment]
@CarstenCroonenbroeck - thanks for your submission to JOSS. This submission currently looks incomplete, i.e. there's no software present in the submitted repository. Could you please clarify where the software is, and ideally, move the paper to that repository?

**Comment by CarstenCroonenbroeck** [comment]
Dear Arfon,

 

the software is an R package available on CRAN (https://CRAN.R-project.org/package=wflo). Hosting the software (and keeping the version up-to-date) at github would be redundant. Is that okay?

 

Best

 

Carsten

 
 

Gesendet: Donnerstag, 21. Mai 2020 um 16:19 Uhr
Von: "Arfon Smith" <notifications@github.com>
An: "openjournals/joss-reviews" <joss-reviews@noreply.github.com>
Cc: "CarstenCroonenbroeck" <c.croonenbroeck@gmx.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [openjournals/joss-reviews] [PRE REVIEW]: wflo: A New Standard for Wind Farm Layout Optimization in R (#2190)


 

@CarstenCroonenbroeck - thanks for your submission to JOSS. This submission currently looks incomplete, i.e. there's no software present in the submitted repository. Could you please clarify where the software is, and ideally, move the paper to that repository?

**Comment by arfon** [comment]
> the software is an R package available on CRAN (https://CRAN.R-project.org/package=wflo). Hosting the software (and keeping the version up-to-date) at github would be redundant. Is that okay?

I'm afraid not. As per our [submission requirements](https://joss.readthedocs.io/en/latest/submitting.html), software submitted to JOSS must:

- Be stored in a repository that can be cloned without registration.
- Be stored in a repository that is browsable online without registration.
- Have an issue tracker that is readable without registration.
- Permit individuals to create issues/file tickets against your repository.

**Comment by CarstenCroonenbroeck** [comment]
Dear Arfon,

 

okay, no problem. I uploaded everything to a sub folder "package" you will easily find.

 

Thanks and best regards

 

Carsten

 
 

Gesendet: Freitag, 22. Mai 2020 um 18:43 Uhr
Von: "Arfon Smith" <notifications@github.com>
An: "openjournals/joss-reviews" <joss-reviews@noreply.github.com>
Cc: "CarstenCroonenbroeck" <c.croonenbroeck@gmx.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [openjournals/joss-reviews] [PRE REVIEW]: wflo: A New Standard for Wind Farm Layout Optimization in R (#2190)


 


the software is an R package available on CRAN (https://CRAN.R-project.org/package=wflo). Hosting the software (and keeping the version up-to-date) at github would be redundant. Is that okay?


I'm afraid not. As per our submission requirements, software submitted to JOSS must:


	Be stored in a repository that can be cloned without registration.
	Be stored in a repository that is browsable online without registration.
	Have an issue tracker that is readable without registration.
	Permit individuals to create issues/file tickets against your repository.

**Comment by CarstenCroonenbroeck** [comment]
Dear Arfon,

so, anything new on the status?

Thanks and best regards

Carsten

**Comment by arfon** [comment]
@CarstenCroonenbroeck - thanks for making this update. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by danielskatz** [comment]
👋 @meg-simula - would you be able to edit this submission? It's not exactly in your area, but I hope you might be willing, given the backlog of submissions

**Comment by danielskatz** [comment]
@whedon invite @meg-simula as editor

**Comment by whedon** [comment]
@meg-simula has been invited to edit this submission.

**Comment by meg-simula** [comment]
@danielskatz Thanks for the invite. I have taken a look, but as I don't speak R natively, I am having difficulty in evaluating the submission at all. I'm afraid that I will have to decline this one.

**Comment by kyleniemeyer** [comment]
I will take this one on as editor.

**Comment by kyleniemeyer** [comment]
@whedon assign @kyleniemeyer as editor

**Comment by whedon** [comment]
OK, the editor is @kyleniemeyer

**Comment by kyleniemeyer** [comment]
@CarstenCroonenbroeck I may be able to find some reviewers who are familiar with wind farm layout optimization, but perhaps less so in R. Do you have any recommendations on that side, who may also be familiar with the problem?

**Comment by CarstenCroonenbroeck** [comment]
Dear Kyle,

 

I am also acquainted with a few WFLO researchers, but so far, no-one is working with R. Yet, that is, maybe we change that with our package. :-)

 

Best

 

Carsten
 

Gesendet: Freitag, 05. Juni 2020 um 23:29 Uhr
Von: "Kyle Niemeyer" <notifications@github.com>
An: "openjournals/joss-reviews" <joss-reviews@noreply.github.com>
Cc: "CarstenCroonenbroeck" <c.croonenbroeck@gmx.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [openjournals/joss-reviews] [PRE REVIEW]: wflo: A New Standard for Wind Farm Layout Optimization in R (#2190)


 

@CarstenCroonenbroeck I may be able to find some reviewers who are familiar with wind farm layout optimization, but perhaps less so in R. Do you have any recommendations on that side, who may also be familiar with the problem?

**Comment by kthyng** [comment]
@whedon check repository

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (197.7 files/s, 78532.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              4            156             10            888
R                                2            168             10            822
Markdown                         1             82              0            645
-------------------------------------------------------------------------------
SUM:                             7            406             20           2355
-------------------------------------------------------------------------------


Statistical information for the repository '2190' was gathered on 2020/07/28.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
@kyleniemeyer sorry I should have checked with you before adding query scope — you can override if you want.

**Comment by CarstenCroonenbroeck** [comment]
I'm sorry, I'm afrain I don't understand. Do I need to do anything now?

**Comment by kyleniemeyer** [comment]
Hi @CarstenCroonenbroeck, sorry for the delay here and confusion. 

@kthyng was reviewing all submissions that had not yet been processed, and one of the things we have implemented in recent weeks/months is some basic checking of software submission size and scope. Because your package is relatively small in terms of lines of code, it was flagged for the editorial board to check the scope. We have recently clarified/documented our submission requirements in terms of (a) what is research software and (b) what represents "substantial scholarly effort": https://joss.readthedocs.io/en/latest/submitting.html 

We will discuss and get back to you—sorry again for the delays.

**Comment by kyleniemeyer** [comment]
Hi @CarstenCroonenbroeck, I'm sorry for the continued delay here—this fell off my radar.

The JOSS editorial board evaluated your submission, and while we do find it in scope for the journal, your package needs some additional work before we solicit reviewers. In particular, it seems to be missing a number of the elements that JOSS looks for:
- There is minimal documentation, including even a README.
- There are practically no unit tests
- You don't seem to have been using git for version control
- There is no open-source license
- There are no community guidelines

You can see the full set of JOSS review criteria here: https://joss.readthedocs.io/en/latest/review_criteria.html. You should probably also review some R-specific resources, including:
- [R Packages book](http://r-pkgs.had.co.nz/)
- [rOpenSci Packages: Development, Maintenance, and Peer Review](https://devguide.ropensci.org)

Considering that this is a fairly small package already, it will be really important for you to improve these elements to make the software follow best practices. If you feel you are able to work on this, I am going to pause the submission until you have been able to resolve these issues.

**Comment by CarstenCroonenbroeck** [comment]
Dear Kyle,

thanks a lot for your effort so far. However, I'm a little bit puzzled by some of your comments. Please let me answer to them point-by-point:

- There is minimal documentation, including even a README.

How can you say that? Every exported function, every data object and the package itself has a thorough documentation following the CRAN package policies. Those are the ".Rd" files in the subfolder "man".

- There are practically no unit tests

That's absolutely right, and I'll do my "homework" on this one.

- You don't seem to have been using git for version control

No, I'm using the [CRAN versioning system](https://cran.r-project.org/web/packages/wflo/index.html). Every previous version starting from the initial release up the the most current one is there, open for inspection.

- There is no open-source license

Yes, there is. File "DESCRIPTION" clearly states that **wflo** is licensed using GPL-3.

- There are no community guidelines

Well, the documentation above, as well as the vignette (see the sweave document in the "vignettes" folder) serves as a user's workflow guide.

In any case, please acknowledge the validity of my points here. The R packages book you cite is exactly the one I used during development of **wflo**. I think I complied with pretty much everything there, and the CRAN team itself seems to agree, since they accepted my package.

Suggestion: Let's put this review process on-hold until the next version release, which is going to be published soon. The next version will be much more mature than the current version, and I will also perform the necessary unit tests there. Are you willing to go into another round, then? If so, does it suffice if I put a note to this thread? Or do I have to re-submit entirely?

**Comment by kyleniemeyer** [comment]
Hi @CarstenCroonenbroeck, while what you did may meet the minimum needs of CRAN, our standards our higher—in fact, one of the reasons JOSS exists is to ensure software follows best, sustainable practices, rather than the minimum of what is necessary to create a package. For R packages, the [rOpenSci developer guide](https://devguide.ropensci.org) is going to be your best resource, rather than the minimum of what CRAN needs, for modern best practices. 

Regarding your points:
- Simply documenting functions is not sufficient—at minimum a [README is also needed](https://devguide.ropensci.org/building.html#readme). This is standard in modern software packages. Depending on the complexity of a project, a [documentation website may also be warranted](https://devguide.ropensci.org/building.html#website)
- Regarding versioning, simply uploading entire new versions does not follow modern best practices for software development. (Again, what is allowed by CRAN is not the same as a good practice.) It also makes it nearly impossible for others to contribute. Now that your software is on GitHub, you should use Git as you continue to work on the software, and *not* simply upload the next new version.
- Simply mentioning the license is not sufficient, you need a plaintext copy of the license in the repository, at the top level. This is explicitly included in the JOSS review criteria: https://joss.readthedocs.io/en/latest/review_criteria.html#software-license
- We also have an explicit requirement for [community guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines). This can go in the README.

All of these issues are things that reviewers of your software would immediately bring up, and likely get stuck on rather than giving more-specific feedback, which is the reason I'm bringing them up at this stage.

If you have a new version coming soon, we can keep this issue open, and you can ping us when you're ready. Please do consider all of the above requirements as you work on the next version.

**Comment by kyleniemeyer** [comment]
@CarstenCroonenbroeck Also, I would just like to point out that (a) I was stating things that JOSS would expect, and require you to improve upon—you did submit your software package to us for review, after all, with (I hope) the understanding that you would receive constructive feedback to improve it; and (b) your response falls a bit short of our standards laid out in the [JOSS Code of Conduct](https://github.com/openjournals/joss/blob/master/CODE_OF_CONDUCT.md).

**Comment by arfon** [comment]
@whedon withdraw

:wave: as this submission has been waiting for a new release for some months now, I'm going to go ahead and withdraw this submission on behalf of the submitting author.

@CarstenCroonenbroeck - when you are ready to resubmit having addressed the feedback above, please do so.

**Comment by whedon** [comment]
Paper withdrawn.
