### ISSUE TITLE
[PRE REVIEW]: ccex: An R client for the C-Cex Crypto Currency Exchange

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#220]
**Submitting author:** @kaneplusplus (<a href="http://orcid.org/0000-0003-1899-6662">Michael Kane</a>)
**Repository:** <a href="https://github.com/kaneplusplus/ccex" target ="_blank">https://github.com/kaneplusplus/ccex</a>
**Version:** 0.1.0
**Editor:** Pending
**Reviewer:** Pending

**What this issue is for**

Thanks for submitting your paper to JOSS @kaneplusplus. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: @kaneplusplus, thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#author_guidelines). In particular, this item:

> - Your software should have a research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)?

Many thanks!

**Comment by kaneplusplus** [comment]
Hi @afron. Thanks for the note. I do think the point is valid. I think the data is very useful for research purposes for the following two general reasons:

1. The crypto-currency market itself still isn't well understood. The fact that USD is included in the market allows someone to price cryptocurrencies in terms of traditional currencies.
2. The order book for each market is available. This is usually very difficult data to find and this alone makes it very interesting for research purposes.

Furthermore, I'm currently using the package to explore the following two questions:

1. One of the altcoins on the exchange is TrumpCoin. It is not affiliated with its namesake. We are looking for economy and sentiment data, focusing on the president, that may be correlated with currency price. If we find correlated pairs, we can argue that people are using the currency to create new markets. We may eventually see currencies for sports teams, movies, and so on whose price is determined by people's belief in their value
2. How do new currencies affect exchange rate inefficiencies? There are daily arbitrage opportunities on the exchange for fractions of a penny. They almost always involve the newer altcoins on the exchange. This is probably because the market is having trouble pricing these new financial products.

It is true that the private interface is less interesting for research since it allows individuals to manage their currency. Would it be sufficient to marginalize this portion of the package for the write-up? Does this answer your question?

**Comment by arfon** [comment]
Thanks for the feedback @kaneplusplus. Based on your feedback here I'm wondering if this is a good candidate for [rOpenSci](https://ropensci.org) (which would also allow for submission here).

@noamross - any interest in this package?

**Comment by kaneplusplus** [comment]
@arfon thanks for the suggestion.

@noamross if you think it's appropriate, I would he happy to contribute to the rOpenSci ecosystem.

**Comment by noamross** [comment]
@kaneplusplus Yes, this package should fit into rOpenSci policies under our [data retrieval category](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit). If you choose to submit with us, please refer to our [packaging guide](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md).  **ccex** will require a vignette, a test suite and continuous integration before we send it to reviewers.

**Comment by kaneplusplus** [comment]
@noamross Thanks for the instructions. I'll try to get to the vignette, test suite, and continuous integration in the next week or so.

**Comment by arfon** [comment]
:wave: what's the status of this submission? Was it ever accepted into rOpenSci?

**Comment by kaneplusplus** [comment]
@arfon it was not. The RESTful API was made unavailable by CloudFlare and the package was re-written as the bittrex package, which was accepted. 

The code is available but not complete. If someone else want to take it, I would support that. However, I think we can remove this submission to ROpenSci.

Does this sound reasonable?

**Comment by arfon** [comment]
> The code is available but not complete. If someone else want to take it, I would support that. However, I think we can remove this submission to ROpenSci.

Sorry, so just to clarify - withdraw this submission _to JOSS_ here?

**Comment by kaneplusplus** [comment]
@arfon No problem. Yes, please withdraw the submission.
