### ISSUE TITLE
[PRE REVIEW]: iRONS: interactive Reservoir Operation Notebooks and Software for water reservoir systems simulation and optimisation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2231]
**Submitting author:** @AndresPenuela (<a href="http://orcid.org/0000-0001-8039-975X">Andres Peñuela</a>)
**Repository:** <a href="https://github.com/AndresPenuela/iRONS" target ="_blank">https://github.com/AndresPenuela/iRONS</a>
**Version:** v1.0.0
**Editor:** @kbarnhart
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @AndresPenuela. **Currently, there isn't an JOSS editor assigned** to your paper.

@AndresPenuela if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02231/joss.02231/10.21105.joss.02231.pdf)

**Comment by AndresPenuela** [comment]
@whedon commands


________________________________
De: whedon <notifications@github.com>
Enviado: Friday, May 22, 2020 9:57:21 PM
Para: openjournals/joss-reviews <joss-reviews@noreply.github.com>
Cc: Andres Penuela-Fernandez <andres.penuela-fernandez@bristol.ac.uk>; Mention <mention@noreply.github.com>
Asunto: [openjournals/joss-reviews] [PRE REVIEW]: iRONS: interactive Reservoir Operation Notebooks and Software for water reservoir systems simulation and optimisation (#2231)


Submitting author: @AndresPenuela<https://github.com/AndresPenuela> (Andres Peñuela<http://orcid.org/0000-0001-8039-975X>)
Repository: <https://github.com/AndresPenuela/iRONS> https://github.com/AndresPenuela/iRONS
Version: v1.0.0
Editor: Pending
Reviewer: Pending
Managing EiC: Arfon Smith

⚠️ JOSS reduced service mode ⚠️

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in our blog post<https://blog.joss.theoj.org/2020/05/reopening-joss>.

Author instructions

Thanks for submitting your paper to JOSS @AndresPenuela<https://github.com/AndresPenuela>. Currently, there isn't an JOSS editor assigned to your paper.

@AndresPenuela<https://github.com/AndresPenuela> if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this list of people<https://bit.ly/joss-reviewers> have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

Editor instructions

The JOSS submission bot @whedon<https://github.com/whedon> is here to help you find and assign reviewers and start the main review. To find out what @whedon<https://github.com/whedon> can do for you type:

@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by AndresPenuela** [comment]
@whedon list reviewers


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: whedon <notifications@github.com>
Enviado: Saturday, May 23, 2020 10:42:00 AM
Para: openjournals/joss-reviews <joss-reviews@noreply.github.com>
Cc: Andres Penuela-Fernandez <andres.penuela-fernandez@bristol.ac.uk>; Mention <mention@noreply.github.com>
Asunto: Re: [openjournals/joss-reviews] [PRE REVIEW]: iRONS: interactive Reservoir Operation Notebooks and Software for water reservoir systems simulation and optimisation (#2231)


Here are some things you can ask me to do:

# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
:wave: @AndresPenuela - Thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier in the week we've had > 50 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by AndresPenuela** [comment]
List of potential reviewers:
Full name: Eric Hutton, email: eric.hutton@colorado.edu<mailto:eric.hutton@colorado.edu>
Full name: Zoran Kapelan, email: Z.Kapelan@tudelft.nl<mailto:Z.Kapelan@tudelft.nl>
Full name: Jon Herman, email: jdherman@ucdavis.edu<mailto:jdherman@ucdavis.edu>, username: jdherman<mailto:jdherman>

De: whedon<mailto:notifications@github.com>
Enviado: 22 May 2020 21:57
Para: openjournals/joss-reviews<mailto:joss-reviews@noreply.github.com>
CC: Andres Penuela-Fernandez<mailto:andres.penuela-fernandez@bristol.ac.uk>; Mention<mailto:mention@noreply.github.com>
Asunto: [openjournals/joss-reviews] [PRE REVIEW]: iRONS: interactive Reservoir Operation Notebooks and Software for water reservoir systems simulation and optimisation (#2231)


Submitting author: @AndresPenuela<https://github.com/AndresPenuela> (Andres Peñuela<http://orcid.org/0000-0001-8039-975X>)
Repository: https://github.com/AndresPenuela/iRONS
Version: v1.0.0
Editor: Pending
Reviewer: Pending
Managing EiC: Arfon Smith

⚠️ JOSS reduced service mode ⚠️

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in our blog post<https://blog.joss.theoj.org/2020/05/reopening-joss>.

Author instructions

Thanks for submitting your paper to JOSS @AndresPenuela<https://github.com/AndresPenuela>. Currently, there isn't an JOSS editor assigned to your paper.

@AndresPenuela<https://github.com/AndresPenuela> if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this list of people<https://bit.ly/joss-reviewers> have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

Editor instructions

The JOSS submission bot @whedon<https://github.com/whedon> is here to help you find and assign reviewers and start the main review. To find out what @whedon<https://github.com/whedon> can do for you type:

@whedon commands

**Comment by AndresPenuela** [comment]
Would it be possible to add @FrancescaPianosi as a submitting author?

**Comment by arfon** [comment]
Could you say what you're trying to accomplish here @AndresPenuela ?

**Comment by AndresPenuela** [comment]
We are trying to develop a toolbox that can serve both the research and professional community in water systems operation and hence contribute to bridge the gap between them and promote the collaboration and integration of research advances in reservoir operation, e.g. hydrological forecast systems, into the real-world reservoir system management

**Comment by arfon** [comment]
Sorry, to clarify, I was wondering why you want to change the submitting author?

**Comment by danielskatz** [comment]
Also, to make it clear, JOSS only supports one submitting author

**Comment by AndresPenuela** [comment]
Thanks, I didn't want to change the submitting author, just wondering if there could be more than one submitting authors but that's all right.

**Comment by kyleniemeyer** [comment]
Hi @kbarnhart, do you have the bandwidth to edit this submission?

**Comment by kyleniemeyer** [comment]
@whedon invite @kbarnhart as editor

**Comment by whedon** [comment]
@kbarnhart has been invited to edit this submission.

**Comment by kbarnhart** [comment]
@kyleniemeyer yes, I can take this on.

**Comment by kbarnhart** [comment]
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment]
OK, the editor is @kbarnhart

**Comment by kbarnhart** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=5.23 s (9.7 files/s, 72374.4 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
Jupyter Notebook                 18              0         373733           2069
Python                           25            469            461           1710
TeX                               1              9              0            104
Markdown                          4             37              0            100
YAML                              1              0              0             16
INI                               1              1              0              4
Bourne Again Shell                1              1              5              1
--------------------------------------------------------------------------------
SUM:                             51            517         374199           4004
--------------------------------------------------------------------------------


Statistical information for the repository '2231' was gathered on 2020/06/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andres Penuela                   7           264            210            0.01
Andres Peñuela                   1       1009251            921           28.30
AndresPenuela                   56         12881        2544225           71.65
FrancescaPianosi                 1            30             30            0.00
ap18525                          1          1276              0            0.04

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andres Peñuela              735            0.1          1.0               14.29
AndresPenuela              1261            9.8          3.6               11.50
FrancescaPianosi              1            3.3          6.9                0.00
ap18525                     678           53.1          0.0                8.55
```

**Comment by kbarnhart** [comment]
@AndresPenuela thank you for submitting iRONS to JOSS. It looks like a valuable contribution to water resources. One of the first things that happens in a JOSS submission is that the handling editor (me) does an initial check of the submission. I have a couple of clarifying questions as part of this stage of the JOSS process. 

1) I'm having a hard time finding the documentation for the functions provided in iRONS/Toolbox folder. I see these functions being used and described in the notebooks, but expected to find some API documentation. Could you point me in the right direction?

2) I see that there are some tests provided in a test folder, but that there are no instructions for how to run the tests. I would recommend that this be added to the readme. In addition, I noticed that your Travis build icon points to builds of a repository that is not iRONS. 

3) I'm a little confused by the installation instructions. While downloading seems to be supported via git clone and pypi, the notebooks all use `sys.path.append('../../Toolbox')` to access the iRONS functions. Yet package contains a `setup.py` file. Is there a place where installation using `setup.py` is described? I would recommend revising the installation procedure and instructions so that a potential user would be able to use the iRONS functions from another directory without the need to modify the path in a notebook using `sys`. I would recommend using `setup.py` to build the package.

**Comment by AndresPenuela** [comment]
@kbarnhart<https://github.com/kbarnhart> thank you for editing this submission and for these initial comments. Also thanks for the clarifications about how the review process works, it is the first time that I submit a paper on JOSS and I’m a bit lost 😉


  1.  The documentation is inside of each of the functions, first with an introduction/explanation of the function and then short comments on the script lines. However, for the moment, this only applies to these functions:
     *   Res_sys_sim.py
     *   HBV_sim.py
     *   Bias_correction.py
     *   day2week2month.py
     *   cum2inst.py

Are these functions well documented in your opinion?
It is true, that the rest of functions are not well commented and I will add more comments/documentation. This applies to:

  1.  Read_data.py
  2.  Operating_policy_functions.py
  3.  Download_forecast.py

  1.  I will add instructions on how to run the test and I have corrected the Travis link, thanks.
  2.  Initially I thought of including a setup.py but then I decided not to and there is an explanation, which I should have included in the readme file and the manuscript itself. What we aim with this toolbox is that water researchers and water practitioners first can run the Notebooks to see examples of what they can potentially do with the toolbox and with Jupyter Notebooks. Then we would like them to download the Toolbox so they can adapt these functions to their own needs (water systems, research projects,...). In other words, we would like them to open the Python scripts that they are interested in, read them, understand the code and then modify and adapt it to their own needs, for example plugging or linking one specific function of iRONS to their own models. That’s why I thought that doing an installation using setup.py would somehow make these process of finding, opening and modifying the files more difficult. And that having all the functions and Notebooks in a single location would be better in this case. But it is true that in that case, running the scripts would be more difficult. If you see it necessary I can add the option to install it using setup.py.

This last point may be unusual in software engineering? but this toolbox is meant to be easily adaptable without a high level of software development expertise. From people who have good Python skills and have experience in developing water resource models, e.g. software consultants that develop models for water companies, to people who are learning and starting to write their own Python scripts or build their first water resources models, e.g. water resources PhD students.

De: Katy Barnhart<mailto:notifications@github.com>
Enviado: 08 June 2020 19:00
Para: openjournals/joss-reviews<mailto:joss-reviews@noreply.github.com>
CC: Andres Penuela-Fernandez<mailto:andres.penuela-fernandez@bristol.ac.uk>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [openjournals/joss-reviews] [PRE REVIEW]: iRONS: interactive Reservoir Operation Notebooks and Software for water reservoir systems simulation and optimisation (#2231)


@AndresPenuela<https://github.com/AndresPenuela> thank you for submitting iRONS to JOSS. It looks like a valuable contribution to water resources. One of the first things that happens in a JOSS submission is that the handling editor (me) does an initial check of the submission. I have a couple of clarifying questions as part of this stage of the JOSS process.

  1.  I'm having a hard time finding the documentation for the functions provided in iRONS/Toolbox folder. I see these functions being used and described in the notebooks, but expected to find some API documentation. Could you point me in the right direction?
  2.  I see that there are some tests provided in a test folder, but that there are no instructions for how to run the tests. I would recommend that this be added to the readme. In addition, I noticed that your Travis build icon points to builds of a repository that is not iRONS.
  3.  I'm a little confused by the installation instructions. While downloading seems to be supported via git clone and pypi, the notebooks all use sys.path.append('../../Toolbox') to access the iRONS functions. Yet package contains a setup.py file. Is there a place where installation using setup.py is described? I would recommend revising the installation procedure and instructions so that a potential user would be able to use the iRONS functions from another directory without the need to modify the path in a notebook using sys. I would recommend using setup.py to build the package.

**Comment by kbarnhart** [comment]
@AndresPenuela thank you for your patience as I completed my pre-review screening. 

After consulting with the rest of the JOSS editorial board I have come to the decision to reject with encouragement to resubmit. I'll outline my reasoning below, including what I think would need to change in order for a successful re submission. In addition, if you have any questions, concerns, or clarification, please do not hesitate to ask them. 

This decision was made on the basis that iRONS did not meet the following JOSS [submission requirement](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements):

- The software should be feature-complete (no half-baked solutions) and designed for maintainable extension (not one-off modifications).

In addition, the partial documentation makes iRONS not quite meet the requirement: 

- The software should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler).

In more detain, my primary concerns are as follows. I've noted in _italics_ what changes would address these concerns:
1. At present, the core, documented code provided in the toolbox is not sufficient as a significant contribution and it is not clear how the package is designed for maintainable extension. _Documenting the entirety of code provided in the current toolbox directory and providing some direction to users regarding how they would extend from this package (e.g., add a new hydrologic model or management function) would address this issue._ 
2. API documentation should be available through some medium that is not examining the source code itself. _This could be addressed a number of ways.  One option would be to use sphinx to create a readthedocs page from the docstrings._
3. The repository does not follow standard package organization. _This can be addressed by re-organizing the iRONS/iRONS directory to conform to standard python packaging (e.g., [this page describing standard namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/)). I would also recommend using a setup.py installation rather than modifying sys.path in the notebooks._

I note that iRONS has an incredible set of notebooks that highlight the functionality of the code and in the context of real examples. From these examples, it is clear that the content of iRONS enables scientific effort.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
