### ISSUE TITLE
[REVIEW]: ExoNoodle: A Python package spectral time-series of transiting exoplanets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2287]
**Submitting author:** @mmartin-lagarde (<a href="http://orcid.org/0000-0003-0523-7683">Marine Martin-Lagarde</a>)
**Repository:** <a href="https://gitlab.com/mmartin-lagarde/exonoodle-exoplanets" target ="_blank">https://gitlab.com/mmartin-lagarde/exonoodle-exoplanets</a>
**Version:** v0.12.3
**Editor:** @arfon
**Reviewer:** @hpparvi, @kevin218
**Archive:** <a href="https://doi.org/10.5281/zenodo.4478762" target="_blank">10.5281/zenodo.4478762</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/93048d70238c7798c6bf672f155f4abf/status.svg)](https://joss.theoj.org/papers/93048d70238c7798c6bf672f155f4abf)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/93048d70238c7798c6bf672f155f4abf"><img src="https://joss.theoj.org/papers/93048d70238c7798c6bf672f155f4abf/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/93048d70238c7798c6bf672f155f4abf/status.svg)](https://joss.theoj.org/papers/93048d70238c7798c6bf672f155f4abf)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://gitlab.com/mmartin-lagarde/exonoodle-exoplanets/-/tree/master/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@hpparvi & @kevin218, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next six weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/mmartin-lagarde/exonoodle-exoplanets/-/tree/master/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mmartin-lagarde) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://gitlab.com/mmartin-lagarde/exonoodle-exoplanets/-/tree/master/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mmartin-lagarde) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @hpparvi, @kevin218 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2287 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2287 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-2081a6a6226c/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02287/joss.02287/10.21105.joss.02287.pdf)

**Comment by arfon** [comment]
@hpparvi, @kevin218 - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Any questions/concerns please let me know.

**Comment by crawfordsm** [comment]
@mmartin-lagarde Do you have the AAS number for the manuscript?

**Comment by mmartin-lagarde** [comment]
@crawfordsm Sure :
• AJ AAS23898 is the original submission
• It was resubmitted earlier this week with : AAS23898R1

**Comment by kevin218** [comment]
Here is my feedback on ExoNoodle:
[Comments.txt](https://github.com/openjournals/joss-reviews/files/4866027/Comments.txt)

I'm happy to iterate on this.  Let me know if you have any questions.

**Comment by arfon** [comment]
Thanks @kevin218!

@mmartin-lagarde - can you let us know here when you've incorporated @kevin218's feedback?

Also, @hpparvi - how are you getting along with your review?

**Comment by mmartin-lagarde** [comment]
Thank you @kevin218 for your constructive and detailed review.

@arfon, I'm currently writing my thesis, and it's taking all my time. I'm afraid I won't be able to incorporate the comments before the end of August. I hope it's not too late for you. Thank you for following on this.

**Comment by arfon** [comment]
:wave: @hpparvi - just checking in on when you think you might be able to complete your review by?

**Comment by arfon** [comment]
Update: I emailed @hpparvi this morning to see when they might be able to complete their review by.

**Comment by arfon** [comment]
Sent a final reminder to @hpparvi this morning. If we don't hear back from them we'll need to find a second reviewer.

@mmartin-lagarde - how are you getting along incorporating @kevin218's feedback?

**Comment by mmartin-lagarde** [comment]
Dear @arfon,
All the comments concerning the code and the user manual are addressed as of now, and available in a new branch 'review_JOSS' : https://gitlab.com/mmartin-lagarde/exonoodle-exoplanets/-/tree/review_JOSS
I am currently making the additions to the paper itself.
Sorry for the delay.

**Comment by hpparvi** [comment]
Dear @arfon, @mmartin-lagarde,

I'll finish the review today using the review_JOSS branch. My apologies for the delay.

Best,
Hannu

**Comment by hpparvi** [comment]
Dear @mmartin-lagarde and @arfon,

Here is my review, sorry for the delay.

**Documentation**
The documentation is very good content-wise. However, the language (transient -> transiting, etc.) and clarity of the text could be improved (a grammar checker and a native English friend/colleague can be useful here). The abstract in the README reads well already, but it would be good if the user manual can be revised to the same level. However, the documentation is understandable to someone in the field, so I would not consider this a show-stopper.

I've created one issue about the documentation that I believe needs to be fixed before the package can be accepted to JOSS, the lack of community guidelines. I believe this should be a quick thing to fix, so it will hopefully not delay the acceptance much.

**Functionality**
The package works as documented without any major issues. However, adding the `run_exonoodle.py` as an installable script would be better than having the script in the project root directory. Again, this is more of a suggestion rather than a request.

**The JOSS manuscript**
As with the documentation, the JOSS manuscript is technically good and covers everything that is needed. However, the language should be improved before it can be accepted. I've created a second issue about the manuscript language, and will be happy to recommend publication after the issue is solved.

**Summary**
The package fulfils its stated goals and functions as promised. The language is the only major issue in the documentation and the JOSS manuscript, and I will be happy to recommend publication after it has been improved.

Best,
Hannu

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02287/joss.02287/10.21105.joss.02287.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02287/joss.02287/10.21105.joss.02287.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
:wave: @mmartin-lagarde - how are you getting on with your updates based on the reviewer feedback?

**Comment by mmartin-lagarde** [comment]
Dear @arfon, I'm sorry it took so much time. It's almost ready. I'm just missing a few complement to the user manual to address the changes asked by the referees.
The branch review_JOSS has been updated, and all is working. I will share you everything Friday at the latest.

**Comment by mmartin-lagarde** [comment]
Dear @hpparvi and @kevin218,

Thank you for both of your reports. Sorry for the late feedback. The changes to the code and its documentation are still un the branch review_JOSS (that will be merged at the end of the review process). Below are the answers to the points you raised in your reviews :

**JOSS Manuscript**
• @kevin218 `As currently written, the title doesn't sufficiently convey the purpose of the package.  Consider changing to, "ExoNoodle: A Python package that simulates spectroscopic time-series data for transiting exoplanets`
   > We propose "Exonoodle: Synthetic time-series spectra Python generator for transiting exoplanets"

• @kevin218 `Outside of the summary, the rest of the paper appears to be missing.  At minimum, I would like to see some examples (with figures) that demonstrate what the tool can do and how it compares to actual results.  The paper also lacks a description of how this software compares to other packages (such as AwesimSOSS; https://github.com/spacetelescope/awesimsoss).  I would recommend looking at AwesimSOSS in more detail to see what type of figures they produce in their README.rst and example notebook.`
  @hpparvi `As with the documentation, the JOSS manuscript is technically good and covers everything that is needed. However, the language should be improved before it can be accepted. I've created a second issue about the manuscript language, and will be happy to recommend publication after the issue is solved.`
   > Examples are being presented in the manual, with a description of the output folder, it did not seem required to add it in the manuscript. However, we added an order of magnitude of the computing time. We had an additional language check and this should be improved. Note that the code is compared in its usage in the companion paper (DOI : 10.3847/1538-3881/abac09)

• @kevin218 `Why is the code called ExoNoodle?`
   > We didn't feel the need for yet another acronym. In the core of the code, the computation is conducted at a specific instant in time. Hence, the computation is a serie of 'instantaneous' spectrum, like the instant noodles. We did not think this description belonged in the paper. But if the reviewer thinks it's appropriate, it can be added.

**User Manual and Documentation**
• @kevin218 `I suggest having a native-English speaker with expertise in transiting exoplanets review the documentation for spelling, grammar, and correct usage of terminology.  For example, "transient exoplanetary system" should be "transiting exoplanet system" and "WASP-43a" should be "WASP-43A", or simply "WASP-43".  There are numerous typos throughout.`
   @hpparvi `However, the language (transient -> transiting, etc.) and clarity of the text could be improved (a grammar checker and a native English friend/colleague can be useful here). The abstract in the README reads well already, but it would be good if the user manual can be revised to the same level. However, the documentation is understandable to someone in the field, so I would not consider this a show-stopper.`
   > The language of the documentation has been checked like the manuscript, and improved.

• @kevin218 `"we create a spectrum of an exoplanet system at a given time" should probably be "at a given orbital phase". What do you mean by "Implies the transit shade"?`
   @kevin218 `Missing TBI: planets on eccentric orbits.`
   @kevin218 `A better default albedo is zero for hot Jupiter exoplanets (not 0.538).`
   @kevin218 `TBD Instead of using "time" with default 0 at mid-transit, I suggest using "phase" in recognition that we're actually talking about orbital phase. I would expect "t_min" and "t_max" to be in units of orbital phase (e.g., 0 to 1, or possibly -1 to +1).  Radians is not a common unit in exoplanets and it certainly isn't a unit of time.`
   > Corrected

• @kevin218 `Effects Ignored: "Doppler schifts due do planets radial velocity and Rossiter-McLaughlin effect;" should be below sensitivity [BS]`
   > Concerning Doppler schifts, while below sensitivity for JWST MIRI, we are not sure that's still true for ground based observations. Concerning Rossiter-McLaughlin effect, that depends on the system characteristics, if above the ppm level, that's relevant for a MIRI observation for instance.

• @kevin218 `Default planet phase_shift_unit should be degrees (a standard unit in exoplanets).`
   > It was the case but was wrongly documented in the user manual

• @kevin218 `I don't understand what is the "time_sampling" parameter.  Please use a more descriptive label, like integration time, or provide a more detailed description.`
   > We added more details in the input section

• @kevin218 `As an option, the user should be able to specify either "impact_parameter" or "a/Rs" since the latter tends to be more common than the former.`
   > Impact factor has been removed since it's a duplicate from inclination. As it would require further developpement, we advise against offering the option to the user to give inclination, or impact factor, or a/Rs

• @kevin218 `Output folder should include both date and time to help users keep track of their runs.`
   > This is done by a numbering system, the last being the highest number. Some simulations can take less than a second and it would potentially crash the code depending on the precision of the time written in the folder name.

• @kevin218 `It isn't obvious that the output .dat file is providing the system (star + planet) flux.  I initially thought it was just the planet flux.`
    > In the description of the code (purpose) and the output description was added that the spectrum correspond to the whole system.

• @hpparvi `I've created one issue about the documentation that I believe needs to be fixed before the package can be accepted to JOSS, the lack of community guidelines. I believe this should be a quick thing to fix, so it will hopefully not delay the acceptance much.`
   > We added a contributing.md

**Scripts**
• @kevin218 `I get an error when running exonoodle_lightcurve_plot.py: could not convert string to float: 'xkcd:light blue'.  I suggest changing to a standard color that doesn't require additional packages or adding this package as a requirement.`
   > Corrected

• @kevin218 `I could not test the other scripts since I do not have MIRISim installed`
   > As these were only for MIRISim users and confusing for others, we removed it from the directory

• @hpparvi `The package works as documented without any major issues. However, adding the run_exonoodle.py as an installable script would be better than having the script in the project root directory. Again, this is more of a suggestion rather than a request.`
   > Actually, the run_exonoodle.py script is more an example for the user to shape to their needs and eventually used in a broader program. We moved it in the scripts folder, and added an 'exonoodle' installable script.


**General Feedback**
• @kevin218 `Is ExoNoodle intended to be a standalone package or is it meant to be run with MIRISim to achieve the final results?  Given that the outputs feed directly into MIRISim, ExoNoodle feels incomplete because the user manual doesn't provide enough information on how to generate the final simulated data (via MIRISim).  I would like to see a brief description of how ExoNoodle ties into MIRISim and a Jupyter Notebook taking people through the process of generating the intermediate results with ExoNoodle, plotting some results, and then generating the final simulated data with MIRISim.  The scripts are there, so it shouldn't take much effort to modify them into core modules and call them with a Jupyter Notebook.  MIRISim should be a requirement for ExoNoodle.`
   > It is not. ExoNoodle is an independent tool, that can work at any wavelength and resolution. Although the use-case of our team is to interface it with MIRISim, this is not a requirement. For example, this JOSS publication is a companion paper to another study that does not use any instrument simulator. (DOI : 10.3847/1538-3881/abac09)
The available scripts were examples and have been removed from the repository (they are not functions to be called) To avoid confusion, there is no longer mention of MIRISim in the ReadMe.

• @hpparvi `The package fulfils its stated goals and functions as promised. The language is the only major issue in the documentation and the JOSS manuscript, and I will be happy to recommend publication after it has been improved.`
   > The language should have been improved now.


We would like to thank you again for your feedback, and we hope we addressed your concerns.
Best, Marine

**Comment by arfon** [comment]
Thanks for the update @mmartin-lagarde! 

@hpparvi, @kevin218 - please come and take a quick look again and see if you're ready to sign off on this submission.

**Comment by kevin218** [comment]
@arfon @mmartin-lagarde 

After addressing the minor comments below, I'd be happy to sign off on this submission.

Paper
-----
In its current form, I suggest removing "Python" from the title.  Otherwise, it sounds like a Python generator, which it is not. So... "ExoNoodle: Synthetic time-series spectral generator for transiting exoplanets"

Planets "orbit" around a star, not "rotate".

Thanks for the info on why it's called ExoNoodle.  It might be worth adding to the README file or User Manual, but definitely not the paper.  I've had numerous people from the ERS team ask me what it means.


User Manual
-----------
The text still reads "transient exoplanetary system" when it should be "transiting exoplanet system".


Testing
-------
All of configuration.ini optional arguments appear to produce the expected results based on the provided source files.  Well done!

**Comment by kevin218** [comment]
One more thought... the MIRISim scripts were quite helpful and I would encourage you to keep them in the GitHub repo.

**Comment by arfon** [comment]
:wave: @mmartin-lagarde - have you managed to address the comments/feedback from @kevin218's most recent feedback?

**Comment by mmartin-lagarde** [comment]
Hi @kevin218, Thank you for your feedback. 
@arfon I'm doing this today or tomorrow, thank you

**Comment by mmartin-lagarde** [comment]
Dear @kevin218,

I addressed the last comments, thank you again.
However, your comment on `Planets "orbit" around a star, not "rotate".` was probably referring to the paper in the master branch (as the mistake is real there), but I could not find it in the review_JOSS branch. Am I missing something?

I reintroduced the MIRISim scripts in the repository.

**Comment by hpparvi** [comment]
Dear @mmartin-lagarde, @arfon,

I'm now happy to sign off the submission. The only thing left I could find is the issue with "transient exoplanetary system" vs "transiting exoplanetary system" (both in the docs and the readme), but this is very minor.

Great work, @mmartin-lagarde, and good luck!

**Comment by kevin218** [comment]
@mmartin-lagarde You're probably right about the orbit/rotate comment.  I can't find it either in the new branch.

**Comment by arfon** [comment]
@kevin218 - given that I *think* you're approving of this submission moving forward to acceptance at this point, would you mind updating your review checklist above to reflect this?

Many thanks!

**Comment by mmartin-lagarde** [comment]
@kevin218 @hpparvi thank you both for your feedbacks.
The was a 'transient' remaining in the readme, that I just corrected. For the documentation however, it was already addressed.

But the link in the README takes you to the doc of the 'master' branch which contains none of the corrections made in the review process here. Make sure to check this one (in the 'review_JOSS' branch  : https://gitlab.com/mmartin-lagarde/exonoodle-exoplanets/-/blob/review_JOSS/exonoodle/docs/ExoNoodle_UserManual.pdf)

I will merge the two branches when the submission is definitely accepted and all the links should work properly then.
Sorry for the inconvenience.

**Comment by kevin218** [comment]
@arfon Checklist updated.  Paper approved.

**Comment by arfon** [comment]
> I will merge the two branches when the submission is definitely accepted and all the links should work properly then.
> Sorry for the inconvenience.

@mmartin-lagarde - please go ahead and merge these branches together now as it looks like both of the reviewers have signed off.

**Comment by mmartin-lagarde** [comment]
@arfon I just merged the branches

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02287/joss.02287/10.21105.joss.02287.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02287/joss.02287/10.21105.joss.02287.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@mmartin-lagarde - this is looking pretty good and I think we're ready to proceed to accept and publish here. One quick question: Has the paper in the AAS journal been accepted yet? If so, we should include the DOI in the `paper.md` file now to cross-link the papers. If not, we can either 1) Hold this paper as `paused` or 2) Publish now and update it once you have the AAS DOI.

Do you have a preference?

**Comment by mmartin-lagarde** [comment]
@arfon Yes, it has been accepted, they went forward with the publication. https://ui.adsabs.harvard.edu/abs/2020AJ....160..197M/abstract
I just included the DOI in the paper and checked that bibliography.

**Comment by arfon** [comment]
@mmartin-lagarde - At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by mmartin-lagarde** [comment]
@arfon I just uploaded the release under: 10.5281/zenodo.4478762

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.4478762 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4478762" target="_blank">10.5281/zenodo.4478762</a> is the archive.

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3847/1538-3881/abac09 is OK
- 10.1086/345520 is OK
- 10.1086/683602  is OK
- 10.1051/0004-6361/201322068 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2064

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2064, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1355424278783684610) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2065
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02287](https://doi.org/10.21105/joss.02287)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@hpparvi, @kevin218 - many thanks for your reviews here! JOSS relies upon the volunteer efforts of folks like yourselves, and we simply wouldn't be able to do this without you ✨ 

@mmartin-lagarde - your paper is now accepted and published in JOSS :zap::rocket::boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02287/status.svg)](https://doi.org/10.21105/joss.02287)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02287">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02287/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02287/status.svg
   :target: https://doi.org/10.21105/joss.02287
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02287/status.svg)](https://doi.org/10.21105/joss.02287)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
