### ISSUE TITLE
[PRE REVIEW]: A comprehensive Fortran error handling framework

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2303]
**Submitting author:** @samharrison7 (<a href="http://orcid.org/0000-0001-8491-4720">Sam Harrison</a>)
**Repository:** <a href="https://github.com/samharrison7/fortran-error-handler/" target ="_blank">https://github.com/samharrison7/fortran-error-handler/</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @samharrison7. **Currently, there isn't an JOSS editor assigned** to your paper.

@samharrison7 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.05 s (499.5 files/s, 119833.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Fortran 90                      14            494            705           3357
Markdown                         7            282              0            822
JSON                             1              0              0             51
TeX                              1              1              0             25
CMake                            1              5              0             16
-------------------------------------------------------------------------------
SUM:                            24            782            705           4271
-------------------------------------------------------------------------------


Statistical information for the repository '2303' was gathered on 2020/06/07.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1145/2338786.2338787 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02303/joss.02303/10.21105.joss.02303.pdf)

**Comment by kyleniemeyer** [comment]
👋 @samharrison7 - Thanks for your submission to JOSS. As described in our blog post announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS we've had > 60 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

Also: based on my initial review of your article, it's a little unclear how this falls inside our scope as "research software". One of our requirements is:
> The software should have an obvious research application.

Can you explain briefly how this falls inside this scope—for example, would it be cited by researchers, and if so, who? Thanks!

**Comment by samharrison7** [comment]
Hi @kyleniemeyer, thanks for the question! To me, this classes as "research software" because it helps in the creation of software for research purposes, by giving researchers a pre-packaged error handler to use in their software. To that end, its obvious research application is to help the development of any research software using Fortran code, e.g. climate sciences, hydrology, ocean modelling, etc. I like to think it would get cited in other research software papers, as I hope it will provide a significant aid to their software development.

**Comment by danielskatz** [comment]
👋 @samharrison7 - The editors have decided that this is out of scope for JOSS, as not "research software" but more infrastructure software.  This says nothing about its value, just that JOSS is not the right place to publish it.  We are therefore going to reject it.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
