### ISSUE TITLE
[PRE REVIEW]: pyBEMT: An implementation of the Blade Element Momentum Theory in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2311]
**Submitting author:** @kegiljarhus (<a href="http://orcid.org/0000-0002-4144-0454">Knut Erik Teigen Giljarhus</a>)
**Repository:** <a href="https://github.com/kegiljarhus/pyBEMT" target ="_blank">https://github.com/kegiljarhus/pyBEMT</a>
**Version:** v0.1.0
**Editor:** @sjpfenninger
**Reviewers:** @rafmudaf, @antviro
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kegiljarhus. **Currently, there isn't an JOSS editor assigned** to your paper.

@kegiljarhus if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.05 s (571.8 files/s, 36098.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          16            287            322            608
reStructuredText                 6            157             60            249
INI                              5             19              0             86
Markdown                         1              7              0             52
TeX                              1              8              0             47
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            31            490            390           1077
-------------------------------------------------------------------------------


Statistical information for the repository '2311' was gathered on 2020/06/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Knut Erik Giljarhus             20          1480            263          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Knut Erik Giljarhus        1217           82.2          0.1               11.18
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.2514/6.2013-4220 is OK

MISSING DOIs

- https://doi.org/10.2172/15014831 may be missing for title: AeroDyn theory manual
- https://doi.org/10.2172/5428795 may be missing for title: Free wake analysis of a wind turbine aerodynamics. Wind energy conversion. ASRL-TR-184-14

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02311/joss.02311/10.21105.joss.02311.pdf)

**Comment by arfon** [comment]
@whedon invite @sjpfenninger as editor

:wave: @sjpfenninger - I realize you're only somewhat able to edit right now but this looks like it's very much in your area. I'll list this as `waitlisted` but if you have the bandwidth, feel free to grab it.

**Comment by whedon** [comment]
@sjpfenninger has been invited to edit this submission.

**Comment by arfon** [comment]
:wave: @kegiljarhus - thanks for your submission to JOSS. As described in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss) announcing the reopening of JOSS, we're currently working in a "reduced service mode", limiting the number of papers assigned to any individual editor.

Since reopening JOSS earlier a week or so ago we've had > 70 papers submitted and as such, yours has been put in our backlog that we will be working through over the coming weeks and months.

Thanks in advance for your patience!

**Comment by Kevin-Mattheus-Moerman** [comment]
@kegiljarhus I have some brief comments on your paper. While we are looking for an editor to handle this submission I recommend that you look at the following. 
1. Work on fixing references which do no render properly in the paper. Also add DOI's for all references that have them.  
2. Consider citing papers that actually use this theory in design, to clarify importance of this work to research. 
3. Check for typos (e.g. moomentum)
4. Consider, if possible/applicable, adding one or more graphical summary figures e.g. graphs or blade designs, to illustrate the functionality/application of this work.  
5. This work may be flagged as ["Minor ‘utility’ package"](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). It would help to clearly outline the novel/signigicant functionality offered by this work. How is it different/better than other packages, and how relevant is it to scientific research? Clearly sketch a picture of why would use and likely cite (because of the scientific significance) this work for their research.

**Comment by Kevin-Mattheus-Moerman** [comment]
@sjpfenninger can you handle this submission? 
Alternatively, @kyleniemeyer you are handling quite a few submissions already but is this something you may be interested in handling? 
Thanks.

**Comment by kegiljarhus** [comment]
Thank you for the comments, @Kevin-Mattheus-Moerman, I will make some changes to the paper to better highlight the relevance of the package. Regarding the graphical summary, do you think adding the [two validation examples](https://pybemt.readthedocs.io/en/latest/validation.html) from the documentation would be appropriate, or were you more thinking about design examples?

**Comment by arfon** [comment]
@whedon assign @sjpfenninger as editor

**Comment by whedon** [comment]
OK, the editor is @sjpfenninger

**Comment by arfon** [comment]
@kegiljarhus - I think @sjpfenninger will be handling this submission but he's out on holiday for a couple of weeks and will attend to this when he returns.

**Comment by sjpfenninger** [comment]
@kegiljarhus I'm looking for reviewers offline, meanwhile, can you ensure that you provide an updated Statement of Need that clarifies the novel/significant functionality, and provide specific examples of how the software is used for research?

**Comment by kegiljarhus** [comment]
Thank you for the update @sjpfenninger . After the feedback from @Kevin-Mattheus-Moerman, I have updated the paper with some more references to use of BEMT, and also provided some examples of the use of the package. I hope this is satisfactory.

**Comment by sjpfenninger** [comment]
Thanks @kegiljarhus ! What I'm still missing is a clearer differentiation between pyBEMT and other packages. I think this may just need some rewording. The paper implies that pyBEMT is the only software with a clean standalone implementation of BEMT, and possibly also the only Python package? I.e. -- why would somebody use pyBEMT rather than any of the numerous other packages? If you have more specific references to the research currently using pyBEMT, that would also be good to include to highlight the need for pyBEMT specifically as opposed to BEMT generally. Meanwhile bear with me as I look for reviewers.

**Comment by kegiljarhus** [comment]
Thank you for the elaboration, I see what you mean. The key aspect is the combination of both propellers and turbines in one package, which is nice especially for educational purposes. With respect to propellers, it is also the only package I am aware of with a model for coaxial rotors. I will reword the paper to emphasize these points. 

I am currently writing other papers where the package is used, so it's a bit of a chicken and egg situation as I would like to be able to cite the software used in those papers.

**Comment by sjpfenninger** [comment]
> Thank you for the elaboration, I see what you mean. The key aspect is the combination of both propellers and turbines in one package, which is nice especially for educational purposes. With respect to propellers, it is also the only package I am aware of with a model for coaxial rotors. I will reword the paper to emphasize these points.

Great, if you can do that, that's sufficient then!

**Comment by sjpfenninger** [comment]
@whedon add @rafmudaf as reviewer

**Comment by whedon** [comment]
OK, @rafmudaf is now a reviewer

**Comment by sjpfenninger** [comment]
@whedon add @antviro as reviewer

**Comment by whedon** [comment]
OK, @antviro is now a reviewer

**Comment by sjpfenninger** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2480.

**Comment by sjpfenninger** [comment]
@rafmudaf @antviro thanks for agreeing to review, and we understand that things may take a bit longer given the current circumstances. Let's head over to #2480 for the actual review!
