### ISSUE TITLE
[PRE REVIEW]: OnPoint: A package for online experiments in motor control and motor learning

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2415]
**Submitting author:** @xiaotsay2015 (<a href="http://orcid.org/0000-0002-3992-9023">Jonathan Sanching Tsay</a>)
**Repository:** <a href="https://github.com/alan-s-lee/OnPoint" target ="_blank">https://github.com/alan-s-lee/OnPoint</a>
**Version:** v1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @xiaotsay2015. **Currently, there isn't an JOSS editor assigned** to your paper.

@xiaotsay2015 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by xiaotsay2015** [comment]
Suggested reviewers:

1) Andytwoods
2) felixhenninger
3) Mullins
4) johnsamuelwrite
5) camillescott
6) ejolly
7) xzyaoi

On July 1, 2020 at 7:12:13 AM, whedon (notifications@github.com) wrote:

*Submitting author:* @xiaotsay2015 <https://github.com/xiaotsay2015> (Jonathan
Sanching Tsay <http://orcid.org/0000-0002-3992-9023>)
*Repository:* <https://github.com/alan-s-lee/OnPoint>
https://github.com/alan-s-lee/OnPoint
*Version:* v1.0
*Editor:* Pending
*Reviewer:* Pending
*Managing EiC:* Daniel S. Katz

*⚠️ JOSS reduced service mode ⚠️*

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating
in a "reduced service mode". You can read more about what that means in our
blog post <https://blog.joss.theoj.org/2020/05/reopening-joss>.

*Author instructions*

Thanks for submitting your paper to JOSS @xiaotsay2015
<https://github.com/xiaotsay2015>. *Currently, there isn't an JOSS editor
assigned* to your paper.

@xiaotsay2015 <https://github.com/xiaotsay2015> if you have any suggestions
for potential reviewers then please mention them here in this thread
(without tagging them with an @). In addition, this list of people
<https://bit.ly/joss-reviewers> have already agreed to review for JOSS and
may be suitable for this submission (please start at the bottom of the
list).

*Editor instructions*

The JOSS submission bot @whedon <https://github.com/whedon> is here to help
you find and assign reviewers and start the main review. To find out what
@whedon <https://github.com/whedon> can do for you type:

@whedon commands


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/2415>, or unsubscribe

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.10 s (242.0 files/s, 54202.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                             7             36              0           3182
JavaScript                       8            118            217            713
HTML                             1             33            107            252
Python                           3             44             75            248
SVG                              1              0              0            229
CSS                              2             30             13            125
Markdown                         2             37              0             80
TeX                              1              5              0             55
-------------------------------------------------------------------------------
SUM:                            25            303            412           4884
-------------------------------------------------------------------------------


Statistical information for the repository '2415' was gathered on 2020/07/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Alan Lee                         7          1629            214          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Alan Lee                   1415           86.9          0.2               19.58
```

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02415/joss.02415/10.21105.joss.02415.pdf)

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1038/118074a0 may be missing for title: Helmholtz’s treatise on physiological optics
- https://doi.org/10.1523/jneurosci.20-23-08916.2000 may be missing for title: Learning of visuomotor transformations for vectorial planning of reaching trajectories
- https://doi.org/10.1146/annurev-neuro-080317-062245 may be missing for title: Closing the loop: from motor neuroscience to neurorehabilitation
- https://doi.org/10.1146/annurev-neuro-060909-153135 may be missing for title: Error correction, sensory prediction, and adaptation in motor control

INVALID DOIs

- None
```

**Comment by xiaotsay2015** [comment]
@whedon <https://github.com/whedon> check references


On July 1, 2020 at 7:46:58 AM, whedon (notifications@github.com) wrote:

Reference check summary:



OK DOIs



- None



MISSING DOIs



- https://doi.org/10.1038/118074a0 may be missing for title:
Helmholtz’s treatise on physiological optics

- https://doi.org/10.1523/jneurosci.20-23-08916.2000 may be missing
for title: Learning of visuomotor transformations for vectorial
planning of reaching trajectories

- https://doi.org/10.1146/annurev-neuro-080317-062245 may be missing
for title: Closing the loop: from motor neuroscience to
neurorehabilitation

- https://doi.org/10.1146/annurev-neuro-060909-153135 may be missing
for title: Error correction, sensory prediction, and adaptation in
motor control



INVALID DOIs



- None


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/2415#issuecomment-652463161>,
or unsubscribe

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by xiaotsay2015** [comment]
Hi Daniel,

I have updated the paper’s bibliographies. They all have a DOI and URL now.
Let me know if there are any next steps.

Thanks again for your time,
JT


On July 1, 2020 at 7:46:03 AM, Daniel S. Katz (notifications@github.com)
wrote:

@whedon <https://github.com/whedon> check references

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/2415#issuecomment-652462589>,
or unsubscribe

**Comment by danielskatz** [comment]
@xiaotsay2015  - Can you explain how this is research software?  See https://joss.readthedocs.io/en/latest/submitting.html, specifically
> The software should have an **obvious** research application.

What is the *research* application here?  What kinds of papers would you expect to including citations to this paper as part of their research?

**Comment by xiaotsay2015** [comment]
Daniel,

Thanks for your question. This package  “supports the functioning of
research instruments or the *execution of research experiments*”. In the
past, if you wanted to do a prism adaptation experiment, you would have to
bring a participant in the lab. But because of the global pandemic,
in-person experiments are halted. Here we provide a solution to designing
your prism adaptation experiment online. This package makes it easy
(provides a template) for motor learning researchers to tailor it to their
own experiment paradigm. Here is an example of an experiment
<https://multiclamp-p.web.app/>, built using this package. I’ve been
getting a lot of requests from the motor learning community to share this
package, so I thought Journal of Open Software would be an appropriate
venue. Let me know if I did not fully answer your question.

JT


On July 1, 2020 at 8:27:10 AM, Daniel S. Katz (notifications@github.com)
wrote:

@xiaotsay2015 <https://github.com/xiaotsay2015> - Can you explain how this
is research software? See
https://joss.readthedocs.io/en/latest/submitting.html, specifically

The software should have an *obvious* research application.

What is the *research* application here? What kinds of papers would you
expect to including citations to this paper as part of their research?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/2415#issuecomment-652486380>,
or unsubscribe

**Comment by xiaotsay2015** [comment]
** Journal of Open Source Software.

Thanks again for your consideration, Daniel.
JT


On July 1, 2020 at 8:34:22 AM, Jonathan Tsay (xiaotsay2015@gmail.com) wrote:

Daniel,

Thanks for your question. This package  “supports the functioning of
research instruments or the *execution of research experiments*”. In the
past, if you wanted to do a prism adaptation experiment, you would have to
bring a participant in the lab. But because of the global pandemic,
in-person experiments are halted. Here we provide a solution to designing
your prism adaptation experiment online. This package makes it easy
(provides a template) for motor learning researchers to tailor it to their
own experiment paradigm. Here is an example of an experiment
<https://multiclamp-p.web.app/>, built using this package. I’ve been
getting a lot of requests from the motor learning community to share this
package, so I thought Journal of Open Software would be an appropriate
venue. Let me know if I did not fully answer your question.

JT


On July 1, 2020 at 8:27:10 AM, Daniel S. Katz (notifications@github.com)
wrote:

@xiaotsay2015 <https://github.com/xiaotsay2015> - Can you explain how this
is research software? See
https://joss.readthedocs.io/en/latest/submitting.html, specifically

The software should have an *obvious* research application.

What is the *research* application here? What kinds of papers would you
expect to including citations to this paper as part of their research?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/2415#issuecomment-652486380>,
or unsubscribe

**Comment by xiaotsay2015** [comment]
Daniel,

As for “What kinds of papers would you expect to including citations to
this paper as part of their research?”

I see studies who will use our tool to create their experiments online
citing our paper. For example, Gorilla is a website where psychologists can
design their own experiments, using existing templates. People who use
Gorilla to design their own experiments will cite Gorilla as well as the
original author who created the template: https://gorilla.sc/publications.

However, their platform does not have a suitable motor learning study,
which is why we created this package. I anticipate that our package will
one day be integrated with Gorilla as well.

Thanks,
JT


On July 1, 2020 at 8:35:29 AM, Jonathan Tsay (xiaotsay2015@gmail.com) wrote:

** Journal of Open Source Software.

Thanks again for your consideration, Daniel.
JT


On July 1, 2020 at 8:34:22 AM, Jonathan Tsay (xiaotsay2015@gmail.com) wrote:

Daniel,

Thanks for your question. This package  “supports the functioning of
research instruments or the *execution of research experiments*”. In the
past, if you wanted to do a prism adaptation experiment, you would have to
bring a participant in the lab. But because of the global pandemic,
in-person experiments are halted. Here we provide a solution to designing
your prism adaptation experiment online. This package makes it easy
(provides a template) for motor learning researchers to tailor it to their
own experiment paradigm. Here is an example of an experiment
<https://multiclamp-p.web.app/>, built using this package. I’ve been
getting a lot of requests from the motor learning community to share this
package, so I thought Journal of Open Software would be an appropriate
venue. Let me know if I did not fully answer your question.

JT


On July 1, 2020 at 8:27:10 AM, Daniel S. Katz (notifications@github.com)
wrote:

@xiaotsay2015 <https://github.com/xiaotsay2015> - Can you explain how this
is research software? See
https://joss.readthedocs.io/en/latest/submitting.html, specifically

The software should have an *obvious* research application.

What is the *research* application here? What kinds of papers would you
expect to including citations to this paper as part of their research?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/2415#issuecomment-652486380>,
or unsubscribe

**Comment by xiaotsay2015** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1037/13536-000 is OK
- 10.1523/JNEUROSCI.20-23-08916.2000 is OK
- 10.1002/cphy.c170043 is OK
- 10.1146/annurev-neuro-080317-062245 is OK
- 10.1152/jn.00266.2007 is OK

MISSING DOIs

- None

INVALID DOIs

- annurev-neuro-060909-153135 is INVALID
```

**Comment by xiaotsay2015** [comment]
@whedon check references

**Comment by xiaotsay2015** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1037/13536-000 is OK
- 10.1523/JNEUROSCI.20-23-08916.2000 is OK
- 10.1002/cphy.c170043 is OK
- 10.1146/annurev-neuro-080317-062245 is OK
- 10.1146/annurev-neuro-060909-153135 is OK
- 10.1152/jn.00266.2007 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02415/joss.02415/10.21105.joss.02415.pdf)

**Comment by arfon** [comment]
@whedon query scope

**Comment by danielskatz** [comment]
@xiaotsay2015 - The JOSS editors have determined that this submission is out of scope as a minor utility due to its small size. If you want the software to be cited, you might consider getting a DOI for it via zenodo.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
