### ISSUE TITLE
[REVIEW]: Pandarus: GIS toolkit for regionalized life cycle assessment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#244]
**Submitting author:** @cmutel (<a href="http://orcid.org/0000-0002-7898-9862">Chris Mutel</a>)
**Repository:** <a href="https://github.com/cmutel/pandarus" target ="_blank">https://github.com/cmutel/pandarus</a>
**Version:** 1.0.1
**Editor:** @arfon
**Reviewer:** @hugoledoux
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.571547" target="_blank">10.5281/zenodo.571547</a>

## Status

[![status](http://joss.theoj.org/papers/99cd637f2eac0ffaba0be09fd3f0d75c/status.svg)](http://joss.theoj.org/papers/99cd637f2eac0ffaba0be09fd3f0d75c)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/99cd637f2eac0ffaba0be09fd3f0d75c"><img src="http://joss.theoj.org/papers/99cd637f2eac0ffaba0be09fd3f0d75c/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/99cd637f2eac0ffaba0be09fd3f0d75c/status.svg)](http://joss.theoj.org/papers/99cd637f2eac0ffaba0be09fd3f0d75c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/cmutel/pandarus" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cmutel/pandarus">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.0.1)? 
- [x] **Authorship:** Has the submitting author (@cmutel) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @hugoledoux it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
Hi @hugoledoux - please work your way through the review checklist above to complete your review (you should be able to check items off the list as you verify them). Please note we have reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines for you but if you have any questions for me or the author please ask here.

**Comment by cmutel** [comment]
Software is uploaded to [Zenodo](https://zenodo.org/record/556151) with the DOI 10.5281/zenodo.556151.

**Comment by cmutel** [comment]
@hugoledoux Any chance you could give me a timeframe on when to expect something? I know people are busy, just asking so I can manage my expectations :)

**Comment by hugoledoux** [comment]
This week I can do this.

**Comment by hugoledoux** [comment]
I'm one of those who still use Python 2.7... but it can't be installed as Python >3.0 is required, right?

**Comment by hugoledoux** [comment]
In general nice and well-documented library, and I'm sure it's really useful for people that are non-expert at GIS.

I have the following remarks below. I tried it a bit but to continue I'd really like to have one full example, as explained below. I know I could figure things out, but as a user, I like to just see quickly what it does, and not having to build my own script from scratch.

## version

The version is not 1.0.1 but 1.0.2. I assume this ain't a problem.

# installation

Only Python >3.0 is supported, which is not mentioned and the setup.py (or used with pip) doesn't complain, but an error is thrown because the open() function of Python 2.7 for instance doesn't have the `encoding` option.

Installing with conda works fine, if Python 3.6 is chosen.

## Software paper

I'd say you 'overlay' 2 GIS datasets, and not only 'match'. This is in my opinion the more technical term used in GIS.

"Calculate the areas left out (present in one input file but not the other) from the aforementioned intersections calculation"
--> a Boolean difference is thus performed could also be stated

## Example usage

As a GIS person, I'd like to have one full example (a full python script) that reads a shapefile (or gpkg or geojson), does the intersection with another file (eg the one in your first example "Intersecting two vector datasets") and outputs to a another shapefile. I looked but couldn't find it, only bits of code (which are useful, don't get me wrong!) and the tests. The test datasets are already included, so why not have 2-3 full examples?

**Comment by cmutel** [comment]
@hugoledoux Updated the readme and docs:

- Updated language (please let me know if there are other suggestions!)
- Made usage example easier to find
- Added notes on Python 3 requirement

Please feel free to make technical criticisms (esp. using the Mollweide as a default projection) as well!

**Comment by hugoledoux** [comment]
@cmutel 

## Example usage

I had seen that `ipynb` file, but when I opened it I had no idea what it was. I am a casual user of Python, and do not use advanced features... Am I the "average user" for your library? I wouldn't know, but I think having an example directly runnable with python would surely help.

I tried converting it to a `py` file, but ran into issues while running... macOS complained about Python not being installed as a framework. 
I also tried the Jupyter notebook thing but I can't run it without errors, and I don't know what I am doing wrong here. The package pandarus is not recognised, while I started jupyter from the conda env... Any idea what I might be overlooking?


## Projection and CRS

    Because Pandarus was designed for global data sets, the Mollweide projection is used as the default equal-area projection for calculating areas (in square meters). Although no projection is perfect, the Mollweide has been found to be a reasonable compromise

--> I agree with the projection by default. However, do you always reproject? I'd would argue that the default should be no reprojection as users often have their data in the same (local) CRS, no? In the Netherlands it's certainly the case. I would argue that you should automatically reproject to Mollweide only when:

1. the input datasets are in a different CRS
2. they are both in WGS84 lat-long (which will be often the case I reckon for your users?)


## Writing output files

I watched your video (it's nice and explains well what you've done) and you state that you can export files in different GIS formats (and not just Python objects), which I would expect since you use fiona/rasterio. But it seems that in the example given the results are only outputted in json, is that correct? You have one function `pandarus.filesystem.json_exporter()`, and `pandarus.maps.Map()` only wraps `open`, not `write`.

And why json and not geojson? Your downstream software use this? I'd argue that having a SHP or geojson output would be super useful, and easy to do.

**Comment by cmutel** [comment]
@hugoledoux Thanks for your detailed questions!

## Example usage

Not sure what went wrong in your installation, I have successfully tested the [installation instructions](http://pandarus.readthedocs.io/?badge=latest#installation) on OS X and Windows. Maybe there are path problems due to multiple Python installations? I normally don't make miniconda the default Python, and so have to do things a but more manually, e.g. `source ~/miniconda3/bin/activate pandarus-test`/

I added the example usage as a [plain Python file](https://github.com/cmutel/pandarus/commit/4dbf364177da4f06b366a68b1458ec55c8c1895f).

## Projection and CRS

I used to skip projecting if both datasets had the same CRS, but this was buggy - it is hard to compare CRS strings/objects, at least in Python. I ended up always projecting to WGS 84 and then Mollweide, as this was guaranteed to work, and almost all spatial datasets should be global (we are modelling/assessing global supply chains).

## Writing output files

The output data here would almost always be consumed by downstream software which only cares about the numeric values. Nevertheless, I modified the paper description and example usage to be more explicit that geojson is also output where it would be useful, e.g. for all possible intersections of one spatial file with another.

**Comment by hugoledoux** [comment]
@cmutel 

No idea about the Jupyter thing, but that's obviously on my side. The added py file works fine, including the output to geojson. 

Projection: as a GIS person, I still think that projecting to something else is not optimal, but I also understand that your users are probably not even aware of CRS. So your solution is probably the best.

As far as I am concerned, this is it. Your library is nice, and it's nice to see the efforts you've put in making it and document it. It makes a bit ashamed of my own projects, so that's a good outcome of this review for me: going back to work and better document my own stuff.

@arfon it's my first review, so let me know if that was "what is expected".

**Comment by arfon** [comment]
> @arfon it's my first review, so let me know if that was "what is expected".

@hugoledoux - I think you've done a great job here. Can you confirm that @cmutel has addressed your feedback? If so, I think we should be good to accept here.

**Comment by hugoledoux** [comment]
He has addressed all issues indeed. I'd accept.

**Comment by arfon** [comment]
> He has addressed all issues indeed. I'd accept.

👍 thanks for confirming.

@cmutel - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by cmutel** [comment]
@arfon New version with revision sugested by Hugo uploaded to [Zenodo](https://zenodo.org/record/571547) with DOI 10.5281/zenodo.571547. Note version update to 1.0.4.

Thanks everyone!

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.571547 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.571547" target="_blank">10.5281/zenodo.571547</a> is the archive.

**Comment by arfon** [comment]
@hugoledoux many thanks for your review here ✨ 

@cmutel - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00244 ⚡️ 🚀 💥
