### ISSUE TITLE
[REVIEW]: PySocialForce: A Python Implementation of the Extended Social Force Model for Pedestrian Dynamics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2494]
**Submitting author:** @yuxiang-gao (<a href="http://orcid.org/0000-0001-6183-2482">Yuxiang Gao</a>)
**Repository:** <a href="https://github.com/yuxiang-gao/PySocialForce" target ="_blank">https://github.com/yuxiang-gao/PySocialForce</a>
**Version:** v1.0.0
**Editor:** @pdebuyl
**Reviewer:** @ixjlyons, @xuqiancheng
**Archive:** Pending

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/c3424cf83f312576444345db2246dca5/status.svg)](https://joss.theoj.org/papers/c3424cf83f312576444345db2246dca5)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/c3424cf83f312576444345db2246dca5"><img src="https://joss.theoj.org/papers/c3424cf83f312576444345db2246dca5/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/c3424cf83f312576444345db2246dca5/status.svg)](https://joss.theoj.org/papers/c3424cf83f312576444345db2246dca5)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/yuxiang-gao/PySocialForce" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ixjlyons & @xuqiancheng, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @pdebuyl know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/yuxiang-gao/PySocialForce">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@yuxiang-gao) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/yuxiang-gao/PySocialForce">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@yuxiang-gao) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ixjlyons, @xuqiancheng it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1103/PhysRevE.51.4282 is OK
- 10.1098/rspb.2009.0405 is OK
- 10.1371/journal.pone.0010047 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02494/joss.02494/10.21105.joss.02494.pdf)

**Comment by pdebuyl** [comment]
@ixjlyons & @xuqiancheng make sure to accept the invitation to the reviewers group and to have a look at the reviewer guidelines linked to at the top of this review page.

The review process will happen in this issue page, so questions to the author or to me can be added as comments here.

**Comment by pdebuyl** [comment]
@yuxiang-gao a comment about the paper: it contains a code listing. This is best kept out of the paper and in the documentation or example files of the software.

**Comment by yuxiang-gao** [comment]
Hi @pdebuyl, thanks for the helpful comment. According to your suggestion, I have modified my paper so that the code listings are kept to the bare minimum and the example codes are now in an example file.

**Comment by xuqiancheng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02494/joss.02494/10.21105.joss.02494.pdf)

**Comment by xuqiancheng** [comment]
@pdebuyl @yuxiang-gao This is a nice implementation of the extended social force model for pedestrian dynamics. It realizes not only the social forces between individuals, but also the social forces for groups. The installation of the code is easy. The tests and exmaple are clear.   
From user perspective, I have two major comments regarding the submission:

-  I didn't see the introduction of the parameters in the [default.toml](https://github.com/yuxiang-gao/PySocialForce/blob/master/pysocialforce/utils/default.toml). It's difficult for user to design their own configuration files for simulations. A brief introduction about how is the simulation result changing with these parameters may be useful, especially for researchers who are not familiar with force-based model.

- The result of [scenarios_pedpedspace.py ](https://github.com/yuxiang-gao/PySocialForce/blob/master/tests/scenarios_pedpedspace.py) is about **lane formation** in bi-directional scenario. However it's difficult to observe the phenomenon since the various colors of the pedestrians in the simulation. It would be better to set a same color for pedsetrians moving in same direction. I suggest to add a new parameter to set the color of pedestrians in the visualization part.

Besides, I have three minor comments:

- I install the code according to the [document](https://github.com/yuxiang-gao/PySocialForce#installation). When I install the pip package from PyPI, I need to add [default.toml](https://github.com/yuxiang-gao/PySocialForce/blob/master/pysocialforce/utils/default.toml) into the package manually to run tests succefully. It should be mentioned in the document.

- There are seven *.py files in [tests](https://github.com/yuxiang-gao/PySocialForce/tree/master/tests), three of them are not start with **test**.  I suggest to rename these three files for pytest auto-discovery.

- I didn't see the documents about **Community guidelines**. It should be added.

I would like to ask the authors to consider these suggestions. I will accept this submission after that.

**Comment by pdebuyl** [comment]
@xuqiancheng thank you for the review!

@yuxiang-gao there is enough material here to warrant an update before proceeding further with the review. Can you address the comments by @xuqiancheng ?

**Comment by yuxiang-gao** [comment]
@pdebuyl @xuqiancheng Thank you for the review and I apologize that I couldn't address the comments until now. I have made the following changes to address @xuqiancheng 's concerns:
* For the first major comment and the first minor comment, I have added a more detailed explanation of the configuration file and added a sample file with comments explaning the parameters.
* For the second major comment, I have made the suggested modifications on the visualization part.
* For the rest of the minor comments, I have followed the suggestions by renaming the tests and adding the contributing guides.

**Comment by pdebuyl** [comment]
Thank you @yuxiang-gao for the reply.

**Comment by pdebuyl** [comment]
@ixjlyons can you proceed to the review?

**Comment by ixjlyons** [comment]
@pdebuyl yes, apologies for the delay. I'm planning to complete my review in the next few days and I'll take the recent updates into account (I had noticed a couple of the same issues already pointed out).

**Comment by ixjlyons** [comment]
My review:

PySocialForce is an extension and improvement upon [svenkreiss/socialforce](https://github.com/svenkreiss/socialforce), implementing the social force model with the addition of group forces. The interface for setting up simulations is straightforward and the modeling appears to be easily extended, enabling further research in the field.

I have a few comments below, but otherwise I recommend accepting.

Code/repository comments:

- Chien-Ming Huang is listed as an author but hasn't made public contributions to the source code. Could you state the rationale for authorship?
- Some of the tests appear to generate the images in the README. You might consider migrating these to examples instead (and you could still run them in CI). They appear to be good demonstrations of usage of the library. I was going to suggest moving the files not prefixed with `test_` to the examples folder before the names were changed upon the initial review.
- This project is in what I would consider the grey area of ["substantial scholarly effort"](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). Some code is shared with [svenkreiss/socialforce](https://github.com/svenkreiss/socialforce), but there has been some refactoring and a number of nice features appear to have been added, so I'm thinking these aren't ground for rejection. I just wanted to point this out to the editor -- I noticed the line count guideline, but Python in particular can be quite expressive and dense in terms of lines of code.
- I like the forces model (`forces.py`) - it seems very extensible. Does it make sense to actually unhide `_get_force` to encourage extending the core classes? I'm not very familiar with the field, but this seems like it could open some possibilities for further extending the pedestrian dynamics models significantly. I believe this is referred to in the paper ("adding new social forces").
- Tests fail with installation from PyPI because of the config file (FileNotFoundErrors). I see this has been pointed out in the README since the initial review, but I would recommend packaging the default config file in the sdist. See https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files
- Minor comment: there's a typo in the file name generated in `examples/example.py`
- I think there could be a benefit to browsable API documentation. It's not clear to me from the JOSS review guidelines if this is necessary or if general docstring coverage of classes/methods is sufficient (user can get html via pydoc).

Paper comments:

- Should the links to OpenAI Gym, Numba, ROS, and Qt be a citation too/instead?

**Comment by pdebuyl** [comment]
Thank you @ixjlyons for the review!

Comments/replies to the review's questions:

1. Installation via pip should proceed successfully.
2. Packaging the files via the "data files" of the package is good practice. We encourage to follow the best practices of the language for the project.
3. The documentation of the API should be available as well. Provided the docstrings are there already, this should be doable with little effort.
4. The documentation is in the README currently. This is ok in itself but it is of course not very flexible.
5. For projects that have a reference paper, it should be cited. Many projects (not all of course) have citation guidelines.

**Comment by pdebuyl** [comment]
@yuxiang-gao Can you address the comments by @ixjlyons ?

**Comment by pdebuyl** [comment]
@yuxiang-gao gentle reminder

**Comment by pdebuyl** [comment]
@yuxiang-gao gentle reminder

**Comment by pdebuyl** [comment]
@yuxiang-gao is there any issue preventing the progress of the review on your side?

**Comment by pdebuyl** [comment]
@yuxiang-gao I am pausing the review. I will not remind you or the reviewers of it.

**Comment by arfon** [comment]
@pdebuyl, I propose that if we've not heard back from @yuxiang-gao in the next 4 weeks, we close and reject this submission. It has now been stale for a very long time.

**Comment by arfon** [comment]
@whedon remind @arfon in 4 weeks

**Comment by whedon** [comment]
Reminder set for @arfon in 4 weeks

**Comment by pdebuyl** [comment]
Hi @arfon , so rejecting it is?

**Comment by arfon** [comment]
@whedon reject 

Due to the lack of input from the author, I'm moving ahead with a rejection here. @ixjlyons, @xuqiancheng, @pdebuyl – many thanks for your efforts here. Sorry this submission didn't make it through to completion.

**Comment by whedon** [comment]
Paper rejected.
