### ISSUE TITLE
[PRE REVIEW]: ParFlow Sand Tank: A tool for groundwater exploration

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2500]
**Submitting author:** @lecondon (<a href="http://orcid.org/0000-0003-3639-8076">Laura Condon</a>)
**Repository:** <a href="https://github.com/hydroframe/SandTank" target ="_blank">https://github.com/hydroframe/SandTank</a>
**Version:** v1.0.6
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @lecondon. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@lecondon if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2500 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/2500 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-446a0298a33b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon check repository

**Comment by Kevin-Mattheus-Moerman** [comment]
@openjournals/dev can you see why this paper wont compile?

**Comment by Kevin-Mattheus-Moerman** [comment]
@lecondon we are reviewing whether this work is in scope for JOSS. In particular it seems this submission might be better suited for our sister journal https://jose.theoj.org/ which focuses on educational software. If you disagree then perhaps help highlight and expand on the research (rather than educational) applications of this software.

**Comment by xuanxu** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02500/joss.02500/10.21105.joss.02500.pdf)

**Comment by lecondon** [comment]
Hello,

I  was not aware of this journal. I agree it would be abetter fit.  Do I need to submit separately there or is there a way to move it over?

Thanks,

Laura

—
Laura E. Condon, PhD
Assistant Professor
Hydrology and Atmospheric Sciences
University of Arizona, Tucson, AZ



On Jul 22, 2020, at 2:02 AM, Kevin Mattheus Moerman <notifications@github.com<mailto:notifications@github.com>> wrote:


External Email


@lecondon<https://github.com/lecondon> we are reviewing whether this work is in scope for JOSS. In particular it seems this submission might be better suited for our sister journal https://jose.theoj.org/ which focuses on educational software. If you disagree then perhaps help highlight and expand on the research (rather than educational) applications of this software.

**Comment by Kevin-Mattheus-Moerman** [comment]
@lecondon good question. I'll check for you. 
@openjournals/dev @labarba @arfon can you advise on this :point_up:

**Comment by labarba** [comment]
There's no way to transfer a submission. The author should study the JOSE documentation to determine if their work is in-scope, and if interested, make a new submission there. (Warning—we're operating at a much reduced pace in JOSE, due to few volunteers available.)

**Comment by lecondon** [comment]
Okay thank you both for the information! I checked the requirements and I think we are good fit for JOSE and we have resubmitted there.

Best,

Laura

—
Laura E. Condon, PhD
Assistant Professor
Hydrology and Atmospheric Sciences
University of Arizona, Tucson, AZ



On Jul 22, 2020, at 1:24 PM, Lorena A. Barba <notifications@github.com<mailto:notifications@github.com>> wrote:


External Email


There's no way to transfer a submission. The author should study the JOSE documentation to determine if their work is in-scope, and if interested, make a new submission there. (Warning—we're operating at a much reduced pace in JOSE, due to few volunteers available.)

**Comment by Kevin-Mattheus-Moerman** [comment]
@lecondon thanks. All the best over at JOSE. This issue will be closed.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
