### ISSUE TITLE
[PRE REVIEW]: cfdm: A Python reference implementation of the CF data model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2531]
**Submitting author:** @davidhassell (<a href="http://orcid.org/0000-0001-5106-7502">David Hassell</a>)
**Repository:** <a href="https://github.com/NCAS-CMS/cfdm" target ="_blank">https://github.com/NCAS-CMS/cfdm</a>
**Version:** 1.8.6.0
**Editor:** @usethedata
**Reviewers:** @bradyrx
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @davidhassell. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @usethedata.

@davidhassell if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02531/joss.02531/10.21105.joss.02531.pdf)

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=341.89 s (73.7 files/s, 12485.4 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
HTML                          23205         575091              0        3501736
Python                          133          13888          21391          24675
reStructuredText               1745          20548          48515          23234
JavaScript                       64           4712           4964          20036
CSS                              22           1818            346           6342
Markdown                          7             99              0            356
Bourne Again Shell                7             73             82            169
DOS Batch                         1             21              1            148
make                              1             24              9            108
TeX                               1             10              0            106
YAML                              1             15             23             61
JSON                              1              0              0             30
SVG                               1              0              0              1
--------------------------------------------------------------------------------
SUM:                          25189         616299          75331        3577002
--------------------------------------------------------------------------------


Statistical information for the repository '2531' was gathered on 2020/07/28.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
David Hassell                  606        515447         317725           72.68
Sadie Louise Barthol           114         21748           3456            2.20
cfpython                       261        146996          71736           19.08
david                           17         48185          16424            5.64
davidhassell                    24          3553           1103            0.41

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
David Hassell            107578           20.9          2.4               15.57
Sadie Louise Barthol      19870           91.4          2.5               12.91
cfpython                 198155          134.8         13.8               14.97
```

**Comment by kthyng** [comment]
@whedon invite @usethedata as editor

**Comment by whedon** [comment]
@usethedata has been invited to edit this submission.

**Comment by usethedata** [comment]
@whedon assign @usethedata as editor

**Comment by whedon** [comment]
OK, the editor is @usethedata

**Comment by usethedata** [comment]
@davidhassell I'm in the middle of a quarterly planning meeting this week.  I'll dig into your paper and repo over the weekend and start looking for reviewers.  Thanks for your submission and for your patience.

**Comment by davidhassell** [comment]
@usethedata Thank you for editing, and I look forward to hearing from you soon.

**Comment by davidhassell** [comment]
@usethedata I'm happy to suggest a reviewer if that helps - just let me know, thanks.

**Comment by usethedata** [comment]
Sorry for the delays.  I've got a couple of requests for reviewers out.

**Comment by usethedata** [comment]
@whedon add @bradyrx as reviewer

**Comment by whedon** [comment]
OK, @bradyrx is now a reviewer

**Comment by bradyrx** [comment]
@usethedata, @davidhassell 

Hi all, thanks for the patience here. It looks like this is stuck in pre-review? I have time now to do this so I'm just going to post my review here using the checklist I used last time I reviewed for JOSS.

Overall, `cfdm` looks great and I'm happy to suggest its acceptance to JOSS following some minor corrections I've listed below. Some are nitpicky grammar on the paper, others are some thoughts to make contributions more accessible to early open-source contributors. I was able to use `cfdm` very quickly with some forecasting data I had saved out to disk. The docs are thorough and give good tutorials. I didn't go too deep into the code base, but after skimming through, it hits the points I care about -- robust testing, leverages inheritance, and has consistently good docstrings.

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/NCAS-CMS/cfdm">repository url</a>?

Yes. The source code is available and the repo is very well structured for open-source science.

- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?

- [X] **Contribution and authorship:** Has the submitting author (@davidhassell) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

Yes, it looks like the two main contributors to the code base are the two authors.

### Functionality

- [X] **Installation:** Does installation proceed as outlined in the documentation?
- [X] **Functionality:** Have the functional claims of the software been confirmed?

Yes, I loaded in some SubX subseasonal forecasting output I had and was able to follow along with the tutorial and inspect its properties.

- [X] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

Yes, I tried playing around with inplace operations (in memory) per the docs and things were faster in place.

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

Really impressed by the thorough tutorial examples on the docs. Well done!

- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [X] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?

There's no `codecov` or `coveralls` indicator of how much coverage the testing gives, but I can see that there is a thorough amount of testing done under `cfdm/test`.

- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

1. I think it would be good to add a code of conduct. See `Insights/Community'. That's the main thing missing (outside of PR templates). They have some stock ones that work well. Ours at `climpred` is based on https://www.contributor-covenant.org/version/1/4/code-of-conduct/.
2. It looks like `CONTRIBUTING.md` in the main repo is decoupled from the "support" page on the docs. I.e., the docs are missing some of this information. I would also suggest adding more information for first-time or early contributors, since there's a lot of steps that go into contributing to a python package on Github. I have a lightweight personal package with some contribution instructions that you're welcome to pull from: https://esmtools.readthedocs.io/en/stable/contributing.html (see "Preparing Pull Requests").
3. I might change the docs page name from "Support" to something more obvious like "How to Contribute".

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?

It is mentioned that `cfdm` is the only library that is guaranteed to handle every possible type of CF-compliant dataset. I think this leaves out popular high-level packages like `iris` (https://github.com/SciTools/iris) that have CF-compliant manipulation of Earth System data, and it doesn't look like `cfdm` is a dependency there (please correct me if I'm wrong). `xarray` doesn't natively handle CF well, but an extension to it `cf-xarray` does: https://github.com/xarray-contrib/cf-xarray. So there might be some other packages that can be nodded to that think of the CF data model.

- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?

Generally well written. See my bottom notes on small fixes to the paper's grammar. There are some spurious semicolons and commas in a few places throughout. Please double check uses of `,` and `;`.

- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

Some notes on the paper:
* Under the summary, the semicolon should be dropped from "They cater for data from model simulations; and from observations, ...". Maybe change the "and" following it to "as well as" for flow.
* The sentence following the previous is structured somewhat awkwardly. I would say something like "CF conventions provide a description of the physical meaning of netCDF data variables, as well as their spatial, temporal, and other dimensional properties."

**Comment by davidhassell** [comment]
@bradyrx 

Thank you very much for taking the time to do this review - we'll get back to you in a day or two on the points that you've raised.

**Comment by davidhassell** [comment]
@bradyrx, @usethedata

Hi. Thanks again for the detailed review. We have taken all of of your points on board, and hope that we can address them with the changes described here.

> There's no codecov or coveralls indicator of how much coverage the testing gives, but I can see that there is a thorough amount of testing done under cfdm/test.

Code coverage is calculated as part of the test suite, and run with the GitHub actions, but is not easy to find. It is currently 87% (e.g.  The "Run test suite and generate a coverage report" section of https://github.com/NCAS-CMS/cfdm/runs/1103183661). We are currently working to make this accessible by adding a new workflow to our GitHub Actions setup which will integrate the Codecov tool to the project and trigger coverage reports against every pull request..

> I think it would be good to add a code of conduct. See Insights/Community'. That's the main thing missing (outside of PR templates). They have some stock ones that work well. Ours at climpred` is based on https://www.contributor-covenant.org/version/1/4/code-of-conduct/.

There is now a code of conduct at https://github.com/NCAS-CMS/cfdm/blob/master/CODE_OF_CONDUCT.md

> It looks like CONTRIBUTING.md in the main repo is decoupled from the "support" page on the docs. I.e., the docs are missing some of this information. I would also suggest adding more information for first-time or early contributors, since there's a lot of steps that go into contributing to a python package on Github. I have a lightweight personal package with some contribution instructions that you're welcome to pull from: https://esmtools.readthedocs.io/en/stable/contributing.html (see "Preparing Pull Requests").
>
> I might change the docs page name from "Support" to something more obvious like "How to Contribute".

We have replaced the "Support" section of the docs with a new "Contributing" section: https://github.com/NCAS-CMS/cfdm/blob/master/docs/source/contributing.rst, which draws on the esmtools approach - thanks. This file will get rendered as html at the time of the next release.

The CONTRIBUTING.md file (https://github.com/NCAS-CMS/cfdm/blob/master/CONTRIBUTING.md) has been modified to be consistent with the new docs. Instead of just duplicating the content from the Contributing section of the documentation, we preferred to provide a summary there and link to the docs page for full detail.

> Generally well written. See my bottom notes on small fixes to the paper's grammar. There are some spurious semicolons and commas in a few places throughout. Please double check uses of , and ;.

We have revised the grammar in this light. The new text is in https://github.com/NCAS-CMS/cfdm/blob/master/joss/paper.md, and in the new whedon-generated pdf following this comment. The changes made in this respect, should you wish to isolate them, are contained in the pull request https://github.com/NCAS-CMS/cfdm/pull/76.

> It is mentioned that cfdm is the only library that is guaranteed to handle every possible type of CF-compliant dataset. I think this leaves out popular high-level packages like iris (https://github.com/SciTools/iris) that have CF-compliant manipulation of Earth System data, and it doesn't look like cfdm is a dependency there (please correct me if I'm wrong). xarray doesn't natively handle CF well, but an extension to it cf-xarray does: https://github.com/xarray-contrib/cf-xarray. So there might be some other packages that can be nodded to that think of the CF data model.

I think that our  original text was indeed less than clear on the separation between being able to manipulate all possible CF-netCDF datasets and implementing the CF data model. The former is possible without the latter, and the latter does not guarantee the former. Many libraries (iris, xarray, cf-xarray, ferret, grads, netCDF Java, ...) understand many features of CF, but none of them implement the CF data model, and also none are complete - in the sense that there are some elements of CF that they do not understand. cfdm both implements the CF data model, and can process every all possible CF-netCDF datasets.

Iris is a interesting example, as they state that they implement "a" data model of the CF conventions (my emphasis), but do not state what it is. It is not, however, the accepted CF data model that cfdm implements (for example, coordinate systems in iris are contained within coordinates, rather than the parent iris cube, which the CF data model would require). This is of course not a problem per se, as the CF data model makes no claims on uniqueness, but in any case iris does not yet provide functionality for everything in CF. From a look around the code base and docs, it appears to not be able to deal with simple geometries, netCDF hierarchical groups, discrete sampling geometries, and compression by gathering (for example).

I hope that a change to the text in the "Statement of need" section will be enough to clear up this subtle area:

**(Old text)** "To the authors' knowledge, cfdm and software built on it are currently the only libraries that are guaranteed to be able to handle every possible type of CF-compliant dataset. All others omit facets that are not currently of interest to their particular user communities."

**(New text)** "To the authors' knowledge, cfdm and software built on it are currently the only libraries that fully implement the CF data model and its application to every feature of the CF-netCDF encoding. All others omit facets that are not currently of interest to their particular user communities."

(the new text is also in the latest pdf version).

**Comment by davidhassell** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02531/joss.02531/10.21105.joss.02531.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02531/joss.02531/10.21105.joss.02531.pdf) :page_facing_up: :point_left:

**Comment by davidhassell** [comment]
@bradyrx, @usethedata 

Apologies, I inserted an incorrect version of the "New text" at the end of the previous comments. it should read:

**(New Text)** "To the authors’ knowledge, cfdm and software built on it are currently the only libraries that can understand all CF-netCDF datasets, made possible by the complete implementation of the CF data model. All others omit facets that are not currently of interest to their particular user communities."

This is what is in the latest `paper.md` and pdf.

Thanks

**Comment by bradyrx** [comment]
Wonderful @davidhassell. Thanks so much for the prompt response and incorporating my suggestions. Looks good to me. I am good for this to be accepted. I know we're still on a `PRE REVIEW` thread, but hopefully this does it. Congratulations, and nice work on the package. That's quite the headache to handle all aspects of CF but very important!

**Comment by davidhassell** [comment]
That's great, @bradyrx. Thank you again for your review and your good suggestions.

@usethedata, is there any progress on  second reviewer?

**Comment by davidhassell** [comment]
@usethedata, We are happy to suggest another reviewer, if there have not yet been any other takers from your invitations.

Thanks, David

**Comment by usethedata** [comment]
Sorry to have been absent here.  I was slammed with end of fiscal year stuff and a reorganization at work.  I could have sworn I opened the review issue for this, but didn't.  This is the pre-review issue.  Let me actually create the review issue and then I'll copy/post the work @bradyrx has already done over into that issue and go from there.

**Comment by usethedata** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2717.
