### ISSUE TITLE
[PRE REVIEW]: FGlT: Fast Graphlet Transform

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2616]
**Submitting author:** @fcdimitr (<a href="http://orcid.org/0000-0003-1190-4075">Dimitis Floros</a>)
**Repository:** <a href="https://github.com/fcdimitr/fglt" target ="_blank">https://github.com/fcdimitr/fglt</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @fcdimitr. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @labarba.

@fcdimitr if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (356.5 files/s, 35297.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                              3            225             77            538
Markdown                         6            166              0            447
MATLAB                           4             59            127            137
TeX                              1             17              0            107
Python                           2             13             24             62
YAML                             1              4              0             46
C/C++ Header                     1             13             24             33
NAnt script                      1             11              0             30
make                             1              3              1              6
Bourne Shell                     2              2              0              6
-------------------------------------------------------------------------------
SUM:                            22            513            253           1412
-------------------------------------------------------------------------------


Statistical information for the repository '2616' was gathered on 2020/08/31.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dimitris Floros                 16          1729            842           88.32
Jason Barmparesos                2            37             14            1.75
kitsiosk                         5           194             95            9.93

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dimitris Floros             880           50.9          0.2               10.45
Jason Barmparesos            34           91.9          0.2               44.12
kitsiosk                     95           49.0          0.1               25.26
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1006/jpdc.1996.0107 is OK
- 10.1093/bioinformatics/bth436 is OK
- 10.1093/bioinformatics/btl030 is OK
- 10.1093/bioinformatics/btl301 is OK
- 10.1017/9781108377706 is OK
- 10.1038/srep35098 is OK
- 10.1038/srep04547 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02616/joss.02616/10.21105.joss.02616.pdf)

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by fcdimitr** [comment]
Hello, there is Statement of need in the paper, I am guessing the parsing failed because sections were defined with 

```
Statement of need
=============
```

I have fixed them, will recompile the PDF.

**Comment by fcdimitr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02616/joss.02616/10.21105.joss.02616.pdf)

**Comment by danielskatz** [comment]
👋 @fcdimitr  - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort] criteria for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by pitsianis** [comment]
Dear @danielskatz @kthyng @labarba 

We are surprised by the automatic or semi-supervised  rejection. 
1. We have followed the JOSS criteria carefully. 
2. The released software is the result of intense effort by the authors, since early March. Its quality and value cannot be measured by the development time length, nor by the code length. We actually paid extra attention to make the code as light-weight in time, and space complexity, as well as, short in code lines. The code has been adopted as a performance test with OpenCilk, an open source concurrency platform from MIT.
3. The FGLT performance surpasses the state-of-the-art software with comparable functionality in admissible network size, computation speed, and space complexity. In speed alone,  the difference on large networks is between several days versus two hours with our code.

**Comment by labarba** [comment]
hi 👋  — I'm not sure why I was tagged on this Pre-Review, as I was not on AEiC rotation when this was processed, nor involved in the discussions... But let me clarify that when a submission is labeled with `query-scope` due to its size, we have a process behind the scenes where members of the editorial board inspect the submission and vote on it going to review or not. What is automatic is the software report using `cloc`—then the AEiC on rotation manually inspects and decides to add the `query-scope` label (or not), and then it goes to the board for further manual checks of the scope. We require at least two additional board members to concur on a desk rejection (as is typical at other journals).

The JOSS eligibility criteria have tightened somewhat over the years, but we have always flagged single-function software as potentially out of scope, and submissions under 1000 lines of code are inspected by the board for meeting the criteria on [Substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort).

We are mindful that JOSS gives a "publication credit" for the software, and continue to be regarded as a valid and equal counterpart to traditional journals, for which reason we are constantly discussing our criteria and refining our process. Like editors at other journals, we have to draw a line somewhere for what we consider a "minimum publishable unit."

Please consider whether this software can be made part of a larger package providing additional functionality, and which would make for a submission that passes that bar.
