### ISSUE TITLE
[REVIEW]: Xgcm: A Python Package for Analyzing Data from General Circulation Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2631]
**Submitting author:** @rabernat (<a href="http://orcid.org/0000-0001-5999-4917">Ryan Abernathey</a>)
**Repository:** <a href="https://github.com/xgcm/xgcm" target ="_blank">https://github.com/xgcm/xgcm</a>
**Version:** v.0.3.0
**Editor:** @kthyng
**Reviewer:** @koldunovn, @vrx-
**Archive:** Pending

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/4aaf651e475de94b815ad619f5c1ddcf/status.svg)](https://joss.theoj.org/papers/4aaf651e475de94b815ad619f5c1ddcf)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/4aaf651e475de94b815ad619f5c1ddcf"><img src="https://joss.theoj.org/papers/4aaf651e475de94b815ad619f5c1ddcf/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/4aaf651e475de94b815ad619f5c1ddcf/status.svg)](https://joss.theoj.org/papers/4aaf651e475de94b815ad619f5c1ddcf)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/xgcm/xgcm" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@koldunovn & @vrx-, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/xgcm/xgcm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rabernat) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/xgcm/xgcm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@rabernat) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @koldunovn, @vrx- it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2631 with the following error: 

 Error reading bibliography ./paper.bib (line 73, column 1):
unexpected "<"
expecting space, letter, digit, white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by kthyng** [comment]
Here we are in the review @koldunovn, @vrx-! You can see your checklists above to drive the review process. As you find issues to raise as part of the review, please share them by starting a github issue in the software repo itself, then link it back to this review issue by including a link to here. This will help keep everything organized. Then you can write a small summary of the issues you've raised in the repo. Let me know if you have questions, esp since this is a unique reviewing approach!

**Comment by rabernat** [comment]
I introduced a typo into our bib file when addressing https://github.com/openjournals/joss-reviews/issues/2628#issuecomment-685008307. This has been fixed in https://github.com/xgcm/xgcm/commit/5634d71af4f45a86062d6b0bbb2138ea416b112a. I have verified that the preview now builds using  https://whedon.theoj.org/.

**Comment by vrx-** [comment]
@whedon generate pdf

**Comment by koldunovn** [comment]
There are just a couple things left:

Issues: https://github.com/xgcm/xgcm/issues/243 https://github.com/xgcm/xgcm/issues/246 https://github.com/xgcm/xgcm/issues/249

Comments to the text:

**Statement of Need**
I think the statement "Xgcm supports orthogonal curvilinear grids, including complex, multiply-connected grid topologies such as the cubed-sphere." should be moved to the beggining of the "Statement of Need", espetially since authors suggest that package will be useful for "plasma physics or astrophysical modeling" where other grid types are quite common. This will more clearly position the package.  

**State of the field**
To my knowlege there are no packages with similar functionality in the python world. But there are similar efforts, at least with respect of trying to get boundaries right, and properly integrate values, for example,  in cdo (https://code.mpimet.mpg.de/projects/cdo/wiki/Cdo#Documentation). NCL (https://www.ncl.ucar.edu/index.shtml), to my knowlege, also understands grid staggering, and, I gues, this will be also true for its sucecsor https://github.com/NCAR/geocat-comp .

**Comment by rabernat** [comment]
Hi all. I'm very grateful for the work of the editors and reviewers so far on this paper. Thanks so much for your time!

The authors have conferred and have decided that we would like to suspend (if possible) or withdraw this paper. We have concluded that publishing a paper about xgcm with an all-male author list is not a good idea. I wish we had realized this before submitting, but the recent NumPy paper fiasco helped open our eyes to the potential harm this can cause.

We have several concrete plans to increase the gender diversity of our contributors and hopefully add some more authors. But this will take time, possibly a year.

I definitely do **not** want to waste the time the reviewers have already spent reviewing this paper. Ideally what we would like to do is to continue this review process, to the point where we have all the boxes checked, but pause going forward to the publication stage. At a future date, hopefully we can pick things up from where we left off.

@kthyng--is this compatible with JOSS policies? If not, what course of action would you recommend?

Sorry for introducing this fly in the ointment to an otherwise very smooth review process. We are trying, imperfectly, to do the right thing.

**Comment by kthyng** [comment]
@rabernat I understand your concern. I think the best course of action is to heartily thank the reviewers for their time. xgcm should be reviewed at the time you want to publish because all of the software at the time of publishing should be reviewed, not just what is in the repo today. The future authors you hope to recruit will make changes that should be included in the review.

So, my suggestion is to withdraw the paper now with the intention of resubmitting at a later date. Is this what you would like to do?

**Comment by vrx-** [comment]
Hi. I've been holding comments while this resolves, so please let me know if the paper is being withdrawn, and we are stoping the review process, or if I should continue.

**Comment by rabernat** [comment]
Sorry for the delay, and thanks for everyone's patience.

Yes, we have decided to withdraw the paper. I'm **extremely grateful** for the time you have spent on this, and I **apologize deeply and sincerely** for not seeing this glaring problem _before_ submitting our paper. The reviewers' time was definitely not wasted from my point of view, as the comments have already led to considerably improvements of the package.

**Comment by kthyng** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
