### ISSUE TITLE
@TheoChristiaanse Thanks for your submission! A very quick initial comment is that was not straightforward for me to:

### ISSUE THREAD

**Issue by TheoChristiaanse** [openjournals/joss-reviews#2652]
@TheoChristiaanse Thanks for your submission! A very quick initial comment is that was not straightforward for me to:

1. find the documentation (the links to the notebooks and tutorials at https://besos.uvic.ca/#documentation don't work )
2. understand which parts of this can be run offline and how that relates to what you describe as the "cloud-based portal" -- is what you offer online simply a hosted version of what is installable as a Python package?
3. understand how BESOS relates to PyEHub which is linked to first thing on https://besos.readthedocs.io/en/stable/

_Originally posted by @sjpfenninger in https://github.com/openjournals/joss-reviews/issues/2620#issuecomment-686974509_

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2652 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@TheoChristiaanse - please do not open new issues on this repository. Make your comments in the dedicated review thread for this paper: https://github.com/openjournals/joss-reviews/issues/2620#issuecomment-686974509
