### ISSUE TITLE
[PRE REVIEW]: J2suscep: Calculation of magnetic exchange coupling and temperature dependence of magnetic susceptibility

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2660]
**Submitting author:** @Swetanshu (<a href="http://orcid.org/0000-0002-0626-0626">Swetanshu Tandon</a>)
**Repository:** <a href="https://github.com/WatsonGroupTCD/J2suscep" target ="_blank">https://github.com/WatsonGroupTCD/J2suscep</a>
**Version:** 1.0
**Editor:** @dpsanders
**Reviewers:** @mturiansky, @mfherbst
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @Swetanshu. **Currently, there isn't an JOSS editor assigned** to your paper.

@Swetanshu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.04 s (369.3 files/s, 78884.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Fortran 90                       9            165            762           2186
TeX                              1              8              0            146
Markdown                         4             13              0             94
make                             2             14              0             30
-------------------------------------------------------------------------------
SUM:                            16            200            762           2456
-------------------------------------------------------------------------------


Statistical information for the repository '2660' was gathered on 2020/09/10.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/jcc.23234 is OK
- 10.1021/ic900992r is OK
- 10.1039/B902745A is OK
- 10.1007/128_2015_645 is OK
- 10.1021/ic502651w is OK
- 10.1039/D0SE00701C is OK
- 10.1039/D0DT01404D is OK
- 10.1002/chem.201405679 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1016/j.ccr.2008.05.014 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.cpc.2010.09.007 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02660/joss.02660/10.21105.joss.02660.pdf)

**Comment by danielskatz** [comment]
👋 @Swetanshu - please add an explicit "Statement of need" section to your paper, then regenerate the PDF by adding ```@whedon generate pdf``` as a new comment here.

**Comment by danielskatz** [comment]
👋 @usethedata - I know you have a few papers already, but would you be willing to edit this one as well?

**Comment by danielskatz** [comment]
@whedon invite @usethedata as editor

**Comment by whedon** [comment]
@usethedata has been invited to edit this submission.

**Comment by Swetanshu** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by Swetanshu** [comment]
@whedon generate pdf

**Comment by Swetanshu** [comment]
@whedon check references

**Comment by Swetanshu** [comment]
Hi @danielskatz, 
Potential reviewers: Alex ganose (username: utf) and Benjamin Morgan (username: bjmorgan).

**Comment by danielskatz** [comment]
Thanks @Swetanshu  - the next step will be assigning an editor, who will then work on reviewers

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02660/joss.02660/10.21105.joss.02660.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02660/joss.02660/10.21105.joss.02660.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@pdebuyl @usethedata @pibion @dpsanders could one of you handle this submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
:wave:  @pdebuyl @jgostick @usethedata @pibion @dpsanders could one of you handle this submission?

**Comment by dpsanders** [comment]
👋 @Kevin-Mattheus-Moerman: I can take it on.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @dpsanders as editor

**Comment by whedon** [comment]
OK, the editor is @dpsanders

**Comment by dpsanders** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02660/joss.02660/10.21105.joss.02660.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02660/joss.02660/10.21105.joss.02660.pdf) :page_facing_up: :point_left:

**Comment by dpsanders** [comment]
👋 @Swetanshu: Thanks for your submission to JOSS! 
Looking over the paper and repo, I have some preliminary comments:

- It's not clear why there are two standalone codes being submitted as one submission.

- Please expand the README in the repo with usage instructions and links to the documentation.

- It is not clear where the data from the DFT calculations comes from or what format it should be in. Please give a complete example.

- I do not see the source for the documentation -- this should be provided. It would be preferable for the docs to be available as web pages etc., rather than a monolithic PDF.

- Ideally, please include a simple usage example in the paper.

Thanks!

**Comment by dpsanders** [comment]
Also I forgot to mention that the software will need some kind of tests to make sure that it is working correctly.

**Comment by Swetanshu** [comment]
Hi @dpsanders: Thank you for your comments and apologies for the late reply. I have tried to address your comments and the changes are described below:

•  It's not clear why there are two standalone codes being submitted as one submission.
The codes “EJ_calc” and “suscep” together provide a means to use the data obtained from density functional theory calculations for simulating the magnetic susceptibility. This requires the calculation of J-values (obtained from EJ_calc) followed by their use in the simulation of the susceptibility (obtained from the suscep code). Although, the two codes complement each other, the calculation of both J-values and susceptibility together is not always required. Additionally, the time required for the calculation of susceptibility can vary from seconds to hours. Keeping these things in mind, we decided to tackle the problem by developing two standalone codes instead of coupling them together.


•  Please expand the README in the repo with usage instructions and links to the documentation.
The readme file in the repository provides a brief description of the package. The detailed documentation has been provided in the github wiki pages. The README has been modified to indicate this.


•  It is not clear where the data from the DFT calculations comes from or what format it should be in. Please give a complete example.
An example has been included in the wiki pages in the example sections. 


•  I do not see the source for the documentation -- this should be provided. It would be preferable for the docs to be available as web pages etc., rather than a monolithic PDF.
	The documentation in the pdf format has been left in the repo but all the information contained in the pdf files is also available in the github wiki pages.


•  Ideally, please include a simple usage example in the paper.
	Considering the length of the input files, the example covered in the paper is only briefly described. A detailed description of the same example is provided in the wiki pages. The input and output files for the same example are provided in the respective directories.


•  the software will need some kind of tests to make sure that it is working correctly.
	A few example input and output files are provided for this purpose. One can compare their output files with the provided ones to test the working of the code.


Let me know if you want me to modify anything else.
Thank you once again!

**Comment by dpsanders** [comment]
@Swetanshu At a glance that looks good, thanks!

Do you have any suggestions for reviewers from the list linked above?

**Comment by Swetanshu** [comment]
@dpsanders From the list: Alex ganose (username: utf) and Benjamin Morgan (username: bjmorgan).
Prof. Julian Gale ( J.Gale@curtin.edu.au) would be extremely suitable but I could not find his name in the list.

**Comment by dpsanders** [comment]
👋 @utf and @mturiansky: Would you be willing and able to review this submission for JOSS, the Journal of Open Source Software? Thanks!

**Comment by mturiansky** [comment]
@dpsanders I'd be happy to. This would be my first review for JOSS though, so please excuse my naivety.

**Comment by dpsanders** [comment]
@mturiansky Thanks! No problem, let me know if you have any questions once the review starts.

**Comment by dpsanders** [comment]
👋 @mfherbst: Would you be willing and able to review this submission for JOSS, the Journal of Open Source Software? Thanks!

**Comment by mfherbst** [comment]
@dpsanders Sure, I'm happy to take it up. But same as @mturiansky it would be my first time reviewing for JOSS.

**Comment by dpsanders** [comment]
@whedon add @mturiansky as reviewer

**Comment by whedon** [comment]
OK, @mturiansky is now a reviewer

**Comment by dpsanders** [comment]
@whedon add @mfherbst as reviewer

**Comment by whedon** [comment]
OK, @mfherbst is now a reviewer

**Comment by dpsanders** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2838.

**Comment by dpsanders** [comment]
Many thanks @mturiansky and @mfherbst!

Please head over to the review issue, where there's a checklist to orient your review.
The guidelines can be found in https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Please don't hesitate to ask if you have any questions. Thanks!
