### ISSUE TITLE
[PRE REVIEW]: Of demultiplexing and quality control

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2714]
**Submitting author:** @khourhin (<a href="http://orcid.org/0000-0001-7712-8270">Etienne Kornobis</a>)
**Repository:** <a href="https://github.com/sequana/of_demultiplexing_and_fastqc" target ="_blank">https://github.com/sequana/of_demultiplexing_and_fastqc</a>
**Version:** v1.0.1
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @khourhin. **Currently, there isn't an JOSS editor assigned** to your paper.

@khourhin if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@arfon perhaps this is a good first submission for @luizirber to handle?
Perhaps @majensen @lpantano (who work on genomics) can help too. 

Note this submission is for 2 repositories.

**Comment by arfon** [comment]
> @arfon perhaps this is a good first submission for @luizirber to handle?

In theory yes, although looking more closely at these two submissions, they are both _very_ small so this submission may not be in scope for JOSS?

```
arfon@mawr ~ $ cloc sequana_fastqc/
      26 text files.
      26 unique files.                              
      10 files ignored.

github.com/AlDanial/cloc v 1.86  T=0.04 s (542.1 files/s, 45739.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           5            138            169            265
CSS                              1             53              7            198
reStructuredText                 4             66              8            133
YAML                             4             29             72            117
make                             2             24              7            110
Markdown                         1             50              0             89
TeX                              1              8              0             56
Bourne Shell                     1              0              0              4
-------------------------------------------------------------------------------
SUM:                            19            368            263            972
```

```
arfon@mawr ~ $ cloc sequana_demultiplex/
      26 text files.
      26 unique files.                              
      14 files ignored.

github.com/AlDanial/cloc v 1.86  T=0.02 s (603.9 files/s, 47789.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           7            162            188            397
reStructuredText                 2             58              2            140
make                             2             24              4            108
YAML                             3              9             22             69
Bourne Shell                     1              0              0              4
-------------------------------------------------------------------------------
SUM:                            15            253            216            718
-------------------------------------------------------------------------------
```

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
👋 @khourhin - I'm sorry to say that after discussion amongst the JOSS editors, we have decided that this submission does not meet the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.  Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by danielskatz** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by cokelaer** [comment]
@danielskatz @arfon @khourdin

Dear Daniel, Dear Arfon,

First of all thanks for your review and work on JOSS and in particular on this submission. This is very much appreciated. 

Yet, as you could expect, we are sad to see that the paper submission has been rejected by the editors. I hope that your decision is not solely based on the fact (as written above) that the "two pipelines are both very small". The reviewer may have done more investigations but it does not appear in the review process as far as I know. We have the feeling that as stated in your "substantial scholarly effort" page, the two pipelines seem to meet your requirements.

First, they represent a substantial efforts (more than your expected 3 months of development). Second, the two pipelines are used on a daily-basis within a genomic platform for a couple of years now and have reached a mature level. Although there are few commits and authors, they are based on the work of technicians, engineers, researchers and I strongly believe that once published in JOSS (maybe), the paper will be cited as is cited a related  paper submitted to JOSS two years ago (https://joss.theoj.org/papers/10.21105/joss.00352).  As you are fully aware, the quality of a software cannot be solely judge upon the number of commits or lines of code. This is usually a good indicator but is not a prerequisites.

I understand that JOSS has grown a lot and I am the first to be happy about this promotion of Open Source Software. I also understand that those pipelines will not revolutionize genomic research since they are essentially wrappers around existing tools as stated in the paper and their goals consists merely in checking the quality of the NGS data. Yet, it cannot be summarized to some lines of codes (that passes your criteria by the way). Indeed, the two pipelines are high-quality software with documentation, wiki, help, etc. ; they can be used easily as preprocessing steps by researchers before performing further analysis.  They also use high-level library developed by us to factorise code across pipelines hence the "small size" of the pipelines. I wished that the reviewer took the time to appreciate that level of complexity (maybe he did ?), which is indeed hidden and transparent to the user/developer.

I would like to kindly ask the editors and reviewer to reconsider their decision. I understand that JOSS has grown and that the entry point has increased, yet I believe that those two pipelines are useful to the NGS community and I would appreciated more feedbacks even if  you are still rejecting our submission. This will help us to better understand the scope of JOSS and decide whether to submit future works or not.

Again, just to make sure there is no  misunderstanding, we really do appreciate your work and hope that our request sounds reasonable and respectful to both editors and reviewers. 

All the best
Thomas

FYI: we work in a NGS sequencing platform (https://biomics.pasteur.fr/) developing software for production and developping new analysis tools on demands (see our group page here: https://biomics.pasteur.fr/salsa).
