### ISSUE TITLE
[PRE REVIEW]: ShinyGAStool: A user-friendly tool for candidate gene association studies

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2723]
**Submitting author:** @kordk (<a href="http://orcid.org/0000-0001-9732-3321">Kord Kober</a>)
**Repository:** <a href="https://github.com/kordk/shinyGAStool/" target ="_blank">https://github.com/kordk/shinyGAStool/</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @kordk. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @Kevin-Mattheus-Moerman.

@kordk if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2723 with the following error: 

 Can't find any papers to compile :-(

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.13 s (22.4 files/s, 8346.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                1            155            292            584
Markdown                         1             27              0             47
HTML                             1              0              0             13
-------------------------------------------------------------------------------
SUM:                             3            182            292            644
-------------------------------------------------------------------------------


Statistical information for the repository '10bd445dfa0134d27616334a' was
gathered on 2020/10/06.
No commited files with the specified extensions were found.
```

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @kordk! Thank you for your submission. I have flagged your submission as possibly out of scope due to its small size. Please see details on "substantial scholarly effort": https://joss.readthedocs.io/en/latest/review_criteria.html#substantial-scholarly-effort. The editorial board will consider your submission to make the decision together in the next week or two. If there is any additional information you'd like to provide, please feel free to do so in this pre-review issue.

**Comment by kordk** [comment]
Hello @kthyng! Thank you for your consideration of our manuscript introducing the ShinyGAStool. The tool implements a regression method that our team have used for genetic association testing in over 20 studies in the past ten years. While we had great success using the method, the genetic data for these studies were collected using a custom microarray or direct genotyping and required a custom analytic pipeline to extract and perform the analysis. Given that genomic data collection has changed into using whole-genome and whole-exome microarray and sequencing methods that have standardized data formats, we found that we and our mentees were limited in their ability to perform these analyses because of inadequate knowledge and expertise with both data extraction and use of various analytic tools. In conjunction with the implementation of more advanced training in informatics, we developed the ShinyGAStool to facilitate simple and easy access to the data and our analytic method. We anticipate that this tool will be used by predoctoral students, post-doctoral fellows, and clinical scientists across numerous disciplines (e.g., medicine, nursing, pharmacy, psychology) who do not have in depth knowledge and expertise in bioinformatics. 

With respect to the substantial scholarly effort, the development of this software was supported by a grant from the NCI (R37 CA233774) and is being incorporated into the curricula as part of an NIH-funded training grant (NINR T32 NR016920). In addition, we used the ShinyGAStool to perform a genetic association analysis for our latest study that evaluated candidate loci associated with peripheral neuropathy in cancer survivors (NCI R01 CA168960). This analysis will be used for an abstract submission for a national meeting and a manuscript is in development. It is our hope that by publishing the ShinyGAStool in JOSS, we will encourage broader use and development of the tool. As we are finding in our program of research, we believe this tool will have very broad appeal and will be very useful for the training of a large number of clinician scientists across a number of academic disciplines.

Of note, we followed the approach of developing the software (including a complete rewrite of the interface) among our co-authors before uploading to GitHub, thus there is a lower number of commits and a shorter history of the project there. 

We also note that we have also included the code that simulated the data for the included demo, which we had inadvertently missed, and which pushes our lines of code (LOC) greater than the 1,000 lines that may have generated a warning.

Finally, the manuscript is contained in the "joss-paper-branch" branch rather than the main branch. Please advise if these files should be moved.

Thank you for your consideration.

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by danielskatz** [comment]
Having the paper in a branch is fine

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.07 s (44.0 files/s, 16379.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                1            155            292            584
Markdown                         1             27              0             47
HTML                             1              0              0             13
-------------------------------------------------------------------------------
SUM:                             3            182            292            644
-------------------------------------------------------------------------------


Statistical information for the repository '1096d1f7853c4c22e6a80891' was
gathered on 2020/10/14.
No commited files with the specified extensions were found.
```

**Comment by danielskatz** [comment]
Note that whedon still sees 584 lines of R code

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02723/joss.02723/10.21105.joss.02723.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02723/joss.02723/10.21105.joss.02723.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
@whedon check references from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch joss-paper-branch
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/nar/gky1120 is OK
- 10.1038/s41591-018-0231-3 is OK
- 10.1016/j.outlook.2017.11.006 is OK
- 10.1177/1099800420915991 is OK
- 10.1177/1099800418772161 is OK
- 10.1177/1099800409336293 is OK
- 10.1111/jnu.12007 is OK
- 10.1016/j.cyto.2012.02.015 is OK
- 10.1016/j.jpainsymman.2016.08.004 is OK
- 10.1016/j.jpainsymman.2016.04.014 is OK
- 10.1002/0471142905.hg1806s71 is OK
- 10.1093/nar/gku1177 is OK
- 10.1093/nar/gkx1031 is OK
- 10.1093/nar/gkv1189 is OK
- 10.1093/nar/gky955 is OK
- 10.1086/519795 is OK
- 10.1097/GIM.0b013e31818fa2c7 is OK
- 10.3390/ijms21030768 is OK
- 10.1002/wsbm.144 is OK
- 10.1186/s12916-018-1122-7 is OK
- 10.1038/gim.2017.211 is OK
- 10.1056/NEJMp1500523 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
In the .bib file, all the "type = {Journal Article}" lines should be removed - whedon/pandoc is putting those into the paper, which is not needed.

**Comment by kordk** [comment]
All the "type = {Journal Article}" lines from paper.bib have been removed.

**Comment by danielskatz** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.03 s (100.0 files/s, 37275.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                1            155            292            584
Markdown                         1             27              0             47
HTML                             1              0              0             13
-------------------------------------------------------------------------------
SUM:                             3            182            292            644
-------------------------------------------------------------------------------


Statistical information for the repository '3730d044a0f6ec023f31455e' was
gathered on 2020/10/16.
No commited files with the specified extensions were found.
```

**Comment by danielskatz** [comment]
@kordk - Whedon still only sees 584 lines of code here.

> We also note that we have also included the code that simulated the data for the included demo, which we had inadvertently missed, and which pushes our lines of code (LOC) greater than the 1,000 lines that may have generated a warning.

**Comment by danielskatz** [comment]
@whedon generate pdf from branch joss-paper-branch

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper-branch. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02723/joss.02723/10.21105.joss.02723.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02723/joss.02723/10.21105.joss.02723.pdf) :page_facing_up: :point_left:

**Comment by kordk** [comment]
@danielskatz - The code has now been successfully pushed to the github repository and verified by eye.

**Comment by kordk** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (124.6 files/s, 34390.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                                1            155            292            584
TeX                              1             31              0            298
Markdown                         3             76              0            261
HTML                             2              9              0            226
-------------------------------------------------------------------------------
SUM:                             7            271            292           1369
-------------------------------------------------------------------------------


Statistical information for the repository '9483b6d126dc5b36333ce41b' was
gathered on 2020/10/16.
No commited files with the specified extensions were found.
```

**Comment by kyleniemeyer** [comment]
@kordk Unfortunately, the JOSS editors have decided that this submission does not meet the substantial scholarly effort criterion for review by JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
