### ISSUE TITLE
[REVIEW]: PyGDH ("pigged"): Python Grid Discretization Helper

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2744]
**Submitting author:** @kfhiga (<a href="http://orcid.org/0000-0003-4866-0748">Kenneth Higa</a>)
**Repository:** <a href="https://bitbucket.org/berkeleylab/esdr-pygdh/" target ="_blank">https://bitbucket.org/berkeleylab/esdr-pygdh/</a>
**Version:** 0.4.3
**Editor:** @melissawm
**Reviewer:** @JamieJQuinn, @zhaowei0566
**Archive:** <a href="https://doi.org/10.5281/zenodo.4556303" target="_blank">10.5281/zenodo.4556303</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/a5c27a933efb1e4dfa308059de26d0f2/status.svg)](https://joss.theoj.org/papers/a5c27a933efb1e4dfa308059de26d0f2)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/a5c27a933efb1e4dfa308059de26d0f2"><img src="https://joss.theoj.org/papers/a5c27a933efb1e4dfa308059de26d0f2/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/a5c27a933efb1e4dfa308059de26d0f2/status.svg)](https://joss.theoj.org/papers/a5c27a933efb1e4dfa308059de26d0f2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://bitbucket.org/berkeleylab/esdr-pygdh/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@JamieJQuinn & @zhaowei0566, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @melissawm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/berkeleylab/esdr-pygdh/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@kfhiga) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/berkeleylab/esdr-pygdh/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@kfhiga) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @JamieJQuinn, @zhaowei0566 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.11588/ans.2015.100.20553 is OK
- 10.1515/jnum-2012-0013 is OK
- 10.1109/MCSE.2009.52 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1109/MCSE.2010.118 is OK
- 10.1149/2.0091507jes is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02744/joss.02744/10.21105.joss.02744.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02744/joss.02744/10.21105.joss.02744.pdf) :page_facing_up: :point_left:

**Comment by melissawm** [comment]
👋🏼 @kfhiga @jamiejquinn @zhaowei0566 this is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#2744` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@melissawm) if you have any questions/concerns.

**Comment by kfhiga** [comment]
@melissawm <https://github.com/melissawm> @JamieJQuinn
<https://github.com/JamieJQuinn> @zhaowei0566
<https://github.com/zhaowei0566> Thank you all for your time!
Kenny

**Comment by JamieJQuinn** [comment]
Repo is on Bitbucket so couldn't link this repo directly. Added a few issues about installation on non-Debian systems.

**Comment by melissawm** [comment]
:wave: Hello all, just checking in to see if there's anything I can help you with.

**Comment by kfhiga** [comment]
Hi everyone and thanks for checking @melissawm. I've committed some changes
in response to the issues noted in the Bitbucket issue tracker. I should
probably have mentioned that here in case Bitbucket doesn't send
notifications on issue updates (sorry, still pretty new to this).

Thanks,
Kenny

**Comment by melissawm** [comment]
No problem! This is the first time I edit a submission that is not on github, so I'm new to this workflow as well. Glad to see things are ok, please ping me if there's any questions or comments. Thanks!

**Comment by JamieJQuinn** [comment]
I'm happy to accept this with a few changes, mostly to the documentation:

**Documentation:**
- I found the SPHINX annotations distracting; I imagine they would be very confusing to a new python user. Can these be removed from the examples in the documentation? I think they're fine in the actual example code.
- I don't think the full source code for each example is required in the documentation. It's easy enough for a user to grab  the examples from the repo. Additionally, it may help to shorten the length of the documentation file (which may be intimidating for new users).  Could the full example code be removed from the end of each section? 
- There's a statement at the end of page one of the documentation:
"*Users should be warned that although PyGDH has been successfully used in past and ongoing research products andis anticipated to be useful to others, it is still under development and should not be considered to be well-tested, stablesoftware.*"
I would expect some users to read this and be unsure about whether the results of code using pygdh can be trusted, however you've stated that the numpy solvers are used, which are very mature and well-tested. Additionally, you provide a number of examples with analytical comparisons so in my opinion, the code is well validated, if not widely verified through community use. Could this statement  be reworded to reflect that the code has been validated with test problems and uses a mature solver under the hood?
- I'd suggest changing section 3.3.1 so that it doesn't look so much like a full example. I personally followed that as if it were a functioning example only to find out there were parts missing. Perhaps this section could instead just describe the program structure without examples and then use the working example in 3.4 to illustrate those. The initial paragraph in 3.3.1 is sufficient in my opinion.

**Code:**
- The examples folder is very busy due to all the example code & outputs being in one single folder. Can these be split into one folder per example?
- I like the level of detail in what the code prints as it runs however it could be clearer what is an info statement, a warning, or an error. Could the difference between info, warnings and errors be made clearer, e.g. replacing statements like '! example error" with "ERROR: example error" and "INFO: creating domain"?

Otherwise I think this is a great package for an domain scientist who just wants some results without getting too deep into the nitty-gritty. As much as I feel I've torn apart the documentation (sorry!), it's a fantastic introduction for a new user, both to the software and to solving these kind of problems numerically. Similarly, the breadth of the provided examples in impressive and they seem to provide a comprehensive view of the problems solvable with pygdh.

**Comment by kfhiga** [comment]
Thank you for the detailed advice! I will get to work on these and let you
know when I've made the changes.
Kenny

**Comment by zhaowei0566** [comment]
Thank the authors @kfhiga  for sharing with the science community an open source code for studying time-dependent and nonlinear user-discretized equations on 0D, 1D, and simple 2D spatial domains using the finite volume method. This may be very useful for people, like me, working on unsteady aerodynamics. I don’t have questions about the technical stuff behind the code as they have been presented in the authors’ another publish work. The code is well written. I installed the code followings the steps using the code given in Downloads page and ran it successfully. The authors prepared a well-organized document. Thanks. I recommend to accept it with minor changes @melissawm  

1. Summary in the article

- Can you please name the software in the article before the reference, for example, “Many user-friendly open source packages,such as (J. E. Guyer & Warren,2009), and many commercial packages, such as (COMSOLAB,n.d.), (Siemens Digital Industries Software,n.d.),” before “as (J. E. Guyer & Warren,2009)” Could you please list the name so that readers do not need to go to reference to check what software you talked?

2. Suggestions:

- Please check citing.rst where you provided the link seems not correct, cannot redirect to a relevant paper (see Chapter Five in Document)
- In the main folder esdr-pygdh, there are three files related to license, just leave one of them to make the code as concise as possible, same for “README”
- Any plan to package them so that people can use pip install or conda install, etc.?

**Comment by melissawm** [comment]
Thank you all! Can I ask that you confirm (and tag me) once those suggestions have been made and both @zhaowei0566 and @JamieJQuinn are satisfied so we can move to acceptance?

**Comment by kfhiga** [comment]
Thank you, Wei and Melissa.

Wei thanks for the advice. I'll look into reducing the number of licensing
files, but if I remember correctly, the apparent redundancy was a
requirement from my institution as a condition for allowing the open source
release. I will look into the pip or conda packaging--another condition
from the U.S. Department of Energy is that we track the number of
downloads, which is done automatically on the Bitbucket download page, but
if pip or conda would handle that too, it would definitely be a possibility.

I'll let you know when I've completed the changes.

Thanks again,
Kenny

**Comment by melissawm** [comment]
Hello, all! Any updates, @kfhiga ?

**Comment by kfhiga** [comment]
Sorry @melissawm, things are moving a bit slowly here. I hope to get all of
the revisions finished within the next couple of weeks. Thanks for checking
up.
Kenny

**Comment by melissawm** [comment]
Hello, all! I see that all boxes are ticked at the reviewer's checklists. Do you have any pending issues to resolve before we move on? Can @kfhiga @JamieJQuinn @zhaowei0566 confirm if we are ready to go? :)

**Comment by kfhiga** [comment]
Hi @melissawm, sorry, still working on this, hope to have it finished this
week!
Thanks for checking:
Kenny

**Comment by kfhiga** [comment]
Hello @melissawm <https://github.com/melissawm> @JamieJQuinn
<https://github.com/JamieJQuinn> @zhaowei0566
<https://github.com/zhaowei0566>,

Thank you again for all of your suggestions. I believe that I've addressed
the recommendations and have committed the changes.

If accepted, I'd like to update the documentation with a link to the
article, along with acknowledgments for all of you, before making a final
commit, if possible. I'd then like to package that release or a later
release for pip and possibly conda and Debian, assuming that my management
clears this (I'm supposed to track download counts, so this might be a
concern).

I wasn't able to remove the redundant license files since I needed to meet
multiple specific requirements (for pip, from my management, etc.).

Thanks again for your help, and please let me know if you need further
changes. This was my first time going through a peer-review process for
software and I thought that it was a great learning experience.

Kenny

**Comment by JamieJQuinn** [comment]
@melissawm I'm happy accepting this. @kfhiga thatnks for your work addressing our concerns; this is a great piece of software!

Cheers,
Jamie

**Comment by kfhiga** [comment]
Thank you, @JamieJQuinn <https://github.com/JamieJQuinn>, and thank you for
all of your advice on improving the package! Hope you're all having a nice
holiday break.
Best regards,
Kenny

**Comment by zhaowei0566** [comment]
Thanks for taking care of my comments. I don't have any further. I recommend to accept the present version. Congratulations! @kfhiga @melissawm

**Comment by kfhiga** [comment]
Thank you, @zhaowei0566 <https://github.com/zhaowei0566>! Thank you for
your suggestions on the package as well. I'll check with my management to
see if they would support me making a pip release.
Happy new year!
Kenny

**Comment by melissawm** [comment]
Hello, @kfhiga ! The only remaining issue that I'm trying to check is the multiple license files. I'm checking if this is compatible with JOSS guidelines and how we can proceed to make sure this is resolved. I'll let you know as soon as I have an answer. Thanks for your patience!

**Comment by kfhiga** [comment]
Hello @melissawm <https://github.com/melissawm>, thank you and no hurry!
I'm grateful for all of the work that goes into running JOSS.
Best regards,
Kenny

**Comment by melissawm** [comment]
Hello, @kfhiga! Here's what I could gather. It would be best for you to have a single license file, and if other filenames are required either by packaging or legal concerns from your employer, these should be links to the unique license file. This way, we avoid redundancy and possible problems with different texts in different versions of these files. Do you think this would be a possible solution?

**Comment by kfhiga** [comment]
Hello @melissawm <https://github.com/melissawm>! Yes, I think that could
work. I'm a little unsure about how soft links created on a Linux system
will carry over to other systems once they're put into a repository, so
I'll try to run some tests on other systems and will get back to you soon.
Best regards,
Kenny

**Comment by kfhiga** [comment]
Hi @melissawm <https://github.com/melissawm>, I apologize for the delay. I
spoke with our licensing people, and they gave me permission to be more
flexible with the license file. So I've removed one file. And rather than
creating soft links, I've changed the documentation generation scripts to
generate the license and copyright pages from the other files in the
repository when they're needed.

I've kept the strategy of having template files that contain the license
and copyright information, except for the relevant years. Another script is
then used to generate the final license and copyright files with the
correct years (this is to make it easy to update the copyright year
information throughout the repository in future years).

I've made the changes and committed the updates. Will this arrangement work
for you?

Also, I'd like to update the acknowledgements and citation information
prior to committing the archival version of the repository.

Thanks!
Kenny

**Comment by kfhiga** [comment]
Hello @melissawm <https://github.com/melissawm>,

I thought so too, but was relieved to see that we had our license variant
approved:
https://opensource.org/BSD-3-Clause-LBNL

I've made the updates and pushed the changes. If you already know the
article citation details, I can add them to the citation page of the
documentation, but I'll otherwise just leave the link to JOSS in place.

Thank you!
Kenny

**Comment by melissawm** [comment]
I think that works, @kfhiga . I'll generate a new proof and I'll ask you to proofread and make sure things are as they should be. Thanks!

**Comment by melissawm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2744 with the following error:

**Comment by melissawm** [comment]
@whedon generate pdf

**Comment by melissawm** [comment]
Sorry @kfhiga - I didn't realize whedon had failed generating the pdf!

**Comment by kfhiga** [comment]
No worries, @melissawm <https://github.com/melissawm>! Let me know if you
need me to do anything.
Thanks,
Kenny

**Comment by whedon** [comment]
PDF failed to compile for issue #2744 with the following error:

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by arfon** [comment]
Looks like this line: https://bitbucket.org/berkeleylab/esdr-pygdh/src/b584ef0622ba8f6189e449dcfcbee9187bbdd3dd/joss/paper.bib#lines-46 is causing Whedon trouble.

Can you change it to `title={{Comsol Multiphysics ®}},`?

**Comment by whedon** [comment]
PDF failed to compile for issue #2744 with the following error:

**Comment by kfhiga** [comment]
Thanks for the tip, just made the change.
@whedon generate pdf

**Comment by melissawm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02744/joss.02744/10.21105.joss.02744.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02744/joss.02744/10.21105.joss.02744.pdf) :page_facing_up: :point_left:

**Comment by melissawm** [comment]
@kfhiga You have to make the command in a separate comment :)

@arfon thanks for the help!

**Comment by kfhiga** [comment]
Ah, thanks @melissawm <https://github.com/melissawm>, good to know. The
proof looks great!

And thanks again @arfon <https://github.com/arfon>, looks like that worked
out nicely.

Best regards,
Kenny

**Comment by melissawm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.11588/ans.2015.100.20553 is OK
- 10.1515/jnum-2012-0013 is OK
- 10.1109/MCSE.2009.52 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1109/MCSE.2010.118 is OK
- 10.1149/2.0091507jes is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by melissawm** [comment]
Hello @kfhiga, at this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by kfhiga** [comment]
Hello @melissawm <https://github.com/melissawm>,

I apologize for the delay, it took me a while to figure everything out.

I have put the annotated tag "0.4.3" on the most recent version of the
software in the Bitbucket repository.

It turns out that LBNL has a subscription to Dryad, so I have created a
dataset (https://doi.org/10.7941/D1Q33B) with the correct title and author
list. I've uploaded ZiP and TGZ archives of the software package, as well
as the documentation, through Dryad. As I understand it, Dryad actually
stores software uploads on a storage area on Zenodo that is directly linked
to the Dryad dataset.

Please let me know if you need anything further. Thank you!
Kenny

**Comment by melissawm** [comment]
Hello, @kfhiga - it seems like this DOI link is broken, can you check to see what's happening? Thanks!

**Comment by kfhiga** [comment]
Hello @melissawm <https://github.com/melissawm>,

Sorry for the inconvenience. I got in touch with Dryad, and turns out
that they prefer to have software-only archives go directly to Zenodo
rather than through their data curation process (where my submission
got stuck).

Here's the new DOI:

10.5281/zenodo.4556303

or hyperlink:

https://doi.org/10.5281/zenodo.4556303

Thank you!

Kenny

**Comment by melissawm** [comment]
Sorry for the delay, thanks for the information. I'll go through with acceptance.

**Comment by melissawm** [comment]
@whedon set 10.5281/zenodo.4556303 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4556303" target="_blank">10.5281/zenodo.4556303</a> is the archive.

**Comment by melissawm** [comment]
@whedon set 0.4.3 as version

**Comment by whedon** [comment]
OK. 0.4.3 is the version.

**Comment by melissawm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.11588/ans.2015.100.20553 is OK
- 10.1515/jnum-2012-0013 is OK
- 10.1109/MCSE.2009.52 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1109/MCSE.2010.118 is OK
- 10.1149/2.0091507jes is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2123

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2123, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1366792272264769536) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2124
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02744](https://doi.org/10.21105/joss.02744)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment]
Congratulations to @kfhiga (Kenneth Higa) and co-authors!!

And thanks to @JamieJQuinn and @zhaowei0566 for reviewing, and @melissawm for editing!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02744/status.svg)](https://doi.org/10.21105/joss.02744)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02744">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02744/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02744/status.svg
   :target: https://doi.org/10.21105/joss.02744
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02744/status.svg)](https://doi.org/10.21105/joss.02744)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by kfhiga** [comment]
Thank you everyone @JamieJQuinn <https://github.com/JamieJQuinn>
@zhaowei0566 <https://github.com/zhaowei0566> @melissawm
<https://github.com/melissawm>! This was my first time submitting an
article specifically for software, and it was a great experience. The open
and automated review and publishing process was really great to see too.
Thanks again!

Kenny
