### ISSUE TITLE
[PRE REVIEW]: Web-based text anonymization with Node.js: Introducing NETANOS (Named entity-based Text Anonymization for Open Science)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#283]
**Submitting author:** @ben-aaron188 (<a href="http://orcid.org/0000-0003-1658-9086">Bennett Kleinberg</a>)
**Repository:** <a href="https://github.com/ben-aaron188/netanos" target ="_blank">https://github.com/ben-aaron188/netanos</a>
**Version:** v1.1.0
**Editor:** @acabunoc
**Reviewer:** @RichardLitt

**Author instructions**

Thanks for submitting your paper to JOSS @ben-aaron188. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ben-aaron188 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @acabunoc it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#author_guidelines). In particular, this item:

> - Your software should have a research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)?

Many thanks!

**Comment by ben-aaron188** [comment]
@arfon Hi. Yes, our tool is written for the purpose of helping researchers share their text data. In the linguistic and content-based research field, a key reason why researchers don't post their data online (and hence refuse access to others) is that the data needs to be anonymized in order to protect the privacy of the participants who provided (or are mentioned in) the text data (e.g interviews). 
The research application is thus that our tool will be a step towards enabling researchers to finally share text data without the need of manual anonymization. Consequently, it will enable proper re-analyses, meta-analyses and other secondary analysis on data that otherwise is unaccessible to anybody other than the original researchers. Eventually, this could lead to a big boost towards open data in the text-based research community (i.e. comp. social science, psychology, linguistics).
Please do let me know if I can clarify this further.

**Comment by ben-aaron188** [comment]
@whedon From your reviewers list, suggestions might be: 
richardlitt (comp. linguistics + Javascript)
nuest (reprod. science + Javascript)

**Comment by acabunoc** [comment]
Hi @richardlitt & @nuest 👋 would either of you be up for reviewing this?

Review guidelines can be found here: http://joss.theoj.org/about#reviewer_guidelines

**Comment by RichardLitt** [comment]
I've partially reviewed the paper. Due to my current work circumstances (not on my main machine and traveling), I wasn't able to install Java to test out the install. I'll be able to do this in approximately 14 days when I am back with my work computer. I've added a reminder to my calendar to come back to this review at that time. 

In the meanwhile, I've raised three issues above which I feel ought to be met before this can be accepted. They're all relatively minor, I believe.

**Comment by arfon** [comment]
> I've partially reviewed the paper. Due to my current work circumstances (not on my main machine and traveling), I wasn't able to install Java to test out the install. I'll be able to do this in approximately 14 days when I am back with my work computer. I've added a reminder to my calendar to come back to this review at that time.

❤️ many thanks @RichardLitt. I'm going to move this over to an actual review issue so when you come back we can wrap this up.

**Comment by arfon** [comment]
@whedon assign @RichardLitt as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @RichardLitt

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/293. Feel free to close this issue now!
