### ISSUE TITLE
[PRE REVIEW]: wktmo: converting weekly data to monthly data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#284]
**Submitting author:** @leoly2017 (<a href="http://orcid.org/0000-0002-8506-8439">You Li</a>)
**Repository:** <a href="https://github.com/leoly2017/wktmo" target ="_blank">https://github.com/leoly2017/wktmo</a>
**Version:** 1.0.3
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @leoly2017. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@leoly2017 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by leoly2017** [comment]
Hello. Many thanks for your comment.

wktmo is an R package which converts weekly time series to monthly. This package, now available in CRAN (v1.0.3), is also included in CRAN task of Time Series Analysis. This is widely applied to researchers working with time series data, especially those working with data that are collected or aggregated on a weekly basis. 

For example, in human diseases surveillance, data are summarized and reported on a weekly basis but may further be utilized on a monthly basis. The dataset, weeklyFlu, in this package, is a surveillance dataset for global influenza by World Health Organization, WHO. Data are reported according to ISO week (ISO= International Organization for Standardization) but they need to be converted to monthly for further analysis and better comparison across years since the dates of a week vary across years. 

With wktmo, researchers can easily convert their raw weekly data to monthly data. Two common week counting methods are included in this package: ISO week and epidemiology week (epi week). ISO week is a widely-used week counting method in general. Epi week, also referred to as Center for disease control (CDC) week, is a common method for researchers in the field of disease surveillance.
More generally, users can specify the start date of the weekly time series if no week counting methods are used.

All in all, wktmo is a useful tool for researchers working with raw weekly data when cleaning and analyzing data. Please let me know if there is further question regarding the research application. Thank you.

**Comment by leoly2017** [comment]
And if possible, I would like to suggest @amoeba and/or @pboesu as the reviewer(s). Thank you.

**Comment by labarba** [comment]
In my opinion, this software classifies as a "utility" package, not research software. I don't think it is eligible for JOSS. We need to draw the line somewhere!

**Comment by arfon** [comment]
> In my opinion, this software classifies as a "utility" package, not research software. I don't think it is eligible for JOSS. We need to draw the line somewhere!

@labarba - I'm inclined to agree with you here. @leoly2017 - this seems like very generic utility-level software and isn't suitable for JOSS. Do you have any plans to extend the functionality of this package to make it more tailored to a particular research application?

**Comment by karthik** [comment]
I concur with @labarba and @arfon that this submission is not suitable for JOSS in the current form.

**Comment by arfon** [comment]
@leoly2017 - I've gone ahead and withdrawn this paper on your behalf.
