### ISSUE TITLE
@coatless comments: Docs

### ISSUE THREAD

**Issue by lrnv** [openjournals/joss-reviews#2867]
@coatless wrote:

Regarding code, the documentation governing the object slots is still a bit sparse. It would be good to understand what is being returned within the `Cort()` object explicitly.

That is, what do the following slot entries correspond to?

```
p_value_for_dim_red
number_max_dim 
min_node_size
verbose_lvl 
vols
f
p
a
b
data
dim
```

_Originally posted by @coatless in https://github.com/openjournals/joss-reviews/issues/2653#issuecomment-733910858_

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2867 with the following error: 

 Can't find any papers to compile :-(

**Comment by lrnv** [comment]
Error should not be there
