### ISSUE TITLE
[PRE REVIEW]: traceR: Profiling Framework for the R Language

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#288]
**Submitting author:** @ingo-k (<a href="http://orcid.org/0000-0002-0041-9894">Ingo Korb</a>)
**Repository:** <a href="https://github.com/allr/tracer" target ="_blank">https://github.com/allr/tracer</a>
**Version:** rolling release
**Editor:** @pjotrp
**Reviewer:** @kbroman

**Author instructions**

Thanks for submitting your paper to JOSS @ingo-k. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ingo-k if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#author_guidelines). In particular, this item:

> - Your software should have a research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)?

Many thanks!

**Comment by pjotrp** [comment]
Performance and research into performance definitely have application in research. I wish there was more of it. @ingo-k maybe it would be good to show an actual use case. Do you have anything?

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
@whedon assign @kbroman as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @kbroman

**Comment by pjotrp** [comment]
@ingo-k before we start review we would highly appreciate you make sure to tick the following boxes:

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="http://mutabit.com/repos.fossil/grafoscopio/">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (1.3.8)?
- [ ] **Authorship:** Has the submitting author (@offray) made major contributions to the software?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by pjotrp** [comment]
@janvitek we have a strange situation here. The submitter Ingo Kor of this paper has gone off github - do you know anything about this? I am writing you as a representative of https://github.com/allr. Can you advise us?

**Comment by pjotrp** [comment]
@arfon I suggest we close this issue. The author has gone away from github and is not responding. If the author comes back we can reopen it.

**Comment by arfon** [comment]
> @arfon I suggest we close this issue. The author has gone away from github and is not responding. If the author comes back we can reopen it.

Agreed.
