### ISSUE TITLE
[PRE REVIEW]: Riroriro: Simulating gravitational waves and calculating SNRs in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2899]
**Submitting author:** @wvanzeist (<a href="http://orcid.org/0000-0002-4231-656X">Wouter van Zeist</a>)
**Repository:** <a href="https://github.com/wvanzeist/riroriro" target ="_blank">https://github.com/wvanzeist/riroriro</a>
**Version:** v0.1.4
**Editor:** @dfm
**Reviewers:** @GregoryAshton, @katiebreivik
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @wvanzeist. **Currently, there isn't an JOSS editor assigned** to your paper.

@wvanzeist if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/1361-6404/aaf81e is OK
- 10.1103/PhysRevD.95.024038 is OK
- 10.1093/mnras/sty908 is OK
- 10.1103/PhysRevD.85.122006 is OK
- 10.1103/PhysRevD.52.605 is OK
- 10.1103/PhysRevD.67.024016 is OK
- 10.1088/0264-9381/24/19/S31 is OK
- 10.1103/PhysRevD.59.084006 is OK
- 10.1103/PhysRevD.65.044001 is OK
- 10.1103/PhysRevD.65.124012 is OK
- 10.1103/PhysRevX.4.031006 is OK
- 10.1017/pasa.2017.51 is OK
- 10.1093/mnras/sty1353 is OK
- 10.21105/joss.01987 is OK
- 10.1103/PhysRevLett.116.061102 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02899/joss.02899/10.21105.joss.02899.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02899/joss.02899/10.21105.joss.02899.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@wvanzeist since the core functionality appears to be under 1000 lines of code I have flagged this submission for an additional scope check by the editorial board. In particular our board will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. This is standard for submissions of this size. We should get back to you within about a week.

**Comment by kthyng** [comment]
Hi @wvanzeist, thanks for your submission. In discussion with the editorial board at JOSS, a question came up. Your package apparently implements a subset of what is in this package (bilby: https://github.com/lscsoft/bilby). Could you tell us what distinguishes your package from bilby? This is especially important since Riroriro is pretty small for lines of code.

**Comment by kthyng** [comment]
I'm keeping the scope query in place while we hear more about this submission, but I want to bring in @dfm who would be the likely handling editor.

**Comment by kthyng** [comment]
@whedon invite @dfm as editor

**Comment by whedon** [comment]
@dfm has been invited to edit this submission.

**Comment by danielskatz** [comment]
@whedon assign @dfm as editor

Thanks @dfm

**Comment by whedon** [comment]
OK, the editor is @dfm

**Comment by dfm** [comment]
@wvanzeist In case you missed it, please respond to @kthyng's [question above](https://github.com/openjournals/joss-reviews/issues/2899#issuecomment-747693470) when you get a chance. Thanks!

**Comment by wvanzeist** [comment]
> Hi @wvanzeist, thanks for your submission. In discussion with the editorial board at JOSS, a question came up. Your package apparently implements a subset of what is in this package (bilby: https://github.com/lscsoft/bilby). Could you tell us what distinguishes your package from bilby? This is especially important since Riroriro is pretty small for lines of code.

Thank you for your comment. Work on Riroriro actually began before Bilby was published, which is why we hadn't come across it in our initial literature review of gravitational wave models. Since it is a related package and notably open-source and in Python, I will add a mention about it in the Riroriro paper.

However, Riroriro's functionality is not the same as that of Bilby. Bilby and Riroriro approach the topic of gravitational waves from distinct, almost opposite ways: Bilby is focused on analysing and performing parameter estimation via Bayesian inference on gravitational wave strain data that the user has to input from detectors or other software like LALSimulation; while Riroriro models, simulates and outputs gravitational wave strain data itself (forward modelling) and can analyse this data in terms of detectability, and can also be used as an educational tool for students learning about gravitational waves.

Does that clarify the purpose of Riroriro?

**Comment by dfm** [comment]
@wvanzeist: Thanks for the info. This sounds good to me! Here at JOSS we're less interested in the educational angle, but I think that the forward modeling aspect is a good fit. Can you ping me once you've added a section clarifying this to the paper and then I'll start recruiting reviewers? This might be a little slow given the holidays but I'll keep you posted.

**Comment by wvanzeist** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02899/joss.02899/10.21105.joss.02899.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02899/joss.02899/10.21105.joss.02899.pdf) :page_facing_up: :point_left:

**Comment by wvanzeist** [comment]
@dfm Thanks! I have added a section to the paper to clarify this difference.

**Comment by wvanzeist** [comment]
Looking at the list of reviewers, the following people have both "gravitational waves" and "Python" as keywords and thus might be suitable: duncanmmacleod, johnveitch, cmbiwer.

**Comment by dfm** [comment]
@GregoryAshton has agreed to be a reviewer. Thanks Greg!

Once I've found a second reviewer, we'll get the review started.

**Comment by dfm** [comment]
@whedon add @GregoryAshton as reviewer

**Comment by whedon** [comment]
OK, @GregoryAshton is now a reviewer

**Comment by wvanzeist** [comment]
Are there any updates on the second reviewer?

**Comment by dfm** [comment]
@wvanzeist: Sorry about the delay! I have not yet recruited a second reviewer but I'll hopefully have an update soon. Thanks for your patience.

**Comment by dfm** [comment]
Thanks all for your patience! @katiebreivik has agreed to be our second reviewer. Thanks Katie!

I'll start the review shortly in a new thread and we'll continue there. As we go, please feel free to ask me any questions - I'm here to help this go smoothly!

**Comment by dfm** [comment]
@whedon add @katiebreivik as reviewer

**Comment by whedon** [comment]
OK, @katiebreivik is now a reviewer

**Comment by dfm** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2968.

**Comment by dfm** [comment]
We can head over to #2968 now for the main review.
