### ISSUE TITLE
[PRE REVIEW]: Simulated Physics and Environment for Autonomous Risk Studies (SPEARS)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#290]
**Submitting author:** @zmimlitz (<a href="http://orcid.org/0000-0001-5431-8362">Zac Mimlitz</a>)
**Repository:** <a href="https://github.com/Van-Bossuyt-Research-Lab/SPEARS_Simulator/" target ="_blank">https://github.com/Van-Bossuyt-Research-Lab/SPEARS_Simulator/</a>
**Version:** 3.0.5
**Editor:** @Kevin-Mattheus-Moerman
**Reviewer:** @agrignard

**Author instructions**

Thanks for submitting your paper to JOSS @zmimlitz. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@zmimlitz if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by kyleniemeyer** [comment]
@arfon I can probably take this, unless (e.g.) @Kevin-Mattheus-Moerman wants to.

**Comment by Kevin-Mattheus-Moerman** [comment]
I am quite swamped at the moment but will check briefly to see if I can find a reviewer here at MIT. Can the authors recommend any reviewers at this point? 

In the mean time (I gave this a super quick glance) could the authors expand the [readme](https://github.com/Van-Bossuyt-Research-Lab/SPEARS_Simulator/blob/master/README.md) to leave a few more bread crumbs for people to follow when they view the project. Here is an example of a more complete [readme](https://github.com/gibbonCode/GIBBON/blob/master/README.md). Perhaps directly link to the [wiki](https://github.com/Van-Bossuyt-Research-Lab/SPEARS_Simulator/wiki/How-to-Set-Up-the-Project) from the readme.md (rather than the GitHub page which is where readers already are). Can you also link to an actual license file in your repository? I recommend adding a graphical example / screen-shot if possible.

**Comment by zmimlitz** [comment]
Author here.  We have no one to recommended as a reviewer at this point but
would encourage that it should be someone with experience reading Java.  We
will reach out for possible reviewers and work on updating the readme file.

Thank you,

Zac Mimlitz
Colorado School of Mines
Chairman, Mines Council of the Arts
Capital Resources Manager, Blaster Hackers
Undergraduate Research Fellow, Van Bossuyt Group
Phone: 435-640-7827

**Comment by Kevin-Mattheus-Moerman** [comment]
I just found this: https://github.com/Van-Bossuyt-Research-Lab/SPEARS_Simulator/wiki/Running-a-Simulation
That link gives a much better impression on what the software does than the readme or paper. As I said please expand the readme and the paper on what the software is for and try to include graphical examples on how it is used. 
I'm waiting to hear back from potential reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
@AlexisDrogoul @rinde @eclab @alexlin0 at [JOSS](http://joss.theoj.org/) we are looking for reviewers for this submission. If [this work](https://github.com/Van-Bossuyt-Research-Lab/SPEARS_Simulator/) looks interesting to you and you are willing to [review](http://joss.theoj.org/about#reviewer_guidelines) for JOSS please let me know.

**Comment by Kevin-Mattheus-Moerman** [comment]
@agrignard is this your cup of tea? Are you available to review this submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by Kevin-Mattheus-Moerman** [comment]
@kyleniemeyer I got this

**Comment by zmimlitz** [comment]
Thank you Kevin

Zac Mimlitz

**Comment by Kevin-Mattheus-Moerman** [comment]
@Denz1994 @samreid @mattpen @agrignard @AlexisDrogoul @rinde @eclab @alexlin0 at [JOSS](http://joss.theoj.org/) we are looking for reviewers for this submission. If [this work](https://github.com/Van-Bossuyt-Research-Lab/SPEARS_Simulator/) looks interesting to you and you are willing to [review](http://joss.theoj.org/about#reviewer_guidelines) for JOSS please let me know.

**Comment by samreid** [comment]
Thanks for the invite @Kevin-Mattheus-Moerman, it sounds interesting but I don't have the time. Good luck!

**Comment by Kevin-Mattheus-Moerman** [comment]
@samreid okay. Thanks for getting back to me!

**Comment by kavonszadkowski** [comment]
Hi Kevin,

sorry to decline, but I don't think this fits my area of expertise well.

Cheers,

Kai

> @Denz1994 @samreid @mattpen @agrignard @AlexisDrogoul @rinde @eclab @alexlin0 @kavonszadkowski at [JOSS](http://joss.theoj.org/) we are looking for reviewers for this submission. If [this work](https://github.com/Van-Bossuyt-Research-Lab/SPEARS_Simulator/) looks interesting to you and you are willing to [review](http://joss.theoj.org/about#reviewer_guidelines) for JOSS please let me know.
>


-- 
  Kai von Szadkowski (M.Sc.)
  Space Robotics

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-6646
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:   kai.von-szadkowski@uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by Kevin-Mattheus-Moerman** [comment]
@kavonszadkowski okay. Thanks for letting us know.

**Comment by rinde** [comment]
Hi Kevin, 

Thanks for the invite, but I unfortunately don't have the time to do a review.

Cheers,
Rinde

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for your reply @rinde

**Comment by Kevin-Mattheus-Moerman** [comment]
@samreid do you know of any colleagues that you could recommend as reviewers for this submission?

**Comment by Kevin-Mattheus-Moerman** [comment]
@zmimlitz apologies for the delay encountered so far. We are doing are best to find reviewers for this submission. If you know of any please post their GitHub handles here. Also could you point me to relevant communities / groups you think I should look at?

**Comment by arfon** [comment]
👋 friendly reminder @zmimlitz to reply to @Kevin-Mattheus-Moerman's [comment](https://github.com/openjournals/joss-reviews/issues/290#issuecomment-318907992)

**Comment by zmimlitz** [comment]
My apologies for the long delay in response, I've been moving and starting
a new job over the last few weeks and life been a little hectic.  That
said, we have been reaching out to identify a potential reviewer and so far
come up short.  We'll continue to all around, and I'll see if anyone at my
new employer would be able to help, and let you know of we find someone.

Thank you,
Zac Mimlitz

On Sep 24, 2017 5:44 AM, "Arfon Smith" <notifications@github.com> wrote:

👋 friendly reminder @zmimlitz <https://github.com/zmimlitz> to reply to
@Kevin-Mattheus-Moerman <https://github.com/kevin-mattheus-moerman>'s
comment
<https://github.com/openjournals/joss-reviews/issues/290#issuecomment-318907992>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/290#issuecomment-331704553>,
or mute the thread

**Comment by agrignard** [comment]
Sure I am interesting to do that

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @agrignard as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @agrignard

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/434. Feel free to close this issue now!

**Comment by Kevin-Mattheus-Moerman** [comment]
@agrignard thanks for reviewing with JOSS! 

@zmimlitz We've started the review process over at #434. I'll close this pre-review issue.
