### ISSUE TITLE
[PRE REVIEW]: uDALES: large-eddy-simulation software for urban flow, dispersion, and microclimate modelling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2950]
**Submitting author:** @tomgrylls (<a href="http://orcid.org/0000-0002-0948-4932">Tom Grylls</a>)
**Repository:** <a href="https://github.com/uDALES/u-dales" target ="_blank">https://github.com/uDALES/u-dales</a>
**Version:** 1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @wimvanderbauwhede, @p-costa,  @ashwinvis
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @tomgrylls. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kyleniemeyer.

@tomgrylls if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.53 s (51.1 files/s, 19341.0 lines/s)
---------------------------------------------------------------------------------------
Language                             files          blank        comment           code
---------------------------------------------------------------------------------------
Fortran 90                              35           2973           3385          14709
MATLAB                                   4            572            841           3755
Markdown                                15            516              0           1305
Bourne Shell                            13            155             99            508
Python                                   3             67             61            140
CMake                                    3             40            101            125
YAML                                     3             17             13            123
TeX                                      1              2              0             31
Windows Module Definition                1              3              0              9
---------------------------------------------------------------------------------------
SUM:                                    78           4345           4500          20705
---------------------------------------------------------------------------------------


Statistical information for the repository '971269ea30b7d0a0420568e3' was
gathered on 2021/01/11.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Birgit Sutzl                     4          3509              3           11.60
Chiel                            3         11444           5722           56.72
Tom Grylls                       1            35             18            0.18
dmey                             6           278           9255           31.50

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Tom Grylls                   22           62.9          7.6                4.55
dmey                        246           88.5         12.3               22.76
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2950 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02950/joss.02950/10.21105.joss.02950.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02950/joss.02950/10.21105.joss.02950.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment]
@tomgrylls I'll be looking for an editor to handle this submission. In the mean time it would be great if you could help suggest reviewers for this work. Also can you please review our documentation on [what the paper should contain](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain), in particular the "Statement of need" section is missing. You can update the paper here by calling: `@whedon generate pdf`. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment]
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by tomgrylls** [comment]
@Kevin-Mattheus-Moerman<https://github.com/Kevin-Mattheus-Moerman> thanks for your email. If more editor suggestions would be helpful, I have been through the list and would suggest the following:

kyleniemeyer
wkearn
abhishekbajpayee
wkearn
mzamoraz

In terms of the statement of need, we have integrated this requirement into the main body of the text (from the end of the first paragraph) as we felt this helped the readability of the paper and thought that a section title would break the paper up. However, if having the statement of the need requirement within the text is insufficient then please let us know and we will add a separate section and heading.

Thanks,

Tom
________________________________

**Comment by tomgrylls** [comment]
To clarify, I meant reviewer suggestions not editors, sorry about that. If more suggestions would be helpful I have added more options to the list in my previous email:

jayten
corentin-dev
kyleniemeyer
wkearn
abhishekbajpayee
wkearn
mzamoraz
zbeekman
chennachaos
ashwinvis
adam-m-jcbs
rabernat
kegiljarhus
p-costa
ashwinvis

Thanks for your help and apologies for any confusion on the below,

Tom
________________________________

**Comment by Kevin-Mattheus-Moerman** [comment]
@leifdenby @jakubfabian @wimvanderbauwhede @crshapiro @tonyinme @claireverhulst @JuhaTonttila @fjansson would you be interested in reviewing this work for [the Journal of Open Source Software (JOSS)](https://joss.theoj.org/): uDALES: large-eddy-simulation software for urban flow, dispersion, and microclimate modelling?

The JOSS [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and focuses on [the software](https://github.com/uDALES/u-dales) and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.02950/joss.02950/10.21105.joss.02950.pdf).  This issue is a "pre-review" issue in which reviewers are assigned. Once sufficient reviewers are recruited we will open a dedicated review issue where the review will take place. [Here](https://github.com/openjournals/joss-reviews/issues/2831) is an example an ongoing review process to give you an idea. 

If you are interested in reviewing, you can comment here. Thanks!

**Comment by wimvanderbauwhede** [comment]
I am willing to review this work, but my current load at work is very high. How quickly does this need to be done?

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @wimvanderbauwhede that's great. We are hearing this from a lot of editors and reviewers at the moment so this is totally understandable. We usually aim for a 2 week review time but we can and have been very flexible especially in these challenging times. I'd say we will start the review within a week and the review will likely be ongoing for about 1-2 months (given peoples current time constraints) (although usually people submit minor initial comments right away given our open review process). Does that sound reasonable? Let me know what works for you.

**Comment by Kevin-Mattheus-Moerman** [comment]
@leifdenby @jakubfabian @crshapiro @tonyinme @claireverhulst @JuhaTonttila @fjansson would you be interested in reviewing this work for [the Journal of Open Source Software (JOSS)](https://joss.theoj.org/): uDALES: large-eddy-simulation software for urban flow, dispersion, and microclimate modelling?

The JOSS [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and focuses on [the software](https://github.com/uDALES/u-dales) and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.02950/joss.02950/10.21105.joss.02950.pdf).  This issue is a "pre-review" issue in which reviewers are assigned. Once sufficient reviewers are recruited we will open a dedicated review issue where the review will take place. [Here](https://github.com/openjournals/joss-reviews/issues/2831) is an example an ongoing review process to give you an idea. 

If you are interested in reviewing, you can comment here. Thanks!

**Comment by crshapiro** [comment]
Thank you for inviting me to review software for this innovative journal. Unfortunately, I don't have the time to commit to being a reviewer for something like this.

**Comment by Kevin-Mattheus-Moerman** [comment]
@leifdenby @jakubfabian @tonyinme @claireverhulst @JuhaTonttila @fjansson would you be interested in reviewing this work for the Journal of Open Source Software (JOSS): uDALES: large-eddy-simulation software for urban flow, dispersion, and microclimate modelling?

The JOSS review process takes place on GitHub and focuses on the software and a short paper. This issue is a "pre-review" issue in which reviewers are assigned. Once sufficient reviewers are recruited we will open a dedicated review issue where the review will take place. Here is an example an ongoing review process to give you an idea.

If you are interested in reviewing, you can comment here. Thanks!

**Comment by tonyinme** [comment]
Hey Kevin,

Thanks for the invite.
Unfortunately, I don't have the time to commit to this.

Thanks,
Tony

**Comment by Kevin-Mattheus-Moerman** [comment]
@crshapiro  @tonyinme thanks for the response. I understand regarding time. Please note that we are not expecting the usual quick turn around at the moment. Instead we can be very flexible and wait if you need quite a lot of time (some reviews take months at the moment). So given this, please let me know if you feel we could assign you but give you (lots of) extra time to complete this review at your own pace. All the best on your busy schedules and thanks for getting back to me.

**Comment by Kevin-Mattheus-Moerman** [comment]
@wimvanderbauwhede thanks for getting back to me. Many of us are under very unusual time constrains so as the message above shows we can be very flexible regarding time to complete this review. We can likely give you the time you need to complete this work at your own pace. Let me know if you can still help. Thanks again for getting back to me.

**Comment by wimvanderbauwhede** [comment]
Hi @Kevin-Mattheus-Moerman sorry for dropping this for a while. Yes, I'm still willing to help. I will try to have a look at this in the next two weeks.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @wimvanderbauwhede as reviewer

**Comment by whedon** [comment]
OK, @wimvanderbauwhede is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@claireverhulst @JuhaTonttila @fjansson @jayten @corentin-dev @zbeekman @ashwinvis @adam-m-jcbs @rabernat @p-costa would you be interested in reviewing this work for [the Journal of Open Source Software (JOSS)](https://joss.theoj.org/): uDALES: large-eddy-simulation software for urban flow, dispersion, and microclimate modelling?

Note we can give you a lot of additional time as we understand reviewers need extra flexibility at the moment. 

The JOSS [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) takes place on GitHub and focuses on [the software](https://github.com/uDALES/u-dales) and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.02950/joss.02950/10.21105.joss.02950.pdf).  This issue is a "pre-review" issue in which reviewers are assigned. Once sufficient reviewers are recruited we will open a dedicated review issue where the review will take place. [Here](https://github.com/openjournals/joss-reviews/issues/2831) is an example an ongoing review process to give you an idea. 

If you are interested in reviewing, you can comment here. Thanks!

**Comment by ashwinvis** [comment]
@Kevin-Mattheus-Moerman I am willing to take it up if I can take ~1 month to review the work.

**Comment by p-costa** [comment]
Hi @Kevin-Mattheus-Moerman, I am happy to review it if I can take about one month.

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @p-costa as reviewer

**Comment by whedon** [comment]
OK, @p-costa is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add  @ashwinvis as reviewer

**Comment by whedon** [comment]
OK,  @ashwinvis is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
Great we now have 3 reviewers and I'll initiate the review process. If others invited want to join I can add them in the review issue as well. Thanks a lot for agreeing to help!

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3055.

**Comment by zbeekman** [comment]
Sorry I missed this, my email inbox is a bit of an EPA superfund site at the moment. Looks very interesting, and I appreciate being thought of. Hopefully I'll have the chance to review some CFD for JOSS in the future!
