### ISSUE TITLE
[PRE REVIEW]: coxeter: A Python package for working with Shapes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3069]
**Submitting author:** @vyasr (<a href="http://orcid.org/0000-0001-5181-9532">Vyas Ramasubramani</a>)
**Repository:** <a href="https://github.com/glotzerlab/coxeter" target ="_blank">https://github.com/glotzerlab/coxeter</a>
**Version:** 0.5.0
**Editor:** @jni
**Reviewers:** @tmaric
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @vyasr. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @hugoledoux.

@vyasr if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.81 s (91.5 files/s, 69507.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
GLSL                             1              0              0          23239
JSON                             2              0              0          20304
Python                          42           1858           2938           5383
reStructuredText                13            191            103            408
Jupyter Notebook                 2              0            668            401
TeX                              2              7              0            294
Markdown                         6             55              0            169
YAML                             3             22              4            133
DOS Batch                        1              8              1             26
TOML                             1              0              0             10
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            74           2145           3721          50376
-------------------------------------------------------------------------------


Statistical information for the repository '9b6a244073b99d88502007bd' was
gathered on 2021/02/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Bradley Dice                   110          2820           1576            3.28
Brandon Butler                  17          2867           3249            4.56
Bryan VanSaders                 23          1565           1055            1.95
Corwin Kerr                      2             8              8            0.01
Eric Harper                      1          1825              0            1.36
Jens Glaser                      1         44855              0           33.42
M. Eric Irrgang                  2           863          44857           34.07
Tim Moore                        4            42             26            0.05
Tobias Dwyer                    40          1825            289            1.58
Tommy Waltmann                  17           334            247            0.43
Vyas Ramasubramani             432         15186          10375           19.05
Will Zygmunt                     1           129            200            0.25

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Bradley Dice               1213           43.0          7.2                9.98
Brandon Butler                1            0.0         17.7                0.00
Bryan VanSaders               1            0.1         53.3                0.00
Corwin Kerr                   6           75.0          1.6                0.00
Tim Moore                     1            2.4         12.8              100.00
Tobias Dwyer                491           26.9          4.0                3.87
Tommy Waltmann              153           45.8          0.6               14.38
Vyas Ramasubramani         8313           54.7          7.0               13.70
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03069/joss.03069/10.21105.joss.03069.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03069/joss.03069/10.21105.joss.03069.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1126/science.1220869 is OK
- 10.1016/j.commatsci.2019.109363 is OK
- 10.1103/PhysRevX.4.011024 is OK
- 10.1063/5.0019735 is OK
- 10.1038/nmat1949 is OK
- 10.1080/00268970601075238 is OK
- 10.1080/2151237X.2006.10129220 is OK
- 10.1021/acs.langmuir.7b02384 is OK
- 10.21105/joss.00787 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1039/C9SM00887J is OK
- 10.1109/MCSE.2018.05329813 is OK
- 10.1063/1.5052551 is OK
- 10.1103/PhysRevLett.107.135701 is OK
- 10.1073/pnas.1415467112 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment]
Hi @vyasr and thanks for your submission. The relevant editors for this submission are currently at full editorial load, so I am going to apply the waitlist label. Your paper will be picked up by an appropriate editor once they are available. Thank you for your patience.

**Comment by jni** [comment]
@kthyng I just finished my last review, and this is in my wheelhouse, so I'd be happy to take this on.

@vyasr if you have suggestions for reviewers that don't [have a conflict of interest per the JOSS guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy), please let us know!

**Comment by vyasr** [comment]
@jni thanks for touching base. Looking through the spreadsheet of reviewers @amritagos, @Jacob-Barhak, and @tmaric are three people who might be interested.

**Comment by Jacob-Barhak** [comment]
Hi Vyas,

This paper looks interesting - if you want my review - I will make it
publicly below

I read through, I saw many claims that the thing I missed most was an
example. If the Authors would give a simple example and show how they apply
their claims to it it will give a good idea to what they are doing.

Calculating volumes for examples has been practiced in CAD systems for many
years - algo using all sorts of constructions from primities with
techniques like CSG trees. I would not comprehend from the text why this is
such a difficult problem - perhaps if the authors show an example of why it
is difficult and how they do this efficiently, it would help. I could not
understand if shape generation is similar to CSG trees or something else.

I did not look at the code, not checked all the references.

I am curious to know how this can help biological modeling - if the simple
example can include this, it would be great.

Generally I like the idea of more python libraries for geometry - the more
the better.  I liked the idea of having a library of primitive shapes with
properties - if it is open to contributions, even better, in which case,
please provide information on how people can contribute.

More information on the paper will be great. Yet I also liked that it was
short and a quick read. So The authors will have to find a balance. Perhaps
links to examples may be a good solution here.


Jacob Barhak Ph.D.
https://sites.google.com/view/jacob-barhak/home

**Comment by jni** [comment]
@Jacob-Barhak thank you for jumping right in, but review hasn't started! :sweat_smile: I should have been more clear above. Review proceeds in a new issue where you would get a reviewer checklist, along with clear criteria for review. If you agree to be a reviewer, the guide is here

https://joss.readthedocs.io/en/latest/reviewer_guidelines.html
https://joss.readthedocs.io/en/latest/review_criteria.html

The review checklist, which again will appear in the issue as actual tick-boxes, is here:

https://joss.readthedocs.io/en/latest/review_checklist.html

JOSS reviews are focused on ensuring software functionality, proper documentation, and proper guidelines for community participation (bug reports, code contributions) in the software.

Given the above, please let me know if you would agree to review the paper; that would be wonderful!

@amitragos, @tmaric, would either of you be willing to help review this paper?

Thank you!

**Comment by whedon** [comment]
OK, the editor is @jni

**Comment by tmaric** [comment]
Sure, please include me as well.

**Comment by Jacob-Barhak** [comment]
So Juan,

You will find my opinion in the paper posted already. I will go no further
than this, especially after seeing the links you sent me.

You see, there is a difference between giving an opinion and performing
tests on a system to give it approval by guidelines one does not agree
with. You went a bit too far with those guidelines.

Especially I did not like the channeling of the license to OSI approved
licenses. You see OSI should no longer dictate licenses and I cannot find
myself in true conscience following their guidelines. I was once a member
of OSI, yet no longer can be affiliated. A few years ago they rejected CC0
as a license and I learned about it this year. This license is more open
than many of the copyright based licenses that OSI approves. In fact
the term open source is misleading and more restrictive if you follow some
of the licenses that OSI approves. I tried to bring it to debate within an
OSI conference without success.

You will find a discussion on the topic here:

Jacob. Barhak, Open Source and Sustainability, COMBINE 2020 October 5-9. Video:
https://drive.google.com/drive/folders/1actGnx6FwvoCcPrrF3qbnO0AmHt10WN6
starting from minute 13:10. Presentation:
*https://jacob-barhak.github.io/COMBINE2020_OpenSource_upload_2020_10_04.odp
<https://jacob-barhak.github.io/COMBINE2020_OpenSource_upload_2020_10_04.odp>*

This alone means I cannot abide by your guidelines that force an OSI
approved license.

However, I also looked at your Conflict of Interest statement - it seems
someone needs to look at the definition of conflict of interest. Conflict
of Interest is resolved by public declaration of the conflict - if the
review is public and non blind, this alone kind of removes the conflict of
interest since people can check. Therefore I am unclear why you
redefined it at all.

In fact, following OSI guidelines will put me in conflict of interest by
its true definition since I personally have potential monetary gains from
patents.

I also looked at your board members and found out that it includes at least
one person who did not support a public open review policy in the past
which I promote.

Finally, the BDFL title seems outdated - I actually raised an issue about
that.

Considering all those considerations I understand that your Journal is
going in the wrong direction. Your people may mean well, yet it seems they
do not comprehend the path this leads to. It is time to challenge this, and
this is what I am doing here.

Hopefully you will understand my hints and improve things -- I will also
raise the issue to NumFocus.

It is important those issues are discussed openly and publicly - I believe
things can still be remedied.

Jacob Barhak
Sole Proprietor

**Comment by jni** [comment]
@whedon assign @tmaric as reviewer

**Comment by whedon** [comment]
OK, @tmaric is now a reviewer

**Comment by jni** [comment]
@wolfv I wonder if as author of scikit-geometry you might be able/willing to review this submission? Please see [here](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) for our reviewer guide and feel free to ask below if you have any questions about the process. Essentially, the review is focused on ensuring functionality, documentation, and community around the software described by the paper. Thanks!

**Comment by Jacob-Barhak** [comment]
So Juan,

If this is not the proper venue please direct the discussion to the proper
venue. Hopefully a good public discussion can remedy things.

If you believe there is value in the venue, then the discussion
should continue somewhere to improve things - hopefully you have a
suggestion. If you cannot suggest one, since this venue triggered the issue
and it is public, it would be good enough. Yet I do hope you have a public
redirect to channel things properly.

Jacob

**Comment by jni** [comment]
Yeah I actually looked around for an appropriate forum but couldn't exactly find one. Our pre-submission enquiries go to https://github.com/openjournals/joss, so creating a new issue there is probably the best bet. I would recommend separate issues for CoI and license requirements discussions.

**Comment by Jacob-Barhak** [comment]
Thanks Juan,

The license issue is now listed here:
https://github.com/openjournals/joss/issues/889

The discussion should continue in that link.

The other issues are minor compared to this one. Hopefully it will gain
attention and will be resolved.

Thank you for redirecting

Jacob

**Comment by wolfv** [comment]
Hi @jni I'd be happy to help review this contribution.

**Comment by amritagos** [comment]
Hi @jni , thank you for nominating me but I'm a little too busy now and I would have decline.

**Comment by jni** [comment]
Awesome! Thank you @wolfv and no worries @amritagos thanks for getting back to us!

**Comment by jni** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3098.
