### ISSUE TITLE
[REVIEW]: root_numpy: The interface between ROOT and NumPy

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#307]
**Submitting author:** @ndawe (<a href="http://orcid.org/0000-0003-0202-3284">Edmund Dawe</a>)
**Repository:** <a href="https://github.com/scikit-hep/root_numpy" target ="_blank">https://github.com/scikit-hep/root_numpy</a>
**Version:** 4.7.2
**Editor:** @danielskatz
**Reviewer:** @wlav
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.842249" target="_blank">10.5281/zenodo.842249</a>

## Status

[![status](http://joss.theoj.org/papers/24bec5e49194ce7101eb9f6da5dd4db5/status.svg)](http://joss.theoj.org/papers/24bec5e49194ce7101eb9f6da5dd4db5)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/24bec5e49194ce7101eb9f6da5dd4db5"><img src="http://joss.theoj.org/papers/24bec5e49194ce7101eb9f6da5dd4db5/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/24bec5e49194ce7101eb9f6da5dd4db5/status.svg)](http://joss.theoj.org/papers/24bec5e49194ce7101eb9f6da5dd4db5)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/scikit-hep/root_numpy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@wlav, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @danielskatz know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/scikit-hep/root_numpy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (4.7.2)?
- [x] **Authorship:** Has the submitting author (@ndawe) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @wlav it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by danielskatz** [comment]
Ok, @wlav - this is ready to go.

Please carry out your review in this issue by updating the checklist above (please make sure you're logged in to GitHub)

The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Please avoid lengthy details of difficulties in this review thread. Instead, please create a new issue in the target repository and link to those issues (especially acceptance-blockers) in this review thread. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

Any questions/concerns, please let me know.

Thanks!!

**Comment by danielskatz** [comment]
@wlav - I see that you've checked off a bunch of thing, but not all of them.  Are the ones that are not checked items you are confirming?  Or have you been opening issues in https://github.com/scikit-hep/root_numpy/issues to discuss them (as it appears)?  If the latter, can you also put pointers to the review issues here so that others can look back and see the review progress?

**Comment by wlav** [comment]
Yes; there are several issues opened (mostly minor stuff except one or two). But @ndawe isn't back until July 27th, so waiting for that event. Will be soon enough.

This one is important: one item missing in the API reference that is exported with `__all__`
[https://github.com/scikit-hep/root_numpy/issues/332](url)

And this would be nice to have fixed/improved (error print, even if that is the 'ok' result for the test), but may be clunky to do:
[https://github.com/scikit-hep/root_numpy/issues/328](url)

There are three more issues that are no more than clarifications, and two where I misunderstood what was going on (e.g. build warnings coming from cython, not root_numpy).

**Comment by danielskatz** [comment]
@ndawe - any update from you on addressing the issues raised in the initial review?

**Comment by ndawe** [comment]
@danielskatz I've finally addressed the remaining issues:

https://github.com/scikit-hep/root_numpy/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3AJOSS%20

 @wlav is certainly welcome to open more if needed

**Comment by wlav** [comment]
@ndawe: I'm posting this whole thing even as it may be a bit pointless, but enough digging has gone into it. On the plus side, I now know everything there is to know about root_numpy ...

Anyway ...

I had a hard time trying to reproduce the performance plots in the paper. Initially, I got this:

![bench_tree2array_v6 06 02](https://user-images.githubusercontent.com/6372198/29198225-d0763f94-7df6-11e7-855d-9ab44bcf3d58.png)

Digging around, the two codes do essentially the same thing, but the setup of ROOT is heavier (because of generality), so that would explain the first part of the left plot as I found it. But for the second part, I don't see why root_numpy would be lagging. The cython generated code seems efficient enough as concerns the inner loop: there is no cython or python specific overhead in there.

For the right plot, it is all self consistent: if the overhead per entry (i.e. in the inner loop) is greater, the linear scaling factor will be higher. And indeed in both your and my case, the right follows the left.

So .... somewhere there was some per-call overhead left. Turns out, that the default root_numpy does not have the optimization flags on. I added -O3, et voila:

![bench_tree2array_v6 06 02_2](https://user-images.githubusercontent.com/6372198/29198975-7e43cffa-7dfd-11e7-8df9-15fdd7ef6aba.png)

Mind you, I have a slower disk (it's a 5 year old spinning one), so convergence as seen on the left is expected, and the relative overhead as seen on the right also expected to be less (but diverging in the same direction nonetheless).

You may want to guarantee that compiler optimizations are on when building root_numpy, or warn that they have not been when doing the benchmark. I'll file an issue on that one; do with it as you like.

Aside, instead of sysinfo (which didn't work for me as the ioctl call failed), I just read /proc/scsi/scsi, which does not require uid==0.

**Comment by danielskatz** [comment]
@wlav - thanks for this very interesting analysis.  We may need to create a new award for most thorough review :)

Are you asking for changes in the repo/paper regarding this, or is this more optional for the author: observation and feedback to improve the work, but not required for JOSS acceptance?

And, you did not check the References box in the checklist.  Is this because the scikit-learn and Tensor Flow references do not have DOIs?  Or something else?

**Comment by ndawe** [comment]
@wlav sees a closer match between ROOT and root_numpy leading me to suspect I have been comparing root_numpy with compiler optimisations enabled to ROOT without optimisation. I'll confirm and recreate the plot if needed.

**Comment by danielskatz** [comment]
thanks @ndawe  - can you also check to see if there are DOIs that should be added for the last 2 entries in the bib file associated with the paper, so we can check off that item as well?

**Comment by wlav** [comment]
@danielkatz: There's an arXiv for TensorFlow: abs/1603.04467 (https://arxiv.org/pdf/1610.06918.pdf; and no, I don't know why the numbers differ). I can't find a doi. The citation for scikit-learn is the way they want it (see: http://scikit-learn.org/stable/about.html).

**Comment by danielskatz** [comment]
Ok, given no DOI for either, I think you can check off the references item, since "all archival references that should have a DOI" do list one; the ones that don't can't since there isn't one.

**Comment by wlav** [comment]
Great, all done! :)

**Comment by danielskatz** [comment]
@ndawe, please let me know when you are satisfied with the state of the documentation and plot (as discussed by you and @wlav above).  If you need to make changes, please do.

Then we can go ahead and accept this, once you say you are ready.

**Comment by ndawe** [comment]
Sure, thanks. I've recreated the benchmark plot after updating to the latest ROOT and with both root_numpy and ROOT compiled with -O2. The diff is here and you can see a slightly closer match:

https://github.com/scikit-hep/root_numpy/pull/346/files

Merging that now. Thanks @wlav for the thorough review!

**Comment by ndawe** [comment]
All good on my end

**Comment by danielskatz** [comment]
Thanks again @wlav for a very nice review, and @ndawe for your updates.

@arfon - this is ready to go to you now.

**Comment by arfon** [comment]
@ndawe - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by ndawe** [comment]
@arfon I've posted a new release on Zenodo: https://zenodo.org/record/842249

DOI: http://doi.org/10.5281/zenodo.842249

The codemeta.json is also updated

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.842249 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.842249" target="_blank">10.5281/zenodo.842249</a> is the archive.

**Comment by arfon** [comment]
@wlav - many thanks for your review here and to @danielskatz for editing this submission ✨ 

@ndawe - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00307 ⚡️ 🚀 💥

**Comment by ndawe** [comment]
@arfon the figure referencing seems to be broken on the web version of the paper ("... as shown in Figure ." and no "Figure #" with the caption). Can this be fixed?

**Comment by arfon** [comment]
@ndawe - apparently this is a known issue with Pandoc --> HTML conversion (https://stackoverflow.com/questions/9434536/how-do-i-make-a-reference-to-a-figure-in-markdown-using-pandoc).

If you can modify the language of the text to not directly cite the figure I can recompile the documents and update them.

**Comment by ndawe** [comment]
Thanks @arfon I've updated the text to remove the reference

**Comment by arfon** [comment]
OK thanks @ndawe. I've updated the PDF and web-version of the paper.
