### ISSUE TITLE
[PRE REVIEW]: imea: A Python package for extracting 2D and 3D shape measurements from images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3072]
**Submitting author:** @nilskroell (<a href="http://orcid.org/0000-0002-6016-5144">Nils Kroell</a>)
**Repository:** <a href="https://git.rwth-aachen.de/ants/sensorlab/imea" target ="_blank">https://git.rwth-aachen.de/ants/sensorlab/imea</a>
**Version:** v0.2.2
**Editor:** @mbobra
**Reviewers:** @Atif-Anwer, @tuelwer
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @nilskroell. **Currently, there isn't an JOSS editor assigned** to your paper.

@nilskroell if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.30 s (39.6 files/s, 13243.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           7            557            752            890
Markdown                         2             66              0            197
TeX                              1             34              0            168
Jupyter Notebook                 2              0           1241            107
-------------------------------------------------------------------------------
SUM:                            12            657           1993           1362
-------------------------------------------------------------------------------


Statistical information for the repository 'a7e7eda1426829055c5a5940' was
gathered on 2021/02/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Nils Kroell                     49          3725           3565           76.36
nkroell                          3          2148            109           23.64

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Nils Kroell                2199           59.0          0.1               12.73
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1016/j.mineng.2011.10.001 is OK
- 10.1016/j.wasman.2020.11.003 is OK
- 10.1016/j.ces.2013.02.043 is OK
- 10.1063/5.0002233 is OK
- 10.1109/IEMBS.2005.1617159 is OK
- 10.1016/s0165-0270(96)00080-5 is OK
- 10.1016/j.patrec.2017.08.022 is OK
- 10.1016/j.wasman.2020.09.033 is OK
- 10.7717/peerj.453 is OK
-  10.25080/Majora-92bf1922-00a is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03072/joss.03072/10.21105.joss.03072.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03072/joss.03072/10.21105.joss.03072.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment]
👋 @nilskroell - Due to the relatively small size of this code, the JOSS editors will now examine if this submission meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS.

**Comment by danielskatz** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by nilskroell** [comment]
Hi @danielskatz, thanks for your fast reply! 

To give you and the editorial board more context on the scholary effort that was required to develop imea, I would like to add the following four points, which are difficult to be discovered from the repository and LOC:

- A substantial scholary effort was applied by conducting a thorough literature review to identify and select all relevant shape measurements proposed and used in scientific literature.
- Determining 2D and 3D shape measurements of arbitrary shapes takes a lot of computational effort, as for example statistical lengths need to be determined at various rotation angles. A lot of time and effort has thus been invested to find and test the most computational efficient implementation. To ensure a clear structure and good maintainability, only the fastest and clearest implementations were integrated in imea.
- Instead of implementing all shape measurements from ground up, a lot of time and effort has been invested to identify existing implementations. Identified implementation has then been extensively tested on various shapes and evaluated. As a result, only the implementations from scikit-image and open-cv have been found suitable and are thus integrated in imea – saving additional LOC and making maintaining imea easier.
- In a previous project, I had invested a lot of effort in implementing various 3D shape measurements in MATLAB, which could then be reformulated for imea and implemented in a rather short time.

For our department and project partners, imea has already been extremely useful in extracting shape measurements in various projects in the short time since it was available for internal validation. Several research publications where imea was used for data extraction are already in preparation. An inclusion of imea into JOSS would help me a lot in making imea more visible for other researchers and citable in upcoming publications.
I look forward to your decision. If you need any additional information – do not hesitate to ask me, I am happy to reply.

Best regards,
Nils

**Comment by danielskatz** [comment]
This has passed the scope check

**Comment by danielskatz** [comment]
👋 @mbobra - would you be able to edit this submission?

**Comment by danielskatz** [comment]
@whedon invite @mbobra as editor

**Comment by whedon** [comment]
@mbobra has been invited to edit this submission.

**Comment by mbobra** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @mbobra

**Comment by mbobra** [comment]
@nilskroell Thank you for your submission! Please give me a week to find some reviewers (I am tied up until the day after tomorrow, but will search for reviewers after that). 

If you have any suggested reviewers, please let me know here (you can give me the Github handle without @ mentioning them, e.g. mbobra instead of @mbobra).

**Comment by nilskroell** [comment]
@danielskatz : Thanks a lot for the fast decision. I'm glad that imea fits the scope of JOSS.

@mbobra : Thanks a lot for taking the time to edit this submission and the clear and fast communication.

Based on the provided [list of potential reviewers](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822) I can suggest the following reviewers:

- **tuelwer**: expertise in image processing, machine learning, computer vision and data science
- **macrocosme**: expertise in image processing and visualization
- **PingjunChen**: expertise in biomedical image analysis and machine learning
- **Atif-Anwer**: expertise in image processing and computer vision
- **lbugnon**: expertise in image processing and machine learning

All suggested reviewers are familiar with Python, have currently no active reviews (as indicated in the list) and have at least one time reviewed for JOSS before. I also made sure, that none of them is working at the same university as I am and that the suggested reviewers come from different fields. However, there are many more potential reviewers with expertise in image processing & Python in the list which could be included. If you need more suggestions @mbobra feel free to contact me.

**Comment by Atif-Anwer** [comment]
Hi! 

I've looked at the repo as well as the draft submission and I would be glad to review the submission. However before committing, I would like to ask about the deadline/timeline available for the review; since I am myself teaching this semester etc. I would hopefully be able to review it in a couple of weeks approximately; testing out the package and etc. If that is ok with JOSS's timeline, then I will be glad to formally accept as reviewer on the JOSS pre-review thread. 
(@mbobra I tried to reply to your email; but the server rejected my email as spam so I figured i'll post here directly)

**Comment by mbobra** [comment]
@Atif-Anwer Thank you so much for your reply (and persistence)! I'm sorry about the spam filter (I will look into it).

JOSS is operating on a reduced service mode (see [here](https://blog.joss.theoj.org/2020/05/reopening-joss)) so we're giving reviewers six weeks to complete their review. This is not a hard deadline, though, so if you need an additional week or so that's fine. Is this okay with you? If so, I'll go ahead and assign you as a reviewer.

**Comment by Atif-Anwer** [comment]
Six weeks is ample time. Ill be able to do it before that for sure. Thanks!

**Comment by mbobra** [comment]
@whedon assign @Atif-Anwer as reviewer

**Comment by whedon** [comment]
OK, @Atif-Anwer is now a reviewer

**Comment by mbobra** [comment]
@whedon add @tuelwer as reviewer

**Comment by whedon** [comment]
OK, @tuelwer is now a reviewer

**Comment by mbobra** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3091.

**Comment by mbobra** [comment]
@Atif-Anwer @tuelwer See you over in #3091 where the review will take place!
