### ISSUE TITLE
[PRE REVIEW]: Defect Detection and Quantification Toolbox (DDQT)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3186]
**Submitting author:** @arunmano121 (<a href="http://orcid.org/0000-0003-2446-5008">Arun Manohar</a>)
**Repository:** <a href="https://github.com/arunmano121/DDQT" target ="_blank">https://github.com/arunmano121/DDQT</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @arunmano121. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @sbenthall.

@arunmano121 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (139.5 files/s, 18381.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           3            294            471            575
reStructuredText                 9            131             21            364
TeX                              1             11              0            106
Markdown                         1             13              0             67
DOS Batch                        1              8              1             26
make                             1              4              7              9
-------------------------------------------------------------------------------
SUM:                            16            461            500           1147
-------------------------------------------------------------------------------


Statistical information for the repository '5eff2b170fa10f2126cecd28' was
gathered on 2021/04/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
AM                              10         16191          14851          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
AM                         1340            8.3          0.6               16.87
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03186/joss.03186/10.21105.joss.03186.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03186/joss.03186/10.21105.joss.03186.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1016/j.addma.2018.04.005 may be a valid DOI for title: Application of supervised machine learning for defect detection during metallic powder bed fusion additive manufacturing using high resolution imaging.
- 10.1109/tim.2004.834070 may be a valid DOI for title: PCA-based feature selection scheme for machine defect classification
- 10.1364/ao.54.002963 may be a valid DOI for title: Unsupervised defect detection in textiles based on Fourier analysis and wavelet shrinkage
- 10.2307/2986224 may be a valid DOI for title: Appropriate critical values when testing for a single multivariate outlier by using the Mahalanobis distance
- 10.5121/ijdkp.2015.5201 may be a valid DOI for title: A review on evaluation metrics for data classification evaluations

INVALID DOIs

- None
```

**Comment by kyleniemeyer** [comment]
Hi @arunmano121, thanks for your interest in JOSS. Due to the relatively small size of your submission, the editors are going to review your submission to see if it meets our requirements for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). You should hear back in a week or so.

**Comment by kyleniemeyer** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by arunmano121** [comment]
Hello,

Here is a list of possible reviewers;
1) ngoiz
2) satish-annigeri
3) corentin-dev
4) e-dub
5) PaulDebus
6) Jesusbill
7) vsangelidakis

Thank you.


On Apr 16, 2021, at 5:31 PM, whedon ***@***.******@***.***>> wrote:



Submitting author: @arunmano121<https://github.com/arunmano121> (Arun Manohar<http://orcid.org/0000-0003-2446-5008>)
Repository: <https://github.com/arunmano121/DDQT> https://github.com/arunmano121/DDQT
Version: v0.1.0
Editor: Pending
Reviewer: Pending
Managing EiC: Kyle Niemeyer

⚠️ JOSS reduced service mode ⚠️

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in our blog post<https://blog.joss.theoj.org/2020/05/reopening-joss>.

Author instructions

Thanks for submitting your paper to JOSS @arunmano121<https://github.com/arunmano121>. Currently, there isn't an JOSS editor assigned to your paper.

The author's suggestion for the handling editor is @sbenthall<https://github.com/sbenthall>.

@arunmano121<https://github.com/arunmano121> if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, this list of people<https://bit.ly/joss-reviewers> have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

Editor instructions

The JOSS submission bot @whedon<https://github.com/whedon> is here to help you find and assign reviewers and start the main review. To find out what @whedon<https://github.com/whedon> can do for you type:

@whedon commands

**Comment by arfon** [comment]
Thanks for your submission to JOSS. After consulting with the JOSS editorial team, we've determined that this work is out of scope for JOSS as it falls into our [minor utility category](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements). 

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
