### ISSUE TITLE
[PRE REVIEW]: SenSARP: A Python package for pre-processing Sentinel-1 SLC data with the Sentinel-1 Toolbox

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3198]
**Submitting author:** @McWhity (<a href="http://orcid.org/0000-0001-5278-8379">Thomas Weiß</a>)
**Repository:** <a href="https://github.com/multiply-org/sar-pre-processing.git" target ="_blank">https://github.com/multiply-org/sar-pre-processing.git</a>
**Version:** 0.1
**Editor:** @pdebuyl
**Reviewers:** @arthur-e, @braunfuss
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @McWhity. **Currently, there isn't an JOSS editor assigned** to your paper.

@McWhity if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.14 s (319.7 files/s, 33004.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
XML                              4              7              0            983
reStructuredText                11            253             80            820
Python                          10            257            347            813
YAML                            10             39             47            314
make                             1             28              6            143
Markdown                         3             40              0            107
Jupyter Notebook                 1              0            274             75
TeX                              1              8              0             73
Bourne Shell                     2              1              0             24
HTML                             1              1              0              6
DOS Batch                        1              0              0              2
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            46            634            754           3361
-------------------------------------------------------------------------------


Statistical information for the repository '3f03b35030edf151abf3af40' was
gathered on 2021/04/21.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
McWhity                         47          3004           1755           67.12
Thomas Weiß                     62           457            432           12.54
Tonio Fincke                    39           764            634           19.72
TonioF                           9            27             17            0.62

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Thomas Weiß                1114          243.8         30.1               23.52
Tonio Fincke                303           39.7         16.1                4.62
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03198/joss.03198/10.21105.joss.03198.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03198/joss.03198/10.21105.joss.03198.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.3390/rs10081286 is OK
- 10.3390/w11091938 is OK
- 10.3390/rs12183037 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon query scope 

@McWhity – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. We should get back to you sometime next week.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by danielskatz** [comment]
@McWhity – Can you explain how reusable this software is?  It seems very specific to one function/one satellite.

**Comment by McWhity** [comment]
Right now the software is limited one satellite type (Sentinel-1). Currently two identical Sentinel-1 satellites are in orbit (S1-A since 2014 and S1-B since 2016) and provide free available microwave data of the entire world every 6 days. The satellites were designed with a lifetime of 7 years (12 years for consumables). To ensure continuous monitoring after the lifetime of S1-A and S1-B two new Sentinel-1 satellites (S1-C and S1-B) are in development and there are planned to be launched in 2022. The figure below shows the expected data volume growth by the Sentinel-1 satellites. Although the software is currently limited to one type of satellite it can be used at least until the end of this century.

![image](https://user-images.githubusercontent.com/25958669/118396892-e1b0d200-b651-11eb-9949-45bcfd1177e1.png)
Hahmann, Thomas, et al. "Sentinel-1 and Sentinel-3-OLCI PAC at DLR." Proceedings of ESA Living Planet Symposium. 2013.

The software in its current form produces a set of four different radiometric and geometric corrected sigma nought radar backscatter data.  For time series/or single time step usage:
1) multi temporal speckle filtered data
2) multi temporal speckle filtered data from different orbits normalized to one specific incidence 
3) single speckle filtered data
4) single speckle filtered data normalized to one specific incidence angle

This software as a standard pre-processing scheme can be used by non expert (pre-processing) users to process Sentinel-1 data and use it for there purposes.
Expert users can easily modify the default xml-graphs (adjusting of the different processing steps for there purposes) via SNAP toolbox and use the software functions to process there data. An upload of further xml-graphs will enhance the functional scope of this software.

The “Step Forum” (https://forum.step.esa.int/search?q=pre%20processing%20Sentinel-1) shows an active community discussing how to best pre-process Sentinel-1 data.
The ReadTheDocs document of this software is used in discussions of the Step Forum (e.g. https://forum.step.esa.int/t/backscatter-normalization-to-a-pre-defined-incidence-angle-for-s-1-grd-hh-channel-data/6949/8
https://forum.step.esa.int/t/help-with-clarifying-radiometric-normalization-of-full-scene-wide-swath-incidence-angle-effects/13894)

**Comment by kyleniemeyer** [comment]
@McWhity Thanks for your patience. We are going to move forward with reviewing your submission, and @pdebuyl has already volunteered to edit the submission (thanks!).

**Comment by kyleniemeyer** [comment]
@whedon invite @pdebuyl as editor

**Comment by whedon** [comment]
@pdebuyl has been invited to edit this submission.

**Comment by pdebuyl** [comment]
@whedon invite me as editor

**Comment by whedon** [comment]
I'm sorry @pdebuyl, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by pdebuyl** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @pdebuyl

**Comment by pdebuyl** [comment]
@McWhity you can propose referees here if you like, that I may consider in addition to the volunteer reviewers who have registered for JOSS (without the @ sign else they will receive many notifications).

**Comment by pdebuyl** [comment]
@kmarkert @arthur-e would you review the article "SenSARP: A Python package for pre-processing Sentinel-1 SLC data with the Sentinel-1 Toolbox" for the Journal of Open Source Software?

**Comment by arthur-e** [comment]
@pdebuyl Yes, I will review this paper. This would be my first review for JOSS, so let me know if there's anything else I should know beyond what's in the [reviewer guidelines](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html).

**Comment by pdebuyl** [comment]
Hi @arthur-e thank you for accepting to review! The page [review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html) is more complete than the guidelines. The [checklist](https://joss.readthedocs.io/en/latest/review_checklist.html) is also useful, but you will see it when the review starts anyway.

During the review, communication with the authors or with me goes through the review page, so that you can ask for clarifications as needed.

**Comment by arthur-e** [comment]
@pdebuyl One thing that's not clear to me from the Reviewer Guidelines is who is responsible for creating the "[REVIEW]" Issue in `joss-reviews`. I can see the example in #1075, but it would be nice to have the markdown version of that checklist. Also, can you provide me a timeline for the review? Thanks!

The guidelines are very thorough about substance or conduct of the review, but I just can't find the logistical details about how to start one.

**Comment by pdebuyl** [comment]
Hi @arthur-e I will create the "REVIEW" issue when I have a second reviewer. There will be an explanation there and the checklist will be created automatically.

**Comment by pdebuyl** [comment]
@alexamici would you review the article "SenSARP: A Python package for pre-processing Sentinel-1 SLC data with the Sentinel-1 Toolbox" for the Journal of Open Source Software?

**Comment by alexamici** [comment]
@pdebuyl I'm totally new to the open access journals, so it appears an interesting thing to do, but I need just a bit to figure out what it means.

**Comment by pdebuyl** [comment]
Hi @alexamici thank you for getting back to me. I'll summarize the principles here:
- The journal is free to publish in and free to read (CC-BY licenses). JOSS is published by "Open Journals" and directly managed by its community.
- The papers in JOSS are short (few pages long max): the focus is on the software. For well built packages (with good documentation, tests, examples, etc) the JOSS paper is a small effort to recognize the software effort.
- Reviews take place publicly on github. You can have a look at ongoing reviews here: https://github.com/openjournals/joss-reviews/issues?q=is%3Aissue+is%3Aopen+label%3Areview
- There is a [review checklist](https://joss.readthedocs.io/en/latest/review_checklist.html) which serves as a guideline.
- Reviewers are expected to install the code and run a few examples to assess its usability.

During the review, you are free to discuss with the authors and the editor via the corresponding github issue page. We have author, reviewer, and editor guidelines on our website https://joss.readthedocs.io/en/latest/index.html

I'll be happy to reply to your questions.

**Comment by pdebuyl** [comment]
Hi @alexamici I see a thumbs up on my last message, does that mean that you agree to perform the review?

**Comment by pdebuyl** [comment]
@whedon assign @arthur-e as reviewer

**Comment by whedon** [comment]
OK, @arthur-e is now a reviewer

**Comment by alexamici** [comment]
> Hi @alexamici I see a thumbs up on my last message, does that mean that you agree to perform the review?

The thumb-up was "OK, I'm going to study" :)

Thank you for considering me, I like the idea very much, but in the last couple of days my schedule exploded and unfortunately I'm not able to accomodate any additional commitment in the short term, not even what looks like a lightweight one. Sorry.

I will register as a reviewer anyhow and I'm happy to try and participate to reviews in the future.

**Comment by pdebuyl** [comment]
Thanks for the reply @alexamici , I understand the time consideration, and for registering as a reviewer!

**Comment by pdebuyl** [comment]
@McWhity any recommendation for a reviewer?

**Comment by McWhity** [comment]
I don't know the person but maybe Andreas Steinberg (https://github.com/braunfuss) would be a good candidate. He worked with the Sentinel-1 Toolbox and he has some open-source software publications (https://www.bridges.uni-kiel.de/en/team/andreas-steinberg?set_language=en)

**Comment by McWhity** [comment]
Another possible candidate might be Pete Bunting (https://github.com/petebunting). He has also some experience in processing Sentinel-1 as well as other Earth Observation data (https://github.com/remotesensinginfo)

**Comment by pdebuyl** [comment]
Thanks @McWhity

**Comment by pdebuyl** [comment]
@whedon add @braunfuss as reviewer

**Comment by whedon** [comment]
OK, @braunfuss is now a reviewer

**Comment by pdebuyl** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3337.
