### ISSUE TITLE
Submission: Advanced viewshed analysis: a Quantum GIS plug-in for the analysis of visual landscapes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#32]
**Submitting author:** @zoran-cuckovic (<a href="http://orcid.org/0000-0001-7626-4086">Zoran Čučković</a>)
**Repository:** <a href="https://github.com/zoran-cuckovic/QGIS-visibility-analysis" target ="_blank">https://github.com/zoran-cuckovic/QGIS-visibility-analysis</a>
**Version:** 0.5.1
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.59896" target="_blank">10.5281/zenodo.59896</a>

## Status

[![status](http://joss.theoj.org/papers/a8f76eeda4f92e7d641757dd0d7ed7f5/status.svg)](http://joss.theoj.org/papers/a8f76eeda4f92e7d641757dd0d7ed7f5)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/a8f76eeda4f92e7d641757dd0d7ed7f5"><img src="http://joss.theoj.org/papers/a8f76eeda4f92e7d641757dd0d7ed7f5/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/a8f76eeda4f92e7d641757dd0d7ed7f5/status.svg)](http://joss.theoj.org/papers/a8f76eeda4f92e7d641757dd0d7ed7f5)
```

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/zoran-cuckovic/QGIS-visibility-analysis">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (0.5.1)?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00032.pdf](https://github.com/openjournals/joss-reviews/files/332396/10.21105.joss.00032.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by zoran-cuckovic** [comment]
Hello!

To test my software all you need is to install the plugin into QGIS from the official repository (as any other standard plugin). The current version (submitted here ) has some 1000 dowlands - without particular errors reported.

**Comment by arfon** [comment]
Hi @zoran-cuckovic - it seems like we're struggling a little to find a reviewer for this package. Please feel free to reach out to people in your community and see if they're willing to help out 😄

**Comment by labarba** [comment]
@zoran-cuckovic — Can you recommend any distribution list where we may ask for help reviewing your submission? I made a call via Twitter:
https://twitter.com/lorenaabarba/status/748864879902195712
... which got retweeted by The Open Source Geospatial Foundation to their 13.9K followers. Yet no one has come forward.
I also targeted someone, but he said it is not his expertise:
https://twitter.com/lorenaabarba/status/748895404578701312

And today, I asked for help with 
https://twitter.com/lorenaabarba/status/750817953440997376

Not sure how  else to reach out!

**Comment by zoran-cuckovic** [comment]
@labarba, @arfon  I have made a request over QGIS developer mailing list. 
Otherwise, my colleagues are mostly human sciences and not software developers - what would be required for a reviewer? Developing software, publishing on software use, actively collaborating over git-hub or similar platform?

**Comment by giohappy** [comment]
I can review it, but I cannot do it immediately. If a week is ok for you I can give a help.

**Comment by zoran-cuckovic** [comment]
Great!
I'm glad we got the thing started!

**Comment by labarba** [comment]
I also got some response via Twitter:
https://twitter.com/geomenke/status/750878480707923968

**Comment by volaya** [comment]
I don't have enough time for a full review, but just a quick comment:

The algorithm looks useful and interesting, but, being part of QGIS, it makes little sense to have it outside of the Processing framework. It would be much more useful and powerful if integrated into Processing.

Hope this helps

**Comment by giohappy** [comment]
I must agree with Victor. Looking at the algorithm configuration, it would
fit very well within the Processing toolbox, but I imagine this could be a
future refactoring/enhancement...

2016-07-07 12:44 GMT+02:00 volaya <notifications@github.com>:

**Comment by kyleniemeyer** [comment]
Robin Wilson (@robintw) volunteered to review via Twitter!

@arfon: can you add him as a JOSS reviewer?

**Comment by zoran-cuckovic** [comment]
@volaya , @giohappy 
I'm not sure the actual relationship of my software with the QGIS core is relevant here (?). I prefer having the plugin solution because inside there are several algorithms combined together and there are many options - and because I plan further enhancements. There are many visibility indices that can be added in the future, so the plan (optimistic) is to create some kind of a toolbox... But, yes, I understand that using processing toolbox allows to combine my algorithm with others: I'm planning to make simplified version(s) for that purpose.

**Comment by arfon** [comment]
> Robin Wilson (@robintw) volunteered to review via Twitter!

Fantastic! @robintw - I've invited you to `@openjournals/joss-reviewers` team which should allow you to update this issue with your review. Also, please take a look at the reviewer guidelines to familiarized yourself with the process http://joss.theoj.org/about#reviewer_guidelines

**Comment by robintw** [comment]
Sorry for the delay in dealing with this - I'm getting on with it now. Am I meant to actually tick the boxes in the checklist in the first post - and if so, how? I don't seem to be able to tick them - should I copy the checklist to reply and tick them there?

**Comment by arfon** [comment]
> Am I meant to actually tick the boxes in the checklist in the first post - and if so, how? I don't seem to be able to tick them - should I copy the checklist to reply and tick them there?

Yes please @robintw. You should have received an invite to the `@openjournals/joss-reviewers` team which will give you appropriate permissions. You can accept the invitation by clicking the link at the top of the page here: https://github.com/openjournals

**Comment by robintw** [comment]
Thanks @arfon - I somehow managed to miss that email. I've now got permissions to edit the checkboxes. I'll post the specific review comments shortly.

**Comment by robintw** [comment]
In general, the software seems to work ok, but there are various issues that mean that I can't tick all of the boxes in the review checklist. I'll go through these points individually below in the checklist categories:

**General:**
- **Versions**
  - The latest version is 0.5.1, and this is what is installed from the QGIS Plugin Manager, but https://hub.qgis.org/projects/viewshed lists latest version as 0.4.1. Please clarify/update as necessary.


**Functionality:**
- **Installation**
   - There are no installation instructions. I knew to use the QGIS Plugin Repository, but not all potential users will know this. Please add basic instructions.
  -  Can this plugin be installed manually (ie. from the cloned git repository rather than through the QGIS Plugin Manager) - if so, please provide instructions. This can be particularly useful when installing on computers without an internet connection.
  - There is no information on what versions of QGIS this plugin works with - please add.
- **Functionality**
  - The plugin seems to work ok with the tests that I've done. However, I have no idea whether it is producing the correct results because of the lack of specific test cases (see below)
- **Performance**
  - The plugin seems to run fast in my limited testing of it. However, there are no large test inputs provided and no speed comparisons with other tools in the documentation, so I am unable to properly comment on this.
   - The author claims that the latest version of this tool (v0.5.1) is significantly faster than the previous versions. However, I could not confirm this as I couldn't find any previous versions (there are no previous releases listed on Github, no tags for previous versions, etc).

**Documentation:**
- **General**
  - Generally the documentation has quite a lot of information on the underlying algorithms etc, but is fairly brief on the actual use of the software, and doesn't contain anything like useful screenshots.
  - The README is very short and has no information on dependencies or installation - both of which are key for a README. The README and documentation should also mention the license, but they don't.
- **Installation instructions:**
  - None provided (see above). Please add.
- **Example usage**
  - There is a folder called `TEST_DATA` with some example inputs, but no description of what any of the inputs are, or what outputs should be produced using these inputs and certain parameter configurations. A 'tutorial' section in the documentation going through an example analysis with data from TEST_DATA, and showing the 'correct' output would be very useful. Output files for the correct output with a range of different inputs and parameter settings should also be provided to allow users to test that the software is functioning as intended.
  - There are no screenshots in any of the documentation, and in fact, no information on where to find the menu items within the QGIS interface (not all Plugins create menu entries under the Plugins menu!)
- **Functionality documentation**:
  - Most parameters are documented in the 'reference' tab of the user-interface - but some are missing. These should be added.
  - The code itself is not well documented: there are no docstrings, and there are large chunks of code commented out (eg. https://github.com/zoran-cuckovic/QGIS-visibility-analysis/blob/master/viewshedanalysis.py#L205) and comments like `#open console !!!! to monitor !!! #and test time !!!!` or `NOT WORKING`, which do not give confidence!
- **Automated tests**
  - None are present. Ideally these should be added, but at the very least examples of correct outputs for multiple sets of input parameters should be provided.
- **Community Guidelines**:
  - None are present. Please add.

**Paper:**
The paper is generally ok, except there are no DOIs in the references, even for the journal papers that should have a DOI. I would also suggest referencing the peer-reviewed paper on GRASS (which has a DOI), rather than just its manual - see https://grasswiki.osgeo.org/wiki/GRASS_Citation_Repository
	
**General:**
I agree with the other comments, that this plugin would be far more useful if it were integrated into the processing toolbox - almost all actual geoprocessing tools in QGIS are being integrated into the processing toolbox. I'm not sure why you suggested making a simpler plugin for use within the toolbox: processing tools can have just as many options, parameters and so on as you can in your own plugin! In fact, the latest version of QGIS includes far better support for releasing processing scripts as parts of a Python plugin. Although integration with the processing toolbox would not be a requirement for this publication, I would strongly suggest it as a sensible way forward.

**Comment by arfon** [comment]
👍 thanks for this thoughtful and thorough review @robintw.

@zoran-cuckovic - please update this thread when you've had a chance to review @robintw's feedback and make the necessary changes.

**Comment by zoran-cuckovic** [comment]
Hello!
As there were quite a number of things to improve, including the documentation in GUI, I have made a new release – it has to be installed manually, as described in [the manual](http://zoran-cuckovic.github.io/QGIS-visibility-analysis/) (with a download link).  

*Functionality:*
1) Installation
-  There are no installation instructions. **Fixed** in the manual (link above)
-  Information on what versions of QGIS this plugin works with. **Fixed**.

2) Functionality 
- Lack of specific test cases. **Fixed**: see the [branch with test data]( https://github.com/zoran-cuckovic/QGIS-visibility-analysis/tree/test-data) .

3) Performance 
- There are no large test inputs provided and no speed comparisons with other tools in the documentation. **Fixed** : data and parameters used in the above link, plus a [speed comparison here]( http://zoran-cuckovic.from.hr/qgis-visibility-analysis-algorithm/) (hope the test would suffice…)
- I couldn't find any previous versions (no previous releases listed on Github, etc). >> I'm not a proficient GitHub user. All previous versions can be found in [QGIS plugins repo](https://plugins.qgis.org/plugins/ViewshedAnalysis/) 

*Documentation:*
1) General 
- The documentation (…) is fairly brief on the actual use of the software, and doesn't contain anything like useful screenshots. **Fixed**: [a tutorial made]( http://zoran-cuckovic.from.hr/qgis-viewshed-plugin-a-tutorial/)
- The README is very short and has no information on dependencies or installation. **Fixed**

2) Installation instructions: 
- None provided **Fixed** (see above).

3) Example usage 
- A 'tutorial' section in the documentation going through an example analysis (…) **Fixed**. Output files for the correct output with a range of different inputs and parameter settings should also be provided (…)**Fixed** (see above "functionality").
- There are no screenshots in any of the documentation, and in fact, no information on where to find the menu items within the QGIS interface. **Fixed** in the manual.

4) Functionality documentation: 
- Most parameters are documented in the 'reference' tab of the user-interface - but some are missing. These should be added. **Fixed**
- The code itself is not well documented: there are no docstrings, and there are large chunks of code commented out. **Fixed** (?): I've cleaned the code and added docstrings at beginnings of functions. 

5) Automated tests 
- None are present. Ideally these should be added, but at the very least examples of correct outputs for multiple sets of input parameters should be provided. **Fixed** (sort of ?) I have added a git branch containing test data, desired output and information on parameters used (5 outputs in all). Same data is used in the tutorial I made recently (link above). 

6) Community Guidelines: 
- None are present. Please add. **Fixed** in Readme + statement added.

*Paper:*
The paper is generally ok, except there are no DOIs in the references **Fixed**. I would also suggest referencing the peer-reviewed paper on GRASS **Fixed**.

**Thanks a lot to the reviewer !**

**Comment by arfon** [comment]
@zoran-cuckovic - thanks for these updates.

@robintw - can when you get a chance could you review these updates and let me know if we're good to accept this submission now?

**Comment by robintw** [comment]
This looks great @zoran-cuckovic - thank you for responding so quickly and so positively.

@arfon I am now happy for this to be accepted :-)

**Comment by arfon** [comment]
Thanks @robintw!

@zoran-cuckovic - could you make an archive of the current release in Zenodo/figshare and copy the DOI into this thread?

**Comment by lidapeng** [comment]
Hello Arfon @arfon . Is the review process for this paper done? If not I want to be a reviewer for this paper. Do I need to register a reviewer account? 
I am running the plugin using the test data given in the data branch. The cumulative viewshed analysis takes a very long time. It also generates many files in the directory. Should I manually install the latest version? @zoran-cuckovic   Thanks.
![viewshed](https://cloud.githubusercontent.com/assets/3634010/17465087/80d04c3a-5cbb-11e6-9745-41350a5006a5.JPG)

**Comment by arfon** [comment]
> Hello Arfon @arfon . Is the review process for this paper done? If not I want to be a reviewer for this paper. Do I need to register a reviewer account? 

@lidapeng - thanks for your interest. This review is now complete. If you're looking for support using the package I'd recommend you take a look at the project repository here: https://github.com/zoran-cuckovic/QGIS-visibility-analysis

**Comment by lidapeng** [comment]
OK. Thanks Arfon.

**Comment by zoran-cuckovic** [comment]
@lidapeng : you shoud select "cumulative" option. If it still doesn't work for you, please raise an issue in the repository.

**Comment by zoran-cuckovic** [comment]
@arfon, @robintw 
I have deposited the submitted version in Zenodo: [http://dx.doi.org/10.5281/zenodo.59896](http://dx.doi.org/10.5281/zenodo.59896)
The badge : [![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.59896.svg)](http://dx.doi.org/10.5281/zenodo.59896)

Thanks again JOSS and reviewer!

**Comment by arfon** [comment]
@zoran-cuckovic - apologies for this request coming so late in the day but would you mind moving the references into the `paper.bib` file and into a bibtex format? We can't do the final paper processing/reference management with Crossref without this sorry.

**Comment by zoran-cuckovic** [comment]
@arfon - I've created the .bib file. Hope it works!

**Comment by arfon** [comment]
@zoran-cuckovic - your paper is now accepted into JOSS. The DOI is http://dx.doi.org/10.21105/joss.00032 🎉 🚀 💥 

Thanks for the review @robintw!
