### ISSUE TITLE
[PRE REVIEW]: The country converter coco - a Python package for converting country names between different classification schemes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#321]
**Submitting author:** @konstantinstadler (<a href="http://orcid.org/0000-0002-1548-201X">Konstantin Stadler</a>)
**Repository:** <a href="https://github.com/konstantinstadler/country_converter" target ="_blank">https://github.com/konstantinstadler/country_converter</a>
**Version:** v0.4
**Editor:** @labarba
**Reviewer:** @rgieseke

**Author instructions**

Thanks for submitting your paper to JOSS @konstantinstadler. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@konstantinstadler if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
:wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#author_guidelines). In particular, this item:

> - Your software should have a research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)?

Many thanks!

**Comment by labarba** [comment]
I've read the paper, and this is not a piece of software with a research mission.

This is not eligible for publication in JOSS.

**Comment by konstantinstadler** [comment]
Hallo Lorena and Arfon,

Thanks for quick review! 

The main purpose of the software is to 
"make addressing research challenges significantly better (e.g., faster, easier, simpler)". 
The research application is the parsing of global data-sets.

One of the challenges we face in our research (Industrial Ecology - linking environmental and economic research to address global sustainability issues) are different country classifications, or even worse, just the use of non-standardized names when sharing data (e.g. in data provided by global organizations). As an example check the different forms of North and South Korea found in various databases - all tests here are based on encountered examples: https://github.com/konstantinstadler/country_converter/blob/master/tests/test_regex_korea.txt - the other test files provide further examples of the difficulties you can face parsing global data sets. To simplify this parsing (actually to make it possible to be automated) we needed a tool to convert between different classifications and to match various forms of one country name. 

We currently use the country converter in various projects, e.g. for parsing data about globally spanning shipping routes (which use non standard country names as trading partner indication), building scenarios based on economic forecasts by the International Monetary Fund (IMF provides data using country names), parsing UN data for Multi Regional Input Output Models (converting UN numeric country codes into internally used ISO3 codes) and  parsing biodiversity data given per country (again, using different country names). Because we now use the country converter for such diverse research projects, and since it has gained some interest outside our institute already (issue submitted by a person working for WIFO Vienna, some personal email request of how to use it from other research institutes), it seemed to be a good candidate for a publication in your journal.

I believe, the country converter will be of much help for researchers from various scientific fields which depend on some secondary data to be extracted from global databases. I hope, that I could make a case for this piece of software as a research tool - please let me know, if you need any further information.

**Comment by labarba** [comment]
Alright, if you could work that big-picture explanation of the research uses of the code into the paper, then we can proceed. The paper currently does not make the case. 

Because JOSS publishes software articles in a wide variety of fields, it's vital for the authors to include a few sentences for a non-specialist to understand why the software is useful for research.

**Comment by konstantinstadler** [comment]
Thanks a lot! I just pushed the updated description to the github repo.

**Comment by rgieseke** [comment]
Hi, I'd be happy to be a reviewer for this.

I'm a potential user (for emissions, GDP, population and other data in Climate Change research) - and also working on subsets of similar functionality in https://github.com/openclimatedata/countrygroups and have been using and contributing to https://github.com/occrp/countrynames.

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by arfon** [comment]
> @whedon start review magic-word=bananas

@labarba - I don't think you've assigned the reviewer yet.

**Comment by labarba** [comment]
Don't I have to start the review first, so that the new issue gets created, and assign the reviewer there?

**Comment by labarba** [comment]
@whedon assign @rgieseke as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @rgieseke

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/332. Feel free to close this issue now!

**Comment by labarba** [comment]
Interesting. So `start review` does nothing if the reviewer hasn't been assigned yet. It would be nice if `whedon` would throw a message for that.

**Comment by arfon** [comment]
> Interesting. So start review does nothing if the reviewer hasn't been assigned yet. It would be nice if whedon would throw a message for that.

👍 yeah. It should at least say _something_

**Comment by arfon** [comment]
@labarba - I've opened a bug report here https://github.com/openjournals/whedon-api/issues/6
