### ISSUE TITLE
[PRE REVIEW]: BOLD.R: A bridge between the Barcode of Life Database System and the Statistical Software R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3250]
**Submitting author:** @nishanmudalige (<a href="http://orcid.org/0000-0003-3981-9868">Nishan Mudalige</a>)
**Repository:** <a href="https://github.com/nishanmudalige/BOLD.R" target ="_blank">https://github.com/nishanmudalige/BOLD.R</a>
**Version:** 0.4.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @nishanmudalige. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @csoneson.

@nishanmudalige if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.15 s (224.0 files/s, 10111.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               31            311            165            791
TeX                              1             17              0            119
Markdown                         2             36              0             96
-------------------------------------------------------------------------------
SUM:                            34            364            165           1006
-------------------------------------------------------------------------------


Statistical information for the repository 'fd52e0b77f996c907a8c9e48' was
gathered on 2021/05/05.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/bioinformatics/btv428 is OK
- 10.32614/RJ-2018-009 is OK

MISSING DOIs

- 10.1093/bioinformatics/bty633 may be a valid DOI for title: ape 5.0: an environment for modern phylogenetics and evolutionary analyses in R
- 10.32614/rj-2014-011 may be a valid DOI for title: The stringdist package for approximate string matching
- 10.18637/jss.v040.i01 may be a valid DOI for title: The Split-Apply-Combine Strategy for Data Analysis
- 10.1007/978-3-540-35306-5_10 may be a valid DOI for title: SeqinR 1.0-2: a contributed package to the R project for statistical computing devoted to biological sequences retrieval and analysis.

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03250/joss.03250/10.21105.joss.03250.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03250/joss.03250/10.21105.joss.03250.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by kthyng** [comment]
Hi @nishanmudalige and thanks for your submission. I have instigated a scope query due to the relatively small size of the code, which will in turn ping the editorial board to take a look and see if it is in scope. This will take 1-2 weeks. In the meantime, I see your submission note about a conference paper. Can you specify what topic the conference paper covers? Is it about the code itself?

**Comment by nishanmudalige** [comment]
Hello Kristen,

Thank you for contacting me about my submission.

The contributed paper I mentioned was based off a poster that I presented for a graduate student poster competition. The paper covers some features of the package that were presented in the poster.

The code submitted to JOSS has been updated since the initial paper was submitted for the conference proceedings due to changes in some of the dependent packages and also to work with a more current version of R, however these are more than just some minor updates.

The old version of the package would experience severe timeout issues when used with a newer version of R and the new code submitted to JOSS has been updated to address this. Some other improvements were made and some minor issues have been addressed as well. Due to the updates made, the manner in which the data and information returned from using the package in the updated code is different to the code I submitted for the conference proceedings I submitted in 2019.

The conference was called The V AMMCS International Conference (Waterloo, Canada, August 2019) and it was an interdisciplinary conference covering topics in applied mathematics, modeling and computer science.

The old paper is expected to appear here: https://www.springer.com/gp/book/9783030635909#aboutBook

If you have any more questions or concerns, please feel free to contact me.

Thank you and regards,

-Nishan

________________________________

**Comment by nishanmudalige** [comment]
> Failed to discover a valid open source license.

Open GNU-3 License added to master branch.

**Comment by kyleniemeyer** [comment]
Hello @nishanmudalige, thanks for your patience. The JOSS editorial board has reviewed your submission, and unfortunately we found that it does not meet our [substantial scholarly effort criterion](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) for review by JOSS. Please see https://joss.readthedocs.io/en/latest/submitting.html#other-venues-for-reviewing-and-publishing-software-packages for other suggestions for how you might receive credit for your work.

**Comment by kyleniemeyer** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
