### ISSUE TITLE
[REVIEW]: Pipengine

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#341]
**Submitting author:** @fstrozzi (<a href="http://orcid.org/0000-0002-6845-6982">Francesco Strozzi</a>)
**Repository:** <a href="https://github.com/fstrozzi/bioruby-pipengine" target ="_blank">https://github.com/fstrozzi/bioruby-pipengine</a>
**Version:** 0.9.3
**Editor:** @biorelated
**Reviewer:** @yannickwurm
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.851892" target="_blank">10.5281/zenodo.851892</a>

## Status

[![status](http://joss.theoj.org/papers/a56e3259c0a44e0f691cea59863deadf/status.svg)](http://joss.theoj.org/papers/a56e3259c0a44e0f691cea59863deadf)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/a56e3259c0a44e0f691cea59863deadf"><img src="http://joss.theoj.org/papers/a56e3259c0a44e0f691cea59863deadf/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/a56e3259c0a44e0f691cea59863deadf/status.svg)](http://joss.theoj.org/papers/a56e3259c0a44e0f691cea59863deadf)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/fstrozzi/bioruby-pipengine" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@yannickwurm, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @biorelated know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fstrozzi/bioruby-pipengine">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.9.3)?
- [x] **Authorship:** Has the submitting author (@fstrozzi) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @yannickwurm it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by biorelated** [comment]
Ping @yannickwurm. Let me know if you need any clarifications.

**Comment by yannickwurm** [comment]
## Paper:

 - [ ] needs a grammar checker (e.g. from M.S. Word). 
 - [ ] Some of the sentences could be shortened to increase clarity
 - [ ] First sentence of Paragraph 2 is a long list - using bullet-points would make it more legible. 
 - [ ] Some readers may not know what "pre-CWL/WDL era" means. I suggest defining any abbreviations that might be ambiguous and linking to suitable sites/refs. 
 - [ ] Has no references. I don't know if that is a problem. Relevant refs could be to (PBS/Torque, Bioruby, etc).


## Readme: 

 - [ ] A sentence in the readme could indicate why this was needed (e.g., why alternatives (pure bash, rake, whatever) were /are inappropriate). --> the JOSS review form requests this to be crystalclear in the paper as well (see "*A statement of need:*").
 - [ ] Community Guidelines: Please add 2-3 sentences on e.g. how someone would add support for another scheculder


"References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?"  @biorelated I don't know what this means. I think wer'e ok

## Code/behavior: 

 - [ ] code includes a bunch of commented things
 - [ ] Test data: https://github.com/fstrozzi/bioruby-pipengine/issues/40
 - [ ] Versions of dependencies: https://github.com/fstrozzi/bioruby-pipengine/issues/41
 - [ ] default output: https://github.com/fstrozzi/bioruby-pipengine/issues/42
 - [ ] What are the other development branches for? Can they be deleted?
 - [ ] Shouldn't gemfile be more specific regarding version numbers to ensure that things run as expected/tested?

**Comment by biorelated** [comment]
Thank you very much @yannickwurm for taking your time to review this manuscript and code submission.  @fstrozzi please could you fix the or comment on the issues or concerns that have been raised by Yannick. In addition there are a couple of issues and checkboxes regarding the functionality and documentation of the software that may require some attention. 
Thank you. 
George

**Comment by fstrozzi** [comment]
Hi @biorelated and @yannickwurm ,
first of all thanks for your time in reviewing this submission and for providing useful feedbacks.

Yannick, here are the answers to your points.

**Paper**

A new version of the paper.md file has been uploaded addressing all the points raised, a paper.bib file was also added with the relevant references for Pipengine. Both are available in the "joss" folder.

**Readme**
The Readme file was improved, with a paragraph on what we considered the Pipengine advantages over previous approaches and the reason why it was developed. Along with that, a new section has been added at the end, briefly describing the source code organisation and where changes need to be made to extend Pipengine and to work with e.g. other job schedulers.

**Code**
Code has been cleaned up of old commented lines, the Gemfile now lists minimum version for the two gems Pipengine depends on and the minimum Ruby version. 

The issues opened on the repository where also addressed with specific commits (I will let Yannick review those and close the issues if the changes will be considered satisfactory). 

For other branches, if those pose a real problem for the archiving and publication on JOSS I will remove them from the repository, otherwise I would prefer to keep them, they contain development and experimental code that could turn out to be useful or picked up by others in the future.

A new version (0.9.6) is now available and pushed on RubyGems, which includes all the changes made to answer to reviewer's comments.

Thank you
Francesco

**Comment by biorelated** [comment]
Thank you very much Francesco ( @fstrozzi ) for the revisions. Yannick (@yannickwurm) what is your assessment of the revisions and are they satisfactory?

**Comment by yannickwurm** [comment]
Thanks v much - yes this looks much improved, but I must apologise that I am unable at this time to carefully doublecheck the authors work. 

However, I do note three issues with the readme: 
 1. "pipenengine"
 2. Executing the followign line (given in the readme) doesn't work: 
```
Yannick@ybook ~/g/b/t/data> pipengine -p pipeline.yml -f samples.yml -s mapping

Launcher for Complex Biological Pipelines . Copyright(C) 2012 Francesco Strozzi, Raoul Jean Pierre Bonnal

PipEngine v0.9.6
List of available commands:
	run	Submit pipelines to the job scheduler

Error: unknown argument '-p'.
Try --help for help.
```

3. I also had the impression that running `pipengine run -d -p pipeline.yml -f samples.yml -s mapping` would create a script onto standard out (or into a local file?). I don't see any such file or output. This may be due to the fact that the `samples.yml` file includes absolute paths to files that don't exist on my system.

**Comment by fstrozzi** [comment]
Hi Yannick,
thanks for your checks, the typos in the Readme command lines were corrected. 

To answer to point number 3, the test files into test/data do work as expected, the runnable scripts are created into an output directory that is specified in the samples.yml file, which in this case is a local ./test directory. I have made this behaviour clearer in the "What happens at run time" section of the Readme.

I have also updated the "Examples" section of the Readme, and the same files described there are also available in the test/examples folder so that the command lines can be tested directly. The output scripts will be generated into a local ./working directory in the case of the examples file.

Please let me know if you encounter other issues with the tests or documentation so that we can address those.

Thank you very much.
Francesco

**Comment by yannickwurm** [comment]
Super Francesco,
This sounds great to me. Cheers and all the best,
Yannick

Typos courtesy of my iPhone

On 26 Aug 2017, at 10:17, Francesco Strozzi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Yannick,
thanks for your checks, the typos in the Readme command lines were corrected.

To answer to point number 3, the test files into test/data do work as expected, the runnable scripts are created into an output directory that is specified in the samples.yml file, which in this case is a local ./test directory. I have made this behaviour clearer in the "What happens at run time" section of the Readme.

I have also updated the "Examples" section of the Readme, and the same files described there are also available in the test/examples folder so that the command lines can be tested directly. The output scripts will be generated into a local ./working directory in the case of the examples file.

Please let me know if you encounter other issues with the tests or documentation so that we can address those.

Thank you very much.
Francesco

**Comment by fstrozzi** [comment]
Thanks Yannick,
if (or when) everything is good for you, could you please let it know to the editor (George) ?

Thanks and cheers
Francesco

**Comment by yannickwurm** [comment]
@biorelated  - all good by me

**Comment by fstrozzi** [comment]
Thanks Yannick ! (@yannickwurm) .

George (@biorelated), I think we have finished here. What I need to do next ? I have created and pushed a new gem version (0.9.7) which includes all the changes made during the review process. I think the submission needs to be changed to reflect the last version of the package, but I don't know if I can do this or if this is up to you.

Thanks
Francesco

**Comment by biorelated** [comment]
Thank you very much Yannick (@yannickwurm)  for providing a detailed review. The submission will reflect the latest version of the package. Gem version (0.9.7) at the time of writing. 

@arfon this work is ready for publishing.

**Comment by arfon** [comment]
@fstrozzi - Your references (in `paper.bib`) currently aren't being cited in the paper body so they won't be compiled by Pandoc when we process the paper. Could you cite them directly please? You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)

**Comment by fstrozzi** [comment]
@arfon I've updated the bib file and added direct citations into the paper body. It should be fine now, thanks.

**Comment by arfon** [comment]
Thanks @fstrozzi. Could you please merge this PR https://github.com/fstrozzi/bioruby-pipengine/pull/43

Following that, could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by fstrozzi** [comment]
@arfon done, and here is the DOI from Zenodo: https://doi.org/10.5281/zenodo.851891 .

Thanks !

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.851892 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.851892" target="_blank">10.5281/zenodo.851892</a> is the archive.

**Comment by arfon** [comment]
@yannickwurm - many thanks for your review here and to @biorelated for editing this submission ✨ 

@fstrozzi - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00341 ⚡️ 🚀 💥

**Comment by fstrozzi** [comment]
Thank you very much @yannickwurm, @biorelated, @arfon

Cheers
