### ISSUE TITLE
[PRE REVIEW]: SIMsalabim: A time resolved drift-diffusion simulation software

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3412]
**Submitting author:** @ljakoster (<a href="http://orcid.org/0000-0002-6558-5295">Lambert Jan Anton Koster</a>)
**Repository:** <a href="https://github.com/kostergroup/SIMsalabim" target ="_blank">https://github.com/kostergroup/SIMsalabim</a>
**Version:** v4.05
**Editor:** @rkurchin
**Reviewers:** @UTH-Tuan, @shahmoradi, @roderickmackenzie
**Managing EiC:** Kyle Niemeyer

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/83fbf3b968bd0e69ddfbeca6668469cf/status.svg)](https://joss.theoj.org/papers/83fbf3b968bd0e69ddfbeca6668469cf)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/83fbf3b968bd0e69ddfbeca6668469cf"><img src="https://joss.theoj.org/papers/83fbf3b968bd0e69ddfbeca6668469cf/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/83fbf3b968bd0e69ddfbeca6668469cf/status.svg)](https://joss.theoj.org/papers/83fbf3b968bd0e69ddfbeca6668469cf)
```

**Author instructions**

Thanks for submitting your paper to JOSS @ljakoster. **Currently, there isn't an JOSS editor assigned** to your paper.

@ljakoster if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (307.5 files/s, 151313.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Pascal                           7            668            984           3357
Markdown                         3            103              0            166
TeX                              1             18              0            116
-------------------------------------------------------------------------------
SUM:                            11            789            984           3639
-------------------------------------------------------------------------------


Statistical information for the repository 'eaec603b8ef16057e4270f3e' was
gathered on 2021/06/25.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3412 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (bf88a2f2cdfb9f7b27544c3e/paper/paper.md): found character that cannot start any token while scanning for the next token at line 4 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:127:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-b63fc70cc085/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by kyleniemeyer** [comment]
Hi @ljakoster, thanks for your interest in JOSS!

Unfortunately, we have extremely limited editor availability to handle submissions right now, and so we need to put your submission on our waitlist untill an appropriate editor becomes available. Thanks for your patience!

It looks like the YAML header in your paper is causing some compilation issues. I *think* the issue is the tabs, rather than spaces, before the items in the list (`  - ` rather than `	-`).

**Comment by Mkoopm** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by Mkoopm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03412/joss.03412/10.21105.joss.03412.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03412/joss.03412/10.21105.joss.03412.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
Hi @rkurchin! Here is another waitlisted submission that I think you may be a good fit for. What do you think?

**Comment by kthyng** [comment]
@whedon invite @rkurchin as editor

**Comment by whedon** [comment]
@rkurchin has been invited to edit this submission.

**Comment by rkurchin** [comment]
Happy to!

@whedon assign @rkurchin as editor

**Comment by rkurchin** [comment]
@whedon assign @rkurchin as editor

**Comment by whedon** [comment]
OK, the editor is @rkurchin

**Comment by rkurchin** [comment]
Hi there @ljakoster, I'll be the editor for your submission. Excited to learn more about your software! Could you take a look a this list of potential reviewers and identify a few people who would be good candidates to review this submission?

**Comment by Mkoopm** [comment]
Hi @rkurchin, I'm a PhD student working with @ljakoster. @ljakoster is on holiday until the beginning of August, so the reply will take a while, unfortunately.

**Comment by rkurchin** [comment]
No worries, thanks for letting me know!

@danielskatz, should I just label this as "paused" and circle back in a couple weeks?

**Comment by danielskatz** [comment]
You don't need to pause it for a couple of weeks, though you could and should if it is longer than that - here you could just use the @whedon remind mechanism to send a reminder in 2 weeks, or 18 days, ...

**Comment by rkurchin** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by rkurchin** [comment]
@whedon remind me in 2 weeks

**Comment by whedon** [comment]
Sorry, I can't set reminders on PRE-REVIEW issues.

**Comment by danielskatz** [comment]
oh, sorry, didn't read enough - yes, you could use paused in this case.

**Comment by rkurchin** [comment]
Hi again @ljakoster, hope you've had/are having a great holiday! When you're back, please let me know so I can unpause this review, and take a look at [this list](https://bit.ly/joss-reviewers) of potential reviewers and suggest a couple that you think might be good fits for your work. Note: please do not @ tag them on GitHub but just post their plaintext usernames.

**Comment by rkurchin** [comment]
👋  @ljakoster, just checking in again, whenever you're back from holiday and ready to get this going again, do let us know!

**Comment by ljakoster** [comment]
hi @rkurchin <https://github.com/rkurchin>,

sorry for the slow reply, just got back to the office.
May I suggest:
-dawbaron
-eteq
-danehkar
-shahmoradi

best wishes,
Jan-Anton

--
Prof. Dr. L.J.A. (Jan Anton) Koster
Zernike Institute for Advanced Materials
University of Groningen
open-source simulator for perovskite and organic PV
<https://github.com/kostergroup/SIMsalabim>
group website <http://www.koster-group.nl>

**Comment by rkurchin** [comment]
👋  Hi there @shahmoradi and @danehkar, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Please feel free to let me know if you have any questions about the process.

**Comment by shahmoradi** [comment]
Thanks for the invitation. My knowledge of Pascal is rusty and aged. But I am happy to help if I am the last resort on this matter.

**Comment by rkurchin** [comment]
Thanks. Our list of volunteers is a bit thin on folks who list themselves as knowing any Pascal and also as doing physics, so if you feel like you can tackle the subject matter, I think you'd be a perfectly fine fit. Let me know what you think!

**Comment by shahmoradi** [comment]
sounds good. Is there a deadline to submit the review?

**Comment by rkurchin** [comment]
Once we have at least two reviewers, we'll start the review issue (this is the pre-review issue). The review process should be quite interactive, with reviewers filing issues (or even PR's) to address any areas that are lacking, either in the code itself or its documentation. So the duration of that can vary a fair bit depending on how quick that back-and-forth is. But once the review starts, you should definitely not feel as though you have to have gone through every element of the checklist before asking the author questions or filing issues on the repo, e.g. if you have issues installing or running the code.

Anyway, for the moment you can sit tight until we get another reviewer, but hope this helps!

**Comment by rkurchin** [comment]
👋 Hi there @eteq, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Please feel free to let me know if you have any questions about the process.

**Comment by rkurchin** [comment]
👋 Hi there @UTH-Tuan, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Please feel free to let me know if you have any questions about the process.

I recognize this submission is a bit outside your subject area expertise, so I'm primarily asking you to review the software design side of it, as we don't have too many reviewer volunteers with Pascal expertise. I'll recruit another complementary reviewer (see next message) to focus primarily on the subject matter.

**Comment by rkurchin** [comment]
👋 Hi there @dalonsoa, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Please feel free to let me know if you have any questions about the process.

I know you didn't note Pascal expertise in your volunteer signup, so I'm hoping that as a semiconductor/PV expert that you can primarily review the subject matter side of things, and we'll lean on other reviewers (see prior comment) to handle the specifics of software design in Pascal.

**Comment by UTH-Tuan** [comment]
@rkurchin Sure, I'll participate. Let me know what I need to do proceed.

**Comment by rkurchin** [comment]
@whedon add @UTH-Tuan as reviewer

**Comment by whedon** [comment]
OK, @UTH-Tuan is now a reviewer

**Comment by rkurchin** [comment]
@whedon add @shahmoradi as reviewer

**Comment by whedon** [comment]
OK, @shahmoradi is now a reviewer

**Comment by rkurchin** [comment]
👋 @MikeHeiber, would you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

Please feel free to let me know if you have any questions about the process.

I know you didn't note Pascal expertise in your volunteer signup, so I'm hoping that as a semiconductor expert that you can primarily review the subject matter side of things, and we'll lean on other reviewers (see prior comments) to handle the specifics of software design in Pascal.

**Comment by MikeHeiber** [comment]
Sorry for the slow response. I've been on holiday the past several days. Unfortunately, I must declare a conflict of interest to providing an unbiased review. I am a recent collaborator of the author's. I would suggest @roderickmackenzie (roderick.mackenzie@nottingham.ac.uk) who has published related simulation codes in the past. He is also much more of an expert in the details of drift-diffusion simulations than I am and should be able to provide a high quality scientific review.

**Comment by rkurchin** [comment]
No problem. Thanks for the straightforwardness and alternative suggestion! @roderickmackenzie, we'd love to have your help here if you're willing! We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by rkurchin** [comment]
emailed Prof. MacKenzie today to follow up:

> Dear Prof. MacKenzie,
> 
> 
> I’m an editor for the Journal of Open-Source Software (JOSS). I’m currently seeking reviewers for a manuscript on drift-diffusion simulations (see more details here), and you were suggested as a qualified reviewer.
> 
> JOSS is a free, open-source, community driven and developer-friendly online journal (no publisher is seeking to raise revenue from the volunteer labor of researchers!). The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged.
> 
> JOSS reviews involve downloading and installing the software, and inspecting the repository and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html . Editors and reviewers post comments on the Review issue, and authors respond to the comments and improve their submission until acceptance (or withdrawal, if they feel unable to satisfy the review).
> 
> Would you be able to review this submission for JOSS? If not, could you provide recommendations of other qualified reviewers?
> 
> Thanks in advance,
> Rachel Kurchin

**Comment by roderickmackenzie** [comment]
Hi There!,
 Thanks for your mail. Sorry for not seeing this I have a special e-mail account setup for high volume stuff which I don't check.. and this went into it.. So as far as I understand the review process, I just write comments here and then the authors respond?

I am happy to take a look but will need a few days to compile and poke at the code base.  I've not used Pascal since the Borland Delphi days of 2000.. 

I've read the manual and had a quick poke around. Some initial comments are:
*Nice manual.
*Nice scientific description in the manual.
*The code seems clear on first impressions.
*I like the hat logo!
*I also like your implementation of the bernoulli function, might be faster than what I do.  Exponentials are always a pain to calculate as they are done iteratively... I would be good though if you could point to literature or show a graph that what you do works.
*The model is clearly a nice thing and a benefit to the community.  The more people are simulating these devices the better as we will have a chance of pushing renewable stuff forward...

Here are some general questions to kick off with:
1. Your use of the V in equations 2.1 -2.6 is a bit confusing because commonly V is only used in the DD equations when hetero-junctions are *not* taken into account.  When the model has been adjusted to handle hetero-junctions (as yours seems to be 2.13-2.14) it's conmen to write Ec and Ev in the DD equations instead of V, to explicitly say that heterosteps can drive current.  This is especially confusing as your fig 2.1 shows hetero steps so made me scratch me head as soon as I started reading until I reached the interfaces section. If you rewrite in terms of Ec and Ev you can get rid of equations 2.13-2.14, it would make the description look more like the classical DD literature as used for things like the III-V materials - and make things a bit clearer.

2.  As I understand it there are two parts to the model a transient part and a steady state parts.  In the intro you talk about transient photovoltage and AC analysis.  However your equation 2.22 is the steady state form of the SRH equation, so you are assuming your trapped carrier distribution is in quasi-steady state. This means that although you can do time domain simulations your trapped carriers will always think they are in quasi-equilibrium.  This won't matter for DC or for slow small perturbation stuff. But you won't for example be able to simulate things far from equilibrium, e.g.  ToF transients are an extreme example of this where carriers are initially captured then gradually released from deeper and deeper traps as time goes on.  TPV transients could also meet this large signal condition depending on the power of the laser pulse, and AC depending on carrier trapping/detrapping rates and the frequency you are at (and trap depth). CELIV will also fall into large perturbation regime etc... etc... I think the user should be alerted to the fact that your carriers are in SS and the model does not explicitly solve the SRH equations in time domain. Many users won't grasp this so I think it needs to be clearly pointed out and what the implications of this are for results.

3. I'm assuming that your trapped carriers introduced through equation 2.22 don't interact with the field? As for some devices (organics) quite a lot of the charge will be trapped (>90%) so this could affect the results. If the trapped charge does not affect the field I think the user should also be told about this in the manual. Maybe include a limitations section in the manual? Again, it depends on what the user is using the code for. If it's some perovskite device with not many traps then this may not be an issue, but if it's some ultra trappy organic thing then..
 
I think my main concern with points 2 and 3 is that the user knows what he/she is dealing with. There are a tonne of papers where people just use software (aka COMSOL etc..) to produce a paper without understand what is going on under the hood and results in miss interpretation of data which is not a good thing.

4. Would be nice if you could add some makefiles. Also would be good if you could tell me (the user) which package I need to install on Ubuntu to get pascal. I'm not super excited about installing free pascal binaries from anything but the Ubuntu repos due to security reasons.

I'll install and play with over the next week then get more computer related comments back to you..

best,
Rod

**Comment by rkurchin** [comment]
Hi @roderickmackenzie, we actually do the review in another issue (this is the "pre-review" issue). Thanks for your comments! I'll copy them over into the new issue when I create it, and that will also generate a checklist for you to fill out to guide you through the review criteria.

**Comment by rkurchin** [comment]
@whedon add @roderickmackenzie as reviewer

**Comment by whedon** [comment]
OK, @roderickmackenzie is now a reviewer

**Comment by rkurchin** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3727.

**Comment by ljakoster** [comment]
@roderickmackenzie many thanks for your input; we'll be working on those
and will post a new version (I'm assuming that's how it's done).

jan anton

--
Prof. Dr. L.J.A. (Jan Anton) Koster
Zernike Institute for Advanced Materials
University of Groningen
open-source simulator for perovskite and organic PV
<https://github.com/kostergroup/SIMsalabim>
group website <http://www.koster-group.nl>
