### ISSUE TITLE
[PRE REVIEW]: visdat: Visualising Whole Data Frames

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#347]
**Submitting author:** @njtierney (<a href="http://orcid.org/0000-0003-1460-8722">Nicholas John Tierney</a>)
**Repository:** <a href="https://github.com/ropensci/visdat" target ="_blank">https://github.com/ropensci/visdat</a>
**Version:** v0.2.0
**Editor:** @arfon
**Reviewer:** @arfon

**Author instructions**

Thanks for submitting your paper to JOSS @njtierney. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@njtierney if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by njtierney** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by njtierney** [comment]
Thanks @whedon !

**Comment by njtierney** [comment]
Hi there,

So visdat has been through the rOpenSci onboarding process [here](https://github.com/ropensci/onboarding/issues/87). When I submitted the package to JOSS I linked to the package repo, not to the [Zenodo DOI](https://zenodo.org/record/837274), I'm wondering if perhaps this is why it didn't get processed the same as [rtimicropem](https://github.com/openjournals/joss-reviews/issues/333), perhaps @arfon can shed some light on this.

Additionally, I have made some minor changes in the paper.md document of visdat since the review of rOpenSci ended, it would be great if I could keep these changes, unless they are too much? You can see the changes [here](https://github.com/ropensci/visdat/commit/4d391b11a1adce8dca8b8d0efbe2f466cfeaa3dc)

This is my first time submitting something to JOSS, please let me know if I have missed anything, this seems like a great process! :)

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/355. Feel free to close this issue now!
