### ISSUE TITLE
[PRE REVIEW]: LilyPad: Real-time two-dimensional fluid/structure interaction simulations written in Processing

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#349]
**Submitting author:** @weymouth (<a href="http://orcid.org/0000-0001-5080-5016">Gabriel D Weymouth</a>)
**Repository:** <a href="https://github.com/weymouth/lily-pad" target ="_blank">https://github.com/weymouth/lily-pad</a>
**Version:** v1.0
**Editor:** @labarba
**Reviewer:** @alignedleft

**Author instructions**

Thanks for submitting your paper to JOSS @weymouth. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@weymouth if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @labarba - the submitting author suggested you as an editor.

**Comment by labarba** [comment]
Roger!

**Comment by weymouth** [comment]
Potential reviewers. From the list it looks like @jochym, @Kevin-Mattheus-Moerman and others would have familiarity with the physics. As far as language, you don't have anyone who uses Processing so I suggest @shiffman. Processing is similar to Java, so we could also go with @pragyansmita.

**Comment by labarba** [comment]
@weymouth : I do not see a license attached to your code submission.

**Comment by weymouth** [comment]
Crazy! It must not have made the transition from the google code repository and I never noticed. I've added it.

**Comment by labarba** [comment]
There is also no Community Guidelines, and I see that the paper mentions "engineering outreach activities and student projects," but there is no Statement of Need and no mention of research applications. You will need to work on these things, while we continue seeking commitment from a reviewer.

**Comment by labarba** [comment]
(I found a "Contributing" section in the wiki. Not where I would've expected it to be…)

**Comment by weymouth** [comment]
Is there a "best practices" reference for how to structure the github site?
I'll be more explicit on the "Statement of Need" and research application in paper.md

**Comment by labarba** [comment]
Good question @weymouth — I don't think there is. Just emergent behavior, I suppose. Most repos will have a `CONTRIBUTING.md` file right on the root of the repo, and additionally a heading in the README that has a sentence and a link to the `md` file. Same goes for installation instructions. I think putting these things in the wiki is going to cause you some headaches, because folks won't find them and they'll ping you.

**Comment by labarba** [comment]
@weymouth : Regarding the statement of need for research applications, the paper currently has only one sentence addressing this: _"This enables users with no previous CFD experience to address open research problems in fluid mechanics; for example, how a plesusaur swims [https://doi.org/10.1017/jfm.2015.61] and how spinning cylinders can eliminate drag [https://doi.org/10.1017/jfm.2017.395]."_

First of all, you should use the `.bib` file for references and add the citations properly in the paper.

Next: mis-typed "plesiosaur."

That sentence is not sufficient to establish the research application of the software. I notice that after the mention of plesiosaur swimming as a research application, you cite the paper titled "Unsteady dynamics of rapid perching manoeuvres”—I didn't read the paper, just skimmed a few pages, but it didn't seem to be a paper on plesiosaur swimming… The next research application mentioned is drag reduction with spinning cylinders (should you use "reduce" rather than "eliminate"?), citing the paper "Flow control with rotating cylinders"—browsing that paper, it mentions Reynolds number is 47,000; but I gather that LilyPad only handles low Reynolds numbers…

**Comment by weymouth** [comment]
I have changed the organisation of the repository to follow your suggestion. 

I've tried to be super clear about the need: a **simple to use** CFD solver for unsteady FSI. I can't state how important simple to use software is for actually **getting research done**! Based on the JOSS requirements, this seems to be within your remit:
 - Your software should have an obvious research application
 - Should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)

I've fixed the references (I had left out one description) and I'm waiting on the PhD student to give me the DOI for the tandem flapping foil paper. For the spinning cylinder results, the LilyPad simulations were low Re, and showed complete elimination of drag (thrust production even). LilyPad can run high Re simulations, but 2D turbulence is quite different than 3D turbulence. I have a PhD student working on that right now...

**Comment by Kevin-Mattheus-Moerman** [comment]
@labarba I am not familiar with the Processing language and my expertise is predominantly solid mechanics. However, I am interested in this submission so I will try to implement/test it. I could act as the (n+1)th reviewer, where n>1 :smile_cat:

**Comment by labarba** [comment]
@weymouth : I'm still working on locating a reviewer from the Processing community. I have someone who tentatively agreed, but is unavailable for another month. Stay tuned.

Meanwhile, thank you for your patience with my pre-review enquiries on your submission.

**Comment by weymouth** [comment]
I added the DOI for the JFM plesiosaur paper (https://doi.org/10.1017/jfm.2017.457) to the paper.bib. 

Our Royal Society plesiosaur paper also just came out (https://t.co/2iUZsQPyzA) if you're interested.

**Comment by labarba** [comment]
@whedon assign @alignedleft as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @alignedleft

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/394. Feel free to close this issue now!
