### ISSUE TITLE
[PRE REVIEW]: ESVM : An Electrostatic 1D-1V Vlasov-Maxwell code for educational purpose

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3581]
**Submitting author:** @michaeltouati (<a href="http://orcid.org/0000-0001-7590-0941">Michael Touati</a>)
**Repository:** <a href="https://github.com/michaeltouati/ESVM" target ="_blank">https://github.com/michaeltouati/ESVM</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6e1e5dcfe9e60d02bf4ba6c6f981fd98/status.svg)](https://joss.theoj.org/papers/6e1e5dcfe9e60d02bf4ba6c6f981fd98)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6e1e5dcfe9e60d02bf4ba6c6f981fd98"><img src="https://joss.theoj.org/papers/6e1e5dcfe9e60d02bf4ba6c6f981fd98/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6e1e5dcfe9e60d02bf4ba6c6f981fd98/status.svg)](https://joss.theoj.org/papers/6e1e5dcfe9e60d02bf4ba6c6f981fd98)
```

**Author instructions**

Thanks for submitting your paper to JOSS @michaeltouati. **Currently, there isn't an JOSS editor assigned** to your paper.

@michaeltouati if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 942

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=3.46 s (3.5 files/s, 595.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Fortran 90                       7             89            183            946
Python                           2             41             30            573
Markdown                         1             15              0             85
make                             1             31             31             37
TeX                              1              1              0              0
-------------------------------------------------------------------------------
SUM:                            12            177            244           1641
-------------------------------------------------------------------------------


Statistical information for the repository '822805d3b6571daeb7c60a6f' was
gathered on 2021/08/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
michaeltouati                    3          1288            644          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Michael Touati              644          100.0          0.0                4.66
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03581/joss.03581/10.21105.joss.03581.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03581/joss.03581/10.21105.joss.03581.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@michaeltouati – due to the small size of this code, the editors will now discuss if it meets the [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort) criterion for review by JOSS. 

Additionally, this submission may be considered out of scope for JOSS due to its focus on educational use cases. Regardless, the scope review will likely take a couple of weeks, thanks for your patience!

**Comment by arfon** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by michaeltouati** [comment]
joglekara	Python
C++	C
FORTRAN
MATLAB
Mathematica	Noble.AI <http://noble.ai/>	***@***.***	Plasma Physics
Kinetic Physics
Numerical Methods
Electromagnetics

**Comment by michaeltouati** [comment]
Potential reviewers :

StanczakDominik	Python
Julia		University of Warsaw	***@***.***	Numerical simulation
Physics (plasmas, especially)

rogeriojorge	Python, C++, Mathematica, Matlab	Fortran	Max-Planck Institute for Plasma Physics, Greifswald, Germany	***@***.***	Physics, Plasma Physics, Nuclear Fusion

sigvaldm	Python
C
C++
Fortran	Haskell	University of Oslo	***@***.***	Computational Physics
Plasma Physics
Numerical Methods
Finite Element Method
Particle-In-Cell

CFGrote	python
C/C++
Fortran
R
Ada	Java
awk
perl	Max-Planck-Institute for Evolutionary Biology	***@***.***	Physics: 
- Plasma physics
- X-ray optics
- X-ray plasma diagnostics
- Many Body physics
- Quantum Electrodynamics
- Atomic Physics
- Extreme Fields
Biology:
- Evolutionary models
- Stochastic simulations
- Genetic analysis pipelines
- RNASeq
- Sequence alignment

joglekara	Python
C++	C
FORTRAN
MATLAB
Mathematica	Noble.AI <http://noble.ai/>	***@***.***	Plasma Physics
Kinetic Physics
Numerical Methods
Electromagnetics

TomGoffrey	Fortran, Python	C, C++	University of Warwick	***@***.***	Astrophysics (my main area of expertise is in stellar physics, but I also have some background in planetary physics), plasma physics, hydrodynamics (shock capturing and modelling in particular), magnetohydrodynamics (I have worked a lot on non-ideal MHD in particular), radiation transport, (large )linear systems, time-integration methods, finite volume methods, arbitrary/Lagrangian meshes, multi-material flow.

StanczakDominik	Python
Julia		University of Warsaw	***@***.***	Numerical simulation
Physics (plasmas, especially)

**Comment by michaeltouati** [comment]
Dear Arfon,

I indeed specified that this code ESVM that I’ve written was for educational purpose. However, since it is available on GitHub, it has already been used by teams of Researchers to investigate new Plasma Physics problems. 

Additionally, in Plasma Physics, people tend to only use the Particle-In-Cell (PIC) method for their investigations. Easily extendable to 2D-2V or 2D-3V, this code, that I wrote initially to teach my students about the limitations of the PIC method, has consequently a non-negligible potential. Therefore, the way I see it, it deserves to be published in JOSS.

I’m surprised by the critics of the small amount of lines of code. I’ve seen papers already published in JOSS that computes the exact same Physical problem with Python and with only one available numerical scheme. ESVM allows the user to choose one of 9 different numerical scheme for the advection of particles in the phase-space and two different numerical schemes for the coupled Maxwell equations. I indeed try to minimize the number of lines of codes when developing it. I didn’t know it was a bad thing.

Finally, I’ve proposed some potential reviewers for my paper. Can you tell me if the way I’ve proposed them is correct? I’m not sure.

Thanking you and wishing you a nice week-end,
Best regards,
Dr Michaël TOUATI

**Comment by jedbrown** [comment]
Have you considered submitting to [JOSE: the Journal of Open Source Education](https://jose.theoj.org/)? It's very similar to JOSS, but for _educational_ materials/software rather than JOSS's focus on *research* software.

**Comment by michaeltouati** [comment]
Dear Jed,

I think I’ve made a mistake by chosing such a title. This is just because
I’ve developped and used this code to teach Plasma Physics to graduate
students.

It can clearly be used for Plasma Physics Research investigations as it is
already the case by two teams who cloned it from GitHub (and myself).

If needed, I can submit it to JOSE but I think it will be better to change
the title and consider the submission to JOSS that is more adapted.

Best regards,
Michaël

**Comment by arfon** [comment]
@michaeltouati – this submission does currently feel more appropriate for JOSE rather than JOSS, both because of the title of the submission but also because of the focus of the paper. 

Could I ask that you resubmit with an update title and research focus in the paper?

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by arfon** [comment]
> @whedon reject

(But we're expecting a re-submission)
