### ISSUE TITLE
[REVIEW]: gmm_diag and gmm_full: C++ classes for multi-threaded Gaussian mixture models and Expectation-Maximisation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#365]
**Submitting author:** @conradsnicta (<a href="http://orcid.org/0000-0002-0049-4501">Conrad Sanderson</a>)
**Repository:** <a href="https://github.com/conradsnicta/armadillo-gmm" target ="_blank">https://github.com/conradsnicta/armadillo-gmm</a>
**Version:** v7.960
**Editor:** @arfon
**Reviewer:** @jordigh
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1012627" target="_blank">10.5281/zenodo.1012627</a>

## Status

[![status](http://joss.theoj.org/papers/c7f0d840fec6ea426c07cf4a83f964f6/status.svg)](http://joss.theoj.org/papers/c7f0d840fec6ea426c07cf4a83f964f6)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/c7f0d840fec6ea426c07cf4a83f964f6"><img src="http://joss.theoj.org/papers/c7f0d840fec6ea426c07cf4a83f964f6/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/c7f0d840fec6ea426c07cf4a83f964f6/status.svg)](http://joss.theoj.org/papers/c7f0d840fec6ea426c07cf4a83f964f6)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/conradsnicta/armadillo-gmm" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@jordigh, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/conradsnicta/armadillo-gmm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v7.960)?
- [x] **Authorship:** Has the submitting author (@conradsnicta) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @jordigh it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@jordigh - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Any questions/concerns please let me know.

**Comment by conradsnicta** [comment]
@jordigh - I'm the first author. If you have any questions on this submission (code, documentation, etc), I'd be happy to answer them.

**Comment by jordigh** [comment]
Thanks, I've started looking it over, and at a glance it looks good. It's my first review, so I'm taking some time to go through each of the points. One question, the code is already in the main Armadillo repo and that's in Sourceforge, right? It wasn't immediately obvious to me where the canonical repo is.

Btw, I work on Octave, not too far afield from Armadillo. I'm a fan. :-)

**Comment by conradsnicta** [comment]
Yes, the gmm code is in the main repo.  We moved it from Sourceforge to GitHub a while back.  The unstable branch is https://github.com/conradsnicta/armadillo-code/tree/unstable which is intended for rapid evolution and experimental code.

Due to the rapid change in the unstable repo, I've setup a separate repo for the purposes of the review: https://github.com/conradsnicta/armadillo-gmm
This essentially contains a snapshot of the Armadillo 7.960.1 release, but the README file is changed to focus on the gmm_diag and gmm_full classes.  I hope this is okay.

**Comment by conradsnicta** [comment]
Hi, any update on the review?

**Comment by conradsnicta** [comment]
@arfon @jordigh - Hi, any update on the review?

**Comment by jordigh** [comment]
I've been busy with some other affairs. I should have time this weekend to complete this review.

**Comment by conradsnicta** [comment]
@jordigh - Thanks for the update.  I've added tests for the `gmm_diag` and `gmm_full` classes to the git repo: https://github.com/conradsnicta/armadillo-gmm.  The corresponding Zenodo archive of the release has also been updated: http://dx.doi.org/10.5281/zenodo.838397. (The DOI in the paper will automatically resolve to the latest version of the release archive).

The new tests are in `tests/gmm.cpp`  The instructions for compiling and running the tests are described in `tests/README.txt`.

The documentation for the `gmm_diag` and `gmm_full` classes is in the `docs.html` file within the repo and archive.  Please let me know if you have any questions on queries.

**Comment by jordigh** [comment]
So, forgive me for being a novice reviewer, but there's a couple of things that aren't clear to me:

* I'm not sure the paper states clearly who the target audience. It speaks broadly of how the problem could be applied to signal processing, statistics, and other fields. Is that sufficient? Any practitioner in those fields would be interested in this?

* At least a few DOIs seem to be missing in the references. For example, 10.1109/79.543975 for the Moon paper.

A few other remarks:

* I only tested the installation on Debian GNU/Linux, but it looks like a standard CMake build and the build dependencies are clearly stated for macOS and Windows. I'm confident it will work in other environments. The instructions seem correct. Only snag: I installed to a DESTDIR instead of systemwide, so I had to make sure that my linker was looking for `$DESTDIR/usr/lib/x86_64-linux-gnu` instead of just `$DESTDIR/usr/lib/`. I'm not sure if this is an odd peculiarity of my Debian system or a general point that should be mentioned in the installation instructions.

* I have managed to compile and execute the gmm example in the documentation. I would like to spend some time over the next few days understanding this example and the results I see to ensure it is reasonable.

**Comment by conradsnicta** [comment]
@jordigh - I've modified the paper as well as the installation instructions to address the issues you've raised. Details below:

> I'm not sure the paper states clearly who the target audience is. It speaks broadly of how the problem could be applied to signal processing, statistics, and other fields. Is that sufficient? Any practitioner in those fields would be interested in this?

Modelling of data via GMMs is a general statistical modelling approach, so it has a multitude of uses in many fields. Its target audience is hence any practitioner who needs to have a probabilistic model of multidimensional data and calculate likelihoods + etc using such a model.  From first hand experience I have used it for signal processing (eg. speech & images), pattern recognition and computer vision (eg. human action recognition). The paper mentions the use areas as examples, and these areas are not meant to be limiting. Nevertheless, I have tightened the first sentence in the paper to clearly state that this is a statistical modelling technique.

> At least a few DOIs seem to be missing in the references.
> For example, 10.1109/79.543975 for the Moon paper.

I've added the missing DOIs (the Moon paper as well as the Dean & Ghemawat paper).

> The instructions seem correct. Only snag: I installed to a DESTDIR instead of systemwide, so I had to make sure that my linker was looking for $DESTDIR/usr/lib/x86_64-linux-gnu instead of just $DESTDIR/usr/lib/. I'm not sure if this is an odd peculiarity of my Debian system or a general point that should be mentioned in the installation instructions.

I've modified the installation instructions to state that the 'lib' directory might be named differently on the user's system and provided examples: _On recent 64 bit Debian & Ubuntu systems it is 'lib/x86_64-linux-gnu'. On recent 64 bit Fedora & RHEL systems it is 'lib64'_.

**Comment by arfon** [comment]
@jordigh - back to you.

**Comment by arfon** [comment]
_bump_ friendly reminder on this @jordigh

**Comment by jordigh** [comment]
Okay, I've looked a bit more at the functionality of `gmm_diag`, and the results seem adequate. I ran the model a few times, looked at the resulting convex combination of multivariate normals, and they seemed to fit the data to a reasonable degree.

Ticking through the other tickboxes of my review, I couldn't find much of an indication of how to contribute to Armadillo except a pointer to the github repo, which I suppose might be enough of an indication in this day and age of near-universal git and pull requests.

I compiled and ran the tests for the two new functions, although I did kludge the Makefile to compile with `-I ../include` like the corresponding Makefile in the `examples/` directory so helpfully already does, plus change its linking option from `-larmadillo` to `-lblas llapacak`. I assume this is because the test suite is generally meant to be ran against a system-installed Armadillo unlike the examples. The two tests look reasonable and both passed. I understand there's no RNG seeding, as I had to explicitly add a call to `arma_rng::set_seed_random()` for my own examples, an addition of which might make it interesting to see if the tests still pass despite lack of complete determinism.

All in all, this looks complete and I can tick off the final box, but I do have one final question: you already have a citable paper for this software in the conference proceedings, so what was the motivation to submit it to JOSS in the first place?

**Comment by conradsnicta** [comment]
@jordigh - Thanks for doing the review. To answer your question: the previous conference paper only covers the `gmm_diag` class, while the JOSS article would cover both the `gmm_diag` class and the newer `gmm_full` class.  Furthermore, the previous paper is at a minor local conference on signal processing, while JOSS directly targets open source software (ie. it's a better fit), as well as having wider reach and prestige.

I will update the citation within the documentation to point to the JOSS article if it is accepted.

**Comment by arfon** [comment]
@conradsnicta - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by conradsnicta** [comment]
@arfon - DOI of the archive: 10.5281/zenodo.1012627  (http://dx.doi.org/10.5281/zenodo.1012627)
Corresponding paper source: https://github.com/conradsnicta/armadillo-gmm/tree/master/paper/

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1012627 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1012627" target="_blank">10.5281/zenodo.1012627</a> is the archive.

**Comment by arfon** [comment]
@jordigh - many thanks for your review ✨ 

@conradsnicta - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00365 ⚡️ 🚀 💥
