### ISSUE TITLE
[PRE REVIEW]: Go-HEP: libraries for High Energy Physics analyses in Go

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#369]
**Submitting author:** @sbinet (<a href="http://orcid.org/0000-0003-4913-6104">Sebastien Binet</a>)
**Repository:** <a href="https://github.com/go-hep/hep" target ="_blank">https://github.com/go-hep/hep</a>
**Version:** v0.4
**Editor:** @arfon
**Reviewer:** @jpivarski

**Author instructions**

Thanks for submitting your paper to JOSS @sbinet. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@sbinet if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @sbinet. Many thanks for your submission to JOSS.

Please review the [author guidelines](http://joss.theoj.org/about#author_guidelines) and prepare a `paper.md` and `paper.bib` file and add them to your repository. Once you've got those in place we can start looking for an editor and reviewer for your submission.

**Comment by sbinet** [comment]
@arfon hello,

I put them in a branch+PR so I could incorporate all reviewers' comments in one go: go-hep/hep#88.

also, it wasn't clear to me whether they had to be at the root of the repo or inside their own directory (and, in that case, whether that directory's name was constrained by some convention).
so I put the `paper.*` files under a directory `joss-paper`, here:

 - https://github.com/go-hep/hep/blob/joss-paper/joss-paper/paper.md
 - https://github.com/go-hep/hep/blob/joss-paper/joss-paper/paper.bib

**Comment by sbinet** [comment]
also, I didn't notice at first but I think I could propose @jpivarski as a potential reviewer.

**Comment by jpivarski** [comment]
In fact, I'd like to review the go-hep code, as I've been meaning to go through it carefully at some point anyway. (I want to learn how you walk through ROOT headers, compared to RIO and root4j.) I have zero experience with Go, so I can't speak to a proper use of Go style, but I have been intending to learn it and this seems to be as good a reason as any.

Other than lack of familiarity with the language, I would be a good choice of reviewer because I'm familiar with the domain, the details of the ROOT file format, and I'm neutral: I don't have any competing projects or conflict of interest. (root4j is for a completely different purpose.) I didn't write any parts of go-hep, naturally.

It would have to be after ACAT (next week), though. There's just a few more conferences this year, so if this review is in the fall, that would be perfect.

**Comment by sbinet** [comment]
SGTM

**Comment by arfon** [comment]
> I put them in a branch+PR so I could incorporate all reviewers' comments in one go: go-hep/hep#88.

Got it. Thanks.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @jpivarski as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @jpivarski

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/372. Feel free to close this issue now!

**Comment by arfon** [comment]
@sbinet @jpivarski - see you over in #372 for the actual review.
