### ISSUE TITLE
Submission: tidytext: Text Mining and Analysis Using Tidy Data Principles in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#37]
**Submitting author:** @juliasilge (<a href="http://orcid.org/0000-0002-3671-836X">Julia Silge</a>)
**Repository:** <a href="https://github.com/juliasilge/tidytext" target ="_blank">https://github.com/juliasilge/tidytext</a>
**Version:** v0.1.1
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.56714" target ="_blank">http://dx.doi.org/10.5281/zenodo.56714</a>

## Status

[![status](http://joss.theoj.org/papers/89fd1099620268fe0342ffdcdf66776f/status.svg)](http://joss.theoj.org/papers/89fd1099620268fe0342ffdcdf66776f)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/89fd1099620268fe0342ffdcdf66776f"><img src="http://joss.theoj.org/papers/89fd1099620268fe0342ffdcdf66776f/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/89fd1099620268fe0342ffdcdf66776f/status.svg)](http://joss.theoj.org/papers/89fd1099620268fe0342ffdcdf66776f)
```

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/juliasilge/tidytext">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.1)?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00037.pdf](https://github.com/openjournals/joss-reviews/files/355835/10.21105.joss.00037.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by rmflight** [comment]
:hand: I am reviewing this

Robert

**Comment by juliasilge** [comment]
I will mention @dgrtwo here so he can follow along as well.

**Comment by rmflight** [comment]
Regarding LICENSE, the LICENSE is the standard CRAN implementation of the MIT LICENSE, which while not exactly standard for OSS, is the standard for CRAN. Therefore I am checking it off.

**Comment by rmflight** [comment]
Below is my review, which is basically copy pasting the above checklist, with some commentary interspersed. All checked off, I recommend to **publish as-is**.

@juliasilge and @dgrtwo: one of the vignettes installing from CRAN did not have the correct title, but I see in the github repo it has been corrected, so no issues. That was the only beef I had.

## Reviewer questions

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/juliasilge/tidytext">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?

> Regarding LICENSE, the LICENSE is the standard CRAN implementation of the MIT LICENSE, which while not exactly standard for OSS, is the standard for CRAN. Therefore I am checking it off.

- [x] **Version:** Does the release version given match the GitHub release (v0.1.1)?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

> dependencies are handled by the R package installation

- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

> The README provides well worked examples showing how the software works, on a real dataset

> Various functions have examples, and also included are 4 vignettes (R long-form documentation) that also demonstrate various analyses.

- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00037.pdf](https://github.com/openjournals/joss-reviews/files/355835/10.21105.joss.00037.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

## Issues with Submission

The CRAN installed version does not have the correct title for one of the vignettes, but I would think that it will propagate soon.

## Recommendation

**Publish as-is**

**Comment by juliasilge** [comment]
Regarding the package's LICENSE, I did try submitting to CRAN with the contents of the whole MIT license in the LICENSE file, as discussed in the [author guidelines](http://joss.theoj.org/about#author_guidelines), but the CRAN administrators did not go for it.

**Comment by rmflight** [comment]
Right, and I figured that was an issue. That is why I just checked it anyway, because you followed the CRAN guidelines, which is where the package is "published" for ease of installation purposes.

**Comment by arfon** [comment]
Thanks for the rapid review @rmflight!

@juliasilge - the final thing here is to make an archive of the software in Zenodo/figshare/other similar service and update this thread with the archive DOI. I can then move forward with accepting this submission :grin:

**Comment by juliasilge** [comment]
I turned on Zenodo before our last, most recent release so there is an archive of v0.1.1, the current version and what is on CRAN right now:
[![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.56714.svg)](http://dx.doi.org/10.5281/zenodo.56714)

Let me know if anything needs to be changed about that, or if I need to make another release for the JOSS submission specifically or anything like that.

**Comment by arfon** [comment]
@juliasilge - this is now accepted into JOSS. Your DOI is http://dx.doi.org/10.21105/joss.00037 🎉 🚀 💥
