### ISSUE TITLE
[PRE REVIEW]: GGLasso - a Python package for General Graphical Lasso computation

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3836]
**Submitting author:** @fabian-sp (<a href="http://orcid.org/0000-0002-0673-9944">Fabian Schaipp</a>)
**Repository:** <a href="https://github.com/fabian-sp/GGLasso" target ="_blank">https://github.com/fabian-sp/GGLasso</a>
**Version:** v0.1.4
**Editor:** @gkthiruvathukal
**Reviewers:** @papachristoumarios, @jameschapman19
**Managing EiC:** Kevin M. Moerman

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2e08880df7b4a4965fd64bd4eeb3d169/status.svg)](https://joss.theoj.org/papers/2e08880df7b4a4965fd64bd4eeb3d169)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2e08880df7b4a4965fd64bd4eeb3d169"><img src="https://joss.theoj.org/papers/2e08880df7b4a4965fd64bd4eeb3d169/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2e08880df7b4a4965fd64bd4eeb3d169/status.svg)](https://joss.theoj.org/papers/2e08880df7b4a4965fd64bd4eeb3d169)
```

**Author instructions**

Thanks for submitting your paper to JOSS @fabian-sp. **Currently, there isn't an JOSS editor assigned** to your paper.

@fabian-sp if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by muellsen** [comment]
@whedon generate pdf

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon invite @gkthiruvathukal as editor

**Comment by gkthiruvathukal** [comment]
@Kevin-Mattheus-Moerman Thanks for the invite. 

@fabian-s Beginning with this submission, I am asking all authors to comment on why their proposed package cannot be submitted to the upstream projects already addressing similar issues. In this case, it would be `scikit-learn`, since the "single Lasso" technique is mentioned in your paper as related work.  Please keep in mind that your answer does not preclude consideration in JOSS. It's more about building upon a successful foundation and ensuring sustainability of the work. 

Lastly, before I can proceed to review, I will need your help to suggest some prospective reviewers. Given that we are in reduced service mode and some reviewers may  not be available, I need at least FIVE reviewers (without the @ mention) to be listed so I can start inviting folks once I receive your response to the above question(s).

**Comment by fabian-sp** [comment]
Here is our list of reviewer suggestions:

joewandy
jameschapman19
papachristoumarios
afrubin
krother
andim
