### ISSUE TITLE
[PRE REVIEW]: pyprop8: A lightweight code to simulate seismic observables in a layered half-space

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3858]
**Submitting author:** @valentineap (<a href="http://orcid.org/0000-0001-6134-9351">Andrew Valentine</a>)
**Repository:** https://github.com/valentineap/pyprop8
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0
**Editor:** @leouieda
**Reviewers:** @hemmelig, @hfmark
**Managing EiC:** Kristen Thyng

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/695768d664162b443c5dec5f7accb114/status.svg)](https://joss.theoj.org/papers/695768d664162b443c5dec5f7accb114)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/695768d664162b443c5dec5f7accb114"><img src="https://joss.theoj.org/papers/695768d664162b443c5dec5f7accb114/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/695768d664162b443c5dec5f7accb114/status.svg)](https://joss.theoj.org/papers/695768d664162b443c5dec5f7accb114)
```

**Author instructions**

Thanks for submitting your paper to JOSS @valentineap. **Currently, there isn't an JOSS editor assigned** to your paper.

@valentineap if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by leouieda** [comment]
👋🏽 Hi @kthyng happy to edit this. The other paper is pretty much done so I think I can take this on 👍🏽

**Comment by leouieda** [comment]
@whedon assign @leouieda as editor

**Comment by whedon** [comment]
OK, the editor is @leouieda

**Comment by leouieda** [comment]
👋🏽 Hi @valentineap thank you for your submission to JOSS! I'll first do some light editorial proof-reading of your paper and package and then search for suitable reviewers. In the mean time, you can:

1. Suggest suitable reviewers (who you already know or from [our list of reviewers](https://bit.ly/joss-reviewers)). Please include their GitHub username without @-mentioning to avoid spamming their notifications (e.g. `leouieda` instead of @leouieda).
2. Please include the missing DOIs in your references picked up by our bot Whedon above.
3. Please also add citations to numpy and scipy, which you mention as dependencies of pyprop8.

When you push changes to your paper, you can ask Whedon to regenerate the PDF by commenting `@whedon generate pdf` here. You can also use the preview service to test paper compilation in a separate branch before merging: https://whedon.theoj.org/

**Comment by valentineap** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03858/joss.03858/10.21105.joss.03858.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03858/joss.03858/10.21105.joss.03858.pdf) :page_facing_up: :point_left:

**Comment by valentineap** [comment]
Thanks for taking this on, @leouieda!

DOIs now fixed and scipy/numpy references added.

Reviewers: I'm a bit stuck here - a couple of names come to mind, but tracking those people down on github is proving difficult! I'm sure many of the people on the list of reviewers tagged 'seismology' (or perhaps even 'geodesy') would be suitable, but I don't recognise many of the names.

**Comment by valentineap** [comment]
@leouieda Just wanted to check that you're not waiting for further input from me here - as far as I know I have dealt with all the identified issues. (Not intending to nag; I know we're all stupidly busy!)

**Comment by leouieda** [comment]
@valentineap thank you for the ping and I’m really sorry for the delay on this. I’ll proceed to invite reviewers so that we can get this going. As soon as we can find 2 willing reviewers we will start the review process, which takes around 2-4 weeks usually. Since there are holidays coming up for many of us, it may be a bit longer.

**Comment by leouieda** [comment]
:wave: @seisman @sgkang would you be interested in reviewing this submission for [JOSS](https://joss.theoj.org/)? This paper is about a software package that does forward modelling and calculates gradients (for inversion) of seismic waves in 1D layered media. It’s meant as a research and teaching/outreach tool. Your combined expertise in seismology, inverse problems, and education would be much appreciated 🙂

Reviews are done entirely through GitHub (issues and pull requests). Please refer to our reviewer guidelines for more information about JOSS and our review process (feel free to ask me any questions as well): https://joss.readthedocs.io/en/latest/review_criteria.html Reviews usually take 2-4 weeks but we can certainly make accommodations if more time is needed (particularly this close to the end of the year holidays).

If you are not able to review at this time, please let me know if you have recommendations for other reviewers. **Please recommend without mentioning a handle to avoid notifying the person** (e.g., you would refer to me as leouieda instead of @leouieda). This way we attempt to reduce the number of people who are subscribed to this thread.

**Comment by seisman** [comment]
@leouieda Hi Leo, thanks for your invitation. It looks really interesting, but I'm afraid I don't have much time in the next few months. 

I would like to recommend my former colleague, Dr. Zhou Lu (GitHub handle: `luzhou-git`, Google Scholar: https://scholar.google.com/citations?user=V2Ijx9EAAAAJ), for review. He is a seismologist working on stress and crustal deformations, and also has a lot of experience in simulating earthquake dynamic and static deformations. I believe he is qualified for reviewing this submission.

**Comment by leouieda** [comment]
@seisman thanks for the suggestion and quick response 🙂 

:wave: @luzhou-git would you be interested in reviewing this submission for JOSS? Please see my comment above for a summary of the paper and instructions on how JOSS reviews work. Your expertise in deformation modelling would be much appreciated.

**Comment by meghanrjones** [comment]
Hi @leouieda, thanks for the invitation. I won't be able to review this submission, but I would like to recommend `hfmark` instead as a reviewer. Hannah is an expert in seismology, teaching, and related software tools.

**Comment by hemmelig** [comment]
Hi @leouieda - sounds good, I'm happy to take on this review. Is there any additional information beyond that available on the JOSS review criteria page of which I should be aware, as a first time reviewer? For example, is there an official review template? I have read the review checklist page of the JOSS documentation and was planning to just base my review around that. Thanks.

**Comment by leouieda** [comment]
👋🏽  @hfmark would you be interested in reviewing this submission for JOSS? Please see [my comment above](https://github.com/openjournals/joss-reviews/issues/3858#issuecomment-995500979) for a summary of the paper and instructions on how JOSS reviews work. Your expertise in seismology and experience with Python software would be appreciated!

**Comment by leouieda** [comment]
@meghanrjones thank you for considering and for the recommendation! 

@hemmelig thank you agreeing to review! The JOSS review is a bit different from traditional reviews. There will be a checklist with criteria for you to fill out (that comes after reviewers are assigned and we actually start the review process). Reviewers are also encouraged to open issues and pull requests in the source repository to work with authors towards meeting all of the JOSS requirements and improving the software overall. So there is no template for a one-off review and this is more of a conversation between authors, reviewers, and editors. Which is kind of how we work on open-source in general (and on purpose). 

For now, we just need to see if we can get a second reviewer assigned before starting the review. If you have any questions about the process at any time, I’m more than happy to answer 🙂

**Comment by leouieda** [comment]
@editorialbot add @hemmelig as reviewer

**Comment by hfmark** [comment]
Hi @leouieda, I'm happy to review this. I also haven't reviewed for JOSS before - I'll look over the documentation.

**Comment by leouieda** [comment]
Thank you @hfmark! 🚀  Please see [our reviewer guide](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) for more details and feel to ask any time.  I'll post a comment with more general instructions as soon as I start the review thread.

**Comment by leouieda** [comment]
@editorialbot add @hfmark as reviewer

**Comment by leouieda** [comment]
@editorialbot start review

**Comment by leouieda** [comment]
@valentineap @hfmark @hemmelig I've now started the review in issue #4217. This means all communication should now be done through that issue instead of this one. I'll post some more instructions there and there should already be information provided by our @editorialbot (formerly @whedon). Thank you for agreeing to review this submission!
