### ISSUE TITLE
[PRE REVIEW]: pyExoRaMa: an interactive tool to investigate the radius-mass diagram for exoplanets

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4013]
**Submitting author:** @francescoa97outlook (<a href="http://orcid.org/0000-0003-1316-1033">Francesco Amadori</a>)
**Repository:** <a href="https://github.com/francescoa97outlook/pyExoRaMa" target ="_blank">https://github.com/francescoa97outlook/pyExoRaMa</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Arfon Smith

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b37a163084e4d4c3bfbb4fcd6055e205/status.svg)](https://joss.theoj.org/papers/b37a163084e4d4c3bfbb4fcd6055e205)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b37a163084e4d4c3bfbb4fcd6055e205"><img src="https://joss.theoj.org/papers/b37a163084e4d4c3bfbb4fcd6055e205/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b37a163084e4d4c3bfbb4fcd6055e205/status.svg)](https://joss.theoj.org/papers/b37a163084e4d4c3bfbb4fcd6055e205)
```

**Author instructions**

Thanks for submitting your paper to JOSS @francescoa97outlook. **Currently, there isn't an JOSS editor assigned** to your paper.

@francescoa97outlook if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1670

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1088/0067-0049/215/2/21 is OK
- 10.1111/j.1365-2966.2011.19399.x is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (209.4 files/s, 31762.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          17            232             43           2712
Markdown                         3             43              0            115
TeX                              1              2              0             39
-------------------------------------------------------------------------------
SUM:                            21            277             43           2866
-------------------------------------------------------------------------------


Statistical information for the repository 'dd67425c43f8486158d84f29' was
gathered on 2021/12/20.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Francesco                        5          2833            205           72.14
Francesco Amadori               20           766            407           27.86

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Francesco                  2402           84.8          0.0                1.75
Francesco Amadori           585           76.4          0.2                0.17
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04013/joss.04013/10.21105.joss.04013.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04013/joss.04013/10.21105.joss.04013.pdf) :page_facing_up: :point_left:

**Comment by arfon** [comment]
@francescoa97outlook – thanks for your submission to JOSS. Before I look for an editor to handle this submission, I'd like to better understand what has already been published here. 

- Your first citation to `Zeng:2021` seems to link to a different publication (see here: https://github.com/francescoa97outlook/pyExoRaMa/blob/main/paper/paper.bib#L2). Please correct this to the actual URL.
- Please add an empty section at the end of your paper named `# References` for the bibliography.
- Any notes you have on what `Zeng:2021` is, i.e., what the difference between that software and this package would be very welcome.

**Comment by francescoa97outlook** [comment]
Dear Mr. Arfon Smith
I answer point by point:



  *   Your first citation to Zeng:2021 seems to link to a different publication (see here: https://github.com/francescoa97outlook/pyExoRaMa/blob/main/paper/paper.bib#L2<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffrancescoa97outlook%2FpyExoRaMa%2Fblob%2Fmain%2Fpaper%2Fpaper.bib%23L2&data=04%7C01%7C%7C7f91cb599f234809329c08d9c3acd894%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755969391832705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Dnp88fbBIgme4bOuNWRLhhpJjFKGFV64%2FMtFQKg8zqA%3D&reserved=0>). Please correct this to the actual URL.
I deleted the link (it was an error). The problem is that the original paper has not already been published. It was submitted by Zeng Li on 15th November. We asked him how much time will be necessary to be officially published, so I report his answer:
“Hi Mario and Francesco,
I will find out and let you know. I also emailed them to ask.
Since the submission of the final proof on Nov.15th, ApJ has not informed me an exact publication date but it said it might take them a month or even two months due to shortage of personels in UK production office. So I suspect it will come out in January or latest February.
Best,
Li”
Is it possible to publish this paper and then adjust the bibliography once the link and the DOI are available?
Have you other suggestions on how to proceed?
We can also wait until the paper is published! Maybe we can advise you to proceed with the submission once it is available.



  *   Please add an empty section at the end of your paper named # References for the bibliography.
I have corrected it.

•          Any notes you have on what Zeng:2021 is, i.e., what the difference between that software and this package would be very welcome.

I have added a new chapter in the paper that explains all the main differences between the two software.

Thank you in advance and let me know if you need anything else!
Have a good day, kind regards,
Francesco

Da: Arfon ***@***.***>
Inviato: lunedì 20 dicembre 2021 12:35
A: ***@***.***>
Cc: Francesco ***@***.***>; ***@***.***>
Oggetto: Re: [openjournals/joss-reviews] [PRE REVIEW]: pyExoRaMa: an interactive tool to investigate the radius-mass diagram for exoplanets (Issue #4013)


@francescoa97outlook<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffrancescoa97outlook&data=04%7C01%7C%7C7f91cb599f234809329c08d9c3acd894%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755969391832705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HhqHaRgWbNpKnys8H94H6R2l2QaPCtKilT5n1zOrXoY%3D&reserved=0> – thanks for your submission to JOSS. Before I look for an editor to handle this submission, I'd like to better understand what has already been published here.

  *   Your first citation to Zeng:2021 seems to link to a different publication (see here: https://github.com/francescoa97outlook/pyExoRaMa/blob/main/paper/paper.bib#L2<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffrancescoa97outlook%2FpyExoRaMa%2Fblob%2Fmain%2Fpaper%2Fpaper.bib%23L2&data=04%7C01%7C%7C7f91cb599f234809329c08d9c3acd894%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755969391832705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Dnp88fbBIgme4bOuNWRLhhpJjFKGFV64%2FMtFQKg8zqA%3D&reserved=0>). Please correct this to the actual URL.
  *   Please add an empty section at the end of your paper named # References for the bibliography.
  *   Any notes you have on what Zeng:2021 is, i.e., what the difference between that software and this package would be very welcome.

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopenjournals%2Fjoss-reviews%2Fissues%2F4013%23issuecomment-997845506&data=04%7C01%7C%7C7f91cb599f234809329c08d9c3acd894%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755969391832705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y%2BeO5zkm7zcjwWtTiPxD9sMaX8xUniNgy1%2BzsjHQ6mc%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQ3LLL6CJX3UN5TSI6YJB5DUR4IITANCNFSM5KNOSTWA&data=04%7C01%7C%7C7f91cb599f234809329c08d9c3acd894%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755969391832705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=c6DqlCnVgou6r8wKVh3JHifaOeE72%2FU7bkoX57gD8s4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C7f91cb599f234809329c08d9c3acd894%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755969391832705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DQ3RZtnaPPiJZLUCKgRZ5TCXM5hHceNreqtYZtVhOZw%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C7f91cb599f234809329c08d9c3acd894%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755969391832705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZeZZo%2BWE4ikqo%2F%2FJyNUXvaKDgbfPXLoXhxj0o2RKI7E%3D&reserved=0>.

**Comment by francescoa97outlook** [comment]
I suggest @jessie-dotson due to the fact he is related to exoplanets

> **Submitting author:** @francescoa97outlook ([Francesco Amadori](http://orcid.org/0000-0003-1316-1033)) **Repository:** https://github.com/francescoa97outlook/pyExoRaMa **Version:** v1.0.0 **Editor:** Pending **Reviewer:** Pending **Managing EiC:** Arfon Smith
> 
> **⚠️ JOSS reduced service mode ⚠️**
> 
> Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).
> ## Status
> 
> [![status](https://camo.githubusercontent.com/4abc00681f63cc4a97882e9c0bd1e12a6cb94b2ff177a507d7378bc099822dd5/68747470733a2f2f6a6f73732e7468656f6a2e6f72672f7061706572732f62333761313633303834653464346333626662623466636436303535653230352f7374617475732e737667)](https://joss.theoj.org/papers/b37a163084e4d4c3bfbb4fcd6055e205)
> 
> Status badge code:
> 
> ```
> HTML: <a href="https://joss.theoj.org/papers/b37a163084e4d4c3bfbb4fcd6055e205"><img src="https://joss.theoj.org/papers/b37a163084e4d4c3bfbb4fcd6055e205/status.svg"></a>
> Markdown: [![status](https://joss.theoj.org/papers/b37a163084e4d4c3bfbb4fcd6055e205/status.svg)](https://joss.theoj.org/papers/b37a163084e4d4c3bfbb4fcd6055e205)
> ```
> 
> **Author instructions**
> 
> Thanks for submitting your paper to JOSS @francescoa97outlook. **Currently, there isn't an JOSS editor assigned** to your paper.
> 
> @francescoa97outlook if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).
> 
> **Editor instructions**
> 
> The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:
> 
> ```
> @whedon commands
> ```

I suggest jessie-dotson from your list due to the fact he is related to exoplanets

**Comment by arfon** [comment]
OK, thanks for the additional information @francescoa97outlook.

> We can also wait until the paper is published! Maybe we can advise you to proceed with the submission once it is available.

I would like to better understand the nature of the Mathematica codebase and this one before proceeding with sending this submission out for review. The question I'm trying to understand is whether or not this submission meets our threshold for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort), especially as this is a port of another codebase.

Would it be possible for you to link to the previous (Mathematica-based) codebase?

/ cc @christinahedges and @dfm for their thoughts here.

**Comment by francescoa97outlook** [comment]
Dear Arfon
[ManipulatePlanetCode_zeng20211021.nb.zip](https://github.com/openjournals/joss-reviews/files/7756722/ManipulatePlanetCode_zeng20211021.nb.zip)

I attach here the version of the Mathematica code given to me by Li Zeng.  
This version contains features that are not present in the official release, due to the fact that Li has added later other parts before sending us, to implement them in Python (i.e. some related to the pure-Hydrogen that are not present in the Mathematica official version, which that will be published on January, but only in the python version). 
Thanks for your time and patience,
Francesco

**Comment by arfon** [comment]
@whedon query scope

@francescoa97outlook – many thanks for sharing this. I'm flagging the scope of this submission to bring it to the attention of a few other editors. We'll be back with a decision in the next couple of weeks.

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by francescoa97outlook** [comment]
> @whedon query scope
> 
> @francescoa97outlook – many thanks for sharing this. I'm flagging the scope of this submission to bring it to the attention of a few other editors. We'll be back with a decision in the next couple of weeks.

Many thanks!

**Comment by francescoa97outlook** [comment]
> @whedon query scope
> 
> @francescoa97outlook – many thanks for sharing this. I'm flagging the scope of this submission to bring it to the attention of a few other editors. We'll be back with a decision in the next couple of weeks.

Dear Arfon! I hope everything is fine!
I have good news, I updated the bibliography with the right reference of Li Zeng article, his paper has just been published!
Thanks for your time, 
I wish you a happy new year,
Francesco

**Comment by arfon** [comment]
:wave: – many thanks again for your submission to JOSS @francescoa97outlook. 

After a review by our editorial team, this submission has been deemed out of scope for JOSS. A number of concerns were raised by our editors but the primary one is that the majority of the functionality of this software is focused on plotting/visualisation and visualisation tools are not allowed in JOSS.

Some additional concerns that were raised by the team:

- This package doesn't offer reusable functionality for researchers.
- The functionality isn't significant beyond what's also possible with other tools (e.g., the Exoplanet Archive)
- The software _as is_ is significantly below the standard that would pass a JOSS review (missing tests, very limited documentation, lack of standard packaging).

One possible alternative to JOSS is to follow [GitHub's guide](https://guides.github.com/activities/citable-code/) on how to create a permanent archive and DOI for your software. This DOI can then be used by others to cite your work.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.
