### ISSUE TITLE
[PRE REVIEW]: Singularity Registry: Open Source Registry for Singularity Images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#419]
**Submitting author:** @vsoch (<a href="http://orcid.org/0000-0002-4387-3819">Vanessa Sochat</a>)
**Repository:** <a href="https://www.github.com/singularityhub/sregistry" target ="_blank">https://www.github.com/singularityhub/sregistry</a>
**Version:** v1.0.0
**Editor:** @pjotrp
**Reviewer:** @smoe

**Author instructions**

Thanks for submitting your paper to JOSS @vsoch. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@vsoch if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @pjotrp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
👋 @pjotrp - the submitting author suggested you as the editor.

**Comment by vsoch** [comment]
Hi @whedon, @arfon, and @pjotrp - many thanks for the introduction, and looking forward to working on this together.

**Comment by pjotrp** [comment]
@whedon assing @pjotrp as editor

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by pjotrp** [comment]
Dear @smoe would you care to review this Singularity submission?

**Comment by smoe** [comment]
Dear @pjotrp,

Singularity is important and everything that fosters its acceptance is appreciated.

The setup is technically sound. I like the distributed effort. What seems missing is the concept of mirroring images for long time availability when a site goes down, which then truly preserves setups for scientific reproducibility. For that to happen, we would need identifiers that are not URL-dependent, though. Another feature I am missing is the automated creation of images, which would nicely work together with the description of CWL workflows that features references to software registries which in turn started to have references to Linux distributions (OMICtools now, bio.tools soon, I hope) and Debian at least having references to the registries already.

Not having an exact clue what you ask me to review now, I went through your JOSS author guidelines on http://joss.theoj.org/about#author_guidelines:
 * License: BSD 3 clause - ok
 * paper.md is short, a bit too short IMHO, but present. Missing for my heart is a clarification how functionality and contributors differ from http://singularity.lbl.gov/, singularity-hub.org and github. Sorry, this is mostly trivial, but I strongly suggest to make these few lines as simple as possible. Frankly, I do not even expect everyone to know what a container is. Should users of docker also consider singularityhub instead of hub.docker.io? Are there features of singularity that are particularly supported by singularityhub?
 * authors found
 * The "summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience" as I already outlined above is marginal.
 * The "clear statement of need that illustrates the purpose of the software" we have - not that any fan of singularity would need it.
 * The "list of key references including a link to the software archive" is weak. Once the paper gets extended with the prior requested bit of extra content for those who are not using singularity already, this will become better. Maybe the authors' guide is a bit vague here. There is the citation system http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html that should be used.
 * Does it "Mention (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it"? No, it doesn't. I described in my initial lines who is waiting for it, though that is possibly too immature to be put into this paper.md. But you can of course outline that you foresee these kind of interactions between your service and others.

The other "requirements for submission" I find kind of redundant and I consider them to be fulfilled.

What I would typically do now is to install this locally and see if this works, which I kind of hope not to be imposed on me because the authors declare to us that they are working with exactly that setup themselves and that what we see is live on https://singularity-hub.org/collections or elsewhere - this is what should be explicitly stated in the paper.md, too.

Otherwise, I hope this was not too obvious, I am a fan.

**Comment by pjotrp** [comment]
Thanks Steffen - we'll have to move to official review so you can tick the boxes. I'll copy your text in.

**Comment by pjotrp** [comment]
@whedon assign @smoe as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @smoe

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/426. Feel free to close this issue now!
