### ISSUE TITLE
[REVIEW]: The psycho Package: an Efficient and Publishing-Oriented Workflow for Psychological Science

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#470]
**Submitting author:** @DominiqueMakowski (<a href="http://orcid.org/0000-0001-5375-9967">Dominique Makowski</a>)
**Repository:** <a href="https://github.com/neuropsychology/psycho.R" target ="_blank">https://github.com/neuropsychology/psycho.R</a>
**Version:** 0.0.2
**Editor:** @leeper
**Reviewer:** @SachaEpskamp
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1165620" target="_blank">10.5281/zenodo.1165620</a>

## Status

[![status](http://joss.theoj.org/papers/0112f81644faa4231be0634f3c0590b0/status.svg)](http://joss.theoj.org/papers/0112f81644faa4231be0634f3c0590b0)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0112f81644faa4231be0634f3c0590b0"><img src="http://joss.theoj.org/papers/0112f81644faa4231be0634f3c0590b0/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0112f81644faa4231be0634f3c0590b0/status.svg)](http://joss.theoj.org/papers/0112f81644faa4231be0634f3c0590b0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/neuropsychology/psycho.R" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@SachaEpskamp, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @leeper know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/neuropsychology/psycho.R">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.0.2)?
- [x] **Authorship:** Has the submitting author (@DominiqueMakowski) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @SachaEpskamp it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #470 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/470/paper/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:75:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #470 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/470/paper/paper.md): did not find expected key while parsing a block mapping at line 2 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/processor.rb:26:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/lib/whedon/processor.rb:26:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-33e05183aa0d/bin/whedon:75:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

```

**Comment by leeper** [comment]
Hi @SachaEpskamp, just a quick reminder about this review!

**Comment by SachaEpskamp** [comment]
Hi, sorry for the delay! This looks like a very nice small package that could be useful in several ways. The installation and examples all perform as expected. Below are some observations I had in no particular order.

Best, Sacha



1. Just entering an object in the console does not print it:
data("bfi")
cres <- correlation(bfi[,1:25])
cres # does nothing
print(cres) # prints results

2. It is not clear where I can find and/or if there are arguments to the print method to, say, the output of correlation( )

3. I don't really like the NA's printed in the correlation output, would be nicer if that was an empty string by default?

4. It would be nice if polychoric and polyserial correlations could be included. The qgraph function cor_auto detects values and uses the lavaan function lavCor to obtain polychoric/polyserial correlations. Perhaps something like this could be included in correlation( ) as well?

5. I like the inclusion of partial correlations. Perhaps an option could be to estimate these using the glasso package rather than significance testing? the EBICglasso function from qgraph, which wraps around glasso from the glasso package, should easily be useable to this end in the backend.

6. It's not clear from the documentation what, if any, arguments I can use in the plot method. For example, can I change the colors of the assess plot (which is really nice btw).

7. The documentation should make clearer what parts are based on other packages. For example, n_factors uses qgraph's cor_auto in the background, which uses lavaan in the background, but both packages are not referenced. I think the psycho package also heavily relies on the psych package, but it is not referenced in the documentation at all.

8. I'd suggest to set the argument forcePD = FALSE in cor_auto. It was a bad design choice of me to make that default to TRUE, and has lead to a lot of problems.

9. Perhaps EGA (DOI:10.1371/journal.pone.0174035) can be included in n_factors?

10. I like the normalize() function, but don't really like the name, as it implies it will make data normally distributed (as the huge.npn() function in huge for example). The function standardizes, not normalizes. Perhaps it could be renamed to standardize?

10. The analyze() function is nice, but I don't really like the string labeling of effect sizes as "Very small", as I am always in favor of numeric effect size measures rather than  labels based on arbitrary thresholds. Can't the numeric effect size be printed instead?

11. When printing the output of analyze( ), I would make use of the cat( ) function to present the output nicely instead of the print function. That is, instead of:

> print(results)
[1] "The overall model predicting ... successfully converged and explained 10.57% of the variance of the endogen (the conditional R2). The variance explained by the fixed effects was of 0.56% (the marginal R2) and the one explained by the random effects of 10.01%."
[2] "The effect of (Intercept) was [NOT] significant (beta = 0.092, SE = 0.22, t(5.81) = 0.42, p > .1) and can be considered as very small (std. beta = 0, std. SE = 0)."                                                                                                
[3] "The effect of ConditionB was [NOT] significant (beta = -0.15, SE = 0.20, t(95.00) = -0.78, p > .1) and can be considered as very small (std. beta = -0.076, std. SE = 0.097)." 

I think the following would be nicer:

> print(results)
The overall model predicting ... successfully converged and explained 10.57% of the variance of the endogen (the conditional R2). The variance explained by the fixed effects was of 0.56% (the marginal R2) and the one explained by the random effects of 10.01%.

	- The effect of (Intercept) was [NOT] significant (beta = 0.092, SE = 0.22, t(5.81) = 0.42, p > .1) and can be considered as very small (std. beta = 0, std. SE = 0).
	- The effect of ConditionB was [NOT] significant (beta = -0.15, SE = 0.20, t(95.00) = -0.78, p > .1) and can be considered as very small (std. beta = -0.076, std. SE = 0.097).

Perhaps the invisible() function can be used to still return the character vector with these texts as well so that the function can be used in a .Rnw or .Rmd file to generate a report though.

**Comment by leeper** [comment]
Thank you, @SachaEpskamp! Great review!

@DominiqueMakowski Can you please give this review a read, make changes as appropriate, and respond to Sacha's points on this thread?

**Comment by DominiqueMakowski** [comment]
Wow, thanks @SachaEpskamp for these very useful comments! (altough some of which will require from me some more learning on programming and statistics 😄). 

I'll open an issue for each one of them to track progress and try to work out as many as I can. 

@leeper, I'll come back here once I've given my best to let you know of the advances.

Thanks again ☺️

**Comment by DominiqueMakowski** [comment]
@leeper I've tackled as many points as I could, and left three open (waiting for opinion or help). @SachaEpskamp Again, thanks a lot for your great suggestions 😌

**Comment by leeper** [comment]
@DominiqueMakowski I'm happy with this as is. Can you please generate a DOI archive for the software in its current form (e.g., using Zenodo) and let me know the DOI?

**Comment by DominiqueMakowski** [comment]
@leeper The DOI is the following: 10.5281/zenodo.1165620

Thanks a lot

**Comment by leeper** [comment]
@whedon set 10.5281/zenodo.1165620 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1165620" target="_blank">10.5281/zenodo.1165620</a> is the archive.

**Comment by leeper** [comment]
Okay. This all looks good. Thank you, @SachaEpskamp for your great review! Thanks, too, @DominiqueMakowski, for the submission!

@arfon This one's for you.

**Comment by arfon** [comment]
@SachaEpskamp - thanks for your review and to @leeper for editing this submission ✨ 

@DominiqueMakowski - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00470 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00470/status.svg)](https://doi.org/10.21105/joss.00470)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00470/status.svg)](https://doi.org/10.21105/joss.00470)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html

**Comment by DominiqueMakowski** [comment]
I added the paper link in the readme,

Thanks again everyone!! 🎉

**Comment by ajstewartlang** [comment]
:wave: @SachaEpskamp might you have the bandwidth to review the following submission that I'm currently editing please? [[PRE REVIEW]: WPSS, a web panel sample service](https://github.com/CDSP-SCPO/WPSS-for-ESS-webpanel)
