### ISSUE TITLE
[REVIEW]: fuse: An R package for ensemble Hydrological Modelling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#52]
**Submitting author:** @cvitolo (<a href="http://orcid.org/0000-0002-4252-1176">Claudia Vitolo</a>)
**Repository:** <a href="https://github.com/cvitolo/fuse" target ="_blank">https://github.com/cvitolo/fuse</a>
**Version:** v3.0.0
**Editor:** @arfon
**Reviewer:** @masalmon 
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.212822" target="_blank">10.5281/zenodo.212822</a>

## Status

[![status](http://joss.theoj.org/papers/392a55daada04a86f95eaa8da134a28d/status.svg)](http://joss.theoj.org/papers/392a55daada04a86f95eaa8da134a28d)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/392a55daada04a86f95eaa8da134a28d"><img src="http://joss.theoj.org/papers/392a55daada04a86f95eaa8da134a28d/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/392a55daada04a86f95eaa8da134a28d/status.svg)](http://joss.theoj.org/papers/392a55daada04a86f95eaa8da134a28d)
```
### Conflict of interest
- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).
### General checks
- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cvitolo/r_fuse">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v3.0.0)?
### Functionality
- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?
### Documentation
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
### Software paper

Paper PDF: [10.21105.joss.00052.pdf](https://github.com/openjournals/joss-reviews/files/456925/10.21105.joss.00052.pdf)
- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by pragyansmita** [comment]
> library(devtools)
> install_github("cvitolo/r_fuse", subdir = "fuse")
Downloading GitHub repo cvitolo/r_fuse@master
from URL https://api.github.com/repos/cvitolo/r_fuse/zipball/master
Error: Could not find build tools necessary to build fuse

I am using R 3.2.5 and have Rtools33 installed. I am still receiving the above error. Any idea how to move beyond to install fuse. Thanks!

**Comment by pragyansmita** [comment]
:hand: I am reviewing this

**Comment by cvitolo** [comment]
@pragyansmita I'm sorry you cannot install fuse. I work only with Linux machines and I cannot reproduce your problem. I use travis-ci to check that there are no problems with installation and tests. As you can see [here](https://travis-ci.org/cvitolo/r_fuse) the package passes all the tests and builds no problem on a linux machine.

**Comment by masalmon** [comment]
@cvitolo by the way on Travis you can also test on OSX by adding

```
os: 
 - linux
 - osx
```

after ` language: r` at the top of your .travis.yml.

Then you can use Appveyor for continuous integration on Windows (there's a `devtools::use_appveyor()` function which automatically creates the Appveyor config file, and then you need to activate CI for the repository on [Appveyor website](https://www.appveyor.com/) ), quite similarly to what you did on Travis. 

Furthermore on Travis and Appveyor there are options for testing your package with several R versions, I do it [here](https://github.com/ropenscilabs/monkeylearn/blob/master/appveyor.yml) and [here](https://github.com/ropenscilabs/monkeylearn/blob/master/.travis.yml). 

Not sure if it'll help you see @pragyansmita's problem, but who knows :-)

**Comment by cvitolo** [comment]
Many thanks @masalmon!

I just added the os: linux osx lines to .travis.yml. Building the job for osx takes ages, is that normal?

Also tried to configure appveyor but I keep getting this error 'Specify a project or solution file. The directory does not contain a project or solution file.'... not sure how to fix this.

**Comment by masalmon** [comment]
You're welcome!

I don't know for osx, maybe it's just because it's the first build?

I am sorry I can't help for Appveyor, I never had this issue. Did you need to do something specific on Travis because of the sub directory structure?

**Comment by cvitolo** [comment]
I just did:

cd fuse

I tried the same in appveyor but that did not fix the problem

**Comment by masalmon** [comment]
Maybe this http://stackoverflow.com/questions/33411765/check-multiple-subdirectories-using-appveyor can help?

**Comment by masalmon** [comment]
Although that's what you already did...

**Comment by janschulz** [comment]
> Specify a project or solution file. The directory does not contain a project or solution file.

I thought this happens when appveyor doesn't see a appveyor.yml file or the file doesn't have a `build` section (or whatever the section is named which builds the project) -> per default it tries to build a MS Visual Studio solution / project file (like the default makefile for make based systems).

**Comment by jkahn** [comment]
Apologies for intervening, but could these details be discussed in an issue on the submitted project rather than here in the review? 

I'll file a ticket with @arfon to encourage this as a general directive to reviewers.

**Comment by arfon** [comment]
> Apologies for intervening, but could these details be discussed in an issue on the submitted project rather than here in the review?

Good suggestion @jkahn. @masalmon @cvitolo @janschulz - would you mind taking this discussion over to the submission repo (https://github.com/cvitolo/r_fuse)?

**Comment by cvitolo** [comment]
Thanks @arfon! I opened an issue on the r_fuse repo. We will continue the discussion there.

**Comment by cvitolo** [comment]
@arfon I cloned the repository to [fuse](https://github.com/cvitolo/fuse) and moved the package to the root dir. That fixed all the problems with appveyor. Would it be possible to continue the review on the cloned repo?

**Comment by arfon** [comment]
> @arfon I cloned the repository to fuse and moved the package to the root dir. That fixed all the problems with appveyor. Would it be possible to continue the review on the cloned repo? 

@cvitolo - just to clarify. You would like to replace the repository associated with this submission from https://github.com/cvitolo/r_fuse to be https://github.com/cvitolo/fuse?

**Comment by cvitolo** [comment]
Yes,  please.  Would that be possible? Thanks

**Comment by arfon** [comment]
> @arfon Yes,  please.  Would that be possible? Thanks!

Sure thing. The review is now associated with https://github.com/cvitolo/fuse. @pragyansmita the updated paper is [10.21105.joss.00052.pdf](https://github.com/openjournals/joss-reviews/files/456925/10.21105.joss.00052.pdf)

**Comment by cvitolo** [comment]
@pragyansmita I don't know what prevents the fuse package to install on your system. The package seems to builds fine for [linux](https://travis-ci.org/cvitolo/fuse/builds/158181099) and [windows](https://ci.appveyor.com/project/cvitolo/fuse) systems. I have also tested various r versions and get no errors, as you can see [here](https://ci.appveyor.com/project/cvitolo/fuse). Do you mind to give it another try? Please let me know if you still have problems.

@arfon Many thanks for changing the repo link!

**Comment by cvitolo** [comment]
@arfon @pragyansmita Just wanted to know whether there is anything I can do to proceed with the review?

**Comment by arfon** [comment]
@pragyansmita - are you ok to start moving forwards with your review?

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon assign @pragyansmita as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @pragyansmita

**Comment by cvitolo** [comment]
Hi @arfon and @pragyansmita. Just wanted to know whether there is anything I can do to move forward with this submission? Many thanks

**Comment by pragyansmita** [comment]
@cvitolo and @arfon - I will take a look. Will let you know if there are questions.

**Comment by pragyansmita** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @pragyansmita, I'm afraid I can't do that. That's something only JOSS editors are allowed to do.

**Comment by pragyansmita** [comment]
@arfon How do I get added as an assignee? I dont have access to update the review form. Thanks!

**Comment by arfon** [comment]
@whedon assign @pragyansmita as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @pragyansmita

**Comment by arfon** [comment]
@pragyansmita - you should be able to edit the check list now 😄

**Comment by pragyansmita** [comment]
@cvitolo I am getting another error on following the install steps (Windows R 3.3.1 and Rtools 3.4)

> packs <- c('zoo', 'tgp', 'devtools')
> new.packages <- packs[!(packs %in% installed.packages()[,"Package"])]
> if(length(new.packages)) install.packages(new.packages)
> devtools::install_github("cvitolo/fuse")
Downloading GitHub repo cvitolo/fuse@master
from URL https://api.github.com/repos/cvitolo/fuse/zipball/master
Installing fuse
"C:/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL "C:/Users/ITS  \
  Admin/AppData/Local/Temp/Rtmp44Yu27/devtools5b06f71667c/cvitolo-fuse-4c33ef8"  \
  --library="C:/R/R-3.3.1/library" --install-tests 

* installing *source* package 'fuse' ...
** libs

*** arch - i386
C:\Rtools\mingw_32\bin\nm.exe: fuse.o: File format not recognized
C:\Rtools\mingw_32\bin\nm.exe: modelStructure.o: File format not recognized
c:/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o fuse.dll tmp.def fuse.o modelStructure.o -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/R/R-33~1.1/bin/i386 -lR
fuse.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'fuse'
* removing 'C:/R/R-3.3.1/library/fuse'
Error: Command failed (1)
> library(fuse)
Error in library(fuse) : there is no package called ‘fuse’

Is something missing in the steps to install?

**Comment by cvitolo** [comment]
Hi @pragyansmita. I have updated the installation instructions in the README. Could you please try again? Many thanks!

**Comment by arfon** [comment]
Friendly bump @pragyansmita 😄

**Comment by arfon** [comment]
> Friendly bump @pragyansmita 😄

👋 @pragyansmita - are you still able to complete this review for us?

**Comment by masalmon** [comment]
If she's not I can volunteer for this.

**Comment by arfon** [comment]
> If she's not I can volunteer for this.

@masalmon - that sounds great. Please go ahead.

**Comment by arfon** [comment]
@whedon assign @masalmon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @masalmon

**Comment by masalmon** [comment]
Great @arfon thanks. @cvitolo I hope to do this this week-end.

**Comment by cvitolo** [comment]
@masalmon Thank you so much!!!

**Comment by masalmon** [comment]
This is a cool package, congrats on making the initial Fortran code in a package and available to R users!

## Reviewer questions
### Conflict of interest
- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).
### General checks
- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cvitolo/r_fuse">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v3.0.0)?

No, the development version is 3.2 and the release version is 3.1.

### Functionality


- [ x] **Installation:** Does installation proceed as outlined in the documentation?
- [ x] **Functionality:** Have the functional claims of the software been confirmed?
- [ x] **Performance:** Have any performance claims of the software been confirmed?
### Documentation
- [x ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?

Yes. Actually the part "The fuse framework takes as input rainfall and potential evapotranspiration time series (areal averages over the river catchment area) and returns a simulated time series of river discharges. It can be used to understand the variability of expected hydrological responses based on model structures. " of the paper could even be at the beginning of the README & vignette (or in the help page for the package.) too.

- [x ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?

I have opened quite a few issues with suggestions for the documentation, but they are nearly all only suggestions.
- [x ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?

The test coverage could be increased a bit though.

- [x ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

The only thing that's not stated at the bottom of the README is whether code contributions are welcome.
### Software paper

Paper PDF: [10.21105.joss.00052.pdf](https://github.com/openjournals/joss-reviews/files/456925/10.21105.joss.00052.pdf)
- [ x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by cvitolo** [comment]
@masalmon Many thanks for your thourough review, your suggestions greaty improved the consistency of the package.

I'm planning to update the release when the review is finished.

I have added the description of the package (as in the paper) to the README and vignette as you suggested.

I have added many more tests and addressed all the issues.

I have added info on related packages and future developments to the paper.

I have added a statement in the README saying code contributions are welcome.

**Comment by masalmon** [comment]
Looks good to me, thanks for your work @cvitolo ! 👏 

@arfon I'd recommend accepting the paper now 😀

**Comment by arfon** [comment]
Thanks @masalmon!

@cvitolo - at this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by cvitolo** [comment]
@arfon I just made a new release (v3.2), here is the new doi: http://doi.org/10.5281/zenodo.212822

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.212822 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.212822" target="_blank">10.5281/zenodo.212822</a> is the archive.

**Comment by arfon** [comment]
@masalmon @pragyansmita - many thanks for the review here ✨ 

@cvitolo - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00052 ⚡️ 🚀 💥
