### ISSUE TITLE
Submission: cartography: Create and Integrate Maps in your R Workflow

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#54]
**Submitting author:** @rCarto (<a href="http://orcid.org/0000-0002-1932-3323">Timothée Giraud</a>)
**Repository:** <a href="https://github.com/Groupe-ElementR/cartography" target ="_blank">https://github.com/Groupe-ElementR/cartography</a>
**Version:** v1.4.0
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.60878" target="_blank">10.5281/zenodo.60878</a>

## Status

[![status](http://joss.theoj.org/papers/0c2d51fc23efb8e1f87d764da8414923/status.svg)](http://joss.theoj.org/papers/0c2d51fc23efb8e1f87d764da8414923)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/0c2d51fc23efb8e1f87d764da8414923"><img src="http://joss.theoj.org/papers/0c2d51fc23efb8e1f87d764da8414923/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/0c2d51fc23efb8e1f87d764da8414923/status.svg)](http://joss.theoj.org/papers/0c2d51fc23efb8e1f87d764da8414923)
```

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Groupe-ElementR/cartography">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v1.4.0)?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00054.pdf](https://github.com/openjournals/joss-reviews/files/437584/10.21105.joss.00054.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by janschulz** [comment]
:hand: I am reviewing this

**Comment by janschulz** [comment]
* Downloaded from the repo via devtools :heavy_check_mark: 
* License is GPL (form 2007 -> DESCRIPTION says GPL-3) :heavy_check_mark:
* redid the example in the readme in an jupyter notebook on R 3.3 :heavy_check_mark: The vignette also worked like a charm :heavy_check_mark:  Unfortunatelly the only EN blogpost in http://rgeomatic.hypotheses.org/842 resulted in some errors (deprecation warnings -> the blogpost seems to require 1.3 but I was on 1.4)
* no performance clames were given, but the examples were reasonable (compared to cartopy/basemaps in python)
* the paper states what the packages tries to solve  :heavy_check_mark: 
* the (devtools) installation worked flawless on windows so dependencies are automatically installed :heavy_check_mark: 
* the examples solve real world needs  :heavy_check_mark: 
* checked the API docs and they look great  :heavy_check_mark: 
* The package is auto checked on travis (Linux)  :heavy_check_mark: (as a windows user I would appreciate appveyor tests as well :-) )
* community guidelines are basically "contribute vie PRs, raise issues or ask questions via issues" -> Minimum is answered  :heavy_check_mark: 
* [paper](https://github.com/Groupe-ElementR/cartography/tree/master/paper) contains a list of authors with affiliations (and one ORCID :+1: ) :heavy_check_mark: 
* the references only cite packages or books and an R NEws item, which seems to have no DOI :-( :heavy_check_mark: 

So IMO there is only one question:

* Version on github is 1.4.0 but CRAN is still on 1.3.0 -> whats the problem here? https://github.com/Groupe-ElementR/cartography/releases vs https://cran.r-project.org/web/packages/cartography/index.html 

Apart form that this looks good to publish!

**Comment by arfon** [comment]
👍 thanks for the rapid review @janschulz. @rCarto - please let me know what's happening with the  version numbers/releases.

**Comment by rCarto** [comment]
Thanks for the review @janschulz.
* I have updated the blogpost to reflect the current version usage. 
* I have added the appveyor CI (which was surprisingly easy).  

@arfon, concerning the version numbers, I was waiting for possible comments or suggestions from JOSS to integrate. Since comments and suggestions do not imply code changes I will upload this release (v1.4.0) to the CRAN today.

**Comment by janschulz** [comment]
> I have updated the blogpost to reflect the current version usage.
> I have added the appveyor CI (which was surprisingly easy). 

Thank you! :tada: 

[Just to make sure: both were just something I observed and not related to the review here. Both could have gone as easily to the upstream repo as a issue -- and probably should have... sorry about that]

**Comment by rCarto** [comment]
no problem

**Comment by rCarto** [comment]
cartography v1.4.0 is on CRAN now.

**Comment by arfon** [comment]
@rcarto - could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by rCarto** [comment]
Here is the DOI url of the archive: http://dx.doi.org/10.5281/zenodo.60878

**Comment by arfon** [comment]
Thanks for the rapid review @janschulz :zap:

@rCarto your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00054 🚀 🎉 💥

**Comment by rCarto** [comment]
Many thanks!
