### ISSUE TITLE
[REVIEW]: hddtools: Hydrological Data Discovery Tools

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#56]
**Submitting author:** @cvitolo (<a href="http://orcid.org/0000-0002-4252-1176">Claudia Vitolo</a>)
**Repository:** <a href="https://github.com/ropensci/hddtools/" target ="_blank">https://github.com/ropensci/hddtools/</a>
**Version:** v0.3.0
**Editor:** Pending 
**Reviewer:** Pending 
**Archive:** <a href="https://dx.doi.org/10.5281/zenodo.247842" target="_blank">https://dx.doi.org/10.5281/zenodo.247842</a>

## Status

[![status](http://joss.theoj.org/papers/3287a12e7ce5d7e89938a6b4f56fc225/status.svg)](http://joss.theoj.org/papers/3287a12e7ce5d7e89938a6b4f56fc225)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3287a12e7ce5d7e89938a6b4f56fc225"><img src="http://joss.theoj.org/papers/3287a12e7ce5d7e89938a6b4f56fc225/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3287a12e7ce5d7e89938a6b4f56fc225/status.svg)](http://joss.theoj.org/papers/3287a12e7ce5d7e89938a6b4f56fc225)
```

**Reviewers and authors**: Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue
in the <a href="https://github.com/cvitolo/hddtools/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers)
in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice
versa will create corresponding breadcrumb trails in the link target.)
### Conflict of interest
- [ ] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).
### General checks
- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cvitolo/hddtools/">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v0.3.0)?
### Functionality
- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** Have any performance claims of the software been confirmed?
### Documentation
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
### Software paper

Paper PDF: [10.21105.joss.00056.pdf](https://github.com/openjournals/joss-reviews/files/455931/10.21105.joss.00056.pdf)
- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment]
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by cvitolo** [comment]
@arfon I have decided to submit to ropensci as well. @noamross suggests to pause this review and wait for the one from ropensci. Would that be possible?

**Comment by labarba** [comment]
rOpenSci is not a journal. I'm not sure there is a conflict ...

**Comment by noamross** [comment]
@labarba There's not a conflict, but we're piloting a system where authors go through our review process, and on acceptance we submit their package to JOSS, and editors have the option of accepting based on rOpenSci's reviews rather than re-reviewing.

**Comment by arfon** [comment]
> @arfon I have decided to submit to ropensci as well. @noamross suggests to pause this review and wait for the one from ropensci. Would that be possible?

Yep it's OK to pause.

> rOpenSci is not a journal. I'm not sure there is a conflict ...

@labarba - this is something @noamross, @karthik and myself have been piloting. This review process is heavily based on the rOpenSci review process so JOSS reviews can go much faster if a package has already been through the rOpenSci review process.

**Comment by noamross** [comment]
This package has been reviewed and accepted by rOpenSci.  See the review thread here: https://github.com/ropensci/onboarding/issues/73 .

Note that, with repository transfer since the initial submission, the new repository URL is https://github.com/ropensci/hddtools . The current version is v0.5.0 and Zenodo DOI is http://doi.org/10.5281/zenodo.247842

**Comment by arfon** [comment]
> This package has been reviewed and accepted by rOpenSci. See the review thread here: ropensci/onboarding#73 .

👍 excellent, thanks @noamross. I'll proceed with accepting this submission now.

**Comment by arfon** [comment]
@cvitolo your paper is now accepted into JOSS. Your paper DOI is http://dx.doi.org/10.21105/joss.00056 ⚡️ 🚀 💥

**Comment by surajitdb** [comment]
Dear Claudia,
                   In Clark et al (2008) it was mentioned that 79 plausible model structures were constructed, however in your latest and previous tutorials using R states between 1 and 1248 (model identification number). Is there any upgradation of FUSE already? 

I have been able run your latest tutorial successfully using R 3.2.5, but not working with R 3.3.3 due to some packages not available in the latest version. For now it is fine with R 3.2.5 version. 

Could you suggest me some more mids apart from mids = 60(TOPMODEL), 230 (ARNOX/VIC), 343(PRMS) and 426(SACRAMENTO). along with their names, say 9 in all. I need 9 plausible model structures for my analysis.

How would one change the coding in R when we have to handle 9 model structures? I have copied snippet from your code.

bestModel <- function(runNumber){
  
  if (runNumber < (numberOfRuns + 1)) myBestModel <- "TOPMODEL"
  
  if (runNumber > (numberOfRuns + 1) & 
      runNumber < (2*numberOfRuns + 1)) myBestModel <- "ARNOXVIC"
  
  if (runNumber > (2*numberOfRuns + 1) &
      runNumber < (3*numberOfRuns + 1)) myBestModel <- "PRMS"
  
  if (runNumber > (3*numberOfRuns + 1) & 
      runNumber < (4*numberOfRuns + 1)) myBestModel <- "SACRAMENTO"
if (runNumber > (4*numberOfRuns +1) & runNumber < (5*numberOfRuns + 1)) myBestModel <- "Another model" 
# Does the above code correct if I have 5 model structures for my analysis?
  
  return(myBestModel)
  
}

Which model structure is being calibrated using hydromad?

Looking forward to your response in anticipation.

Thanking you.

Regards,

Surajit

**Comment by surajitdb** [comment]
This was tested according to https://cvitolo.github.io/fuse/articles/fuse_vignette.html.

**Comment by surajitdb** [comment]
Sorry Claudia,
                      The snippet of the code is 
How would one change the coding in R when we have to handle 9 model structures? I have copied snippet from your code.

bestModel <- function(runNumber){

if (runNumber < (numberOfRuns + 1)) myBestModel <- "TOPMODEL"

if (runNumber > (numberOfRuns + 1) &
runNumber < (2*numberOfRuns + 1)) myBestModel <- "ARNOXVIC"

if (runNumber > (2*numberOfRuns + 1) &
runNumber < (3*numberOfRuns + 1)) myBestModel <- "PRMS"

if (runNumber > (3*numberOfRuns + 1) &
runNumber < (4*numberOfRuns + 1)) myBestModel <- "SACRAMENTO"
if (runNumber > (4*numberOfRuns +1) & runNumber < (5*numberOfRuns + 1)) myBestModel <- "Another model"

return(myBestModel)

}

# Does the above code correct if I have 5 model structures for my analysis?
