### ISSUE TITLE
[REVIEW]: EFAshiny: An User-Friendly Shiny Application for Exploratory Factor Analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#567]
**Submitting author:** @PsyChiLin (<a href="http://orcid.org/0000-0002-4381-7163">Chi-Lin Yu</a>)
**Repository:** <a href="https://github.com/PsyChiLin/EFAshiny" target ="_blank">https://github.com/PsyChiLin/EFAshiny</a>
**Version:** 1.0.0
**Editor:** @cMadan
**Reviewer:** @DominiqueMakowski
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1171998" target="_blank">10.5281/zenodo.1171998</a>

## Status

[![status](http://joss.theoj.org/papers/e6ea4369f55422a9dd6ff5dad606848b/status.svg)](http://joss.theoj.org/papers/e6ea4369f55422a9dd6ff5dad606848b)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/e6ea4369f55422a9dd6ff5dad606848b"><img src="http://joss.theoj.org/papers/e6ea4369f55422a9dd6ff5dad606848b/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/e6ea4369f55422a9dd6ff5dad606848b/status.svg)](http://joss.theoj.org/papers/e6ea4369f55422a9dd6ff5dad606848b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/PsyChiLin/EFAshiny" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@DominiqueMakowski, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @cMadan know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PsyChiLin/EFAshiny">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (1.0.0)?
- [x] **Authorship:** Has the submitting author (@PsyChiLin) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @DominiqueMakowski it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00567/joss.00567/10.21105.joss.00567.pdf
```

**Comment by DominiqueMakowski** [comment]
@cMadan @PsyChiLin

EFAshiny is both an R package and an online app designed to provide a clear, straightforward pipeline to exploratory factor analysis, a widely used statistical method. It is a nice package, very well done, that will be very useful to many people in social science and related fields. Installation and launch work as expected, and everything looks in order within the paper and the documentation.

Below are some observations:

### General
1) The documentation on how to use the package is ok (with example data).
2) There is no CRAN depot
3) There is no github release, which will be necessary for further publication
4) There is no automated test coverage check, which could be a useful addition  
5) Dependencies are stated clearly

### Specific
1) In "numeric statistics" (data summary): enable the display of Median & MAD would be useful
2) For the "distribution" tab in data summary, it would be nice to 1) have the possibility to have density plots rather than histograms and 2) to render these plots dynamically using ggplotly. I believe this wouldn't be complicated to implement.
3) Correlation plot (data summary) could possibly benefit from being generated with ggcorrplot instead of corrplot, allowing for increased flexibility and visual coherence. (altough the aesthetic gain is indeed relative).
4) Factor retention: why not allow the use of different methods for factor retention, or methods summary (see the [psycho's](https://cran.r-project.org/web/packages/psycho/vignettes/overview.html#how-many-factorscomponents-to-retain) function and [this](https://github.com/neuropsychology/psycho.R/issues/29) unsolved issue)
5) Exploratory graph analysis, It would be a small yet useful addition to be able to plot the graph with different layouts (tree, circle, ..., see [qgraph](http://sachaepskamp.com/documentation/qgraph/) documentation)
6) It would be great to be able to extract figures in R (in ggplot format or so), to further use them in rmarkdown reports or customize them.
7) In the same vein, a button to get the R code used to generate the results would be very useful for learning R and implement automated processing scripts.
8) I understand this is a package for exploraty factor analysis (hence its name), however, I'm curious on the possibility of adding a CFA tab (at the end, refitting the model using CFA (and, maybe at the beginning, an option to split the data into a training and a test dataset))... Your tool would be then sufficient for the entire, end-to-end, factor analysis.
9) In general, the feature that lacks the most is the easy possibility to interface your app with a programming R usage. In other words, the possibility to use your package within a more general script pipeline. That includes the possibility to extract the data (for example, the loadings with their confidence intervals), the code used at each step to generate the results etc., to be able to further reproduce the entire analysis without launching the app and clicking on the buttons.

These are minor suggestions that do not hinder the general quality of the package. Therefore, I'm very positive about its publication.

Best,

**Comment by cMadan** [comment]
Thank you for the prompt and thorough review, @DominiqueMakowski!

**Comment by PsyChiLin** [comment]
@DominiqueMakowski Thanks for these useful suggestions! 
I have opened several issues for all of them to track their progress. Will improve this project in the next couple of days.
@cMadan Will let you know the progress after I have advanced this submission. 
Thanks again !

**Comment by PsyChiLin** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00567/joss.00567/10.21105.joss.00567.pdf)

**Comment by PsyChiLin** [comment]
@cMadan I have tackled all the points except for the CFA one, which is not directly addressed. The latest version is 1.0.1 with github release.  All the information/references in the tutorial and paper are updated (thus I re-generate the pdf file) according to the useful suggestions from the review process. Again, many thanks for all these great suggestions, @DominiqueMakowski  !!

**Comment by DominiqueMakowski** [comment]
@cMadan @PsyChiLin I'm happy with these changes 🎉

**Comment by cMadan** [comment]
@PsyChiLin, I think we're almost all set then! Can you archive the current code on Zenodo or FigShare and tell me the DOI?

**Comment by PsyChiLin** [comment]
@cMadan The DOI : 10.5281/zenodo.1171998
Thanks a lot !

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1171998 as archive

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1171998 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1171998" target="_blank">10.5281/zenodo.1171998</a> is the archive.

**Comment by arfon** [comment]
@DominiqueMakowski - many thanks for your review here and to @cMadan for editing this submission ✨ 

@PsyChiLin - your submission is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00567 ⚡️ 🚀 💥

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00567/status.svg)](https://doi.org/10.21105/joss.00567)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00567/status.svg)](https://doi.org/10.21105/joss.00567)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by PsyChiLin** [comment]
@arfon @cMadan @DominiqueMakowski 
Thanks a lot for all the processes !
