### ISSUE TITLE
[PRE REVIEW]: RNAsik: A Pipeline for complete and reproducible RNA-seq analysis that runs anywhere with speed and ease

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#576]
**Submitting author:** @serine (<a href="http://orcid.org/0000-0002-9195-2626">Kirill Tsyganov</a>)
**Repository:** <a href="https://github.com/MonashBioinformaticsPlatform/RNAsik-pipe" target ="_blank">https://github.com/MonashBioinformaticsPlatform/RNAsik-pipe</a>
**Version:** 1.4.9
**Editor:** @pjotrp
**Reviewer:** @andrewyatz

**Author instructions**

Thanks for submitting your paper to JOSS @serine. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@serine if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
PDF failed to compile for issue #576 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0     59      0 --:--:-- --:--:-- --:--:--    59
Error reading bibliography ./paper.bib (line 447, column 16):
unexpected "/"
expecting letter, digit, white space, "#", "," or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

```

**Comment by arfon** [comment]
@serine - it looks like there is an issue with your bibtex file. I think the issue is that [this URL](https://github.com/MonashBioinformaticsPlatform/RNAsik-pipe/blob/master/paper.bib#L447) needs quoting.

Once you've fixed this you can as @whedon to compile your paper again by typing `@whedon generate pdf`

**Comment by serine** [comment]
Right, thanks guys, I wasn't sure how to include URL citation in `.bib` let work on this today. 

Also what are you building with ? `pandocs`? If I can build with `pandoc` it'll be alright?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
https://github.com/openjournals/joss-papers/blob/joss.00576/joss.00576/10.21105.joss.00576.pdf
```

**Comment by arfon** [comment]
@serine - thanks for debugging this. The PDF is looking better now.

**Comment by pjotrp** [comment]
@whedon assign @pjotrp as editor

**Comment by whedon** [comment]
OK, the editor is @pjotrp

**Comment by serine** [comment]
@pjotrp FYI, I just tweaked the docs a little, essentially added this [link](http://bioinformatics.erc.monash.edu/home/kirill/sikTestData/) with a bit more explanation. 

`RNAsik` will return `multiqc_report.html`. The other two links were done in addition to the pipeline run.

- To make [Degust](http://degust.erc.monash.edu) session you'll need upload counts file.

- IGV links were done with `mk_igv_link.py` now located in [`scripts/`](https://github.com/MonashBioinformaticsPlatform/RNAsik-pipe/tree/master/scripts) directory

We are working on automatically pushing counts to Degust, but that would require experimental break down i.e grouping samples into conditions, will be done through `samplesSheet.txt` later on. 
Can't really do automatic `igv_links.html` because data needs to be in hostable place, i.e you gotta have nginx or apache running on your server, hence running `mk_igv_link.py` manually

**Comment by pjotrp** [comment]
@whedon assign @andrewyatz as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @andrewyatz

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/583. Feel free to close this issue now!
