### ISSUE TITLE
[PRE REVIEW]: Async Modules Supporting ES5 & ES6 with Control Flow

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#589]
**Submitting author:** @IbrahimTanyalcin (<a href="http://orcid.org/0000-0003-0327-5096">Ibrahim  Tanyalcin</a>)
**Repository:** <a href="https://github.com/IbrahimTanyalcin/taskq" target ="_blank">https://github.com/IbrahimTanyalcin/taskq</a>
**Version:** v2.1.4
**Editor:** @arfon
**Reviewers:** @xirdneh

**Author instructions**

Thanks for submitting your paper to JOSS @IbrahimTanyalcin. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@IbrahimTanyalcin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular, this item:

> - Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)? The section [_'what should my paper contain'_](http://joss.theoj.org/about#paper_structure) has some guidance for the sort of content we're looking to be present in the `paper.md`.

Many thanks!

**Comment by whedon** [comment]
PDF failed to compile for issue #589 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0     50      0 --:--:-- --:--:-- --:--:--    50
Error producing PDF.
! Misplaced alignment tab character &.
\f@nch@olf ...018). Async Modules Supporting ES5 &
                                                   ES6 with Control Flow. \t...
l.242 \end{document}

Looks like we failed to compile the PDF

**Comment by IbrahimTanyalcin** [comment]
Hi Arfon,

Thank you very much for the inquiry. I will directly give examples from a project where I am the frontend developer:

http://deogen2.mutaframe.com/

This work has been published in Nucleic Acids Research (https://academic.oup.com/nar/article/45/W1/W201/3819233) and in a newer version we are making several calls to other databases, while having to instantiate many different modules sequentially. Taskq helps with controlling the load order without bloating the page with polyfills while executing functions in a non-render blocking way (because it uses ES6 Promises combined with requestAnimationFrame.)

Combining Promises with requesAnimationFrame (rAF) in fact stems from an old concept of throttling browser events which I talk about this concept in one my latest work:

http://ieeexplore.ieee.org/document/8291800/

The article above is mainly about rendering performance and different visualization modules (https://github.com/IbrahimTanyalcin/LEXICON) which can benefit from taskq.

As far as I know, combining Promises with requestAnimationFrame has not been tried in javascript module proposals. It enables 4 things:

- Non-render blocking execution --> performance
- Fall back mechanism to rAF for older browsers (this is important because whenever I demonstrate a software to hospitals, researchers etc, there are always people stuck with ie10 etc. because of regulations etc.) --> compatibility
- Requires no polyfill/transpiling while taking advantage of latest EcmaScript implementation (Promises) - Control on browser execution of scripts --> debugging etc.

Let me know if you need further clarification,

Regards,

**Comment by danielskatz** [comment]
@arfon - this is waiting for you to respond.

**Comment by arfon** [comment]
@IbrahimTanyalcin - thanks for the additional context. I think this is pretty close to an edge-case for us (as to whether this is research software) but given your role (and it's usage) on the http://deogen2.mutaframe.com project I'm happy to proceed with this submission.

@raganwald - :wave: hi! Would you be willing to review this submission for JOSS? You can get an idea of what this means here: http://joss.theoj.org/about#reviewer_guidelines

**Comment by arfon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/joss-reviewers

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by arfon** [comment]
@HadrienG, @xirdneh, @serine - would you be willing to review this submission for JOSS? Ideally I'd like to find two reviewers for this submission.

**Comment by HadrienG** [comment]
Hi! Sorry for the delay in answering this.
Unfortunately I do not have the time at the moment.

**Comment by arfon** [comment]
@fil, @pgadige - would you be willing to review this submission for JOSS?

**Comment by Fil** [comment]
Not available this time, sorry

**Comment by serine** [comment]
sorry, I wouldn't be able to review this one. From some brief investigation I think it'll be pretty difficult for me to asses this one. For example the demo link (http://deogen2.mutaframe.com/) has a lot going on there in terms of javascript

![screenshot from 2018-04-19 11-44-22](https://user-images.githubusercontent.com/6700099/38966750-1b62c1bc-43c7-11e8-9ee0-51c9e29da6ce.png)
 
Also I didn't look particular hard but I didn't see this line in the demo, which is how you get the library from my brief read

	<script type="text/javascript" src="../taskq.js" charset="UTF-8"></script>

The README looks comprehensive, but I'm still not sure how can I make an assessment of how installable and runable this tool is.

All the best

**Comment by IbrahimTanyalcin** [comment]
Hi Serine,

I have 2 versions of the server, for the new features, I test them for android, iOS, Safari , Firefox and Chrome First in test subdomain.

For the test server, please visit test-tube.mutaframe.com

You can there see taskq in action. Many thanks!

IBT,

**Comment by xirdneh** [comment]
Hi, @arfon are you still looking for reviewers?
The topic seems interesting. I've worker with javascript async capabilities before.
Also, seems like the repository has a test suite and a `package.json` for easy installation.

I'm not entirely sure how the demo project uses it (http://deogen2.mutaframe.com/) since most of the functionality is distributed in multiple files. I'm having some problems finding out the entry point.

There are a fair amount of examples in the repository so I should be able to install and test the library locally.

**Comment by IbrahimTanyalcin** [comment]
All async scripts at mutaframe are managed by Taskq, however it might be much easier to start from the examples posted on medium and the repo since they are more isolated. I have given the same links to Serine as well.

**Comment by arfon** [comment]
> Hi, @arfon are you still looking for reviewers?

@xirdneh - yes, I'd still love to get a reviewer for this. Are you able to help?

**Comment by arfon** [comment]
@IbrahimTanyalcin - I'm afraid to say I don't think we're going to be able to review this submission in JOSS. I've tried multiple times to find reviewers (outside of this thread) to no avail. :-(

**Comment by xirdneh** [comment]
Sorry about the delay.
Things have been quite hectic at work but it's slowing down now.
Is there a due date?
I can probably do a review of this by the 1st week of July.
Is that ok?

**Comment by IbrahimTanyalcin** [comment]
For me it does not make much of a  difference, as long as someone takes a look at it :). I'd be more then happy to ease the review process as anyway I can.

**Comment by xirdneh** [comment]
@IbrahimTanyalcin Thanks. I'll probably ask you a few questions in the next days.
What do you think @arfon ?

**Comment by arfon** [comment]
That would be great. Thanks @xirdneh. I'll go ahead and set up the actual review issue now.

**Comment by arfon** [comment]
@whedon assign @xirdneh as reviewer

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by whedon** [comment]
OK, the editor is @arfon

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/780. Feel free to close this issue now!

**Comment by arfon** [comment]
@xirdneh - please head over to #780 for the actual review
