### ISSUE TITLE
[REVIEW]: Aronnax: An idealised isopycnal ocean model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#592]
**Submitting author:** @edoddridge (<a href="http://orcid.org/0000-0002-6097-5729">Edward Doddridge</a>)
**Repository:** <a href="https://github.com/edoddridge/aronnax" target ="_blank">https://github.com/edoddridge/aronnax</a>
**Version:** 0.1.0
**Editor:** @kyleniemeyer
**Reviewer:** @dvalters
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1290742" target="_blank">10.5281/zenodo.1290742</a>

## Status

[![status](http://joss.theoj.org/papers/ef1f658f5566796213a2865b46794ccd/status.svg)](http://joss.theoj.org/papers/ef1f658f5566796213a2865b46794ccd)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ef1f658f5566796213a2865b46794ccd"><img src="http://joss.theoj.org/papers/ef1f658f5566796213a2865b46794ccd/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ef1f658f5566796213a2865b46794ccd/status.svg)](http://joss.theoj.org/papers/ef1f658f5566796213a2865b46794ccd)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/edoddridge/aronnax" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dvalters, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @kyleniemeyer know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/edoddridge/aronnax">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (0.1.0)?
- [x] **Authorship:** Has the submitting author (@edoddridge) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @dvalters it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00592/joss.00592/10.21105.joss.00592.pdf)

**Comment by kyleniemeyer** [comment]
@edoddridge @dvalters @rabernat 👋 the review actually takes place in here. Thanks!

**Comment by rabernat** [comment]
It looks like this issue is specifically for @dvalters' review. Is there a separate one for mine? 

First time reviewing for JOSS, sorry for the n00b question...

**Comment by kyleniemeyer** [comment]
@rabernat no worries—we haven't improved the process yet for two reviewers. We have a single review issue, so that all the interactions take place together. @dvalters will "officially" fill out the checklist, but you should also go through it and see if you agree/disagree with the points; if you do, you can just mention in in a comment.

We also encourage reviewers to file issues in the software's repository (if appropriate), and then mention them here.

For other guidance, our full reviewer guidelines are here: https://joss.theoj.org/about#reviewer_guidelines

**Comment by kyleniemeyer** [comment]
Hi @dvalters @rabernat just wanted to check in on the status of your reviews. Thanks!

**Comment by dvalters** [comment]
@kyleniemeyer thanks for the ping, will finish the review soon now.

**Comment by dvalters** [comment]
Hi @eddodridge, @kyleniemeyer here is my review: 

This is going to be quite short as I could find little to fault to prevent it being accepted into JOSS.

The software is engineered to a high standard and the documentation is well written, even as a non ocean modelling specialist I felt I understood what the model did and the basics of how it worked. If the documentation lacks anything, it's a full 'API-style' documentation (i.e. more detailed documentation of the modoules/subroutines in the code). But I don't think this should prevent from being accepted into JOSS now.

I thought the "Reproducing published results" and the "Verification" sections were a particularly strong point of the documentation site. The description of the algorithms behind the model are also much welcomed. The `paper.md` is also nice and detailed.

The use of the pytest testing framework is also well implemented. 

I've ticked the 'functionality' box in the checklist above, as it appears to work as expected and produce the expected results. But hopefully the other more domain-specialised reviewer(s) will be able to pick up anything I may have missed in this area. 

## Benchmarking/Performance

A question for @edoddridge - is there a test that runs the benchmarking simulations featured in the documentation? (It may be in the test suite and possibly overlooked it...) Just so I can tick off the "Performance" checkbox thoroughly.

## Python 3 compatibility

I was going to comment on the lack of support for Python 3, but I see you already have an issue open here: https://github.com/edoddridge/aronnax/issues/186. It would be good to see this implemented one day due to the impending Python 2.7 retirement soon(ish). Not a barrier to acceptance in JOSS though I don't think.

**Comment by edoddridge** [comment]
Thanks @dvalters! Really appreciate the feedback.

>  If the documentation lacks anything, it's a full 'API-style' documentation (i.e. more detailed documentation of the modoules/subroutines in the code).

Fair enough. I haven't done this yet because I've been refactoring the code lately, and I'm not sure that it's stable enough to justify the time.

> is there a test that runs the benchmarking simulations featured in the documentation?

There's a script, but it's not part of the test suite, nor is it run as part of the continuous integration (it takes long enough to run that waiting for it every time is a pain); it's `benchmark.py` in the `benchmarks` folder. I'll open a ticket about adding that info to the docs.

**Comment by kyleniemeyer** [comment]
Hi @rabernat, have you had a chance to review this submission yet?

**Comment by dvalters** [comment]
Thanks @edoddridge - I am happy with it all from my point of view as reviewer

**Comment by edoddridge** [comment]
@kyleniemeyer @rabernat - any news on this?

**Comment by rabernat** [comment]
I will look it over later today.

**Comment by rabernat** [comment]
Sorry for my long delay. I am satisfied by @dvalters's detailed review and am happy to approve this publication.

**Comment by kyleniemeyer** [comment]
Thanks @rabernat!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00592/joss.00592/10.21105.joss.00592.pdf)

**Comment by edoddridge** [comment]
Thanks @rabernat and @kyleniemeyer.

I've updated the author affiliations, and the DOI is 10.5281/zenodo.1290742

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kyleniemeyer** [comment]
@whedon set 10.5281/zenodo.1290742 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1290742" target="_blank">10.5281/zenodo.1290742</a> is the archive.

**Comment by kyleniemeyer** [comment]
@arfon this paper is now accepted and ready to be published!

**Comment by arfon** [comment]
@dvalters & @rabernat - many thanks for your review here and to @kyleniemeyer for editing this submission ✨ 

@edoddridge - your paper is now published in JOSS and your DOI is https://doi.org/10.21105/joss.00592 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00592/status.svg)](https://doi.org/10.21105/joss.00592)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00592/status.svg)](https://doi.org/10.21105/joss.00592)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by edoddridge** [comment]
Thanks you all!
