### ISSUE TITLE
[REVIEW]: Nostril: A nonsense string evaluator written in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#596]
**Submitting author:** @mhucka (<a href="http://orcid.org/0000-0001-9105-5960">Michael Hucka</a>)
**Repository:** <a href="https://github.com/casics/nostril" target ="_blank">https://github.com/casics/nostril</a>
**Version:** v1.0.0
**Editor:** @jakevdp
**Reviewer:** @desilinguist
**Archive:** <a href="http://dx.doi.org/10.22002/D1.935" target="_blank">10.22002/D1.935</a>

## Status

[![status](http://joss.theoj.org/papers/3c54089889db42f3e77df88b0a3fcd91/status.svg)](http://joss.theoj.org/papers/3c54089889db42f3e77df88b0a3fcd91)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/3c54089889db42f3e77df88b0a3fcd91"><img src="http://joss.theoj.org/papers/3c54089889db42f3e77df88b0a3fcd91/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/3c54089889db42f3e77df88b0a3fcd91/status.svg)](http://joss.theoj.org/papers/3c54089889db42f3e77df88b0a3fcd91)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/casics/nostril" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@desilinguist, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @jakevdp know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/casics/nostril">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@mhucka) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @desilinguist it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by jakevdp** [comment]
@desilinguist thanks for agreeing to review! The review will take place here in this issue – all relevant info is above. Please feel free to reach out to me if you have questions about the process!

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00596/joss.00596/10.21105.joss.00596.pdf)

**Comment by arfon** [comment]
👋 @desilinguist - please take a look at this when you get a chance.

**Comment by desilinguist** [comment]
This is a package that uses information retrieval methods to solve a very niche but interesting problem - figuring out whether a given string is completely nonsense or whether it is likely to be "meaningful text" but specifically in the context of identifier names used in source code. It's a very interesting approach and I quite like it.

In general, the submission is pretty much good to go except for a few things. Here are my suggestions: 

1. The installation could be improved. It would be nice to have an actual package hosted on PyPI or on anaconda.org instead of installing from the git repository. It would also be nice to explicitly list the dependencies in the repository README.

2. Although the main readme does state what the primary use case is ("... to decide whether short strings returned by source code mining methods are likely to be program identifiers ... or random characters or other non-identifier strings"), I think this can be improved a little bit. It would be nice tp provide a bit of explanation as to why this is something that someone would need to do. Perhaps have some pointers to the source code mining literature and a brief summary?

3. There is no API-level documentation per se (it could easily be added via readthedocs.org). The documentation link from the main README is broken. It would also be nice to take the very-nicely-written documentation from under `docs/explanations` and move it to readthedocs since right now it's not really easily discoverable. 

4. It would be nice to use a real test library instead of having custom functions. Did the authors try other libraries like `nose`, `nose2`, or `unittest`? If it turns out that the custom test functions ( `test_lableled()` and `test_unlabeled()`) are indeed necessary, perhaps they should be moved to a `utils.py` under the `tests` folder since it's odd to have them be part of the main source code. 

5. The references in the paper don't seem to have DOIs.

6. The statement of need in the paper can be improved in the same way as I suggested above.

All in all, this is a really nice package and I think it should be accepted to the journal pending some of the changes I suggested above. Thanks for the great work @mhucka!

**Comment by desilinguist** [comment]
@jakevdp @arfon I am assuming you got notified of this.

**Comment by arfon** [comment]
> @jakevdp @arfon I am assuming you got notified of this.

👍yep, thanks @desilinguist!

**Comment by arfon** [comment]
@mhucka - please take another look at this when you get a chance.

**Comment by mhucka** [comment]
Apologies for the delay. I'm currently traveling for another workshop, but I should be able to get to this next week, finally.

**Comment by mhucka** [comment]
Update: I've now fixed one issue, which is that I used an antipattern in `setup.py` that caused dependencies not to be installed automatically. I should be able to respond to the remaining issues this week.

**Comment by mhucka** [comment]
Thank you for the review and suggestions.  Here are some replies, finally:

> The installation could be improved. It would be nice to have an actual package hosted on PyPI or on anaconda.org instead of installing from the git repository. It would also be nice to explicitly list the dependencies in the repository README.

I have now fixed an antipattern in `setup.py` that caused dependencies not to be properly installed by Python's setuptools, which is undoubtedly what led to the comment about the need to list the dependencies.  The dependencies should now be installed automatically by `setup.py`, and the entire processs should go more smoothly now.  I've updated the installation instructions and also included a mention of the dependencies just for completeness' sake.  Having a package hosted on PyPI is a future goal.

> Although the main readme does state what the primary use case is ("... to decide whether short strings returned by source code mining methods are likely to be program identifiers ... or random characters or other non-identifier strings"), I think this can be improved a little bit. It would be nice tp provide a bit of explanation as to why this is something that someone would need to do. Perhaps have some pointers to the source code mining literature and a brief summary?

The revised readme and the paper now include more motivations on this point, which was admittedly not sufficiently addressed in the first version of the paper.

> There is no API-level documentation per se (it could easily be added via readthedocs.org). The documentation link from the main README is broken. It would also be nice to take the very-nicely-written technical explanation of how the package works from under docs/explanations and move it to readthedocs since right now it's not really easily discoverable.

I've fixed the link to the documentation file in the README.  Putting docs on readthedocs.org is a future goal.

> It would be nice to use a real test library instead of having custom functions. Did the authors try other libraries like nose, nose2, or unittest? If it turns out that the custom test functions ( test_lableled() and test_unlabeled()) are indeed necessary, perhaps they should be moved to a utils.py under the tests folder since it's odd to have them be part of the main source code.

Indeed, it would be nice, but due to limited time I cannot undertake this now, and in any case it is not a publication requirement for JOSS.  However, like some of the other suggestions above, I've added this to the issues in GitHub as a future goal.

> The references in the paper don't seem to have DOIs.

There are now DOIs where possible.  (Not all publications have DOIs.)

> The statement of need in the paper can be improved in the same way as I suggested above.

This is now done.

**Comment by mhucka** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00596/joss.00596/10.21105.joss.00596.pdf)

**Comment by mhucka** [comment]
Hmm. I don't know why Whedon isn't responding. It worked for one of my other JOSS papers ... @arfon do you have any thoughts about the command above didn't regenerate the pdf?  ([Here](https://github.com/openjournals/joss-reviews/issues/653#issuecomment-377441772]) is an example of where it worked in the context of another review.)

**Comment by arfon** [comment]
:wave: @desilinguist - could you take another look when you get a chance?  I think we're close to being done here.

**Comment by desilinguist** [comment]
LGTM 👍🏼

**Comment by arfon** [comment]
@jakevdp - are we good to accept here?

**Comment by jakevdp** [comment]
Yes, I think we're good to go!

**Comment by mhucka** [comment]
Thanks!

**Comment by mhucka** [comment]
@arfon and @jakevdp and @desilinguist  – Thanks! 

I used Caltech's DataCite-based DOI service this time around. The DOI is now [10.22002/D1.935](http://dx.doi.org/10.22002/D1.935) and should be operational.

**Comment by arfon** [comment]
@whedon set 10.22002/D1.935 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.22002/D1.935" target="_blank">10.22002/D1.935</a> is the archive.

**Comment by arfon** [comment]
Thanks for your review @desilinguist and to @jakevdp for editing this one!

@mhucka - your paper is now accepted into JOSS and your DOI is http://joss.theoj.org/papers/10.21105/joss.00596

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00596/status.svg)](https://doi.org/10.21105/joss.00596)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00596/status.svg)](https://doi.org/10.21105/joss.00596)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
