### ISSUE TITLE
[REVIEW]: Optim: An optimization package for Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#615]
**Submitting author:** @anriseth (<a href="http://orcid.org/0000-0002-5861-7885">Asbjørn Nilsen Riseth</a>)
**Repository:** <a href="https://github.com/JuliaNLSolvers/Optim.jl" target ="_blank">https://github.com/JuliaNLSolvers/Optim.jl</a>
**Version:** v0.14.0
**Editor:** @labarba
**Reviewer:** @ahwillia
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1211551" target="_blank">10.5281/zenodo.1211551</a>

## Status

[![status](http://joss.theoj.org/papers/ccd4ac7b58bbb2c577866594733968f2/status.svg)](http://joss.theoj.org/papers/ccd4ac7b58bbb2c577866594733968f2)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ccd4ac7b58bbb2c577866594733968f2"><img src="http://joss.theoj.org/papers/ccd4ac7b58bbb2c577866594733968f2/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ccd4ac7b58bbb2c577866594733968f2/status.svg)](http://joss.theoj.org/papers/ccd4ac7b58bbb2c577866594733968f2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/JuliaNLSolvers/Optim.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ahwillia, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JuliaNLSolvers/Optim.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.14.0)?
- [x] **Authorship:** Has the submitting author (@anriseth) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @ahwillia it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00615/joss.00615/10.21105.joss.00615.pdf)

**Comment by labarba** [comment]
## Reviewer 2 instructions & questions

@abelsiqueira, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

  ### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JuliaNLSolvers/Optim.jl">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v0.14.0)?
- [ ] **Authorship:** Has the submitting author (@anriseth) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by labarba** [comment]
@abelsiqueira — Our journal management system hasn't been upgraded yet to assign two reviewers, so we manually create a Review Checklist for you. Check It out ☝️

**Comment by labarba** [comment]
@anriseth — In your paper, I do miss some brief note about existing software providing similar functionality (in the same or other programming language). We don't have a novelty requirement, but we do want to see other software mentioned or cited, as appropriate.

**Comment by pkofod** [comment]
> In your paper, I do miss some brief note about existing software providing similar functionality (in the same or other programming language). We don't have a novelty requirement, but we do want to see other software mentioned or cited, as appropriate.

Does a brief note include a discussion / comparison or is it just mentions?

**Comment by labarba** [comment]
Mention other software that has same/similar functionality, briefly comment on differences and equivalence, but no need to discuss or make comparisons requiring you to run the other software. It's a matter of giving acknowledgement to the existence of the other software, not claim originality or superiority.

**Comment by abelsiqueira** [comment]
Review

The Optim package for Julia is well known in the community, and it's now considered an essential part of it. The package follows the good practices expected by JOSS, and I have only a few minor questions, corrections, and suggestions to make:

- Clarify that optimization means mathematical optimization. Possibly in the title.
- Shouldn’t John Myles White be an author? I’m not familiar with the package history, nor with ownership “rules”, but since he’s made major contributions, it warrants the question. Answering this will probably clarify Tim Holy's situation as well.
- What’s the difference between “Newton with trust region” and “Hessian-vector with trust region”?
- `ParticleSwarm` doesn’t appear to be documented.
- There are no clear community guidelines, as requested by JOSS. In my opinion, indicating the issues tab for reporting issues, problems and discussing contributions and indicating the gitter or discourse channel for help should be enough.
- At least one reference needs DOI.

Best,

**Comment by pkofod** [comment]
> Shouldn’t John Myles White be an author? I’m not familiar with the package history, nor with ownership “rules”, but since he’s made major contributions, it warrants the question. Answering this will probably clarify Tim Holy's situation as well.

Maybe we should bring in @labarba to clarify the rules. The situation is that John Myles White's current employment has very strict rules regarding review of work and publication done outside of his place of work. What we could do is finish these reviews, and then when they "good to go" we can try to see if what is there in the end fits their legal requirements. For good measure, I think I'll ping @johnmyleswhite to show that we're not trying to cheat anyone here.

Regarding @timholy the story is relevant as well, as he initially made a lot of contributions to the package, and is a relevant author as well. It would be :+1: to add him as well, but we were not comfortable adding an author that we have not been able to get explicit consent from.

The two potential co-authors were the two founding persons of Optim, but neither have been active contributors or maintainers for quite a while, and both are aware of this submission. However, @anriseth and I are perfectly happy to include one or both as authors as long as the legality and explicit consent can be established.

**Comment by pkofod** [comment]
> Review
> 
> The Optim package for Julia is well known in the community, and it's now considered an essential part of it. The package follows the good practices expected by JOSS, and I have only a few minor questions, corrections, and suggestions to make:
> 
>     Clarify that optimization means mathematical optimization. Possibly in the title.
>     Shouldn’t John Myles White be an author? I’m not familiar with the package history, nor with ownership “rules”, but since he’s made major contributions, it warrants the question. Answering this will probably clarify Tim Holy's situation as well.
>     What’s the difference between “Newton with trust region” and “Hessian-vector with trust region”?
>     ParticleSwarm doesn’t appear to be documented.
>     There are no clear community guidelines, as requested by JOSS. In my opinion, indicating the issues tab for reporting issues, problems and discussing contributions and indicating the gitter or discourse channel for help should be enough.
>     At least one reference needs DOI.
> 
> Best,

@abelsiqueira Thanks again for your feedback. We've tried to address your concerns in the two latest PRs: https://github.com/JuliaNLSolvers/Optim.jl/pull/546 https://github.com/JuliaNLSolvers/Optim.jl/pull/548 . We would appreciate if you could verify that the changes cover your concerns. The authorship concerns will depend partially upon what @labarba has to say on the matter based on my earlier comment.

**Comment by labarba** [comment]
Normally, we expect all persons who've made substantial contributions to the software to be in the list of authors. If both @johnmyleswhite and @timholy have been inactive in the project for a long time, and they approve of the JOSS submission not listing them as authors, then we can accept that. But their names should still be listed in an original copyright notice, as per the license conditions. (I didn't check if this is already the case.)

**Comment by pkofod** [comment]
> Normally, we expect all persons who've made substantial contributions to the software to be in the list of authors. If both @johnmyleswhite and @timholy have been inactive in the project for a long time, and they approve of the JOSS submission not listing them as authors, then we can accept that. But their names should still be listed in an original copyright notice, as per the license conditions. (I didn't check if this is already the case.)

The LICENSE.md file mentions "John Myles White and other contributors"

> and they approve of the JOSS submission not listing them as authors, then we can accept that

Yes, but let me repeat that this is not due to an explicit wish to exclude them. I think we will try to go the route of waiting for the review of @ahwillia , and then when everything is good to go besides the authorship, we will ship the draft off to facebook's legal department and see what they say. In Tim's case it's not so much that we've been looking for an explicit approval to exclude him, we've rather been unable to receive consent to publish what you see in the draft with his name attached to it. I figure it's a busy time in general, and especially so for Julia core contributors, so maybe we'll hear back before this review is over.

**Comment by ahwillia** [comment]
Does the year of the LICENSE matter? It is listed as 2012 and John Myles White is the only name listed. I think it would make sense to add a few more names there. Perhaps "John Myles White, JuliaNLSolvers organization, and other contributors" ?

I might be wrong, but I seem to remember the package being nearly entirely re-written by @pkofod at some point. So to me it seems fine that John doesn't necessarily need to be on the author list.

Overall the package is extremely mature and extensively used in the Julia community. So it is a no-brainer that this should be accepted and published. I struggle to come up with suggestions and feedback. Here a couple of small comments:

* There is a checkbox for me at the top of the page which says that all references need a DOI? If this is a requirement, it seems like some of the references in the paper are missing them.

* I think this was mentioned before, but I think it would be nice to have a short section in the documentation and/or the paper to discuss what other libraries are available to users. It seems like you have recently added support for manifold optimization (really cool!!) and to my knowledge this isn't available in `scipy.optimize` (but see [pymanopt](https://pymanopt.github.io/)). There is a nice discussion about the advantages of Julia in the documentation, but it might still be useful to mention these other libraries by name in the paper?

* Similar to above, it might be nice to have a citation to `Convex.jl` and `JuMP.jl` somewhere in the paper. I know `Optim.jl` is quite different than those packages, but it would be nice to mention them and briefly explain to new users how they are different.

* This is really minor and not necessary - but in addition to `grid_search` (a zeroth order multivariate solver) you might consider adding `rand_search`, see [Bergstra & Bengio (2012)](http://www.jmlr.org/papers/volume13/bergstra12a/bergstra12a.pdf). I expect this would be trivial to implement and it could be useful.

* Out of curiosity, is there a nice API to do a nested optimization? Let's say I wanted to use `rand_search` to tune a few hyperparameters of a complex model. For each set of hyperparameters I used a more sophisticated method (e.g. L-BFGS). That would be a super rad use case of this package!

I am happy to sign off on the package as is. Great work putting this together!

**Comment by labarba** [comment]
We do it like this, reflecting major release years, with author lists changing according to level of contribution:

(c) 2012 Founding Author, Second Founder
(c) 2014 Founding Author, Second Founder, New Contributor
(c) 2018 Main Contributor, New Contributor, Another Contributor, Founding Author, Second Founder

You just keep adding (c) lines below, and over time some authors may drop.

Then the license text comes below.

**Comment by pkofod** [comment]
Thanks for the feedback @ahwillia 

> There is a checkbox for me at the top of the page which says that all references need a DOI? If this is a requirement, it seems like some of the references in the paper are missing them.


I think some of these have already been adressed. Is it possible to generate a new paper pdf @labarba ?

For the rest, 

> I think this was mentioned before, but I think it would be nice to have a short section in the documentation and/or the paper to discuss what other libraries are available to users. It seems like you have recently added support for manifold optimization (really cool!!) and to my knowledge this isn't available in scipy.optimize (but see pymanopt). There is a nice discussion about the advantages of Julia in the documentation, but it might still be useful to mention these other libraries by name in the paper?

I am totally fine mentioning scipy.optimize (and JuMP and Convex), but it is not totally clear to me where to draw the line. Should R's optim also be mentioned then?

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00615/joss.00615/10.21105.joss.00615.pdf)

**Comment by ahwillia** [comment]
> I am totally fine mentioning scipy.optimize (and JuMP and Convex), but it is not totally clear to me where to draw the line. Should R's optim also be mentioned then?

It wouldn't hurt, I suppose. Is the biggest different between R's optim, `scipy.optim`, and Julia's Optim the language? Or are there other differences that are worth mentioning?

Those are the questions I could see a new user wondering.

**Comment by pkofod** [comment]
> It wouldn't hurt, I suppose. Is the biggest different between R's optim, scipy.optim, and Julia's Optim the language? Or are there other differences that are worth mentioning?
> 
> Those are the questions I could see a new user wondering.

Gotcha. I'll talk to @anriseth and come up with some changes to address your comments (the other ones as well). Thanks.

**Comment by pkofod** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00615/joss.00615/10.21105.joss.00615.pdf)

**Comment by anriseth** [comment]
We have updated the license and addressed @ahwillia's points (scipy.optimize, JuMP, and Convex.jl). Thanks for the feedback!

**Comment by abelsiqueira** [comment]
Sorry about the absence.

I reviewed the corrections and the concerns are all addressed, though there are just two new things I noticed:

- I remembered [NLP.py](http://pythonoptimizers.github.io/NLP.py/latest/) as another similar high-level language software, it might fit in the comparison as well.
- The authors of the references are jumbled (maybe some style I'm not aware?):
> Second, First, First Second, First Second

**Comment by arfon** [comment]
> Second, First, First Second, First Second

Yeah, I'm not sure about this. We're just using the default Pandoc/citeproc styles but I agree it's a little weird...

**Comment by labarba** [comment]
I see that both reviewers have checked off all items in the review checklist.

Can I have confirmation that the reviewers recommend acceptance?
@abelsiqueira @ahwillia ?

Also, can I have confirmation from the authors that they've finished working on it?
@anriseth

**Comment by ahwillia** [comment]
Yes I recommend acceptance.

On Mar 19, 2018 12:39 PM, "Lorena A. Barba" <notifications@github.com>
wrote:

I see that both reviewers have checked off all items in the review
checklist.

Can I have confirmation that the reviewers recommend acceptance?
@abelsiqueira <https://github.com/abelsiqueira> @ahwillia
<https://github.com/ahwillia> ?

Also, can I have confirmation from the authors that they've finished
working on it?
@anriseth <https://github.com/anriseth>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openjournals/joss-reviews/issues/615#issuecomment-374342839>,
or mute the thread

**Comment by pkofod** [comment]
> Also, can I have confirmation from the authors that they've finished working on it?
> @anriseth

I know Asbjørn submitted it, but please allow me to reach out to the other potential authors one last time, so get their final comments on wether they want to be credited as co-authors of if the acknowledgement is sufficient.

**Comment by abelsiqueira** [comment]
I recommend acceptance

**Comment by labarba** [comment]
OK, everyone. Thank you sincerely to @ahwillia and @abelsiqueira for their review.

@arfon -- We're waiting for the authors to do a final effort of adjusting their author list with contributors currently not named, due to their employment restrictions. After they give us the flag, the paper is ready for publication.

**Comment by pkofod** [comment]
JMW has responded that the acknowledgement is sufficient, but I've yet to hear back from Tim Holy.

**Comment by pkofod** [comment]
I think the constructive way forward is to publish as is with the acknowledgement of John Myles White and Tim Holy's contributions early in Optim.jl's life. As mentioned above, this was suggested by JWM in private correspondence, but we have still not heard back from Tim since our very early communication about making a submission to JOSS in January through e-mail, github pings, or otherwise. @anriseth @labarba @arfon

**Comment by labarba** [comment]
Looks good — small typo in the Acknowledgements:

> We would also like to thank everyone who _has_ contributed…

**Comment by pkofod** [comment]
https://github.com/JuliaNLSolvers/Optim.jl/pull/565 the typo is fixed on mastee

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00615/joss.00615/10.21105.joss.00615.pdf)

**Comment by labarba** [comment]
@arfon : This submission is ready for acceptance.

@anriseth : We now need you to make a new release, upload the revised software to your DOI-granting data/software repository, and post the DOI here.

**Comment by pkofod** [comment]
Alright, but then the v0.14 self-reference in the paper needs to be changed as well, right?

**Comment by pkofod** [comment]
Sorry, since I edited, I guess it doesn't create a notification. Does that doi look alright @labarba ?

**Comment by labarba** [comment]
@arfon --- ball on your court now to complete acceptance.

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1211551 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1211551" target="_blank">10.5281/zenodo.1211551</a> is the archive.

**Comment by arfon** [comment]
@abelsiqueira, @ahwillia - many thanks for your reviews here and to @labarba for editing this submission ✨ 

@anriseth - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00615 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00615/status.svg)](https://doi.org/10.21105/joss.00615)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00615/status.svg)](https://doi.org/10.21105/joss.00615)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by anriseth** [comment]
Great to hear, thank you to everyone who gave us feedback and has contributed :smiley:
