### ISSUE TITLE
[REVIEW]: HSImage: A Python and C++ library to allow interaction with ENVI-BIL hyperspectral images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#630]
**Submitting author:** @DTChuck (<a href="http://orcid.org/0000-0002-3832-775X">Ryan Brown</a>)
**Repository:** <a href="https://github.com/DTChuck/HSImage" target ="_blank">https://github.com/DTChuck/HSImage</a>
**Version:** v1.2.0
**Editor:** @arfon
**Reviewer:** @abhishekbajpayee
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1250506" target="_blank">10.5281/zenodo.1250506</a>

## Status

[![status](http://joss.theoj.org/papers/384b49b4cef462415060598df6fe0930/status.svg)](http://joss.theoj.org/papers/384b49b4cef462415060598df6fe0930)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/384b49b4cef462415060598df6fe0930"><img src="http://joss.theoj.org/papers/384b49b4cef462415060598df6fe0930/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/384b49b4cef462415060598df6fe0930/status.svg)](http://joss.theoj.org/papers/384b49b4cef462415060598df6fe0930)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/DTChuck/HSImage" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@abhishekbajpayee, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

  ### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/DTChuck/HSImage">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.2.0)?
- [x] **Authorship:** Has the submitting author (@DTChuck) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @abhishekbajpayee it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00630/joss.00630/10.21105.joss.00630.pdf)

**Comment by arfon** [comment]
@abhishekbajpayee - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Any questions/concerns please let me know.

**Comment by DTChuck** [comment]
Checking in on the progress of this review. Anything that you need from me, just ask.
@abhishekbajpayee
@arfon

**Comment by DTChuck** [comment]
Just checking in again. Please let me know if you need anything from me to complete the review. @abhishekbajpayee
@arfon

**Comment by abhishekbajpayee** [comment]
@DTChuck Sorry about the delay. Will try and get this done within the next day or do. Quick question: should I add my remarks / questions here as comments?

**Comment by abhishekbajpayee** [comment]
@DTChuck here are some questions I have:
1. Does this require Python 3.x and won't work for Python 2.x? If so, why is that? I ask because even though a lot of people are moving to Python 3.x, adoption might suffer because of the Python 3.x requirement because a ton of people still use Python 2.x. If they end up having to install Python 3.x then managing 2 versions of Python becomes confusing. 
4. I tried to create a `virtualenv` and then tried to install HSI using `pip install HSI` but that did not seem to work. However, installing works if I just run `pip install HSI` outside a `virtualenv` Any idea why?

Here is a checklist of suggested fixes:
- [ ] Clearly state, both in documentation and in the repo readme installation instructions, what the dependencies are. Ideally, include specific commands that a user can run in order to install the dependencies.
- [ ] Links to images and documentation in the repo readme are broken. The text is correct but links to the wrong destinations.

**Comment by DTChuck** [comment]
Addressing 2: I haven't seen that issue before. I was able to install it in a virtualenv on both my Mac and Ubuntu PC, but it could just be some setting I have. It could possibly be due to the OpenCV installation not being present in the virtualenv, as that can't be installed via pip as a dependency. If you have any logs or error messages, I can take a look and see what may be happening.

As for 1: All of my development environment is Python3. I will look to see if it is feasible to use Python2 as well. 

What did you find confusing about the installation instructions? I thought that I included all of the dependencies in the installation instructions. I can take another look at that and get it fixed up. I will work on the links and get those fixed as well. Thanks for your feedback!

**Comment by abhishekbajpayee** [comment]
Regarding installation instructions, I think it would be better if you list the dependencies as a list. Also, it would make it super easy for others if you include a few lines that users can just copy and paste into a terminal to install the dependencies. I am pretty sure it is possible to install Boost libs using `apt-get`. Installing OpenCV can be a bit tricky but I know that it is possible to install OpenCV in one line using `conda`.

I doubt that the issue with installing in a `virtualenv` is related to OpenCV. When I try to install in a `virtualenv`, I see the following:
```
ab9@ab9-laptop:~/projects/HSI$ source bin/activate
(HSI) ab9@ab9-laptop:~/projects/HSI$ pip install HSI
Collecting HSI
  Could not find a version that satisfies the requirement HSI (from versions: )
No matching distribution found for HSI
(HSI) ab9@ab9-laptop:~/projects/HSI$ 
```

**Comment by DTChuck** [comment]
I am going to update the instructions later today. I am also spooling up an Ubuntu VM so I can test python 2.7 and 3.x installation in a clean environment. I will check both of the boxes above once I have finished. Thanks for the feedback!

**Comment by DTChuck** [comment]
I have checked everything over. I added a list of dependencies and tested installation on Python 2. It looks like it installs and tests just fine on Python 2.7 so I added that to the dependency list. I fixed the dead links in the README file. Let me know if you want me to take a look at anything else repo related. 

As far as your installation error, I still haven't been able to reproduce it. I tested both Python 2.7 and 3.4 in new virtualenvs on a clean VM today, and it installed just fine. Was the virtualenv a Python 2 or Python 3 environment? Its possible that it just did not build because the setup.py file did not allow Python 2 builds on the version you were testing. That should be different now. If you still have this error, we can look into some more debugging steps. Thanks!!

**Comment by arfon** [comment]
@abhishekbajpayee - please come and take a look at this review again when you have a chance.

**Comment by DTChuck** [comment]
I would very much like to move this review forward. If there is anything I can do to help, let me know.
@arfon 
@abhishekbajpayee

**Comment by abhishekbajpayee** [comment]
Next comments from my end:
1. I am not sure how to check for release version because I don't see any GitHub releases in the project repo. @arfon should I be looking somewhere else?
2. Even after running `pip install virtualenvwrapper`, I don't see any script called `virtualenvwrapper.sh` in `/usr/local/bin`. I checked the official documentation for `virtualenvwrapper` at http://virtualenvwrapper.readthedocs.io/en/latest/index.html and they seem to suggest the same steps as you list. For some reason, it is not working for me. Is it necessary to use `virtualenvwrapper`? If not, it would be best not to mention this in the installation steps because it is likely to confuse others too.
On Ubuntu 16.04, given all other dependencies are satisfied, I was able to install by just using traditional `virtualenv` by running the following (my guess is that this should work on most other versions of Ubuntu as well): 
```
$ virtualenv hsi_env
$ cd hsi_env
$ source bin/activate
$ pip install HSI
```
3. Creating the symlinks for `cv2.so` wasn't required for me to successfully import `HSI`.
4. Since you do require the python bindings for OpenCV to be built, it would be useful to add a short note saying if someone is installing OpenCV 2.4.x then they should ensure building of python bindings is enabled by running `cmake -DWITH_PYTHON=ON ..` in the build folder.
5. The URL for full documentation listed under the "Documentation" does not link to the URL. Would be ideal to link. Same goes for URL for library of images.
6. I am able to import `HSI` in a python shell but wasn't able to test on any data. Mainly because I am not sure how to clone the library of images. Would be good to include instructions on how to do that. Also, how large is this dataset?

Not critical but things to think about:
1. Overall, the `install_opencv.sh` script is greatly and will be useful for a bunch of folks. I see that it is explicitly installing `python3-dev`, `python3-tk` and `python3-numpy`. Is this intended / necessary?
2. In the `install_opencv.sh` script, are the flags passed to `cmake` required? It seems that a simple `cmake ..` configures the build just fine.

Sorry about the delayed response. I will be sure to set aside time every couple days to respond so we can get this done soon.

**Comment by abhishekbajpayee** [comment]
@arfon @DTChuck any updates?

**Comment by DTChuck** [comment]
Here are the answers to your questions:
1) I created a release for version 1.2.0. You should be able to see that on the repository page
2) Python best practice is to encapsulate everything in virtual environments. I'm not sure why the `virtualenvwrapper` didn't work for you, but I want to leave virtual environment instructions in the install instructions, as that is the recommended Python workflow.
3) That's good. I know that it might be necessary for some people when creating virtualenvs so I wanted to explicitly mention it.
4) OpenCV 2.x is not supported by this software. This software only supports OpenCV 3.x
5) Fixed the links. Had a bad character in the actual link address in the markdown file, but once i found and removed it, the links worked again.
6) You can test the software by cloning the repository. A single hyperspectral image is included in the GitHub repository and can be cloned along with the repo. You should be able to follow the directions in the testing section of the README.md to test the software.

Additional things:
1) The python3-dev is needed for the compilation of the OpenCV python interface. python3-numpy is needed as OpenCV uses Numpy to store image matrices, and python3-tk is needed to display OpenCV images, as OpenCV Python uses TKinter to display images.
2) The cmake flags are not required, but should provide better performance to most systems. To most users, the differences should be transparent and not cause any issues at all. 

Thanks a bunch for getting back to me. Let me know if you need me to look at anything else

**Comment by abhishekbajpayee** [comment]
Thanks for creating the release version and fixing the links. Next few issues / clarifications:

1. When I was asking do you need to use `virtualenvwrapper`, I specifically meant to ask whether you need to use `virtualenvwrapper` _in addition_ to `virtualenv`. Using only `virtualenv` worked for me and I think that should work for most people. If this is the case, you do not need to mention `virtualenvwrapper` in the install instructions at all.
2. Adding a small note next to "OpenCV 3.x - C++ and Python" saying that OpenCV 2.x is not supported would be very useful. I know a ton of folks still use OpenCV 2.x.
3. You mention that `python3-dev`, `python3-numpy` and `python3-tk` are required for OpenCV functionality. However, it seems that `HSI` works with Python 2. If that is the case, I feel like these packages should not be required. Perhaps only `python-dev`, `python-tk` should be enough and `pip install numpy` should take care of the Numpy requirement?
4. For reading images, I see that 2 files `header_filename` and `raw_filename` are required. Do these files typically have the same filename (just different extensions) and are in the same directory? If so, would it make sense to pass only 1 argument to `HSI.hsimage()` and locate the other file automatically?
5. I think the example section could use more detail and perhaps some images. Can you show some interesting functionality in a visual manner here?
6. When I view the JOSS paper (`paper.md`), I don't see anything under the references section. Is this a bug and needs fixing?

I can close the installation and functionality checks once points 1 through 4 are addressed. That should only leave a couple other checks which I think can be closed by end of this week. Almost there!

**Comment by DTChuck** [comment]
Glad to hear we are getting close :)

1) I added a separate install instruction for virtualenv on its own. I like virtualenvwrapper as a module as it allows me to simply call `workon <env_name>` to jump into any virtual environment. I left the instructions for virtualenvwrapper in, but as an optional step.

2) Added a note in the README.md and the Documentation stating that OpenCV 2.x is not supported.

3) As far as I know, the python-x libraries are required for Python 2.x support and the python3-x libraries are required for Python 3.x support. I don't know which version of Python the user is going to be running so I figured that it was necessary to install both sets to ensure that it worked for both Python 2 and Python 3. The user SHOULD have installed numpy separately at this point, but I can'
t necessarily trust that they did so before running the script, so I also included a numpy installation so that it is guaranteed to be in place for the OpenCV install

4) I had the same thought earlier in the design process, but I changed to requiring both the names independently because the hope for this software is that it is database agnostic. I would like other people to be able to use it apart from the dataset that I put together, and their file structure and naming conventions may be different than mine. I didn't want to enforce a naming convention on other researchers. That was my reasoning for not automatically picking up the names of the files.

5) I will work on it and hopefully get some more detailed examples up in the next day or so.

6) The references are generated through bibtex and only show up in the compiled PDF. I can see them when I look at the article proof [here](https://github.com/openjournals/joss-papers/blob/joss.00630/joss.00630/10.21105.joss.00630.pdf)

**Comment by DTChuck** [comment]
I have added an additional example script and placed images in the README file that should display some of the capabilities of the software.

**Comment by DTChuck** [comment]
Just wanted to get an update on this. I have addressed all the recommendations that were mentioned above. Let me know if you need anything else from me.
@abhishekbajpayee

**Comment by DTChuck** [comment]
I followed the citation information for hsdar as specified on their webpage [here](https://cran.r-project.org/web/packages/hsdar/citation.html). There was no DOI listed.

I followed the citation information for pybind11 as specified [here](https://github.com/pybind/pybind11/commit/e7d304fbc6f0aa22b6105e2b1a4807c7a294eafa). Again, no DOI listed.

The OpenCV citation information also did not contain a DOI. [Citation Info](https://github.com/opencv/opencv/wiki/CiteOpenCV).

**Comment by abhishekbajpayee** [comment]
@DTChuck last couple things:

1) Is it possible to use matplotlib instead of OpenCV for plotting in Python? If so, I would recommend using that in the example script. I just ran into some issues running the example script because of the `cv.imshow()` calls. In my experience, the OpenCV plotting backend provides very little extra functionality and often requires extra configuration.
2) Can you add something like "Contribute" or "How to contribute" or something similar to the last heading in the README file? That way, anyone wishing to contribute will easily be able to navigate to the right place and figure out that they have to email you.

I will close the References check once I hear from @arfon about the DOI issue.

**Comment by arfon** [comment]
> @arfon, the papers lists references to OpenCV, pybind11 and hsdar (R package) which do not have DOI numbers. Is that OK?

Yes, that's fine. We only ask for a DOI if there is one available. Thanks for checking!

**Comment by DTChuck** [comment]
@abhishekbajpayee 
1) I suppose you could use matplotlib for the plotting instead of OpenCV, but the images are stored in OpenCV format and are intended to be used in OpenCV functions. If the imshow() function isn't working, that indicates something has gone wrong in your environment or installation, and other OpenCV functions may also not work properly. It is fairly typical of examples leveraging OpenCV to use the built-in image viewing functions. 

2) Added.

**Comment by abhishekbajpayee** [comment]
@arfon any word on the references issue?

**Comment by abhishekbajpayee** [comment]
@arfon @DTChuck all done!

**Comment by DTChuck** [comment]
@abhishekbajpayee 
Thanks for all your help on this. I will look into using matplotlib as the base for the example script. I appreciate the work you have done on this review.

@arfon What do I need to do to get this from "under review" to "complete"? Let me know if you need anything from me.

**Comment by arfon** [comment]
@DTChuck - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by DTChuck** [comment]
Here is the archive DOI. I am also going to place it in the README of the GitHub repository. Thanks!!



[![DOI](https://zenodo.org/badge/96904936.svg)](https://zenodo.org/badge/latestdoi/96904936)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1250506 as archive

**Comment by whedon** [comment]
OK. <a href="http://dx.doi.org/10.5281/zenodo.1250506" target="_blank">10.5281/zenodo.1250506</a> is the archive.

**Comment by arfon** [comment]
@abhishekbajpayee - many thanks for your review here ✨

@DTChuck - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00630 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippet:

```
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00630/status.svg)](https://doi.org/10.21105/joss.00630)
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00630/status.svg)](https://doi.org/10.21105/joss.00630)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
