### ISSUE TITLE
[REVIEW]: Dataviz: A package of domain specific visualizations and languages for the Pharo live coding environment

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#720]
**Submitting author:** @offray (<a href="http://orcid.org/0000-0002-4640-6984">Offray Vladimir Luna Cárdenas</a>)
**Repository:** <a href="https://mutabit.com/repos.fossil/dataviz/" target ="_blank">https://mutabit.com/repos.fossil/dataviz/</a>
**Version:** 2.2.3
**Editor:** @arfon
**Reviewer:** @seandenigris
**Archive:** Pending

## Status

[![status](http://joss.theoj.org/papers/9b27dbce146ff072c3878b23dac913da/status.svg)](http://joss.theoj.org/papers/9b27dbce146ff072c3878b23dac913da)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/9b27dbce146ff072c3878b23dac913da"><img src="http://joss.theoj.org/papers/9b27dbce146ff072c3878b23dac913da/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/9b27dbce146ff072c3878b23dac913da/status.svg)](http://joss.theoj.org/papers/9b27dbce146ff072c3878b23dac913da)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="http://mutabit.com/repos.fossil/grafoscopio/doc/tip/Packages/Dataviz/intro.md" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@seandenigris, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @acabunoc know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="http://mutabit.com/repos.fossil/grafoscopio/doc/tip/Packages/Dataviz/intro.md">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (2.2.3)?
- [x] **Authorship:** Has the submitting author (@offray) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #720 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment]
@whedon can't automatically compile this PDF so here is a manually generated one: [10.21105.joss.00238.pdf](https://github.com/openjournals/joss-reviews/files/1633321/10.21105.joss.00238.pdf)

**Comment by arfon** [comment]
@seandenigris - how are you getting along with your review?

**Comment by arfon** [comment]
@acabunoc - this review seems to be stuck?

**Comment by offray** [comment]
I'm waiting any comment from reviewers, I have already asked issued in the source code repository of the project, but after that the review is not advancing any more. How can I help?

**Comment by seandenigris** [comment]
Sorry, here is an issue with several hiccups in the installation process: http://mutabit.com/repos.fossil/grafoscopio/tktview/034355733a92437ab8a25a936bc8a003127f944a

**Comment by offray** [comment]
Thanks Sean. I will be dealing with this installation issues on this weekend. Now I'm finishing a writing with a close deadline.

**Comment by offray** [comment]
@seandenigris I have addressed your observations (including the creation of a new repository to avoid confusions between Grafoscopio and Dataviz packages and improved documentation). See the ticket in the new repository, at [1] (info from other issue/repository was migrated there also).

[1] https://mutabit.com/repos.fossil/dataviz/info/964c4bd0e0b2a112

@arfon I have changed the repository address of the submission I originally made to the JOSS. What I need to do to reflect that?

**Comment by arfon** [comment]
@offray - I've updated the repository address at the top of the issue.

**Comment by offray** [comment]
@arfon That link would work, but if you just put https://mutabit.com/repos.fossil/dataviz/ the repository will take care of any internal rerouting, including pointing to the readme file. Could you please change it to https://mutabit.com/repos.fossil/dataviz/ . Thanks.

**Comment by arfon** [comment]
@whedon assign @arfon as editor

**Comment by arfon** [comment]
I've followed up with @seandenigris by email.

**Comment by offray** [comment]
In my University, they have asked about a formal letter that says that this article is under review. 

While review is finished, how can I get this formal letter from the JOSS?

**Comment by arfon** [comment]
Feel free to email me directly about this @offray (arfon.smith@gmail.com)

**Comment by arfon** [comment]
@offray - I think we might need to find a new reviewer for this submission. @yochannah - do you have any suggestions for potential reviewers?

**Comment by yochannah** [comment]
hmmm, I think @hendekagon is a Pharo aficionado - @hendekagon, might you be interested in reviewing this, and/or do you know anyone else who might be able to help?

**Comment by offray** [comment]
Let's wait to @Hendekagon's answer for a while, and then I could ask again in the broader Pharo community in case we need another reviewer.

Thanks

**Comment by yochannah** [comment]
I will also try pinging him by email in case his github notifications aren't set up to notify him

**Comment by yochannah** [comment]
Quick follow up - @arfon I don't think I'm going to be able to suggest any reviewers for a Pharo package in the end I'm afraid.

**Comment by arfon** [comment]
> Sorry, recently became a dad. If you can find another reviewer great. Otherwise, I'll do what I can. 

@seandenigris - congratulations. We'd be very grateful if you could stick with us - finding reviewers for 
Pharo submissions has proven very challenging.

> Also, as I follow the readme, obvious problems pop up almost immediately. It is very slow for me to find and report these and would be more efficient if a project team member went through the process themselves to catch the obvious bugs and then I can verify in a fraction of the time.

@offray - to @seandenigris' point - please verify your own usage examples in your documentation. Reviewers shouldn't be responsible for catching obvious issues.

**Comment by Hendekagon** [comment]
hi - I'm sorry but I'm so busy this year I don't think I'm going to have time, but I'll help however I can

**Comment by Hendekagon** [comment]
BTW will this package install in Pharo 7 ?

**Comment by labarba** [comment]
👋  @offray — It looks like we're waiting for and your team to make improvements in the submission before continuing the review. Can you report on your status?

**Comment by offray** [comment]
@labarba This is my report:

  - On [26e5a577fe](https://mutabit.com/repos.fossil/dataviz/info/26e5a577fe8e0eb5)
    - [ ] I have been working on a better decoupling Dataviz and Grafoscopio, making the last a prerrequisite of the former.
    - [x] I'm improving the documentation for a more modern approach to installation using Metacello instead of Gopher (tested and working).
  - I'm porting Grafoscopio and Dataviz to Pharo 7. It is not a requirement from the reviewer, @seandenigris, but since my first commit of the Dataviz paper, almost a year ago until today we have a new Pharo version and makes sense to have the package usable there (@Hendekagon asked for it and will be in common demand soon). This will imply to updating documentation and screenshots for Grafoscopio and will be the more demanding part. 

I hope to have another update in the beginning of next week, but after that I will be pausing until first week of March, to prepare and make my final PhD dissertation.

**Comment by labarba** [comment]
Hi @offray — I hope your PhD dissertation has gone well. You mentioned the first week of March ... are you ready to re-engage with this submission? Please let us know.

**Comment by offray** [comment]
Hi @labarba the dissertation went pretty well. Thanks for asking.

 I didn't take into account the time for paperwork after dissertation (I'm still on it), but hopefully it will be done this week so next one I will be re-engaging in the submission. 

I have been porting Grafoscopio to Pharo 7 and I have it running now, but still more code migration needs to be done. On next week I will be having good news on the porting of Grafoscopio and Dataviz to Pharo 7 on showing the stoppers/delayers I have found (hopefully not many).

**Comment by seandenigris** [comment]
@offray great. Should I have another go or wait for [966385f0fc](https://mutabit.com/repos.fossil/dataviz/tktview?name=966385f0fc)?

**Comment by offray** [comment]
@seandenigris Let's way for [966385f0fc](https://mutabit.com/repos.fossil/dataviz/tktview?name=966385f0fc). It should be done for this week. I will make here the proper announcement.

Thanks

**Comment by danielskatz** [comment]
👋 @offray - how is this change coming along?

**Comment by offray** [comment]
Hi Daniel,

Sorry, but I have still busy with paperwork for the PhD degree (yes
bureaucracy can be slowly painful in many place of the Global South).

I have been stabilizing important Grafoscopio functionality in the back
end with recent commits (as shown in Grafoscopio-OffrayLuna.360)
recently, but still I need to port SQLite DB functionality to have a
proper migration of Dataviz package to Pharo 7.0.x and dealing with all
the reported concerns of the reviewer in current Pharo stable release.

**Comment by offray** [comment]
@seandenigris I have finally closed [[966385f0fc](https://mutabit.com/repos.fossil/dataviz/tktview?name=966385f0fc)], so I think that that closes all your open issues on the paper and gives support of the package on Pharo 7. All dependencies are pulled correctly with a simplified and modern installation (using Metacello instead of Gopher), and the proper interactive notebooks loading has been checked. I have updated the `readme` documentation in the [package documentation repository](https://mutabit.com/repos.fossil/dataviz/doc/tip/readme.md.html).

Thanks for your valuable feedback in helping me to improve Dataviz package.

Could you please take a look to see if all your issues/tickets have been properly addressed?

**Comment by arfon** [comment]
I have just emailed @seandenigris and asked him to take another look.

**Comment by seandenigris** [comment]
I did another pass and opened [a new ticket](https://mutabit.com/repos.fossil/dataviz/tktview/6aebe8d0850e45be980e6d7a333f148156990c89): 

I don't think any of them are necessarily blocking. I'm just not sure how to judge e.g. "functionality" and performance. What's the metric? Is it a judgement call? There is extensive documentation in various sources, so it seems impractical to verify everything

**Comment by offray** [comment]
Thanks @seandenigris for your detailed ticket. For organizational purposes, I will split it into smaller ones trying to separate Dataviz related ones from Grafoscopio GUI and other non-package issues. Despite of not being blocking concerns, I would like to review them and to tell you when they have been addressed to have the best package I can have after this process. I'll do it soon, to keep the review momentum.

**Comment by seandenigris** [comment]
Okay, pending an answer to my previous question, I'm going to conditionally check off Functionality and Performance, as well as Documentation, statement of need, and Installation instructions.

For "Example usage", while there is plenty of information available in the docs, I'd like to see at least one easily findable and runnable example in the image. Maybe fixing point 3 or 5 in my ticket would help.

**Comment by arfon** [comment]
:wave: @offray - how are you getting along here?

**Comment by arfon** [comment]
:wave: @offray - any updates on progress here?

**Comment by offray** [comment]
Hi @arfon 

Unfortunately I am unable to made further advances because I needed to deal with the bureaucracy and legalize of [my University](http://ucaldas.edu.co/). So after having previous consent of my thesis advisor, proper written approval of the previous PhD director about publishing in JOSS as a way to cover one of my graduation requisites and started this long time ago with my two submitted papers to the JOSS, the new PhD director decided that JOSS is not a valid journal to fulfill publishing requirements and told me that I need to find another place to submit my articles and restart the process. This ended in a law suit that I lost, because in Colombia courts are not a guarantee for equal treatment between citizens and institutions, or making the last ones to keep their word to the firsts.

The law suit final decision came last Thursday and now I'm restarting the process of writing academic papers about my research and finding "proper" publications under "particular indexes" to fulfill a convoluted process, where new University administrator can reverse any written decision of the previous ones, and make PhD students to restart a totally new publishing process after a public dissertation.

Its really a shame that frontier ways of publishing, as JOSS, are not recognized as valid because they are not in particular indexes (that was the University's argument). I will try to finish this paper, but, after 7 months using regular conduits and even legal resources to validate these alternative circuits and publications and trying to make my university to keep its written words, I need to follow the final decision.

I'm really sorry about this and I understand if this process has taken too long for the review and JOSS decided to end it, but I could not focus on writing or normal academic activities, while the diplomatic and legal process where happening with all the uncertainty behind the decision. At least, this repository is a public record of the injustices we need to fight, particularly in the Global South about getting alternative publishing circuits recognized as equals.

Thanks for your patience and understanding.

**Comment by arfon** [comment]
❤️ sorry to hear about these struggles @offray. Can I just check what 'indexes' are you referring to here? Do the journals you publish in need to be indexed by e.g. Scopus or something else?

**Comment by offray** [comment]
@arfon yes, the journals do need to be in a particular index. Because my thesis deals with non-hegemonic subjects, artifacts and places of knowledge, like hackerspaces, where the Grafoscopio and Dataviz software was prototyped, developed and extended, trying to make visible other ways of publishing and places for that seem like a perfect fit in my view, the one of my advisor and the previous PhD director. But under the new administration, seems that anything not listed in Scopus, Scimago or something like that, is not valid peer review, even despite the previous documented knowledge and written acceptance of JOSS, despite the (also written) acknowledgement about it not being in those indexes.

:-/

I will need to find a "traditional" journal in particular indexes and places, Once I get my new papers accepted in those magazines, I will come back to finish this paper. Because documenting the struggles that new magazines like JOSS have into being treated as equals in particular places, like my university, is part of the shared effort we as a academic community made to create alternative ways of publishing.

**Comment by kthyng** [comment]
Hi @offray. We are working on being indexed by Scopus, though I believe it hasn't come through yet. (@arfon would know best.) Would that change things for you? If so, we could keep this submission open for now.

**Comment by arfon** [comment]
> @arfon would know best

Still no news on this but we've not received a 'no'.

**Comment by kthyng** [comment]
Perhaps we could do something like pause this submission if it would be fine once we are indexed on Scopus. @offray what do you think?

**Comment by offray** [comment]
Yes, being indexed in Scopus would change things for me. The issue is that it needs to have a particular rank on it. I think that pausing this submission is the best approach meanwhile, but I'm pretty interested in the Scopus indexing/ranking for JOSS. Let me know how it advances.

**Comment by kthyng** [comment]
@offray I have added the "paused" label for now. I will try to add a reminder to this issue to ping you in a month to check in about Scopus, but I'm not sure if it works on non-reviewers. I'm afraid I can't commit to keeping you up-to-date on the status myself.

**Comment by kthyng** [comment]
@whedon remind @offray in 4 weeks

**Comment by whedon** [comment]
Reminder set for @offray in 4 weeks

**Comment by offray** [comment]
Thanks @kthyng . Any news on the Scopus issue would be greatly appreciated. I'm now trying to find and write a new publication for my research related articles, but I really would like to use the ones already submitted in JOSS to fulfill my degree requirements. 

JOSS is on equal foot as any journal on Scopus and pushing the boundaries about academic/research peer review process and artifacts.

**Comment by whedon** [comment]
:wave: @offray, please update us on how things are progressing here.

**Comment by offray** [comment]
@kthyng Hi. Is there any news on the Scopus front? Fo the moment I'm looking for a place to publish, included in such index (or similar ones). It may seems that Software X, will fit the requirement, with a more traditional publishing approach. 

Hopefully soon JOSS will be included in the index that some universities consider the valid ones.

**Comment by arfon** [comment]
> @kthyng Hi. Is there any news on the Scopus front? Fo the moment I'm looking for a place to publish, included in such index (or similar ones). It may seems that Software X, will fit the requirement, with a more traditional publishing approach.

Unfortunately not. Our application is still being considered but we don't have any update other than that. I suspect it will be many more months rather than something that will be resolved imminently.

I'm not sure if Google Scholar is relevant to you but JOSS is now properly indexed there.

**Comment by danielskatz** [comment]
@offray & @kthyng - since we don't have any knowledge on when Scopus indexing will happen, I suggest that we mark this as withdrawn.  It's now been over 18 months since the original submission and holding this here isn't fair to anyone.

**Comment by kthyng** [comment]
@danielskatz Yes that makes sense.

@offray ok?

**Comment by arfon** [comment]
> @offray & @kthyng - since we don't have any knowledge on when Scopus indexing will happen, I suggest that we mark this as withdrawn. It's now been almost 3 years since the original submission and holding this here isn't fair to anyone.

👍 I support this decision.

**Comment by offray** [comment]
I support this decision also. 

It's a shame that my University decided to only value particular indexes as the only ones required for quality per review. Also the long and painful process for me, of having a written permission to apply here and seeing how the new PhD director took back decisions made by his predecessor. 

Thanks for the work with my other approved paper and with this one and I hope to participate again with other publicacion once conditions change.

**Comment by danielskatz** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
