### ISSUE TITLE
[PRE REVIEW]: The Vascular Modeling Toolkit: A Python Library for the Analysis of Tubular Structures in Medical Images

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#736]
**Submitting author:** @rlizzo (<a href="http://orcid.org/0000-0002-0811-6513">Richard Izzo</a>)
**Repository:** <a href="https://github.com/vmtk/vmtk" target ="_blank">https://github.com/vmtk/vmtk</a>
**Version:** v1.4.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @wouterpotters, @brainstorm

**Author instructions**

Thanks for submitting your paper to JOSS @rlizzo. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@rlizzo if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by Kevin-Mattheus-Moerman** [comment]
@wouterpotters are you interested in reviewing this for [JOSS](http://joss.theoj.org/about)?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon assign @wouterpotters as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @wouterpotters

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks @wouterpotters I'll leave this pre-review issue open for a bit longer (before initiating the review process) to try to attract some more reviewers.

**Comment by Kevin-Mattheus-Moerman** [comment]
@rlizzo if you have any suitable reviewers in mind, please let me know.

**Comment by Kevin-Mattheus-Moerman** [comment]
It seems like this could be interesting to the simvascular folks. @osmsc @sshadden @jmerkow @alexkaiser @updega2 @gmaher @fkong7 are you interested in reviewing this [Journal of Open Source Software](http://joss.theoj.org/about) submission? 
The review process is focused largely on the software and a short paper, see the [reviewer guidelines](http://joss.theoj.org/about#reviewer_guidelines). 

[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00736/joss.00736/10.21105.joss.00736.pdf)

[--> Check software repository :floppy_disk: : <--](https://github.com/vmtk/vmtk)

Here is an example of recent review process: 
https://github.com/openjournals/joss-reviews/issues/691

**Comment by wouterpotters** [comment]
@Kevin-Mattheus-Moerman As this is my first review for JOSS, I have two questions that might be relevant already for the pre-review process: 
1. I noticed some of the authors already published [this paper](https://www.ncbi.nlm.nih.gov/pubmed/19002516). This 2008 paper essentially describes all the main features, the structure and the goals of the current toolbox, the open source toolbox is also mentioned. Despite changes to the toolbox over the years one could view this as a duplicate publication; what is the JOSS policy on this? I would like to emphasise that the authors do mention the [previous publication](https://www.ncbi.nlm.nih.gov/pubmed/19002516) explicitly in their manuscript. Furthermore, I also noted that in the past years there were a lot of improvements, but these focus mainly on user interface improvements, relatively small changes and bug fixes. Please correct me if I'm missing key additions since 2008 @rlizzo
2. Back in 2016 and 2017 I committed some small improvements for this repository. (without directly cooperating with the toolbox owners); I guess this is not considered a conflict of interest by JOSS? I have no affiliation with the authors of the manuscript.

**Comment by rlizzo** [comment]
Thanks for the feedback @wouterpotters,

**In reference to point 1:**

- While the core functionality of the library (outlined in the 2008 paper mentioned) is largely intact, there have been major improvements to functionality, performance, and user-interface. From the [v0.9 version](https://github.com/vmtk/vmtk/tree/v0.9.0) (released in 2010), the improvements have been largely documented on the [vmtk news webpage](http://www.vmtk.org/news/). A quick count shows that there have been 52 new functions added through new `vmtkScripts`. In addition, nearly every script has seen some modifications and improvement through that time. While the list of additions is too numerous to add here, I've highlighted some excerpts from release notes below: 

[Particle Tracing](http://www.vmtk.org/news/2013/12/13/new-tutorial-particle-tracing.html)

> vmtkmeshmergetimesteps: a script used to create a mesh file which will contains all the data relative to the velocity components for each timestep we want to generate traces.
vmtkparticletracer: a script used to generate traces (VtkPolydata) from a velocity vector field.
vmtkpathlineanimator: a script used to animate the traces previously generated.

[VMTK 1.2 Release](http://www.vmtk.org/news/2014/01/24/vmtk-1.2-released.html)

> vmtkimagemorphology: a script used to apply binary or grayscale morphology filter to the input image.
vmtkimageotsuthresholds: a script used to automatically label an image using multiple Otsu thresholding.
vmtksurfacemassproperties: a script for clipping using polyball and tube functions.
vmtksurfacearrayoperation: a script that allow curvature-dependent density meshing.
vmtksurfacebooleanoperation: a script used to perform a boolean operation between two surfaces.
vmtksurfaceregiondrawing: a script used to draw a closed contour on a surface and generate a distance field on the surface.
vmtksurfacecurvature: a script that allow to compute curvature of an input surface, optionally reporting results back to a reference surface (by point id).
vmtksurfacepolyballevaluation: a script used to evaluate the polyball function on the vertices of a surface.
vmtksurfaceregiondrawing: a script that allow to draw a closed contour on a surface and generate a distance field on the surface.
vmtkcenterlineinterpolation : a script used to smooth centerlines with a moving average.
vmtkmesharrayoperation: a script that allow to perform an operation between arrays of two meshes and store result in the first mesh.
vmtkmeshconnectivity: a script used to extract the largest connected region or the closest point-connected region from a mesh.
vmtkmeshpolyballevaluation: a script used to evaluate the polyball function on the vertices of a mesh.
vmtkmeshvolume: a script that allow to computes the volume of a mesh.
vmtkmeshcutter: a script used to generate a slice from a mesh, contributed by Simone Manini, Orobix Srl.
vmtkmeshextractpointdata:a script used to extract extract the magnitude value (and its components) of an array for a point id of a mesh, contributed by Simone Manini, Orobix Srl.
vmtkmeshmergetimesteps: a script used to create a mesh file which will contains all the data relative to the velocity components for each timestep we want to generate traces, contributed by Simone Manini, Orobix Srl.
vmtkparticletracer: a script used to generate traces (VtkPolydata) from a velocity vector field, contributed by Simone Manini, Orobix Srl. Check how it works on the particle tracing tutorial
vmtkpathlineanimator: a script used to animate the traces previously generated, contributed by Simone Manini, Orobix Srl. Check how it works on the particle tracing tutorial
Thanks to Martin Sandve Alnaes from Simula, Norway for contributing improvements to capping. Now we can use a mix of methods for different boundaries without losing boundary markers for subsequent meshing.
There is a new algorithm which allows to generate multiple boundary layers of different thickness. Check how it works on the mesh generation tutorial.

[VMTK 1.3 Release](http://www.vmtk.org/news/2016/01/22/vmtk-1.3-released.html)

> Added support for VTK 6.x and VTK 7.x. vmtk now builds against the latest official versions of both VTK and ITK.
vmtkimagebinarize: binarize an input image using two thresholds and producing a label map.
vmtksurfacearraysmoothing: perform smoothing on the values of a point data array defined on a surface.
vmtksurfacecliploop: clip an input surface using a user-defined loop.
vmtksurfaceendclipper: remove branches of a tubular surface by specifying seeds on the surface and using automatically oriented planes.
vmtksurfaceloopextraction: interactively define loops on a surface.

[VMTK 1.4 Release](http://www.vmtk.org/news/2018/03/19/vmtk-1.4.0-released.html)

>We now allow you to use all of the functionality that VMTK offers in filtering images, creating surfaces, centerlines, or volumetric meshes, while seemlessly being able to employ any external processing available in the scientific python ecosystem. With the following new methods, you can losslesly translate data (generated in either VMTK or in Python proper) back and forth between the VTK data formats and Numpy Arrays:
vmtkImageToNumpy
vmtkNumpyToImage
vmtkCenterlinesToNumpy
vmtkNumpyToCenterlines
vmtkSurfaceToNumpy
vmtkNumpyToSurface
vmtkMeshToNumpy
vmtkNumpyToMesh
A tutorial has been provided on the VMTK website which walks you through the process of interacting with the translation routines
With the VMTK-Numpy conversion utilities, we now allow VMTK data structures to be saved (and read) to disk as HDF5 or Python Pickle objects. These methods are available in the following methods:
vmtkNumpyWriter
vmtkNumpyReader

- We have completely revised our build system, and created a whole CI suite / testing / distribution system in order to help us ensure continuity between changes in the code base. 
- We've added many new tutorials and documentation updates.
- VMTK extensions for 3D Slicer and Blender have been released.
- @lantiga may be able to elaborate more on this topic, as he is the original author of the toolkit.

**In reference to point 2:**

I just wanted to post the two pull requests which have you tagged in them. Please let us know the policy on this:
- "Added opacity function for vmtkimagemipviewer.py" - https://github.com/vmtk/vmtk/pull/173
- "Added functionality to change the position of a window" - https://github.com/vmtk/vmtk/pull/168

**Comment by rlizzo** [comment]
While I don't have any strong feelings on other potential reviewers, I might suggest @arokem or @brainstorm. Thank you!

**Comment by brainstorm** [comment]
Happy to review this! ;)

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon add @brainstorm as reviewer

**Comment by whedon** [comment]
OK, @brainstorm is now a reviewer

**Comment by Kevin-Mattheus-Moerman** [comment]
@rlizzo @wouterpotters the submitted work is sufficiently advanced with respect to the previous versions to warrant a potential JOSS paper. Future releases of this software, if again significantly enhanced, may also warrant a new additional JOSS paper, since in this way accurate citing and credit giving is enabled. 

@wouterpotters thanks for bringing up the point of your contributions to this work in the form of ~2 pull requests. Since these are minor contributions from several years ago, and you are not a co-author or active collaborator currently, I do not see this as a serious source of conflict of interest. It is a benefit that you are technically familiar with this work so will hopefully be able to provided a thorough review. Nevertheless it is good that our review process is open, and multiple reviewers are recruited, such that any issues should come to light.

**Comment by rlizzo** [comment]
Thanks for the feedback @Kevin-Mattheus-Moerman!

**Comment by rlizzo** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by wouterpotters** [comment]
Thanks for the additions and comments @rlizzo  and @Kevin-Mattheus-Moerman.
