### ISSUE TITLE
[PRE REVIEW]: rowan: A Python package for working with quaternions

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#757]
**Submitting author:** @vyasr (<a href="http://orcid.org/0000-0001-5181-9532">Vyas Ramasubramani</a>)
**Repository:** <a href="https://bitbucket.org/glotzer/rowan" target ="_blank">https://bitbucket.org/glotzer/rowan</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewers:** @pdebuyl, @CorySimon

**Author instructions**

Thanks for submitting your paper to JOSS @vyasr. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@vyasr if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @labarba it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment]
:wave: @labarba - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment]
PDF failed to compile for issue #757 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    11    0    11    0     0     64      0 --:--:-- --:--:-- --:--:--    64
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.joss.00757.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by vyasr** [comment]
@arfon do I have to place the paper in the root of the repository? I looked at the repos for other JOSS papers and some of them are structured like mine (with a paper folder), but perhaps that's only possible after it's actually it's been published.

**Comment by vyasr** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by vyasr** [comment]
Do you know why whedon failed to build the original version? The comment on this thread contains a file not found error, do I need to point it somewhere?

**Comment by labarba** [comment]
@vyasr You have inline math with `$…$` in your paper. Maybe this is causing trouble with compilation? Have a look at this thread, and investigate: https://github.com/openjournals/joss/issues/409#issuecomment-390285394

**Comment by vyasr** [comment]
Oh OK got it thanks. I'll have a look.

Regarding reviewers, a potential good fit based on the [JOSS reviewers list](https://docs.google.com/spreadsheets/d/1PAPRJ63yq9aPC1COLjaQp8mHmEq3rZUzwUYxTulyu78/edit#gid=856801822) is Lemaitre Cédric ([clemaitre58](https://github.com/clemaitre58)). Computer vision + aerodynamics is probably a good background for discussing quaternions.

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00757/joss.00757/10.21105.joss.00757.pdf)

**Comment by arfon** [comment]
> @arfon do I have to place the paper in the root of the repository? I looked at the repos for other JOSS papers and some of them are structured like mine (with a paper folder), but perhaps that's only possible after it's actually it's been published.

@vyasr - the paper can live anywhere in the repository.

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00757/joss.00757/10.21105.joss.00757.pdf)

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00757/joss.00757/10.21105.joss.00757.pdf)

**Comment by vyasr** [comment]
Seems like the original compilation issue was an unrelated problem. The original version compiles fine now without changing its location and with the `$...$` syntax in use.

**Comment by labarba** [comment]
@vyasr It would help us if you could give a couple of examples of how this software could be used in research situations.

**Comment by labarba** [comment]
Meanwhile, have a little fun with this video from A Capella Science: https://youtu.be/SZXHoWwBcDc

**Comment by vyasr** [comment]
:) Thanks for that.

Regarding the usage, the primary usage of the package has to do with analyzing molecular dynamics or Monte Carlo trajectories of systems of anisotropic particles. We run simulations using [HOOMD-blue](http://hoomd-blue.readthedocs.io/en/stable/), which supports simulating particles like convex polyhedra. For example, if you're trying to understand how the hard sphere equation of state translates to cubes, you could run systems of hard cubes here. Since such particles are no longer isotropic, it's not enough to track their positions, we also need to track their orientations. We do that by storing a quaternion that gives the orientation by rotating the particle relative to some reference orientation.

We can then extract information from the system based on how particle orientations change over time. One example might be to use the distance metrics in `rowan` to see how much the orientation of neighboring particles change over time to characterize whether a system is a [plastic crystal](https://en.wikipedia.org/wiki/Plastic_crystal), but there are lots of other analyses of this type that we can do. Additionally, it's useful for visualization. One example of code using `rowan` is the [`plato`](plato-draw.readthedocs.io) visualization package; you can see some of the results of this visualization in the [examples](https://bitbucket.org/glotzer/plato-gallery/src/master/) repository.

The reason for my original suggestion of a reviewer was that while quaternions are not yet super commonly in use in our field (because simulations of anisotropic particle are still not super common), use of quaternions for attitude calculations and other aeronautical quantities is much more common, as is the use of quaternions in robotics and computer vision. But if the profile I've just provided gives you a better idea for a reviewer then that would be welcome.

**Comment by labarba** [comment]
I reached out over the weekend to three people on the robotics side, asking for a review. But the above helps: you may add a paragraph into the paper describing this usage.

**Comment by vyasr** [comment]
Sounds good, I will make those edits and push out a new version.

**Comment by pdebuyl** [comment]
Hi @labarba I am on the list of JOSS reviewers, do Molecular Dynamics simulations and have written a library https://github.com/pdebuyl/fortran_quaternion
I propose to review the paper/code.

**Comment by labarba** [comment]
Thanks for volunteering to review, @pdebuyl!

**Comment by labarba** [comment]
@whedon assign @pdebuyl as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @pdebuyl

**Comment by labarba** [comment]
I've had one review request declined and two other unanswered. I'd like to give it one more day before starting the review issue, to see if we get a second reviewer.

**Comment by pdebuyl** [comment]
May I begin anyway?

**Comment by pdebuyl** [comment]
sorry, I had not seen that this is a "pre review". I'll wait for the review.

**Comment by labarba** [comment]
You can start review of the software (downloading, installing, checking docs, etc.), but you don't have the review checklist until I start the REVIEW issue.

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00757/joss.00757/10.21105.joss.00757.pdf)

**Comment by vyasr** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00757/joss.00757/10.21105.joss.00757.pdf)

**Comment by vyasr** [comment]
I've made the suggested edits to the paper. There's one reference that's typesetting rather oddly (the second one in the list for HOOMD-blue), and I'm not sure how to fix that since the md file is a few levels removed from the final Latex file that's compiled into the PDF. Any help there would be appreciated. Aside from that, it should be prepared for review.

**Comment by vyasr** [comment]
Also thanks for offering to review @pdebuyl !

**Comment by labarba** [comment]
@whedon add @CorySimon as reviewer

**Comment by whedon** [comment]
OK, @CorySimon is now a reviewer

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by labarba** [comment]
@arfon Is `whedon` sleeping?

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/787. Feel free to close this issue now!
