### ISSUE TITLE
[PRE REVIEW]: BAMnostic: an OS-agnostic toolkit for genomic sequence analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#779]
**Submitting author:** @betteridiot (<a href="http://orcid.org/0000-0002-0243-4609">Marcus</a>)
**Repository:** <a href="https://github.com/betteridiot/bamnostic" target ="_blank">https://github.com/betteridiot/bamnostic</a>
**Version:** 0.8.4
**Editor:** @pjotrp
**Reviewers:** @luizirber, @peterjc

**Author instructions**

Thanks for submitting your paper to JOSS @betteridiot. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@betteridiot if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @pjotrp it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00779/joss.00779/10.21105.joss.00779.pdf)

**Comment by arfon** [comment]
👋@pjotrp - the submitting author suggested you as the handling editor. Feel free to nominate someone else if you think there's a better fit with a different editor.

**Comment by betteridiot** [comment]
Unofficially: I love that the JOSS bot is called whedon.

**Comment by pjotrp** [comment]
I can be the editor. Pretty cool software.

**Comment by betteridiot** [comment]
@remills As last author

**Comment by betteridiot** [comment]
As instructed, using the provided list of potential reviewers, I think the following would be well suited and qualified if they were selected to review this submission (in no particular order):
@ctb 
@afrubin 
@conradstack
@jean997
@wdecoster
@Adrianzo
@luizirber

**Comment by luizirber** [comment]
I can review it, but would recommend to wait til Monday to see if anyone else wants to review it =]

**Comment by betteridiot** [comment]
For the sake of complete transparency, a portion of my BgzfReader is a heavily modified version of the BGZF reader that @peterjc wrote. There is even attribution within that module to it. Furthermore, early on, I had consulted @peterjc about the project.

**Comment by peterjc** [comment]
Yes, @betteridiot got in touch with me about BAMnostic  be earlier this year - I've not been able to make time for any detailed input, but did suggest switching to a standard OSI approved open source license (since done).

My BGZF code referred to is in Biopython, see https://github.com/biopython/biopython/blob/master/Bio/bgzf.py

That BGZF code is now dual licensed (3-clause BSD or the legacy Biopython License Agreement), so having a derivate of that code here in BAMnostic under the 3-clause BSD license is absolutely fine from my point of view.

My pure-Python SAM/BAM code written on top of this still exists on branches, currently the latest code is here:
https://github.com/peterjc/biopython/tree/SamBam2015/Bio/Sequencing/SamBam

I have not had the time to polish this up to release ready status, and was wary of the continuously evolving nature of the SAM/BAM/CRAM file formats turning that into a continuous support burden. Currently the latest branch is here:

I would be technically able to review this, but the timing is awkward - I am away next week for a conference etc. Unless you mind waiting until mid July 2018, it would be better to ask someone else. Sorry.

**Comment by pjotrp** [comment]
Thanks @peterjc. I think we can afford to wait a few weeks and we would appreciate your review.

**Comment by pjotrp** [comment]
Hi @peterjc, are you in a position to review? Or should we appoint someone else?

**Comment by pjotrp** [comment]
@whedon list commands

**Comment by pjotrp** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by pjotrp** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/826. Feel free to close this issue now!
