### ISSUE TITLE
[REVIEW]: fgivenx: a python package for functional posterior plotting

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#849]
**Submitting author:** @williamjameshandley (<a href="http://orcid.org/0000-0002-5866-0445">Will Handley</a>)
**Repository:** <a href="https://github.com/williamjameshandley/fgivenx" target ="_blank">https://github.com/williamjameshandley/fgivenx</a>
**Version:** v2.1.0
**Editor:** @arfon
**Reviewer:** @FaustinCarter, @zhampel
**Archive:** <a href="https://doi.org/10.5281/zenodo.1404584" target="_blank">10.5281/zenodo.1404584</a>

## Status

[![status](http://joss.theoj.org/papers/cf6f8ac309d6a18b6d6cf08b64aa3f62/status.svg)](http://joss.theoj.org/papers/cf6f8ac309d6a18b6d6cf08b64aa3f62)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/cf6f8ac309d6a18b6d6cf08b64aa3f62"><img src="http://joss.theoj.org/papers/cf6f8ac309d6a18b6d6cf08b64aa3f62/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/cf6f8ac309d6a18b6d6cf08b64aa3f62/status.svg)](http://joss.theoj.org/papers/cf6f8ac309d6a18b6d6cf08b64aa3f62)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/williamjameshandley/fgivenx" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@FaustinCarter & @zhampel, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/williamjameshandley/fgivenx">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2.1.0)?
- [x] **Authorship:** Has the submitting author (@williamjameshandley) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/williamjameshandley/fgivenx">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v2.1.0)?
- [x] **Authorship:** Has the submitting author (@williamjameshandley) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by FaustinCarter** [comment]
I have some specific comments on the paper which I outline here by paragraph. I'll have comments on the code soon.

Paragraph 1:
------------
 - Why does this end in a colon? Are you about to present an example?
 - Your tense is off. I think you mean "probability distributions" rather than "a probability distribution" (which would imply a single distribution for all unknown parameters in the universe!)

Paragraph 2:
-------------
 - I'm not sure what the point of this paragraph is. The age of the universe and the idea that space expands don't seem to be relevant at any further point in the paper.

Paragraph 3:
-------------
 - Plots like what? Are you suggesting that the idea in the above paragraph could be parameterized into two variables that have a joint probability distribution? What are those variables? Can you include the plot of those variables made from your software?

Paragraph 4:
-------------
 - `scipy`, `getdist`, and `corner` all have instructions on how to cite them in an academic publication. It would be good to include those citations in addition to links to their webpages. A reference to a MCMC paper would also be good to make it easy for readers to look that up.
 - I'll also put in a shameless plug here for the `pygtc` package ([10.21105/joss.00046](http://joss.theoj.org/papers/fac5017b39292e539933d12936615f4a)) which is an alternative to `corner` and probably belongs in that list, although that's up to you.
 - After a more careful reading I think you are implying that corner plots are nice, but there is more to the story (i.e. looking at the actual model described by all the MCMC realizations?) and that's where your software comes in? I think you need to make this more explicit.

Paragraph 5:
-------------
 - Mixed voice. You switch between third person (one does, one could) and first person plural (we do, we could, our ability). It would be good to unify the voice over the whole paper.
 - Is the phrase "plotted thus" supposed to be a reference to Fig. 1? If so, say something like: "in Fig. 1 panel (a) we plot the parameter covariances between _m_ and _c_ for _X_ realizations (blue) and _Y_ realizations (red). In panel (b) we plot the function _y_=_mx_+_c_ for _X_ realizations. In panel (c) we plot something called _DxL_ which is never mentioned in the paper and should be. In panel (d) we plot the probability of measuring _y_ for a given _x_, which is essential a contour version of panel (b)."
 - Why is there a red distribution and a blue distribution? Is that two separate sets of fake data that are being fit to the same model?

Paragraph 6:
-------------
 - A couple references seem broken.

Paragraph 7:
-------------
 - The first line of this is the first mention you make of what your package actually does in words. I think this should come earlier and there should be a little more description of what `fgivenx` is designed to do right from the start.

**Comment by FaustinCarter** [comment]
A few comments on the install process:

 - I could not find installation instructions anywhere ( so I just guessed with pip). I also could not find a link to the documentation? Is it hosted somewhere, or is the user supposed to build it themselves? If the second, it would be good to include installation instructions and document building instructions directly in the github readme and in the description on PyPI.

 - No description of anything at all on the PyPI page for fgivenx.

 - For some reason the tests directory is not included in the source that is available at PyPI (this is v. 2.1.0), which means the tests do not install with pip. They are available in the zipped up source files in the github release.

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00849/joss.00849/10.21105.joss.00849.pdf)

**Comment by williamjameshandley** [comment]
@FaustinCarter 

My apologies for the poor initial state of the paper, I'm new to this system, and it wasn't clear to me initially how to preview the paper rendering prior to submission. 

Re paras 2 and 3, there was a missing figure, the presence of which hopefully makes them more clear.

I believe I have addressed all of the issues you raised, but it wasn't clear to me how to cite getdist

**Comment by williamjameshandley** [comment]
@FaustinCarter 
>* I could not find installation instructions anywhere ( so I just guessed with pip). I also could not find a link to the documentation? Is it hosted somewhere, or is the user supposed to build it themselves? If the second, it would be good to include installation instructions and document building instructions directly in the github readme and in the description on PyPI.
>* No description of anything at all on the PyPI page for fgivenx.
>* For some reason the tests directory is not included in the source that is available at PyPI (this is v. 2.1.0), which means the tests do not install with pip. They are available in the zipped up source files in the github release.


I've updated the README.md, and now updated the pypi so that it mirrors it, you can see it in alpha state [here](https://pypi.org/project/fgivenx/2.1.1a/). Tests now included in pypi.

> The tests passed except for one which failed when it tried to import getdist. I think that since getdist is not a dependency of fgivenx, the tests should not fail if it is not installed. Instead, the code should check to see if getdist is available and skip the test in question if the import fails.

I've now done this, but I'm not sure in the best way to implement this (In particular, it broke my 100% code coverage).

**Comment by williamjameshandley** [comment]
I've now updated both pip and readthedocs so that they mirror the README.rst file in the GitHub repo, and added the additional information that was requested to the README. I also expanded the test suite so that it tests with and without the optional dependencies

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00849/joss.00849/10.21105.joss.00849.pdf)

**Comment by FaustinCarter** [comment]
Round 2
======

OK, I have some new comments! I actually tried it out on some data and made a pretty sweet plot of some residuals. I had to wrap my function to get the order of the args correct for your code (and to make it plot residuals rather than the function), but it worked just fine.

<p>
<img src="https://user-images.githubusercontent.com/10946756/43928316-0d9e8d04-9bf6-11e8-8e64-be6f252fe0a6.png" width=300/><img src="https://user-images.githubusercontent.com/10946756/43928322-10c136b2-9bf6-11e8-9c3a-3326eb5c4616.png" width=300/>
</p>

I also reinstalled the latest version in a fresh environment and all the tests ran just fine (although installing matplolib via pip in a conda environment on OSX breaks everything...). OK, now onto comments. Once these are addressed I can check off the last few boxes above and recommend you for publication.

General
--------
 * The version on PyPI is 2.1.8. The latest release on github is 2.0.0, which means the Zenodo DOI is for v. 2.0.0. I think if you generate a new release of 2.1.8, then the Zenodo hook should automatically update you with a new DOI for 2.1.8. Then I can check the version box on the checklist above.

 * Citing getdist: I ran into the same problem when I was trying to cite them. I eventually settled with the following citation: `Lewis, Antony. 2015. “Getdist Github Repository.” https://github.com/cmbant/getdist`

 * I think that the file outlining contributions could be added to the end of the readme. That's a more natural place for it, and it encourages people to get involved right from the start!

 * In general I strongly feel that` __init__.py` should be reserved for initializing things. This is perhaps my interpretation of what being Pythonic should mean, but in my view a better (and more consistent) approach would be to put your top-level functions in a file called fgivenx.py, and then use the `__init__.py` file to import those into the package namespace (`from .fgivenx import *`, or just defining them in `__all__`). Now you have access to those from the top level, but your users can easily locate them in your package (instead of hunting around for ages until finally thinking to look in the `__init__.py` file). The Hitchhiker's Guide to Python agrees on this point (https://docs.python-guide.org/writing/structure/), but if you feel strongly about keeping it the way it is, it's your package! I'm not going to make that a requirement of the review.

 * You might consider also generating a conda-forge recipe for your package in the future. Makes it easy for conda users to manage the dependencies. This is just a weak suggestion for an eventual future and doesn't affect this review.

Documentation
---------------
 * In the introduction of the docs, you say the driving routine is `compute_contours`, but your example does not explicitly call that function. In fact, I'm not sure that funciton exists? Do you mean `compute_pmf`?

 * The docstring for `fgivenx.samples.compute_samples` refers to the docstring for `compute_contours`. This shoudl be fixed to reference the correct function.

 * The "Introduction" should be the first thing one sees upon going to the docs website, and then there can be a link to the API. Especially since the figure should directly follow the example code in the introduction, and now it is on the landing page, but doesn't show up after the example code in the introduction.

 * It would be good to start a changelog and include that in the documentation somewhere.

* The docstring for `compute_samples` does not mention parameter `logZ`. Also does not mention that if `logZ` (apparently an array) is passed, then the user must pass a list of functions to `f` instead of a single function.

* The docstring of `compute_pmf` could be more explicit that the return value is a tuple. I had to actually go look at the code to figure out what it was really returning.

* I suggest a comprehensive review of all the docstrings to make sure they accurately reflect the function signature (and return value) and describe all the parameters, args, and kwargs. Also, each parameter should be defined in the doc string rather than saying "go look at this other docstring". Referring to another docstring is fine for kwargs that will be passed through to some other function, but not for required parameters.

Plotting
--------
* For plotting routines, ax could be an optional argument. Then, if not supplied, it creates an axis, plots on it, and returns the axis (or maybe figure) back again. This is more of a suggestion than anything, but it makes the plotting a bit more friendly for matplotlib novices because then `fgivenx.plot.plot` just gives you a nice figure. I'm not going to hold the review up on this point.

 * It's not clear to me what the plots test is actually doing. Ideally it would generate an image and compare it to some pre-rendered image, but I don't see you loading pytest-mpl at all. In fact, the second test doesn't even use pytest at all I don't think.

Paper
------
This is much, much better now. Just a few additional comments.
 * You can replace "we" with "I" everywhere since you are the only author and you aren't the queen.
 * Paragraph 3: should be "... a probability distribution..."
 * Paragraph 3: ref to Fig. 2 should include reference to the appropriate panel.

Random
--------
I'm mystified by line 37 in `samples.py`. It looks like you are zipping two lists of different length together for the case where `logZ` is omitted. That should just return an iterator that is the length of the shortest list (which I think is length 1), but somehow it doesn't? I see where you set `f=[f]`, but not where you make that new list the same length as the samples dimension you are zipping against. How does this even work?

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00849/joss.00849/10.21105.joss.00849.pdf)

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00849/joss.00849/10.21105.joss.00849.pdf)

**Comment by williamjameshandley** [comment]
Nice plots!

**Comment by williamjameshandley** [comment]
> General
> ----------
> * The version on PyPI is 2.1.8. The latest release on github is 2.0.0, which means the Zenodo DOI is for v. 2.0.0. I think if you generate a new release of 2.1.8, then the Zenodo hook should automatically update you with a new DOI for 2.1.8. Then I can check the version box on the checklist above.

I've updated the new version to 2.1.9, and created a release so that Zenodo is up-to-date.

> * Citing getdist: I ran into the same problem when I was trying to cite them. I eventually settled with the following citation: Lewis, Antony. 2015. “Getdist Github Repository.” https://github.com/cmbant/getdist
> * I think that the file outlining contributions could be added to the end of the readme. That's a more natural place for it, and it encourages people to get involved right from the start!

Both of these are now done.

> * In general I strongly feel that__init__.py should be reserved for initializing things...

I've done this, by moving the relevant code to `fgivenx/drivers.py` and importing it in `__init__.py`. I couldn't get `fgivenx/fgivenx.py` to work for python2 in a clean manner.

> * You might consider also generating a conda-forge recipe for your package in the future. Makes it easy for conda users to manage the dependencies. This is just a weak suggestion for an eventual future and doesn't affect this review.

I don't really have any experience of using conda, but know that a lot of people do. One way to make sure that this does get done in the future would be to post an 'issue' to the GitHub -- that way I'll be reminded/encouraged to get round to this at some point in the future.

**Comment by williamjameshandley** [comment]
>Documentation
>----------------------
>* In the introduction of the docs, you say the driving routine is compute_contours, but your example does not explicitly call that function. In fact, I'm not sure that funciton exists? Do you mean compute_pmf?
>* The docstring for fgivenx.samples.compute_samples refers to the docstring for compute_contours. This shoudl be fixed to reference the correct function.

I've now introduced three new driver functions `fgivenx.plot_contours`, `fgivenx.plot_lines`, and `fgivenx.plot_dkl`, and changed all references to those


>* The "Introduction" should be the first thing one sees upon going to the docs website, and then there can be a link to the API. Especially since the figure should directly follow the example code in the introduction, and now it is on the landing page, but doesn't show up after the example code in the introduction.
>* It would be good to start a changelog and include that in the documentation somewhere.

Done


>* The docstring for compute_samples does not mention parameter logZ. Also does not mention that if logZ (apparently an array) is passed, then the user must pass a list of functions to f instead of a single function.

I think I've clarified this.

>* The docstring of compute_pmf could be more explicit that the return value is a tuple. I had to actually go look at the code to figure out what it was really returning.

Currently the return section of the docstring has a list of the two arguments. What do you think would make this clearer?

>* I suggest a comprehensive review of all the docstrings to make sure they accurately reflect the function signature (and return value) and describe all the parameters, args, and kwargs. Also, each parameter should be defined in the doc string rather than saying "go look at this other docstring". Referring to another docstring is fine for kwargs that will be passed through to some other function, but not for required parameters.

Done.

**Comment by williamjameshandley** [comment]
>Plotting
>-----------
> * For plotting routines, ax could be an optional argument. Then, if not supplied, it creates an axis, plots on it, and returns the axis (or maybe figure) back again. This is more of a suggestion than anything, but it makes the plotting a bit more friendly for matplotlib novices because then fgivenx.plot.plot just gives you a nice figure. I'm not going to hold the review up on this point.

I think this a great idea. I've leveraged plt.gca() to get this behaviour. If ax is not passed, then it just plots on the last axis, or creates one if there isn't one, consistent with the way that `matplotlib.pyplot.plot` works.

> * It's not clear to me what the plots test is actually doing. Ideally it would generate an image and compare it to some pre-rendered image, but I don't see you loading pytest-mpl at all. In fact, the second test doesn't even use pytest at all I don't think.

I've added a matplotlib test that checks that it produces the correct image to this test.

**Comment by williamjameshandley** [comment]
> Random
> ------------
> * I'm mystified by line 37 in samples.py. It looks like you are zipping two lists of different length together for the case where logZ is omitted. That should just return an iterator that is the length of the shortest list (which I think is length 1), but somehow it doesn't? I see where you set f=[f], but not where you make that new list the same length as the samples dimension you are zipping against. How does this even work?

This function assumes that it's given a list of functions and a list of samples, i.e. it's been already pre-processed to be evidence-weighted as in `fgivenx.drivers.compute_pmf`. I've updated the docstring to reflect this.

**Comment by williamjameshandley** [comment]
Many thanks for all these comments. I think this is really good process for improving distributed code.

**Comment by FaustinCarter** [comment]
Round 3
======

This is all looking great. There are just a couple lingering things I see in the docs:

 * The plot images aren't loading at Read the Docs
 * There is a ghost section in the API table of contents since you moved your main code out of the `__init__.py` file.

and with the tests:

 * You should add `pytest-mpl` as a testing dependency as tests will immediately fail without it.
 * For some reason the test image isn't installing from PyPI so the image comparison test fails; the entire baseline images directory is missing. The other tests all passed with the latest version installed via pip from PyPI.

I think once those are fixed and a new release is created to update the Zenodo DOI then I'll green light you.

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00849/joss.00849/10.21105.joss.00849.pdf)

**Comment by williamjameshandley** [comment]
> * The plot images aren't loading at Read the Docs

Links fixed.

> * There is a ghost section in the API table of contents since you moved your main code out of the __init__.py file.

Added a section here with example usage and showing the global imports.

> * You should add pytest-mpl as a testing dependency as tests will immediately fail without it.

I don't actually use `pytest-mpl`, only the ones that come already packaged as `matplotlib.testing.decorators.image_comparison`, so I don't think you should need this (and [travis](https://travis-ci.org/williamjameshandley/fgivenx) seems to agree)

> * For some reason the test image isn't installing from PyPI so the image comparison test fails; the entire baseline images directory is missing. The other tests all passed with the latest version installed via pip from PyPI.

I've added the image comparison documents to the `Manifest.in`, so this should now work from PyPI

> I think once those are fixed and a new release is created to update the Zenodo DOI then I'll green light you.

I've also added a new release as [v2.1.11](https://doi.org/10.5281/zenodo.1345486), an explicit reference to the version number in the paper.md, and updated paper.bib

You may need to refresh caches to see the updates to the documentation (I did).

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00849/joss.00849/10.21105.joss.00849.pdf)

**Comment by FaustinCarter** [comment]
Round 4
======

Ok, I made a fresh environment with just: `python, matplotlib, scipy, numpy, pytest`. I then did `pip install fgivenx` and got version 2.1.11. I then ran the tests as: `pytest fgivenx`. I immediately get an `@imagecomparison` decorator error. As far as I can tell this is because `matplotlib` tests require at a minimum the `nose` package. I then installed `nose` and reran the tests. Everything went smoothly but the image compare test failed because the image with which to compare against is still not getting added to the pip installed directory.

I'm not sure I should hold you up on this point though because my package that I published via JOSS also doesn't actually load any of the tests via pip install. You have to get the code off github to run them. After this review is over I plan to fix that!

I think at a minimum if you can add either `nose` or `pytest-mpl` to the testing dependencies, and then make a note in the docs/readme about how to manually download the comparison image, then I'll call it good!

**Comment by williamjameshandley** [comment]
OK. I think I've sorted this out now (and updated the documentation)

The following pip commands in a fresh virtual environment work for me:
```bash
python -m venv joss
source joss/bin/activate

pip install fgivenx
pip install pytest pytest-mpl
export MPLBACKEND=Agg
pytest joss/lib/python3.7/site-packages/fgivenx
```

I can't unfortunately update the zenodo link in the paper since there is a 'major incident' currently occurring.

**Comment by FaustinCarter** [comment]
OK, this is great! As far as I'm concerned this review is finished; I am satisfied that you are ready for publication.

**Comment by arfon** [comment]
:wave: @zhampel - when do you think you might be able to complete your review by?

**Comment by zhampel** [comment]
@arfon I should have my review ready by Wednesday

**Comment by arfon** [comment]
> @arfon I should have my review ready by Wednesday

Great!

**Comment by zhampel** [comment]
@williamjameshandley Nice work with fgivenx. I have a few comments which I'll put in a couple of posts for you. I'll put up the comments regarding the paper and documentation now, and I'll have a couple more regarding the code itself either later today or early tomorrow.

**Comment by zhampel** [comment]
Paper
===
I think the paper could use a little cleanup. I found a few minor mistakes and would like to add some additional comments regarding the text as well. Take them as suggestions, but I feel like they'd make the paper smoother.

- Title after 'fgivenx:' should be capitalized

Paragraph 1
------------
- I find 'scientific models' not particularly specific or descriptive. Numerical maybe? Or change Scientists to Researchers.

Paragraph 2
------------
- Plots such as... I think 'plots' is a too colloquial. Find a better way to say this like 'Countour 
- No dashes in Markov Chain Monte Carlo. But after writing it out, add '(MCMC)' for clarity.
- I think 'available freely online.' is better, where the word online is the link. Also add a period at the end of that sentence ;)

Paragraph 3
------------
- Generally, ensure that there’s no confusion about what probability we’re talking about. For example, one could in principle compare probabilities of a linear to quadratic functions, but that’s not what fgivenx does.
- Lines are straight, so I would change them all to line or linear as descriptors:
straight line - > line, straight line relationship -> linear relationship
- If one has a probability distribution -> Given probability distributions
- would also be uncertain -> characterized by some uncertainty.
Is the linear relationship uncertain? I think you should clarify it's the probability of assuming a linear function to predict y given x. 
- The appropriate plot... -> This is depicted as P(y|x) in the bottom right panel of Figure 2.

Paragraph 4
------------
- Capitalize Python. This goes for all other mentions of Python as well
- I think 'fgivenx is a package for showing the relationships as depicted in Figure 2…` sounds a bit smoother
- is a little over-simplified -> provides a simple illustration
- Move the citation to the end of the phrase: 'in recent Planck studies… perturbations (citations),'

Paragraph 5
------------
- Capitalize Python.

Figure 1
--------
- may have noted -> may note
- Explain what the contours are. Confidence intervals with some quoted %?

Figure 2
--------
- caption has two periods
- Something change like this: An example of plots -> Example output of fgivenx provided some input data and linear test function.

**Comment by zhampel** [comment]
Documentation
===========
I appreciate the completeness that you put into the docstrings. I have a few comments.

Introduction
------------
In the 2nd paragraph of the Description
- These packages -> This package?

API
---
- no quotes necessary around iso-probability posterior mass
- Is logZ relative evidences w.r.t. models? I.e. is it the ratio P/Q? Or is it some other type of function prior?
Is this Q(\theta)? Z is not used in any of the latex equations.
And maybe make it a little more explicit that the user need not normalize it.
I know you say relative, but just make it super clear so there’s no possible confusion.
Also please make distinction between evidences comparing models and parameter priors, just to be safe.
- I suppose just ensure that any and all python variables that are part of equations are clearly and properly annotated in the docstrings.
- theta samples -> can you make it latex or mathjax, and also say 'parameters \theta' so it's clear

**Comment by zhampel** [comment]
At the moment I have only one comment in my notes regarding the code:
-I really like the kwargs.pop functionality you put it. So smooth :)

For now, it's really just ensuring the docstrings are uber clear, and I'll finish up my code review.

**Comment by williamjameshandley** [comment]
@zhampel Many thanks for your detailed comments.
* Paper: I think I've addressed all your issues.
* Documentation: I've tried to make the docstrings as descriptive as possible, without being too verbose. I agree the evidence was unclear. Hopefully now it's relatively obvious what these functions are expecting as an optional argument.
* Installation. Updated the readme accordingly. Does installing [Pillow](https://pypi.org/project/Pillow/) fix your issues? If so I'll update the Readme for mac-users.

Once you're happy with my updates (all on github), and we've fixed the OSX failure, I'll update the version numbers and PyPi.

> I really like the kwargs.pop functionality you put in. So smooth :)

I don't know how to do it any other way now. It came from [Effective Python](https://effectivepython.com/), which I thoroughly recommend (and is split up into nice, bitesize examples).

**Comment by zhampel** [comment]
@williamjameshandley 

- For the paper edit, you are missing periods in the last sentence of the last paragraph, as well as one at the end of the caption of Figure 1.
- From your reply to the the documentation comments, it seemed like you were going to make edits to the docstrings. I didn't see any commits to that end. Were you planning on doing so or just agreeing that there was some ambiguity there?
- I will try the Pillow install today to check your fix.

**Comment by zhampel** [comment]
@williamjameshandley 
- I must not have refreshed my page properly or something, so I finally saw the docstring edits you made.
- After installing pillow now, I get some ignored QueueManagerThread warning, but no error.

Good job cleaning this up!

**Comment by zhampel** [comment]
@williamjameshandley 

Code
====
A few comments about the code. They are minor and nit-picky. Everything else looks well-written and functionally appropriate.

- _check_args in _utils.py: There are a few extra indents on some `raise ValueError` statements
- _normalize_weights in _utils.py: Could use a little more space for readability. It's a little tight compared to the rest of your code.

Maybe rerun flake8 just to check one last time to make sure there aren't any other stragglers.

One more thing about the testing suite:
- is test_plot_lines actually running a test? I don’t see an image_comparison style test like you have in test_plotting in test_drivers.py.

**Comment by zhampel** [comment]
@arfon I've checked off all my boxes and consider my review finished. I have made a few last minor comments to @williamjameshandley, though they are stylistic and do not require my approval for publication.

**Comment by arfon** [comment]
:zap: thanks @zhampel.

@williamjameshandley - please let me know when you've had a chance to respond to @zhampel and @@FaustinCarter's feedback.

**Comment by zhampel** [comment]
@arfon Also, I can't find an email link on your personal websites. Can you please send me a quick email from the link provided on my own homepage [here](https://zhampel.github.io/)? Thanks.

**Comment by zhampel** [comment]
@arfon sorry that github email isn't working for some reason. My academic email zhampel@icecube.wisc.edu is fine please.

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00849/joss.00849/10.21105.joss.00849.pdf)

**Comment by williamjameshandley** [comment]
@zhampel 

>* I must not have refreshed my page properly or something, so I finally saw the docstring edits you made.

I find one often needs to force refresh the cache in order to see updates

>Maybe rerun flake8 just to check one last time to make sure there aren't any other stragglers.

Done

>is test_plot_lines actually running a test? I don’t see an image_comparison style test like you have in test_plotting in test_drivers.py.

I've added some more tests to this, so that each separate test actually runs `image_comparison` tests. Tests and figures also uploaded to PyPi.


>After installing pillow now, I get some ignored QueueManagerThread warning, but no error.

Added a note to the README.rst

@arfon I believe that I have now addressed all the issues raised

**Comment by williamjameshandley** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00849/joss.00849/10.21105.joss.00849.pdf)

**Comment by arfon** [comment]
@williamjameshandley - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by williamjameshandley** [comment]
@arfon [Zenodo Link](https://zenodo.org/record/1404584#.W4U4fnUzq00)

**Comment by arfon** [comment]
@whedon set 10.5281/zenodo.1404584 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1404584" target="_blank">10.5281/zenodo.1404584</a> is the archive.

**Comment by arfon** [comment]
@FaustinCarter, @zhampel - many thanks for your reviews here ✨ 

@williamjameshandley - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00849 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00849/status.svg)](https://doi.org/10.21105/joss.00849)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00849">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00849/status.svg" alt="DOI badge" >
</a>
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00849/status.svg)](https://doi.org/10.21105/joss.00849)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
