### ISSUE TITLE
[PRE REVIEW]: TDAstats: R pipeline for computing persistent homology in topological data analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#858]
**Submitting author:** @rrrlw (<a href="http://orcid.org/0000-0003-0503-9580">Raoul R. Wadhwa</a>)
**Repository:** <a href="https://github.com/rrrlw/TDAstats" target ="_blank">https://github.com/rrrlw/TDAstats</a>
**Version:** v0.2.0
**Editor:** @leeper
**Reviewers:** @corybrunson

**Author instructions**

Thanks for submitting your paper to JOSS @rrrlw. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@rrrlw if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @leeper it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #858 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    320      0 --:--:-- --:--:-- --:--:--   324
Error reading bibliography ./paper.bib (line 16, column 5):
unexpected "d"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
:wave: @leeper, the submitting author suggested you as the handling editor.

**Comment by rrrlw** [comment]
Thank you, @arfon, for the quick response and all the efforts put behind making JOSS successful. I suggested @leeper as the corresponding bio mentioned extensive experience with R packages. @leeper, I hope you find this an interesting submission. I have two notes that should make the reviewers'/editors' tasks easier:

1. TDAstats v0.2.0 (development version on GitHub repo) is being submitted to JOSS, even though only v0.1.0 is currently available on CRAN. Assuming all goes well, I was hoping to submit the final version of the package to CRAN and, given CRAN's submission policy (update every 1-2 months), would prefer to avoid overburdening CRAN volunteers by also submitting v0.2.0 (version would be incremented to 1.0.0 post-review). Thus, instead of using `install.packages("TDAstats")`, reviewers would need to use `devtools::install_github("rrrlw/TDAstats")` to evaluate the most recent version of the package.
2. The markdown file at https://github.com/rrrlw/TDAstats/blob/master/JOSS-paper/reviewer-checklist.md contains the JOSS reviewer checklist and how I think this submission meets each point. I hope it saves the reviewers' time.

Thank you, again, for your time. @whedon appears to have found a formatting error in the bibliography file. I will correct it ASAP, and recompile the pdf.

Best,
Raoul

**Comment by rrrlw** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by rrrlw** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00858/joss.00858/10.21105.joss.00858.pdf)

**Comment by rrrlw** [comment]
The error has been fixed, and the article proof generated by @whedon appears as intended. From the list of people who have agreed to review for JOSS, @corybrunson would likely be the best fit to review this submission given the familiarity with R and expertise in topological data analysis. Please let me know if there's anything I can do to make the pre-review/review process easier. Thank you!

**Comment by corybrunson** [comment]
I would be delighted to review this package! I can finish within one week. (I wouldn't call my experience expertise, but i'm familiar with the concepts implemented.)

**Comment by rrrlw** [comment]
Thank you, @corybrunson! Looking forward to your feedback.

**Comment by leeper** [comment]
@corybrunson That's great. I'll add you as a reviewer and get this going right now.

**Comment by leeper** [comment]
@whedon assign @corybrunson as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @corybrunson

**Comment by leeper** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/860. Feel free to close this issue now!
