### ISSUE TITLE
[PRE REVIEW]: edarf: Exploratory Data Analysis using Random Forests

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#89]
**Submitting author:** @zmjones (<a href="http://orcid.org/0000-0002-7523-0471">Zachary Jones</a>)
**Repository:** <a href="http://github.com/zmjones/edarf/" target ="_blank">http://github.com/zmjones/edarf/</a>
**Version:** 1.0.0
**Editor:** @cMadan
**Reviewer:** @PhilippPro

**What this issue is for**

Thanks for submitting your paper to JOSS @zmjones. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @karthik it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment]
@karthik - do you think you could edit this submission for us?

**Comment by cMadan** [comment]
I can edit this one.

**Comment by arfon** [comment]
@whedon assign @cMadan as editor

**Comment by whedon** [comment]
OK, the editor is @cMadan

**Comment by arfon** [comment]
> I can edit this one.

✨ @cMadan. Once you've found a reviewer you can do:

```
@whedon assign @username as reviewer
@whedon start review
```

**Comment by cMadan** [comment]
@zmjones - I've been trying to find a reviewer but haven't been able to yet. Would you like to suggest one?

**Comment by zmjones** [comment]
i asked on twitter. most people i would suggest know me personally and probably wouldn't be really objective.

that said, anybody in the https://github.com/mlr-org group would be capable of reviewing it (i work with them though). i think also anybody in https://github.com/ropensci. 

similar packages include caret, ggrandomforests, mlr. those package authors might be willing.

**Comment by cMadan** [comment]
@zmjones - thanks for the suggestions!

@ehrlinger, @PhilippPro, @ja-thomas - would you be interested in being a reviewer for this package? (see http://joss.theoj.org/about for the reviewer guidelines)

**Comment by PhilippPro** [comment]
I can do this, I am generally also interested in random forests. 

At first glance it seems like most functionalities are already given in the packages, of course not with a unified interface. And of course they could be extended. 
Moreover the ranger package is missing and party is not exact random forest. And there are much more packages that are similar to random forest (like party), see here for a long list in [my blog](http://philipppro.github.io/More_complete_list/).

**Comment by zmjones** [comment]
hey @PhilippPro. thanks!

do check out their [reviewing criteria](http://joss.theoj.org/about).

it appears that i didn't do a very good job of putting in a "need" bit in the paper, and although i have a vignette i don't have it linked in the readme. do you know a way to do that btw? i generated it locally and then pushed that directory, but i don't know how to get github to render it without creating a new gh-pages branch. 

as far as novelty is concerned (though again, see the reqs, as this isn't needed). local importance (and hence class specific importance) is only available for `randomForest` (and isn't as general), and partial dependence isn't really available in any of them (and not in this general form). i also have a bunch of visualization functionality in there that doesn't exist elsewhere.

except for mlr of course. i wrote this package before i started working on mlr, and although this is nearly a strict subset of the functionality in mlr, it does get used quite a bit by people in my field because the start-up costs are really low. e.g., load your data as normal, one line for the random forest call (most people don't tune really, but at least with random forests this isn't as big of an issue), and then immediately on to interpretation stuff with edarf.

**Comment by PhilippPro** [comment]
What do you mean with "need" bit?
Sorry, I think I cannot help with the rendering in github. Maybe ask @jakob-r.

I will try to do the review until the end of next week.

**Comment by zmjones** [comment]
Under documentation it says
"
A statement of need

The authors should clearly state what problems the software is designed to solve and who the target audience is.
"
so this is one of the reviewing criteria. 

i will sort out the vignette issue today, and submit to cran as well.

i'll look into adding support for ranger too. Arborist looks really nice. I hadn't seen that before. My reading of the reviewing criteria is that this is not an issue, but you can decide for yourself of course.

**Comment by arfon** [comment]
@whedon assign @PhilippPro as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @PhilippPro

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by arfon** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/92. Feel free to close this issue now!

**Comment by arfon** [comment]
@PhilippPro @zmjones please head over to #92 for the actual review of this submission.
