### ISSUE TITLE
[REVIEW]: GB_code: A grain boundary generation code

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#900]
**Submitting author:** @https://github.com/oekosheri (<a href="http://orcid.org/0000-0002-9616-4602">raheleh Hadian</a>)
**Repository:** <a href="https://github.com/oekosheri/GB_code" target ="_blank">https://github.com/oekosheri/GB_code</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewer:** @vyasr, @trallard
**Archive:** <a href="https://doi.org/10.5281/zenodo.1433530" target="_blank">10.5281/zenodo.1433530</a>

## Status

[![status](http://joss.theoj.org/papers/ef363f347a2d4406ea0cf2b54504e039/status.svg)](http://joss.theoj.org/papers/ef363f347a2d4406ea0cf2b54504e039)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/ef363f347a2d4406ea0cf2b54504e039"><img src="http://joss.theoj.org/papers/ef363f347a2d4406ea0cf2b54504e039/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/ef363f347a2d4406ea0cf2b54504e039/status.svg)](http://joss.theoj.org/papers/ef363f347a2d4406ea0cf2b54504e039)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/oekosheri/GB_code" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@vyasr & @trallard, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @labarba know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/oekosheri/GB_code">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@https://github.com/oekosheri) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/oekosheri/GB_code">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Authorship:** Has the submitting author (@https://github.com/oekosheri) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by vyasr** [comment]
@labarba I'm not quite sure how to review aspects of this repository. It's written in Python, but it's not really a Python package, it's a collection of scripts for a particular purpose. There is no Python API, the intent is just to run these scripts on the command line. That being the case, the normal aspects of a Python package (a setup.py for installation, a Python API, etc) don't really apply. I can request tests for the command line API and some versioning on the repository itself, but since the package won't be `setup.py installed` the version would also just be viewed by looking at the repository source.

Should I just treat this as a command line tool, and give advice accordingly? Or should I be providing suggestions on how to expose/improve a Python API and follow more standard Python packaging guidelines? @oekosheri do you want/see a use for making this tool scriptable within Python rather than as a standalone set of scripts?

**Comment by oekosheri** [comment]
True, I have not provided a setup.py but this is definitely a python package.
Both main scripts are modules (collection of functions and classes) as well as command line scripts because of the main functions in the end that parses input arguments. Why I have chosen this structure: historical reasons + the underlying physics + preference by the scientists who use it. 
If you think I should use a setup.py, I can add it of course. If you have suggestions as to how it should be written, let me know please. If you meant something else that I didn't understand correctly please clarify it a bit more to me.

**Comment by vyasr** [comment]
You understood my comment correctly. The underlying code is cleanly divided into functions and classes, and you are correct that in the strict sense the repository is a Python package since it is importable thanks to the __init__.py file. I was mostly alluding to the fact that it is not immediately installable, and that the intended API appears to be entirely command line based. You've put together a nice implementation of a cool scientific application, I'm just trying to get a sense for how to make it most useful.

My recommendations will depend a little bit on how you anticipate people making use of the code. If your intended usage is purely from the command line, then I think my comments regarding how to appropriately evaluate this apply because there really isn't much of an API other than simply executing the scripts as you demonstrate in your README. On the other hand, if you want people to be able to interface directly with the Python functions that you provide (in my opinion, you should allow that since it gives users much more flexibility and they might find use-cases you didn't anticipate), then there are a few things you would want to do. Your repository should be restructured  in the form of a standard Python package (see [here](https://docs.python-guide.org/writing/structure/) for example) and you would use a setup.py to make it installable and accessible. If you want to expose a command line interface, the way to do it in that context would be using setuptools entry_points (if you're not familiar, you can see the [official docs](https://setuptools.readthedocs.io/en/latest/setuptools.html#eggsecutable-scripts) as well as a few [basic](https://amir.rachum.com/blog/2017/07/28/python-entry-points/) [tutorials](https://www.eflglobal.com/setuptools-entry-points/)). Even if you don't provide a Python API, making your scripts available on the command line in this fashion would make it easier for people to incorporate the commands into their own (Python, bash, etc) scripts.

Let me know your thoughts on these ideas and I can tailor my feedback accordingly.

**Comment by oekosheri** [comment]
Thank you for your help.
To answer your question:
Currently, the more classic scientists use it via the Linux terminal and the younger scientists use the Jupyter notebooks. They can import different modules for the functionality they need and there are also additional functions in the notebooks.  As far as the further development goes, I see only myself as the only developer of this code. 

1- you say: _"Your repository should be restructured in the form of a standard Python package "_, I do not quite understand how. Do you mean to separate the script part (main functions) of the codes from the modules (functions/class)?  
If your answer is yes, I must say I would prefer to keep them as is because of historical preference.
If your answer is different, please let me know.

2- I think it would probably make more sense to me to use the "entry point" solution for the setup.py and keep the scripts as they are.

**Comment by vyasr** [comment]
As you pointed out, your code already is a package. The standard structure for Python packages, however, is to have all the code in a subdirectory of the repository:
README.rst
LICENSE
setup.py
requirements.txt
sample/__init__.py
sample/core.py
sample/helpers.py
docs/conf.py
docs/index.rst
tests/test_basic.py
tests/test_advanced.py

**Comment by oekosheri** [comment]
Yes, that's right. thanks.
 So I'm trying re-structuring and I have a question. I put the two scripts/modules in gb_code directory. My setup.py file looks like this:

```
 from setuptools import setup
  
packages = [
    'gb_code',
       ]
setup(
    name='GB_code',
    version='0.1.0',
    author='R.Hadian',
    author_email='shahrzadhadian@gmail.com',
    packages=packages,
    entry_points = {
        'console_scripts': [
            'csl_generator = gb_code.csl_generator:main',
            'gb_generator = gb_code.gb_generator:main',
        ],
    },
    url='https://github.com/oekosheri/GB_code',
    license='LICENSE',
    description='A GB generation code',
    long_description=open('README.md').read(),
)
```
It copies the executable scripts in python bin, so very good but it does not copy them in site-packages. 
if instead of _setuptools_ I use _distutils.core_ the modules will be installed in site-packages but the entry points are not recognised. Do you know what may be the issue?

Thanks in advance.

**Comment by oekosheri** [comment]
A follow up on my previous post:
I tried``` pip install . ``` and that did the task. i.e. package was copied to my python site-packages and executables to python bin. I wonder if this is the best practice though. If you know of a better way, let me know.

**Comment by vyasr** [comment]
I don't know exactly what caused the issue that you were having, but in general setup.py is known to have some buggy behavior in odd cases like that, so I don't think that you're doing anything wrong. You could try on a different python version if you have conda/virtualenv handy and see how that behaves, but I wouldn't be too worried.

**Comment by oekosheri** [comment]
Ok, Thanks, So I updated the repository now.

**Comment by oekosheri** [comment]
Sorry to bother but I was wondering whether the review process is progressing. Do I need to do make any other changes at this point?
 I have a deadline for introducing my work and want to know whether the review process will be done before that.

**Comment by labarba** [comment]
👋 @vyasr, @trallard — could you give us an update on your timeline for review?

**Comment by trallard** [comment]
sorry, I have blocked some time on Monday-Tuesday to do so so should be able to update then

**Comment by vyasr** [comment]
Hi sorry I had a couple of things come up after my flurry of activity two weeks ago. I will get to this tomorrow.

**Comment by vyasr** [comment]
Thanks for those changes! Sorry for the delay. Here is my next set of comments. 

- Python functions should add some function/class level documentation of the APIs. The functions all have docstrings, which is helpful, but they should also have some description of what the arguments are and what the object types are (floats, lists, some internal class, etc).
- Since you have a setup.py already and your project is pure Python, you can make it even easier to install by uploading your project to PyPI (or even Anaconda cloud). For more information on this, see the [Python Packaging Guide](https://packaging.python.org/), and specifically the guide on [managing and packaging your own project](https://packaging.python.org/tutorials/packaging-projects/).
- Can you add some tests to make sure that the outputs are as expected? I can run your code, but I don't have great topical knowledge of CSL so it would be helpful if you added a tests folder that would run the generator and then check that the output files are what you would expect from theory. For this, you can use the Python [unittest](https://docs.python.org/3/library/unittest.html) framework, or [pytest](https://docs.pytest.org/en/latest/) if you want something more sophisticated.

**Comment by oekosheri** [comment]
Thank you for your comments.
- I will add more description to the docstrings to describe the parameters a bit more but I hope I don't have to necessarily have full descriptions the same way python does for example. That would take a very long time.
- I  think I can consider this later but for now the installation is rather easy and it seem to work fine. 
- The reason I added the Jupyter notebooks to this directory is that they technically show the functionality aside from the command line. So I thought that should serve the purpose of testing as well. If I must add the unittest I will but If the notebooks suffice that would be my preference.
- For a variety of reasons I do not want to accept contribution to the code at this point. I plan to expand this code and when the time comes I will add a contribution section to the README. I hope this is alright.

I submitted the code more than two months ago and have a deadline for presenting it before leaving my institute. Prior to submitting it, I have put quite some time and effort into making the functionality and presentation of it match the needs of current/future users. I really appreciate the fact that I could improve the installation procedure following your comments last time but I also have a time limit now. Aside from completing the docstrings which I will try to finish tomorrow, I would appreciate it if you could test the code now as is.

**Comment by oekosheri** [comment]
@labarba @vyasr @trallard I have updated the repository after adding more to the doctrings of the csl_generator script. I have checked the requirement for the documentation in JOSS and think my code satisfies it for the most part. If there is another necessary step that I'm missing please let me know.  
Aside from this, I would like to know the timeline for the review process as I must present the code before my departure.

**Comment by vyasr** [comment]
That's fair enough. I can review as is. 

The only remaining requirement I have is that you update the setup.py script to have install_requires = ['numpy']. Currently if you try to install this into a clean environment it will fail to run. The requirements.txt file is helpful, but users using pip/setup.py based installation should get the dependencies automatically. pandas and matplotlib are not necessary, since they're just for the notebooks, not the package itself (as far as I can tell).

Regarding not accepting contributions, as far as I am concerned that is fine. @labarba may have more to say on that front, but I will check that box for now and can revise if needed.

Once the setup change is made I can approve.

**Comment by oekosheri** [comment]
@vyasr thanks! I updated setup.py file with the required numpy version.
@labarba please let me know whether I should add anything to README regarding the contributions. As stated before, my preference is that for now I will not accept contributions. Later on I can change that.

**Comment by trallard** [comment]
- [documentation](https://github.com/oekosheri/GB_code/issues/5):  as @vyasr  noticed before your README is your main documentation, but you also have a couple of notebooks in the `test` directory it would be nice to point to their existence

**Comment by oekosheri** [comment]
Thank you @trallard 
I specified the version of python in setup.py (additionally in README).
I detailed the status on contribution in README.
Regarding the Jupyter notebooks: I have mentioned them in the README and have linked to them. 
I can maybe put them outside Test and on the root directory if they are not visible. What is your suggestion?

**Comment by trallard** [comment]
Thanks a lot for the quick actions @oekosheri.

I closed the notebooks issue as I realized that I did not notice the link to the notebooks.
But for now I'd leave them where they are

**Comment by labarba** [comment]
@oekosheri : The note on the README is fine. We discussed among JOSS editors, and the minimum requirement is to have an open issue tracker, and to include mention in the README of the contributions policy, but accepting third-party contributions is not a requirement.

@trallard, @vyasr : Are you both comfortable with recommending acceptance, at this point? I need a clear statement of agreement from you to move forward.

**Comment by vyasr** [comment]
Yes, I'm fine approving this for acceptance now.

**Comment by oekosheri** [comment]
@trallard I just added two lines to README from the paper as the statement of need.
@labarba Thanks for the explanation. Please let me know of the next steps I need to take.
@vyasr thank you for your help!

**Comment by labarba** [comment]
👋 @trallard Awaiting your confirmation that you recommend acceptance, at this point.

**Comment by trallard** [comment]
Sorry @labarba,  I have been to a conference/travelling. 
I am happy to recommend the acceptance at this point

**Comment by labarba** [comment]
@oekosheri The paper currently has one big **Summary** section that includes background, software description, and some indication of the intended audience. This content would benefit from some re-organization to bring out the research application of the software into a "Statement of Need." We request that in the [Author's Guide](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain). The guide doesn't explicitly require this section to be separated explicitly under its own heading, but I really prefer it that way. Many JOSS authors already do this.

So, could you add "Statement of Need" as a heading, and write a paragraph that describes to a non-specialist the research application of this software? Examples and references are useful, but keep it brief.

Note that there are some spaces missing around the software name in the last paragraph.

**Comment by labarba** [comment]
To clarify ☝️ — I think the content is already there, only it needs to be re-organized a bit, with a bolded paragraph heading or sub-heading "Statement of Need."

**Comment by oekosheri** [comment]
@labarba Thanks for the tips. So I reorganised it as you suggested and made some additional modifications. Please let me know if it looks/reads better now.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00900/joss.00900/10.21105.joss.00900.pdf)

**Comment by oekosheri** [comment]
@labarba I just corrected the affiliation: 
@whedon generate pdf

**Comment by oekosheri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by labarba** [comment]
* Small edit:  capitalize "Statement" on the heading.

* "in comparison to other GB generation codes in different scientific groups `GB_code` is faster due its extensive usage of python and Numpy library and is more comprehensive" >> several small grammatical issues with this clause, but my main question is whether you can say that `GB_code` "is faster" if you are not providing evidence via a performance comparison. Do you have this evidence somewhere?

Note that Python should be capitalized and NumPy also uses a capital P.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00900/joss.00900/10.21105.joss.00900.pdf)

**Comment by oekosheri** [comment]
I made some changes to the paragraph.
The point about being faster: personal usage of other codes (I mean the two that I know, there are not many published general GB generation codes so far as I know) have led me to write it. It becomes increasing more important when creating larger structures. 

I added the "To our knowledge" to reduce the emphasis. I can remove it altogether if you think it does not fit.

**Comment by oekosheri** [comment]
I don't have numbers of course and it is not a crucial point for the paper so I rephrased it according to your suggestion. Please let me know if it is better now. Thank you.

**Comment by labarba** [comment]
**Editorial fixes**:


`GB_code` is mainly designed to be a command line tool as it is documented >> `GB_code is designed to be a command-line tool, as documented… (delete superfluous adverb, hyphen compound adjective, add comma, delete extra words)

README file of the repository but the modules >> add comma before “but”

Inputs the two scripts as modules, the former >> period instead of comma

Of the following works >> edit the citation to remove the parenthesis around the list of refs.

Some functionality from this code (Wojdyr, 2013) >> makes no sense to say “this code” followed by a reference in parenthesis; please use the code name, or write “from the code by Wonder (2013)”

`GB_code` is an interactive >> interactive

The target audience are  >> The target audience is

Extensive use of NumPy library >> the NumPy library

GB_code >> `GB_code` (consistent formatting)

The user will be guided through in a step by step manner how to find and create the GB of interest. >> The user will be guided in a step-by-step manner on how to find and create… (note the hyphens)

GB plane orientation which is often lacking >> comma before “which”

---

Please add missing DOIs to journal articles in references.

**Comment by oekosheri** [comment]
Thanks for the edits.
I corrected them all except:

- Of the following works >> edit the citation to remove the parenthesis around the list of refs.

by parenthesis do you mean the brackets? I have them around all other citations too. Should I remove them all?

**Comment by labarba** [comment]
When the citation is part of the sentence, then use: Author (year). If the citation is not part of the sentence, then it should appear in parenthesis.
E.g.
1. "We take inspiration from Smith et al. (2006) to ... "
2. "The code implements Theory 1 (Jones 2012) and Theory 2 (Roberts 2014) to obtain ... "

For the syntax to obtain brackets in the right places, see: https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html

**Comment by oekosheri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #900 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0     93      0 --:--:-- --:--:-- --:--:--    93
Error reading bibliography ./paper.bib (line 50, column 4):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by oekosheri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #900 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0     95      0 --:--:-- --:--:-- --:--:--    96
Error reading bibliography ./paper.bib (line 50, column 4):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by oekosheri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #900 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    135      0 --:--:-- --:--:-- --:--:--   136
Error reading bibliography ./paper.bib (line 50, column 4):
unexpected "y"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by oekosheri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00900/joss.00900/10.21105.joss.00900.pdf)

**Comment by oekosheri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00900/joss.00900/10.21105.joss.00900.pdf)

**Comment by oekosheri** [comment]
@labarba Sorry for testing a few times. Does the last version look acceptable?

**Comment by labarba** [comment]
Something is wrong with the DOI links. For example, the second reference links to: `https://doi.org/https://doi.org/10.1103/PhysRevMaterials.2.043601`

Please clean up the BibTeX entries so they resolve properly.

**Comment by oekosheri** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00900/joss.00900/10.21105.joss.00900.pdf)

**Comment by oekosheri** [comment]
It must be correct now. I removed the https. Please let me know.

**Comment by labarba** [comment]
Great!

The next step is for you to make an archival copy of the full repository in a service like Zenodo, get a DOI, and tell us the archive DOI here so we can add it to the publication.

**Comment by oekosheri** [comment]
Thanks @labarba.
I tried to integrate the repository on Zenodo and it constantly fails. Do you have any instructions on zenodo integration? I can't find any details on JOSS pages.

**Comment by oekosheri** [comment]
Thanks @labarba, so eventually I managed to integrate the repo with Zenodo and it created a badge with Doi. 
[![DOI](https://zenodo.org/badge/140718298.svg)](https://zenodo.org/badge/latestdoi/140718298)
Is it correct?

**Comment by labarba** [comment]
That DOI resolves correctly, yes. But note that the authors are listed as "oekosheri; Arfon Smith" in the Zenodo entry. Probably you had a pull-request from Arfon that you merged, and Zenodo is taking the authors from the committers, automatically. You need to manually edit the metadata to display the correct author list in Zenodo.

**Comment by oekosheri** [comment]
I edited it, thanks. Do I need to do any thing else?

**Comment by labarba** [comment]
Lastly, I do have a question for you. You've only listed yourself as author in the Zenodo archive. We only see yourself as a committer in the code repository. Yet you have three authors in the JOSS paper. I'm a little worried about courtesy authorship here. The last author is the Director of the Computational Materials Design department at MPIE, and the second author is the group leader of Adaptive Structural Materials. Can you look at the [JOSS authorship guide](https://joss.readthedocs.io/en/latest/search.html?q=authorship&check_keywords=yes&area=default), reflect on this (possibly discuss with your listed co-authors) and make a final determination that the author list is what you all want?

From the JOSS guidelines:

> **Authorship**

>Purely financial (such as being named on an award) and organizational (such as general supervision of a research group) contributions are not considered sufficient for co-authorship of JOSS submissions, but active project direction and other forms of non-code contributions are. The authors themselves assume responsibility for deciding who should be credited with co-authorship, and co-authors must always agree to be listed. In addition, co-authors agree to be accountable for all aspects of the work.

**Comment by oekosheri** [comment]
I am the sole contributor of the code, which is a collection of work I did in the last couple of years under the active direction of the other two authors. So I can update Zenodo author list and include them as well.

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.1433530 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1433530" target="_blank">10.5281/zenodo.1433530</a> is the archive.

**Comment by labarba** [comment]
@arfon : This submission is accepted and ready to be published. 

@vyasr, @trallard : Thank you for your valuable contribution to JOSS by reviewing this publication!

**Comment by oekosheri** [comment]
Thank you all for your help! :) @labarba @vyasr @trallard @arfon

**Comment by arfon** [comment]
@vyasr, @trallard - many thanks for your reviews here and to @labarba for editing this submission ✨ 

@oekosheri - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00900 :zap: :rocket: :boom:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00900/status.svg)](https://doi.org/10.21105/joss.00900)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00900">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00900/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00900/status.svg
   :target: https://doi.org/10.21105/joss.00900
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00900/status.svg)](https://doi.org/10.21105/joss.00900)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
