### ISSUE TITLE
[PRE REVIEW]: Gravity: Estimation Methods for Gravity Models in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#926]
**Submitting author:** @pachamaltese (<a href="http://orcid.org/0000-0003-1017-7574">Mauricio Vargas</a>)
**Repository:** <a href="https://github.com/pachamaltese/gravity" target ="_blank">https://github.com/pachamaltese/gravity</a>
**Version:** v0.8.2
**Editor:** @yochannah
**Reviewers:** @DiegoKoz

**Author instructions**

Thanks for submitting your paper to JOSS @pachamaltese. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@pachamaltese if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00926/joss.00926/10.21105.joss.00926.pdf)

**Comment by yochannah** [comment]
@whedon assign @yochannah as editor

**Comment by whedon** [comment]
OK, the editor is @yochannah

**Comment by yochannah** [comment]
@pachamaltese thanks for your submission! Is there anybody you can think of who might be interested in reviewing this paper?

**Comment by yochannah** [comment]
👋 Hey @xuanxu and @vyasr, is this a package either or both of you might be interested in reviewing?

**Comment by pachamaltese** [comment]
Hi @yochannah <https://github.com/yochannah>. I have no clue. Sorry!

**Comment by vyasr** [comment]
Hmm no sorry, this doesn't look like something I'd know enough to review. Looks cool though!

**Comment by yochannah** [comment]
No worries @vyasr and thanks for responding.

**Comment by yochannah** [comment]
👋  Hey @khaors, might this be something you's be able to review?

**Comment by pachamaltese** [comment]
this is not physics!! it's economics

**Comment by cole-brokamp** [comment]
> @cole-brokamp, would you be interested in reviewing this?

Looks interesting, but I think the domain is outside of my area of expertise.  Sorry I couldn't be of more help!

**Comment by yochannah** [comment]
Thanks @cole-brokamp for letting us know!

**Comment by yochannah** [comment]
@pachamaltese I haven't had any responses from the reviewers I've emailed so far unfortunately, but I've emailed a few more so hopefully we'll have someone soon. In the meantime I noticed that a couple of the links in your reference section have what I'm guessing is a copy/paste error - showing https://doi.org twice, like this:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/9271438/45980449-f0ce5600-c049-11e8-9962-2b718e265bc0.png">

**Comment by pachamaltese** [comment]
@yochannah thanks for letting me know !! I actually fixed that in the original repository. How can I reflect those changes here?

**Comment by yochannah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00926/joss.00926/10.21105.joss.00926.pdf)

**Comment by yochannah** [comment]
@pachamaltese That looks mostly better! The first link is fixed, but the final link in the references section is still broken - it looks ok visually but returns an error when you click.

**Comment by pachamaltese** [comment]
@yochannah thanks a lot !! that was an error, I fixed that here https://github.com/pachamaltese/gravity

**Comment by yochannah** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00926/joss.00926/10.21105.joss.00926.pdf)

**Comment by yochannah** [comment]
Looks good now!

**Comment by yochannah** [comment]
I think @DiegoKoz may be interested in reviewing! 🎉 I'm still on the hunt for a second reviewer - quite a few haven't responded to my emails thus far.

**Comment by DiegoKoz** [comment]
Hi @pachamaltese, its a pleasure! 
As I told @yochannah, it's the first time I do a review, and especially of this kind, I'll try to do my best

**Comment by pachamaltese** [comment]
@DiegoKoz thanks a lot !!

**Comment by DiegoKoz** [comment]
Hi @pachamaltese, while looking for a second reviewer, let me make some comments about documentation.

It would be nice that the vignette does more than creating the dataset. It's great that you include the dataset from Head and Mayer, It would be fantastic if you make a vignette where you use it for the different functions, and which are the advantages from each way of estimating the gravity model. I don't think this is an indispensable criteria for accepting the paper, because the documentation inside the functions seems enough, but it would be a nice thing to have. At least a minimal example in the readme of the repo. 

Another thing you should add to the Readme is the Community guidelines: There should be clear guidelines for third-parties wishing to contribute, report issues and seek support

**Comment by pachamaltese** [comment]
thanks a lot @DiegoKoz 
of course I'm expanding the vignettes

**Comment by DiegoKoz** [comment]
### minor detail
 in the documentation of the functions, the `regressors` param, it says "curreny", I think it is repeated in all the functions. 

### Mayor issue
 It's kind of problematic that the function renames the first input from the `regressors` param, and always assume that is a distance. It would be better to add the parameter `distance`, as you added the `incomes` as a separate thing.  For example, I run the following:
`bvu(dependent_variable = "flow", regressors = c("flow","contig","rta"),
incomes = c("gdp_o", "gdp_d"), codes = c("iso_o", "iso_d"),
robust = TRUE, data = gravity_no_zeros)` 

And didn't make any warning.

In general, I'm not comfortable with the strict dependence of the ordering (inc_0, inc_d). I think it would be better to have different parameters for those things, to avoid confusion. 

The function works as it is, and the documentation clarify the needed order, so just take it as a suggestion.

**Comment by DiegoKoz** [comment]
Also, I don't understand why you choose to return de summary of the models instead of the object? From what I see, this is general for all the functions. Returning the object you fit would allow the users to predict, make intervals, etc. And also use the `moldr` and `broom` packages.

**Comment by pachamaltese** [comment]
@DiegoKoz I'm gonna add you to contributors!! The summary was to do exactly what the Stata package does, and you are right that "free translation" would be better

**Comment by pachamaltese** [comment]
The summary was to do exactly what the Stata package does, and you are right that "free translation" would be better

**Comment by DiegoKoz** [comment]
@pachamaltese I think adding the reviewer as a contributor would emerge a conflict of interests (right @yochannah ?) but thanks anyway!!

### minor detail
The example in `?nbpml()` is not done _the tidy way_ as the rest of the documentation. 

### detail
Also with `nbpml()`, my computer just crashed (twice) because of the amount of computation needed. This is because of `MASS::glm.nb()` is computationally demanding, right? I'm using the examples in the documentation.

**Comment by pachamaltese** [comment]
@DiegoKoz ok, no worries!
yeah, glm eats a lot of ram, you can check inside `nbpml.R` and see the short example for CRAN (i.e. a test with a smaller dataset that takes <10 seconds)

**Comment by DiegoKoz** [comment]
I think it's more a matter with CPU rather than RAM.

The example inside nbpml.R runs, but gives lot's of warnings like  "non-integer x = 16.451930" which lend me to this: [stackoverflow thread](https://stats.stackexchange.com/questions/164889/how-to-deal-with-non-integer-warning-from-negative-binomial-glm )
the negative binomial is used for counting. That may be one of the reasons for the inefficiency with the computation. I assume that you didn't come up with using this distribution but you are rather reproducing it from the literature (I'm not sure from where). 
If that's the case, I would suggest a warning in the documentation and removing the warnings from the output (because it is ok to give something that isn't an integer)

**Comment by DiegoKoz** [comment]
### Minor detail. 

Take this into account: 
![image](https://user-images.githubusercontent.com/28060531/46699645-d9b66900-cbf0-11e8-9072-4a7b24cb546a.png)
 
I change "USA" for a wrong name. The error should say something about the wrong name. Probably its filtering and ending with an empty tibble that afterward gives this error message. I should be easy to check that the names are ok, right?

**Comment by Robinlovelace** [comment]
I might be able to help with this. could take a few months though if you need a review.

**Comment by paulofelipe** [comment]
Nice to know about this package. I have one suggestion. Nowadays, one of the recommendations to assess the effects of trade policy is to use pair fixed effects ([wto book](https://www.wto.org/english/res_e/booksp_e/advancedwtounctad2016_e.pdf)). However, in some settings, this can mean the user will need a method that works with high dimensional fixed effects (in ols or ppml, for example). Otherwise, the estimation can be memory intensive and slow. After a quick look at the repository, I didn't notice any mention to that. In Stata, [Thomas Zylkin](http://www.tomzylkin.com/) wrote a specific function for the ppml case ([ppml_panel_sg](https://econpapers.repec.org/software/bocbocode/S458249.htm)). For ols estimation, it is common to use the `reg2hdfe` function.

In R, the user can estimate a high dimensional linear model using the [lfe package](https://cran.r-project.org/web/packages/lfe/lfe.pdf). In order to allow high dimensional fixed effects in PPML, I think it's necessary to rewrite ppml model using `lfe` inside. I have a [sketch here](https://github.com/paulofelipe/Structural-Gravity/blob/master/R/aux_functions.R).

Again, great to know about the package. I will try it soon.

**Comment by yochannah** [comment]
@Robinlovelace thanks for the offer! @pachamaltese has been very patient, but I think that a few months might be a little bit too long :)

**Comment by yochannah** [comment]
@paulofelipe might you be interested in reviewing this packages by any chance?

**Comment by pachamaltese** [comment]
@DiegoKoz once again thanks a lot for the feedback !!
I did some changes to the functions so that you can now use broom with it, and here I added a vignette (WIP) http://pacha.hk/gravity/articles/crash-course-on-gravity-models.html that explains the models

I'll add the rest of the feedback such as warnings and more, and also to shorten the paper draft a bit.

**Comment by yochannah** [comment]
@DiegoKoz @pachamaltese You two are doing such a great job reviewing the package I'll kick off the formal review now. I'd still like a second reviewer but may add them in later in the process.

**Comment by yochannah** [comment]
@whedon assign @DiegoKoz as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @DiegoKoz

**Comment by yochannah** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1038. Feel free to close this issue now!

**Comment by yochannah** [comment]
@DiegoKoz @pachamaltese  - let's head over to #1038 where there is a full review checklist 👍
