### ISSUE TITLE
[REVIEW]: Lithology: A Landlab submodule for spatially variable rock properties

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#979]
**Submitting author:** @kbarnhart (<a href="http://orcid.org/0000-0001-5682-455X">Katherine Barnhart</a>)
**Repository:** <a href="https://github.com/landlab/landlab" target ="_blank">https://github.com/landlab/landlab</a>
**Version:** 1.5.4
**Editor:** @kthyng
**Reviewer:** @speleophysics, @tristan-salles
**Archive:** <a href="https://doi.org/10.5281/zenodo.1464308" target="_blank">10.5281/zenodo.1464308</a>

## Status

[![status](http://joss.theoj.org/papers/74487c5a6820fb2fe2898960ad6d2ea0/status.svg)](http://joss.theoj.org/papers/74487c5a6820fb2fe2898960ad6d2ea0)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/74487c5a6820fb2fe2898960ad6d2ea0"><img src="http://joss.theoj.org/papers/74487c5a6820fb2fe2898960ad6d2ea0/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/74487c5a6820fb2fe2898960ad6d2ea0/status.svg)](http://joss.theoj.org/papers/74487c5a6820fb2fe2898960ad6d2ea0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/landlab/landlab" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@speleophysics & @tristan-salles, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @kthyng know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/landlab/landlab">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (1.5.4)?
- [x] **Authorship:** Has the submitting author (@kbarnhart) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/landlab/landlab">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (1.5.4)?
- [x] **Authorship:** Has the submitting author (@kbarnhart) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @speleophysics, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00979/joss.00979/10.21105.joss.00979.pdf)

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00979/joss.00979/10.21105.joss.00979.pdf)

**Comment by kbarnhart** [comment]
@kthyng Looks like I have the authority to ask for pdf recompilation. It also looks like my PR fixed the citation formatting.

**Comment by kthyng** [comment]
Looks good, @kbarnhart! Thanks.

**Comment by tristan-salles** [comment]
I am pleased to recommend publication of this additional new module to Landlab! 

This is clearly going to be of interest to many of the existing users of this code and has also the potential to attract more researchers who are interested in adding more realism in their models with spatially variable lithologies producing variable erodability and diffusivity. 

Following are some of my comments and minor issues that I've found during the review process.

### Version number

The current Landlab Github release is 1.5.3 and therefore does not match the proposed release 1.5.4. That is the reason why I didn't click it the checklist. Yet it looks like this is going to be handle later and the relevant version will be release after the initial JOSS submission. 

### Functionality & documentation

There isn't _per se_ a specific installation for this submodule but there is already existing and well-establish documentation regarding the installation of Landlab. I did pull the specified request number [#674](Pull Request # 674) from  Landlab repository and didn't have any issue with the local installation following the `pip` method and everything worked as expected. 

I have downloaded the corresponding Jupyter notebooks (linked provided in the manuscript). I followed the instructions regarding the installation of additional packages:
+ xarray 
+ HoloViews
+ Bokeh 

and was able to run all the cells without issues. 

The tutorial and step-by-step guide to illustrate the capability of this new submodule are well explained and illustrative as well as simple. I've noticed that the Jupyter notebook is quite large >(>60 MB) maybe it will be better to clear all cells before uploading the notebook to its repo on Github but you might want to keep the plots... Also the two last links to the readme website for the 2 lithology objects are not working and should be updated. 

As already pointed above the submodule is part of the Landlab software and contains the requirement from the review checklist:
+ statement of need
+ clearly-stated list of dependencies
+ the Jupyter notebooks from the manuscript present an example usage
+ an API documentation for this particular submodule is provided and properly referenced in the manuscript.
+ automated tests are part of Landlab and I assume are ran for this submodule as well
+ there is clear community guidelines statement

### Additional minor comments:

+ in the paper in addition to pointing to the _Landlab_ GitHub main repository I will also suggest to add a link to the _Lithology_ [repo](https://github.com/landlab/landlab/tree/master/landlab/components/lithology) 
+ in the `lithology` class the documentation has the word 'corresponding' misspelled (cooresponding)  several times. There is also a space that could be deleted just after 'number-of' in the 'number-of -nodes' in the following sentence. 
+ in the ``run_one_step`` method I've noticed a typo on the first parameter name called `dz_advenction` instead of `dz_advection`.

**Comment by speleophysics** [comment]
I am happy to recommend this new Landlab module for publication. In general, I agree with @tristan-salles assessment and comments. The new module is a nice contribution that will undoubtedly be used widely within the community. The purpose is expressed clearly in the accompanying paper, and the code works as advertised.

I have read through the documentation and gone through the tutorials. In the process, I found a few erroneous links to the documentation in the tutorials and have made a few suggestions for clarification (provided as issues in the landlab/tutorials repo, https://github.com/landlab/tutorials/issues/38#issue-366912619,  https://github.com/landlab/tutorials/issues/36#issue-366512363). However, overall, the documentation is well-written and easy to understand. 

Regarding the checklist above, there are two items I have not yet checked: 1) as noted by @tristan-salles , the version number is not yet updated, 2) A few of the references in the paper are missing DOIs.

**Comment by kbarnhart** [comment]
Thanks to both @tristan-salles and @speleophysics for constructive and thoughtful reviews. I anticipate finishing revisions by early next week. I'll make a note here when I'm done.

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00979/joss.00979/10.21105.joss.00979.pdf)

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00979/joss.00979/10.21105.joss.00979.pdf)

**Comment by kbarnhart** [comment]
@kthyng I'm almost done but have a final question related to DOIs. 

Once I know how to deal with the DOIs correctly, then the only thing I have left to do (after the reviewers confirm there is nothing left to do) is make a Landlab release that is tagged v1.5.4. 

The questions I have are in two broad categories:
1.  How to best deal with archiving when the majority of the submission is in the Landlab source code repository, but an additional part of it is in the Landlab tutorials repository.  
2. How to best deal with reserve DOIs for repositories with Zenodo and Github linked by webhooks. 

The work here is in two repositories (rather than one). This is because the Landlab source code is in one repo and the tutorials are in a second. The real *software* contribution is the source code, so I think the way to deal with this is to list the archive as the source cod Zenodo repository. 

On the second issue: We have Github and Zenodo webhook-linked for landlab _and_ my research indicates that it is not  possible to make a pre-reserved DOI for a GitHub repo that is webhook-linked to Zenodo. I have thus made references in the text to the _concept DOIs_ on Zenodo for these two repositories. I think that this makes sense to link to the concept DOIs, but let me know if you think I should do otherwise. 

Unless I make a special Zenodo archive just for this manuscript (that would not be listed with the rest of the Landlab Zenodo DOIs under the Landlab concept DOI) I don't think I can make a reserve DOI. 

However, a DOI specific to Landlab 1.5.4 will be generated when I create the release. I can respond with that DOI when you ask for the archive DOI at the end of the review process. 

Does it make sense to plan to proceed in that way?

**Comment by kyleniemeyer** [comment]
@kbarnhart regarding this question: 

>However, a DOI specific to Landlab 1.5.4 will be generated when I create the release. I can respond with that DOI when you ask for the archive DOI at the end of the review process.
>
>Does it make sense to plan to proceed in that way?

Yes, we just need the DOI at the end of the process, once all changes have been made and the submission is accepted.

**Comment by kyleniemeyer** [comment]
@kbarnhart for your question #1, for JOSS you should archive the source code and provide that DOI. For the tutorials, I think you can do two things:
- Link to the location from the source code (e.g., in the README), and
- Archive the tutorials separately and reference that DOI in your paper

**Comment by jedbrown** [comment]
If the tutorials are considered a key component (and especially if they have been part of the review), then I would recommend @kyleniemeyer's second option: create a DOI and reference it in the paper.

**Comment by kbarnhart** [comment]
Thanks for the thoughts @kyleniemeyer and @jedbrown ! Based on your suggestions (and because the tutorials have been part of the review) this is what I think makes sense. Let me know if you think otherwise. 

Once I verify that the reviewers are happy with the revisions I will. 

1. Create a release of the tutorials repository and get the release specific zenodo DOI for it. 
2. Update the manuscript to reflect 
    a. that the tutorials repository DOI is the release-specific v1.5.4
    b. that the landlab source code DOI referenced in the text is the concept DOI but the archive link is the release specific DOI. 
   c. Do appropriate merging and then make a release of the landlab source code at v1.5.4
   d. Provide the v1.5.4 release specific DOI here to be used as the archive.

**Comment by jedbrown** [comment]
Looks good to me.

**Comment by kthyng** [comment]
Thanks for your input @kyleniemeyer and @jedbrown!

@kbarnhart Sounds like you have a good plan. I think we just need to hear back from @speleophysics with the go ahead and then we'll be good to move forward.

**Comment by kbarnhart** [comment]
@speleophysics would it be OK if I moved ahead with making the release?

**Comment by kthyng** [comment]
I just read through @speleophysics previous comments and I think everything has been satisfied. I feel comfortable moving forward.

@kbarnhart I'm setting your paper as accepted now! Can you create an archive (on Zenodo, figshare, or other) and post the archive DOI here?

**Comment by kbarnhart** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.00979/joss.00979/10.21105.joss.00979.pdf)

**Comment by kbarnhart** [comment]
@kthyng the zenodo archive is [http://doi.org/10.5281/zenodo.1464308](http://doi.org/10.5281/zenodo.1464308)

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.1464308 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1464308" target="_blank">10.5281/zenodo.1464308</a> is the archive.

**Comment by kthyng** [comment]
Hey @arfon we have an accepted paper here!!

Thanks to @speleophysics and @tristan-salles for their reviews, and congrats to @kbarnhart!

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00979/status.svg)](https://doi.org/10.21105/joss.00979)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00979">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00979/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00979/status.svg
   :target: https://doi.org/10.21105/joss.00979
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00979/status.svg)](https://doi.org/10.21105/joss.00979)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=

**Comment by speleophysics** [comment]
Yes. I am/was ok with acceptance. I've been out of contact doing field work
the last week.
-------------------------
Matt Covington
Associate Professor
Department of Geosciences
340 N. Campus Dr.
216 Gearhart Hall
University of Arkansas
Fayetteville, AR 72701

webpage - http://www.speleophysics.com/
-------------------------

**Comment by arfon** [comment]
:wave: @kthyng - there are a couple of steps I need to take before we should close this issue. I'll do that now...

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/11

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/11, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/12
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.00979](https://doi.org/10.21105/joss.00979)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment]
OK, looks like that worked :zap:

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](http://joss.theoj.org/papers/10.21105/joss.00979/status.svg)](https://doi.org/10.21105/joss.00979)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.00979">
  <img src="http://joss.theoj.org/papers/10.21105/joss.00979/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: http://joss.theoj.org/papers/10.21105/joss.00979/status.svg
   :target: https://doi.org/10.21105/joss.00979
```
This is how it will look in your documentation:

[![DOI](http://joss.theoj.org/papers/10.21105/joss.00979/status.svg)](https://doi.org/10.21105/joss.00979)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: http://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3Nzk=
